import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-7.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-7-first-pass-review.json"


def refs():
    return [
        {"url": "https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "title": "高雄市立鹽埕國民中學公開英文段考；僅取對話主旨、細節、指代與推論能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": "dialogue main idea, details, reference, and inference", "observedPattern": "公開英文評量以短對話測量人物、時間、地點、目的、問題、解決方案與後續行動；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"},
        {"url": "https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "title": "新北市立北投國民中學公開定期評量試題頁；僅取對話資訊整合與語意推論方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": "dialogue information, purpose, sequence, and inference", "observedPattern": "公開英文評量要求學生整合多輪對話的時間、地點、觀點、代名詞與計畫；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"},
        {"url": "https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "title": "新北市立新埔國民中學公開段考試題頁；僅取生活對話順序、問題與解決方案判讀方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": "daily dialogue sequence, problem, solution, and plan", "observedPattern": "公開英文評量以生活對話判讀事情順序、說話者觀點、問題處理與共同計畫；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"},
    ]


def make_q(base, prompt, options, answer, explanation, strategy, steps):
    q = json.loads(json.dumps(base)); q.update({"prompt": prompt, "options": [{"id": k, "text": v} for k, v in options], "answer": {"value": answer, "explanation": explanation + f" 正確答案：{answer}"}, "examPatternRefs": refs(), "solutionStrategy": strategy, "solutionSteps": steps, "reviewStatus": "draft", "updatedAt": "2026-09-21"})
    q["provenance"]["sourceUrl"] = refs()[0]["url"]
    q["provenance"]["sourceLocator"] = "公立學校公開英文評量的對話主旨、細節、順序與推論模式；本題只改寫能力、資料型態與推理層次。"
    q["provenance"]["authoringNote"] = "依官方課綱、本單元 KG 與三所公立學校公開英文評量模式獨立改寫；題幹、選項、答案、解析與互動任務均未複製來源。"
    return q


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-3-iv-7"
    data["title"] = "3-Ⅳ-7：從對話線索整合主要內容、細節與後續行動"
    data["content"] = {"summary": "理解對話不能只翻譯最後一句；要沿著說話者、事件、時間、地點、目的、問題、感受與下一步建立資訊鏈。本課以搭車、工作坊、檔案傳送、食譜、考試感受、設備故障、代名詞、房間處理、共同排程與戶外準備等原創對話，練習抓主旨、定位細節、排序事件、辨認觀點、追蹤指代並從明示線索推出合理行動。", "sections": [{"heading": "先畫出對話的事件鏈", "body": "每輪對話都可拆成 Situation、People、Problem、Evidence、Response、Next step。先找誰在說什麼，再把 because、so、after、finally、but 等連接詞圈起來，避免只被某個熟悉單字吸引。"}, {"heading": "主旨要能包住多句話", "body": "主旨不是逐字抄一句，而是用較短的句子概括問題與處理方向。若對話同時提到遲到、打電話與接送，答案應說明交通延誤後安排接送，而不是只說母親或圖書館。"}, {"heading": "細節、順序與觀點分開", "body": "When／where 問定位，first／next／finally 問順序，I thought／I found 顯示兩人的觀點可能不同。回答前先標問題類型，再回到對話中的直接證據，不能把 A 的感受誤當成 B 的感受。"}, {"heading": "指代和推論要有回指證據", "body": "it、this、there 等詞要沿著前一句的名詞和動作回查；推論只能在對話明示線索支持的範圍內。若只知道天氣 clear，不必擴大成一定沒有任何風險；若對話沒有原因，就保留不能確定。"}]}
    data["studyHighlights"] = ["先用事件鏈整理人物、問題、證據、回應與下一步。", "依主旨、細節、順序、觀點、指代與推論分類問題。", "回到原句找時間、地點、連接詞與代名詞的直接支持。", "用一段涵蓋多句話的摘要回答主旨，不把單一細節冒充全部內容。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "最後一句能代表整段對話嗎？", "body": "展示原創對話：學生錯過公車、打電話、母親到圖書館接送。學生先各自寫一句摘要，再比較只寫『母親』與寫出交通問題及解決方案的差異，建立主旨必須包住事件鏈的需求。"}, {"id": "explain", "phase": "explain", "heading": "六格對話追蹤卡", "body": "建立 Situation、People、Problem、Evidence、Response、Next step 六格。每讀一輪就填一格，接著依題目要求切換到 where／when／why／how／what does it refer to，讓摘要與細節有不同的證據標準。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從多輪話語追蹤解決方案", "body": "以投影機故障與改用 Room 8 大螢幕示範：先標 problem，再找 B 提出的 response，最後將兩句合成 solution。錯誤選項若只重述故障，便指出它沒有回答 What solution。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一對話換問題類型", "body": "用工作坊、寄檔案、食譜、考試、代名詞與會議六組原創對話，先預測問題屬於主旨、細節、順序、觀點或指代，再互換題目回答；同伴必須在文本中畫出證據位置。"}, {"id": "transfer", "phase": "transfer", "heading": "從對話寫成可執行摘要", "body": "將戶外活動準備對話改寫成三句摘要：已完成什麼、誰補充什麼、下一步如何做。再刪掉一個細節，請同伴判斷主旨是否仍在；若失去問題或計畫，重新排序資訊。"}, {"id": "reflect", "phase": "reflect", "heading": "我回答的是問題還是印象？", "body": "回看答案，標記主旨過窄、細節錯位、順序顛倒、觀點混淆、指代無回指或推論過度。每個修訂都要補回一段可定位的原句證據，沒有證據就改寫成不能確定。"}], "summary": ["以六格事件鏈整理對話中的問題、證據、回應與下一步。", "先分類題目，再用相應的時間、地點、觀點或指代證據回答。", "用涵蓋多輪對話的摘要掌握主旨，不被單一細節取代。", "推論保持在對話明示線索內，無證據時保留不確定性。"], "exitCheck": [{"prompt": "主旨和細節題的證據範圍有何不同？", "expectedEvidence": "能說明主旨要整合多句話，細節則回到特定時間、地點、人物或動作。"}, {"prompt": "如何判斷 it 指的是哪個名詞？", "expectedEvidence": "能回查前文候選名詞、數量與動作，說明語意和句法如何支持指代。"}, {"prompt": "對話資料不足時，如何避免把合理猜測當成答案？", "expectedEvidence": "能指出直接證據，若沒有足夠線索則回答不能確定或提出需要確認的資訊。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "沿著對話事件鏈整合主旨、細節、順序、觀點、指代與下一步，提出有文本證據的答案。", "scenario": "學生擔任班級紀錄員，要把校園對話整理成可供同學採取行動的摘要與細節回覆。", "variables": [{"symbol": "e", "meaning": "人物、事件、問題、證據與回應"}, {"symbol": "q", "meaning": "主旨、細節、順序、觀點、指代或推論問題"}, {"symbol": "n", "meaning": "後續行動、限制與可回指的句子"}], "steps": [{"id": "step-1", "prompt": "A student missed the bus, called her mother, and will be picked up at the library. What is the main point?", "options": ["A transport problem is followed by a pickup plan.", "The student only likes the library.", "The mother missed the bus too."], "answer": "A", "feedback": "A 包住問題與解決方案兩個主要事件，不把單一地點或未提供的資訊當主旨。"}, {"id": "step-2", "prompt": "A says, 'Send me the science file.' B says, 'I will email it after dinner.' What does it refer to?", "options": ["the science file", "dinner", "the speaker's room"], "answer": "A", "feedback": "沿前一句回查名詞與 B 的動作，email it 的 it 指 science file。"}, {"id": "step-3", "prompt": "The projector is broken, and B suggests using the large monitor in Room 8. What is the solution?", "options": ["Use the large monitor in Room 8.", "Repair the projector immediately.", "Cancel every class."], "answer": "A", "feedback": "A 是對話明示的替代方案；其他選項不是 B 提出的行動或超出資料。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；簡短對話、生活事件與主要訊息定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由簡短對話理解主要訊息與生活細節。", "以人物、時間、地點與行動整理內容。"], "representations": ["校園對話、事件順序、交通、活動與計畫。"], "examplesOrEvidence": ["本課以搭車、工作坊、檔案、食譜與戶外準備原創對話承接公開結構。"], "misconceptions": ["只抄最後一句，忽略前因與後續行動。"], "assessmentEmphasis": ["重視對話主要內容、細節與順序。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖像、對話任務與訊息整合定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["透過多輪對話與任務理解人物、目的與行動。", "依時間、地點、問題與計畫整合資訊。"], "representations": ["工作坊、路線、檔案、設備、排程與戶外活動。"], "examplesOrEvidence": ["本課以對話事件鏈與六格卡重新設計活動。"], "misconceptions": ["把一人的觀點、單一細節或猜測當成整段對話結論。"], "assessmentEmphasis": ["評量資訊整合、順序、觀點與後續行動。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；生活溝通文本、推論與對話理解定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["從上下文、說話者與代名詞形成對話理解。", "以主旨、細節、問題、解決方案與限制表達結論。"], "representations": ["main idea、detail、sequence、viewpoint、reference、inference、next action。"], "examplesOrEvidence": ["本課將多輪校園對話改寫成事件鏈、回指證據與遷移摘要。"], "misconceptions": ["以常識補上對話未說的原因或結果。"], "assessmentEmphasis": ["評量主旨、細節、指代、推論與語意連貫。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持短對話、生活事件與主要訊息理解。", "可靠對話理解需整合人物、事件、時間、目的、問題、回應與下一步。", "可用事件鏈、問題分類、回指證據與摘要修訂把閱讀轉成可驗證回答。"], "versionDifferences": ["南一較突顯短對話主要訊息、細節與順序；康軒較突顯多輪任務、人物計畫與行動；翰林較突顯上下文、指代、推論與解決方案。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Situation、People、Problem、Evidence、Response、Next step 六格追蹤事件鏈。", "用交通、活動、檔案、設備、排程與戶外準備原創對話練習主旨與細節轉換。", "以摘要刪減、代名詞回指與不能確定標記檢查推論界線。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織對話主旨、細節、順序、觀點、指代、推論與後續行動。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    specs = [
        ("A student tells a friend, 'I missed the bus, so I called my mother. She will pick me up at the library.' What is the main point?", [("A", "A transport problem is followed by a pickup plan."), ("B", "The student only likes the library."), ("C", "The mother missed the bus too."), ("D", "The student will walk home alone.")], "A", "A includes the problem and the stated solution without adding an unsupported result.", "把多句事件壓縮成問題加處理方案的摘要。", ["圈 missed the bus 找出問題。", "圈 so 與 will pick me up 找出因果與下一步。", "用一句話包住交通問題和接送安排。", "排除只取地點、替母親增加事件或捏造獨自行走。", "回看每句話，確認摘要沒有漏掉方案也沒有超出對話。"]),
        ("A: 'Are you joining the art workshop?' B: 'Yes, at two o'clock in Room 12.' When and where will B join?", [("A", "At two o'clock in Room 12."), ("B", "At twelve o'clock in Room 2."), ("C", "After dinner in the library."), ("D", "On Friday outside.")], "A", "B directly gives both the time and room in the reply.", "將 when 與 where 兩個問題欄位分開定位，再合併答案。", ["確認問題要找時間與地點。", "回到 B 的同一句圈 at two o'clock 與 Room 12。", "把兩個直接細節合成 A。", "排除交換數字、改變地點與補上未出現的日期。", "用問句重述答案，確認時間和地點都沒有遺漏。"]),
        ("A: 'Could you send me the science file?' B: 'Sure. I will email it after dinner.' What does A want?", [("A", "The science file."), ("B", "A dinner invitation."), ("C", "A new classroom."), ("D", "A printed map.")], "A", "A's request explicitly names the science file; it is the object of send and email it.", "從請求中的名詞與後文代名詞回指確認資訊。", ["找 A 的請求動詞 send。", "圈 send 的受詞 the science file。", "用 B 的 it 回查同一物件，確認沒有換成 dinner。", "排除邀請、教室與地圖等對話未提的物件。", "將 A 的問題改寫成『想收到什麼？』，答案仍是 science file。"]),
        ("First, the friends choose a recipe. Next, they buy vegetables. Finally, they cook together. What happens next after choosing?", [("A", "They buy vegetables."), ("B", "They cook before choosing."), ("C", "They cancel the recipe."), ("D", "They go to a library.")], "A", "Next identifies the second step in the stated sequence.", "讀順序標記詞，再只選緊接在指定事件後的行動。", ["圈 First、Next、Finally 建立三步時間線。", "定位 choosing a recipe 是第一步。", "尋找它後面的 Next，得到 buy vegetables。", "排除把 finally 提前、取消或換成無關地點的選項。", "依序口述三步，確認 A 是第二步而不是最後一步。"]),
        ("A: 'I thought the test was difficult.' B: 'Really? I found the reading part quite easy.' How does B feel about the reading part?", [("A", "B thinks it was easy."), ("B", "B thinks it was impossible."), ("C", "B did not take the test."), ("D", "B is asking for a new test." )], "A", "B directly says the reading part was quite easy, even though A had a different opinion.", "把說話者分開，將 B 的觀點與 A 的感受對照。", ["標記 A 的 difficult 與 B 的 easy 是不同人的觀點。", "題目問 B，所以只回看 B 的 found...easy。", "選 A，保留 reading part 的範圍。", "排除把 A 的意見套給 B 或加入對話未說的結果。", "重述成『B 對 reading part 的評價』，確認主詞與部分都正確。"]),
        ("A: 'The classroom projector is not working.' B: 'Let's use the large monitor in Room 8.' What solution does B suggest?", [("A", "Use the large monitor in Room 8."), ("B", "Cancel every class."), ("C", "Buy a new projector today."), ("D", "Move the monitor to the library.")], "A", "B's sentence gives the alternative device and its room.", "先找問題，再找 B 以 Let's 提出的明示方案。", ["圈 projector is not working 找出問題。", "在 B 的句子找 Let's use 這個解決方案標記。", "保留 large monitor 與 Room 8 兩個必要細節。", "排除取消、購買與改搬地點等未提出的行動。", "把問題與方案配對，確認 A 真正解決的是投影設備故障。"]),
        ("A: 'I left my red notebook on the bus.' B: 'I hope you find it.' What does it refer to?", [("A", "the red notebook"), ("B", "the bus"), ("C", "the speaker's friend"), ("D", "the hope")], "A", "The lost object named before the pronoun is the red notebook.", "回查代名詞前的名詞、動作與語意角色。", ["列出 it 前的候選名詞 notebook 與 bus。", "檢查 find 的受詞：人可以被找到，遺失物也可被找到。", "red notebook 是被 left on the bus 的物件，最直接回指 it。", "排除把地點、人物或抽象 hope 當成物件。", "將句子替換成 I hope you find the red notebook，確認語意自然。"]),
        ("A: 'The room is very dark.' B: 'I will open the curtains.' What does B intend to do?", [("A", "Let in more light."), ("B", "Close the curtains."), ("C", "Leave the room immediately."), ("D", "Turn off every lamp.")], "A", "Opening curtains is a plan to let more light into a dark room.", "由明示動作與前一句問題推導最小、合理的目的。", ["辨識問題是 room very dark。", "找 B 的明示行動 open the curtains。", "用常識但不超出線索，推得讓更多光進來。", "排除相反動作、離開與使房間更暗的選項。", "說明 A 是受對話支持的近端目的，不添加改裝房間等遠因。"]),
        ("A dialogue covers choosing a meeting day, checking everyone's schedule, and agreeing on Friday afternoon. What is the final decision?", [("A", "They will meet on Friday afternoon."), ("B", "They will never meet."), ("C", "They will meet every morning."), ("D", "They are still choosing a recipe." )], "A", "The final agreement states Friday afternoon as the meeting time.", "追蹤討論過程到最後的共同決定，不被中途候選日取代。", ["整理三步：提出日期、檢查行程、達成 agreement。", "題目問 final decision，所以以最後明示的 Friday afternoon 為準。", "選 A，保留 day 與 time。", "排除否定、每天早上與不同任務等未支持結論。", "回述『大家最後同意什麼』，確認 A 是共識而不是提議。"]),
        ("A: 'I printed the map and packed water.' B: 'Great. I checked the weather, and it should stay clear tomorrow.' What is the group preparing for?", [("A", "An outdoor trip tomorrow."), ("B", "A rainy indoor exam yesterday."), ("C", "A cooking contest tonight."), ("D", "A library book return.")], "A", "The map, water, and clear weather tomorrow together support preparing for an outdoor trip.", "整合多個細節做範圍受控的主旨推論。", ["列出已完成準備：map、water、weather check。", "把 tomorrow 與 stay clear 連到需要在戶外移動的活動。", "用 outdoor trip 概括共同目的，保留時間範圍。", "排除室內考試、烹飪與還書等不符合資料的活動。", "說明 A 是由多項線索支持的推論，不把未提地點或交通方式當確定事實。"]),
    ]
    for i, spec in enumerate(specs, 1):
        p = ROOT / f"questions/english/question-english-performance-3-iv-7-{i}.json"; q = make_q(json.loads(p.read_text(encoding="utf-8")), *spec); p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-7")


if __name__ == "__main__":
    main()
