import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-4.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-4-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創表格、長條圖、折線圖、刻度、溫度、回收量、借閱量與活動時間表，承接公開課程的圖表閱讀與資料表達方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-3-iv-4"
    data["title"] = "3-Ⅳ-4：從標題、軸線、刻度與資料變化理解簡易圖表"
    data["content"] = {"summary": "圖表不是把數字換成英文就完成閱讀；要先讀標題、欄列或橫縱軸、單位與刻度，再依問題比較最高最低、早晚、相等與變化，最後用不超過資料的句子描述趨勢。本課以借書量、訪客數、溫度、回收公斤數、點心調查、公車時間、閱讀量、長條刻度、折線變化與活動時間表等原創資料，練習把表格和圖形轉成準確英文回答，並區分資料直接支持的結論與需要平均、原因或額外計算才可提出的推論。", "sections": [{"heading": "先讀圖表的身份和單位", "body": "Books Borrowed in April 加上 Number of books 的縱軸，說明圖表量的是四月借書本數；標題、軸線與單位先決定每個數字代表什麼。若直接比較高度而沒看刻度或欄位，可能把溫度、公斤和人數混為一談。"}, {"heading": "最高最低要逐格比較", "body": "Monday 12、Tuesday 18、Wednesday 15 中，18 是最高；24°C、21°C、27°C、23°C 中，21°C 是最低或 coolest。先把問題的比較詞圈起來，再逐格讀數字，不能用日期順序或柱子顏色猜答案。"}, {"heading": "刻度決定數量換算", "body": "每條格線代表 10 visitors，第三條格線就是 30 visitors，不是 3 或 10。讀長條圖時先找零點、每格單位與柱頂位置；若柱頂落在兩格之間，要保留估計或回查圖例，不假裝有精確數字。"}, {"heading": "趨勢描述要保留範圍", "body": "折線從一月升到三月、四月下降，只能說這段期間先增加後減少；沒有控制條件或原因資料時，不能說某政策造成變化。活動時間表則是安排，不是數量趨勢；回答時先判斷資料型態，再選 compare、increase、decrease、equal 或 schedule。"}]}
    data["studyHighlights"] = ["先讀標題、軸線、欄位、單位與刻度，再解讀數字。", "以最高、最低、早晚、相等與差異問題逐格比較資料。", "依圖例和每格單位換算長條高度，不把格線當成單純數字。", "用有範圍的語句描述趨勢，避免把相關變化當成原因。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "看最高的柱子就一定知道答案嗎？", "body": "展示完全自編的訪客長條圖，一張沒有標題和單位，一張補上 Number of visitors、每格 10 人與日期。學生先各自回答，再比較答案差異，從錯誤中發現圖表身份和刻度比柱子外觀更先需要讀。"}, {"id": "explain", "phase": "explain", "heading": "圖表七欄讀取卡", "body": "建立 Title、Categories、Axis or columns、Unit、Scale、Comparison、Change／limit 七欄。先用標題和軸線翻譯資料身份，再標單位與格線，最後回答問題要求的比較或趨勢；沒有原因欄時不自行補因果。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從格線讀出 30 位訪客", "body": "以 each grid line represents 10 visitors、bar reaches the third grid line 示範：先找每格單位，再計算 10+10+10，得到 30。比較若只回答 third line，說明那是位置不是資料量；若圖表沒有零點，先標示需要更多圖例。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一資料換成不同問題", "body": "給出借閱、溫度、回收、點心、公車和活動時間表六組原創圖表。學生先各自寫 highest、coolest、earlier、equal 或 schedule 問題，再交換回答；同伴必須指出標題、欄位、單位或刻度的證據，不能只說柱子比較高。"}, {"id": "transfer", "phase": "transfer", "heading": "把圖表結論寫成不過度的摘要", "body": "輪換折線上升下降、學生閱讀量與活動排程。學生寫一句資料直接支持的結論，再寫一句不能由圖表單獨證明的原因或平均問題；將 first／then、more／less、earlier／later 與 between 等詞連回資料範圍。"}, {"id": "reflect", "phase": "reflect", "heading": "我讀的是資料還是圖形印象？", "body": "回看答案，標記 title／unit 錯誤、scale 錯誤、比較錯誤、趨勢超出範圍或因果過度推論。修訂時回到原始欄位與數字，若圖表沒有支持原因、平均或個體差異，就把句子改成描述而非解釋。"}], "summary": ["以 Title、Categories、Axis、Unit、Scale、Comparison、Change／limit 七欄讀圖表。", "先判斷資料身份與刻度，再回答最高最低、早晚與相等。", "用格線單位和圖例換算，不把位置誤當數量。", "以有範圍的描述區分圖表直接證據和額外推論。"], "exitCheck": [{"prompt": "讀圖表的第一步為什麼不是直接比較柱子？", "expectedEvidence": "能先找標題、軸線、欄位、單位與刻度，確認數字代表的資料。"}, {"prompt": "如何從每格 10 人的第三條格線得到數量？", "expectedEvidence": "能將每格單位與格線位置相乘，說明第三格代表 30 而不是 3 或 10。"}, {"prompt": "折線先升後降時可以提出什麼結論？", "expectedEvidence": "能描述指定期間的增加與減少，但不把沒有資料支持的原因或因果當成確定結論。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "從圖表標題、欄位、軸線、單位、刻度與變化，提出符合資料範圍的英文結論。", "scenario": "學生擔任校園資料小編，要讀借閱、天氣、回收、公車與活動時間表，替不同讀者寫出準確的圖表摘要。", "variables": [{"symbol": "i", "meaning": "標題、軸線、欄位、單位與刻度"}, {"symbol": "c", "meaning": "最高、最低、早晚、相等與資料差異"}, {"symbol": "t", "meaning": "趨勢、排程、範圍與推論界線"}], "steps": [{"id": "step-1", "prompt": "A table lists Monday 12, Tuesday 18, and Wednesday 15 visitors. Which day has the highest number?", "options": ["Tuesday has the highest number, with 18 visitors.", "Monday has the highest number, with 12 visitors.", "Wednesday is the earliest day, so it has the highest number."], "answer": "A", "feedback": "A compares the values directly and reports the matching day and unit."}, {"id": "step-2", "prompt": "Each grid line represents 10 visitors. A bar reaches the third grid line. How many visitors does it represent?", "options": ["It represents 30 visitors.", "It represents 3 visitors.", "It represents 10 visitors because the bar is one object."], "answer": "A", "feedback": "Three intervals of 10 visitors give 30; the grid scale must be used rather than the bar count."}, {"id": "step-3", "prompt": "A line chart rises from January to March and then falls in April. Which statement is careful?", "options": ["The value increased through March and then decreased in April.", "A new rule definitely caused the increase.", "The value stayed exactly the same all year."], "answer": "A", "feedback": "A describes the visible trend and its time range without inventing a cause or ignoring the fall."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語簡易圖表、表格與生活資料定位；核讀 2026-09-21。", ["由簡易圖表、表格和生活資料理解主要訊息。", "以標題、數字、比較和基本句型表達資料。"], ["借閱、訪客、天氣、回收、時間與活動表。"], "只看柱高或數字，沒有讀標題、單位、刻度與欄位。", "重視圖表主要內容、細節與生活資料表達。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語圖片、表格、數量與情境任務定位；核讀 2026-09-21。", ["透過圖片、圖表和任務比較數量、時間與變化。", "依順序、單位、最高最低和行程完成回應。"], ["表格、長條、折線、溫度、回收、交通與活動時間。"], "把第三格當成 3，或將排程、數量、原因和趨勢混為一談。", "評量圖表主要內容、細節、比較與功能性摘要。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語圖表閱讀、刻度、趨勢與資料評量定位；核讀 2026-09-21。", ["從標題、軸線、單位、刻度和資料變化形成圖表理解。", "以比較、趨勢、排程與證據界線表達結論。"], ["title、axis、unit、scale、comparison、trend、schedule、limit。"], "忽略刻度或把圖表相關變化解讀成已證實的因果。", "評量資訊定位、換算、比較、趨勢與不過度推論。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持簡易圖表、表格、生活資料與英語摘要。", "可靠圖表理解需整合標題、欄位、軸線、單位、刻度、比較、趨勢與資料界線。", "從讀數到文字結論可用圖表卡、刻度換算、資料型態轉換與同伴回指驗證。"], "versionDifferences": ["南一較突顯簡易圖表、表格與生活資料；康軒較突顯圖片、數量、順序、時間與任務；翰林較突顯標題、軸線、刻度、趨勢、排程與不過度推論評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Title、Categories、Axis、Unit、Scale、Comparison、Change／limit 七欄讀圖表。", "用借閱、天氣、回收、點心、公車、訪客與活動排程原創資料練習比較。", "以圖表摘要和因果界線檢查學生是否把資料直接證據與推論分開。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織圖表標題、軸線、欄位、單位、刻度、比較、趨勢、排程與推論界線。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 七欄填完後先讓同伴只看摘要猜圖表身份，再回看標題和單位；若猜錯，優先修正資料身份或刻度，不用增加空泛解釋。"
    data["teaching"]["body"][4]["body"] += " 寫趨勢摘要時固定時間範圍和資料型態，若要說原因、平均或個別差異，另列為需要額外資料的問題，而不是塞進結論。"
    data["teaching"]["body"][5]["body"] += " 同伴若能重述數字卻說不出單位或期間，補回圖表身份；若結論超出資料，改用 appears、during this period 或 cannot tell from the chart。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "3-Ⅳ-4：從標題、軸線、刻度與資料變化理解簡易圖表", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-4")


if __name__ == "__main__":
    main()
