import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-4-iv-8.json"
REPORT = ROOT / "implementation/reports/english-performance-4-iv-8-first-pass-review.json"
URLS = [
    ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "鹽埕國中公開英文段考", "提示寫作、句子排序、連接詞與段落組織"),
    ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "北投國中公開定期評量試題頁", "短段落提示、支持細節與語意銜接"),
    ("https://www.hcjh.ntpc.edu.tw/p/406-1000-7527%2Cr146.php", "新埔國中公開段考試題頁", "讀者、段落連貫、改寫與修訂"),
]

def refs():
    return [{"url": u, "title": f"{t}；只取{loc}的能力方向，未複製原題、選項、圖表或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量常把主題句、支持細節、句子順序、連接詞、完整句與讀者目的放進生活情境；本課將能力重新改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in URLS]

def research(publisher, url, focus):
    return {"publisher": publisher, "edition": f"{publisher} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": f"{url}；{focus}；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["從主題句建立段落焦點，再以支持細節完成意思。", "用順序、連接詞、完整句與結尾讓讀者能追蹤訊息。"], "representations": ["主題句、支持句、流程大綱、連接詞、結論句與提示圖表。"], "examplesOrEvidence": ["本課以節水、步行上學、種豆、社團建議、校園菜園、整理環境與安全路線等原創情境重組能力。"], "misconceptions": ["把無關事實當支持細節、只寫片段、順序跳躍，或忽略讀者與目的。"], "assessmentEmphasis": ["評量焦點、細節相關性、組織、銜接、完整句與修訂。"]}, "licenseBoundary": "本紀錄只保存公開來源的章節定位、教學方向與評量能力；不抄錄任何出版社或學校教材正文、原題、選項、圖片、答案、影音或版面。"}

def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    data.update({"title": "4-Ⅳ-8：依主題句、支持細節與連接詞寫出有組織的簡短段落", "updatedAt": "2026-09-21", "authoringStandard": "version-fused-v1"})
    data["content"] = {"summary": "簡短段落不是把幾句英文排在一起，而是讓主題句先告訴讀者方向，再用相關細節、合理順序、連接詞與結尾完成一個可追蹤的意思。本課以節水、步行上學、種豆、社團、菜園、環境整理與安全騎車等原創情境，練習從提示規劃、成句、組織到修訂。", "sections": [{"heading": "先找段落的中心", "body": "主題句要能回答段落在談什麼，且留下可展開的焦點。例如 We can save water through small daily actions. 後面可以接關水龍頭、重複使用水等細節；Yesterday my pencil fell under the desk 雖然是完整句，卻沒有支撐節水主題。"}, {"heading": "支持細節要有工作", "body": "每一句支持句都要證明、解釋、舉例或推進主題。看到提示資料時，問它是在回答 how、why、when 還是 what next；若只換話題，便不是支持細節。"}, {"heading": "順序和連接詞讓讀者跟得上", "body": "步驟可用 first、next、finally；原因與結果可用 because、therefore、as a result；轉折可用 however。連接詞不是裝飾，要檢查前後兩句的邏輯是否真的相接。"}, {"heading": "完整句與結尾完成溝通", "body": "Because the rain was heavy. 只有從屬子句，讀者會等待主要句；可改為 We stayed inside because the rain was heavy. 結尾則回扣建議、結果或下一步，使段落不突然中止。"}]}
    data["studyHighlights"] = ["用主題句定義單一焦點，再檢查每個細節是否支撐它。", "依流程、時間、因果或重要性安排句子，不把連接詞當成萬用填空。", "辨認片段並補足主詞與主要動詞，最後用結尾回扣讀者目的。", "寫完以讀者視角重讀：是否知道主題、理由、順序與下一步。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "一串句子為什麼還不像段落？", "body": "把節水主題的兩個相關句和一個鉛筆句混在一起，請學生用讀者視角圈出離題句。接著替段落貼上主題、支持或離題標籤，先感受焦點比文法術語更早決定可讀性。"}, {"id": "explain", "phase": "explain", "heading": "段落地圖：主題—證據—關係—收束", "body": "先寫一句 topic sentence，再為每個提示標記它要提供例子、原因、步驟或結果，接著選擇順序與連接詞，最後加上 conclusion。每句都必須能回答『它怎麼幫助讀者理解中心？』。"}, {"id": "worked-example", "phase": "worked-example", "heading": "把種豆提示排成可讀流程", "body": "將 cover the seed、water it gently、put soil in a cup、watch it grow 重新排序為容器—土壤—種子—澆水—觀察，示範先用時間順序，再用 first、next、then、finally 讓讀者不必猜步驟。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一提示換成不同功能句", "body": "小組從校園菜園、環境整理或安全騎車提示卡中，分別寫主題句、兩個支持細節與結尾；交換後由讀者指出一個離題句、一個缺少連接的地方和一個可補強的理由。"}, {"id": "transfer", "phase": "transfer", "heading": "為真實讀者寫一段建議", "body": "選擇給低年級學生的安全路線或社團建議，先畫三格大綱，再寫五句短段落。保留地圖或提示提供的限制，依讀者需要選 because、so、however 或 finally，不能只堆砌漂亮單字。"}, {"id": "reflect", "phase": "reflect", "heading": "用四問修訂自己的段落", "body": "逐句問：主題清楚嗎？細節相關嗎？順序能追蹤嗎？結尾有回扣嗎？將片段補成完整句，將跳躍處加上真正表達邏輯的連接詞，再朗讀確認讀者能預測下一步。"}], "summary": ["主題句先建立焦點，支持句再提供例子、原因、步驟或結果。", "用提示資料決定段落順序，不用無關句填滿字數。", "連接詞必須表達真實的時間、因果或轉折關係。", "補足完整句並以結尾回扣目的，再從讀者角度修訂。"], "exitCheck": [{"prompt": "如何判斷一句話是支持細節而不是離題資訊？", "expectedEvidence": "能指出它如何解釋、舉例、證明或推進主題句，並排除只在同一情境出現但沒有關係的句子。"}, {"prompt": "寫流程段落時，為什麼不能只把 first、next、finally 填上去？", "expectedEvidence": "能說明連接詞要符合實際順序，並能用種豆或其他課內流程展示前後關係。"}, {"prompt": "看到 Because the rain was heavy. 時要怎麼修訂？", "expectedEvidence": "能補上主要子句，例如 We stayed inside because the rain was heavy，並說明補足主詞和主要動詞。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "依提示建立主題句、支持細節、邏輯連接與完整結尾，完成可讀的短段落。", "scenario": "你是校刊小編，要把同學提供的提示整理成給真實讀者看的五句英文段落。", "variables": [{"symbol": "t", "meaning": "topic sentence 與單一焦點"}, {"symbol": "s", "meaning": "supporting details、順序與連接詞"}, {"symbol": "c", "meaning": "complete sentence、conclusion 與讀者目的"}], "steps": [{"id": "step-1", "prompt": "Which sentence is the best topic sentence for a paragraph about saving water?", "options": ["We can save water through small daily actions.", "My blue pencil fell under the desk yesterday.", "Water is a word with five letters."], "answer": "A", "feedback": "A 提出節水這個可展開的中心；B、C 雖可成句，但沒有建立段落焦點。"}, {"id": "step-2", "prompt": "The class reused boxes and spent less money. Which connector best shows the result?", "options": ["Therefore,", "However,", "Meanwhile,"], "answer": "A", "feedback": "Therefore 表示前一句行動造成後一句結果；however 是轉折，meanwhile 是同時發生。"}, {"id": "step-3", "prompt": "How can you revise the fragment Because the rain was heavy.?", "options": ["We stayed inside because the rain was heavy.", "Because the rain was heavy and.", "The rain because was heavy."], "answer": "A", "feedback": "A 補上主要子句 We stayed inside，形成完整句並保留原因關係。"}]}
    data["versionResearch"] = [research("nani", URLS[0][0], "生活提示、段落主旨與寫作遷移"), research("kanghsuan", "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf", "任務、句子組織、連接與讀者"), research("hanlin", "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf", "功能文本、短文組織與修訂")]
    data["fusionRecord"] = {"commonCore": ["三筆公開課程與評量證據共同支持以提示完成有目的的英文短文。", "段落理解需要主題、相關細節、順序、連接和完整句。", "寫作必須依讀者與目的修訂，而不是只追求句數。"], "versionDifferences": ["南一較適合從生活提示進入主旨與遷移；康軒較突顯任務、句子組織與讀者；翰林較突顯功能文本、段落結構與修訂。本課把三種方向重組為段落地圖。"], "originalAdditions": ["以節水、步行、種豆、菜園與安全路線設計不同寫作入口。", "用離題句診斷、四問修訂與連接詞邏輯卡形成互動。", "以讀者能否預測下一步作為段落成功標準。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方公開證據與本單元 KG，獨立重寫主題句、支持細節、組織、連接、完整句與結尾；未複製公開試題、選項或答案。Terra 第二輪與正式發布審查尚未完成，維持 draft。"}
    explanations = ["A 能提出節水的單一焦點，後文可用行動細節展開；其餘句子離題或只談字面。", "支持句必須解釋步行如何改善社區健康，而非只重述天氣或個人物品。", "種豆要依實際先後排列，先準備容器與土，再放種子、澆水、觀察。", "給低年級學生建議時，開頭應直接提出加入社團的好處或建議，讓讀者知道段落方向。", "重複使用盒子造成少花錢的結果，因此用 Therefore 最準確。", "菜園能讓學生學科學，觀察根、莖或發芽變化是直接支持此主題的細節。", "結尾應回扣整理環境的做法與共同責任，不能突然加入無關活動。", "Because 子句不能獨立成句，補上 We stayed inside 才有完整主句。", "好的大綱依研究、安排、練習、回顧等焦點組織，不把不同主題混在一起。", "安全路線段落要同時交代安靜巷道、地圖標記與停看聽等行動，才能符合讀者的安全目的。"]
    strategies = ["先辨認寫作目的與讀者，再建立主題—支持—結尾的段落地圖，最後檢查句子完整與邏輯連接。"] * 10
    steps = ["讀提示並圈出主題、讀者、目的、限制與可用資料。", "先寫或辨認能統攝全文的主題句，排除雖完整但離題的句子。", "將其餘資訊分類成例子、原因、步驟、結果或結論，再依真實邏輯排序。", "檢查連接詞是否表達正確的時間、因果或轉折，並補足主詞與主要動詞。", "從讀者角度重讀全文，確認每句都支撐焦點、結尾有收束，且答案能由提示證明。"]
    for i, p in enumerate(sorted(ROOT.glob("questions/english/question-english-performance-4-iv-8-*.json"), key=lambda x: int(x.stem.rsplit('-', 1)[1])), 1):
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = strategies[i-1]; q["solutionSteps"] = steps; q["answer"]["explanation"] = f"{explanations[i-1]} 正確答案：{q['answer']['value']}"; q["provenance"]["sourceLocator"] = "公立學校公開英文評量中的提示寫作、句子組織、連接與修訂能力；本題改寫為本單元原創情境。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 4-iv-8")

if __name__ == "__main__":
    main()
