import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-2-iv-2.json"
REPORT = ROOT / "implementation/reports/english-performance-2-iv-2-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創寄宿家庭、校園、商店、車站、鄰里與聚會對話，承接公開課程的日常用語、禮貌互動與情境溝通方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-2-iv-2"
    data["title"] = "2-Ⅳ-2：依社交情境選擇自然、禮貌的生活用語"
    data["content"] = {"summary": "生活用語的正確性不只在文法，也在於是否符合時間、關係、場合與對方需要。同一句拒絕、道歉、邀請或求助，若忽略語氣與後續行動，可能讓對方感到失禮或得不到幫助。本課以寄宿家庭初見、踩到腳、借充電器、邀讀書、擁擠公車站、車站迷路、商店婉拒、比賽恭喜、鄰居搬箱子與生日邀約等原創情境，練習辨識社交目的、選擇自然句型、補足理由或替代方案，並檢查對話能否順利繼續。", "sections": [{"heading": "先判斷關係和場合", "body": "第一次見寄宿家庭的晚上可用 Good evening，對熟朋友則可能用 Hi；這不是死背時間表，而是同時看見面時間、熟悉程度與互動目的。先問 Who、When、Where，再從候選句中排除太隨便或太正式的用語。"}, {"heading": "道歉、感謝與邀請要接上下一步", "body": "踩到同學先說 I am sorry，再確認對方是否沒事；借到充電器先 Thank you，再說明幫助；邀請讀書則給出時間和活動。生活用語若只說一個禮貌詞，對方仍不知道事情如何往下走。"}, {"heading": "拒絕可以保留關係", "body": "商品太貴或不能赴生日晚餐時，先表達感謝或遺憾，再給出簡短原因，必要時提出替代時間。I am sorry, I cannot make it because … 比直接 No 更能讓對方理解限制；理由要真實且不需要揭露過多私人細節。"}, {"heading": "求助與提供幫助要具體", "body": "迷路時說 Could you tell me how to get to the station? 比 Help me 更能讓對方知道任務；看到鄰居搬重箱子，可問 Would you like some help?，把選擇權留給對方。自然溝通同時照顧資訊清楚和對方自主。"}]}
    data["studyHighlights"] = ["以關係、時間、地點與目的判斷生活用語是否自然。", "讓道歉、感謝、邀請和拒絕連接理由、確認或下一步。", "用禮貌拒絕保留關係，不過度透露私人資訊。", "以具體求助和可選擇的幫助句讓對話真正可行。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "同一句 No 會造成什麼差別？", "body": "安排完全自編的商店與生日邀約兩幕：學生先用 No 回應，再比較加上 Thank you、I am sorry、because 或替代時間後，對方是否知道原因與下一步。活動不先講規則，讓學生從對話能否繼續的結果發現禮貌語句的功能。"}, {"id": "explain", "phase": "explain", "heading": "情境用語四格卡", "body": "每個情境填 Who／Purpose／Tone／Next move 四格。Who 看關係與對象，Purpose 判斷是問候、道歉、感謝、邀請、拒絕、求助或祝賀，Tone 選自然禮貌程度，Next move 檢查是否需要理由、時間、方向或確認。"}, {"id": "worked-example", "phase": "worked-example", "heading": "把婉拒寫成保留關係的句子", "body": "以朋友生日晚餐但有家庭活動的原創對話示範：I am sorry, I cannot come because I have a family event. Could we meet another day? 先表達遺憾，再給必要原因，最後提出替代方案；比較直接 No 與過度解釋，討論兩者各自的溝通問題。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "用角色卡配對自然句型", "body": "給寄宿家庭、擁擠公車站、車站迷路、借充電器與鄰居搬箱子五組角色卡。學生抽卡後先說目的，再選一句並演出；同伴只用 Who、Purpose、Next move 檢查，若句子太模糊或太命令式，要求現場改寫而非背標準答案。"}, {"id": "transfer", "phase": "transfer", "heading": "同一目的換不同關係", "body": "把問路、邀請、拒絕與提供幫助分別改成對朋友、老師、陌生人和鄰居的版本。學生保留核心任務但調整稱呼、禮貌程度與資訊量，最後讓對方用一句話重述自己聽到的請求，驗證語句真的清楚。"}, {"id": "reflect", "phase": "reflect", "heading": "我有禮貌但有完成任務嗎？", "body": "回看錄音，把句子標成 greeting、reason、request、response、next move。若只有禮貌詞而缺少目的，補上具體問題；若只有命令而忽略對方選擇，改成 Could you …? 或 Would you like …?，再請同伴判斷關係是否被保留。"}], "summary": ["以 Who、Purpose、Tone、Next move 四格分析生活用語。", "讓禮貌詞和理由、確認、方向或替代方案連在一起。", "依關係調整同一溝通目的的正式程度與資訊量。", "以對方能否重述請求檢查語句清楚與對話延續。"], "exitCheck": [{"prompt": "選生活用語時為何要看關係與場合？", "expectedEvidence": "能指出時間、熟悉程度、地點與目的會影響問候或請求的自然程度。"}, {"prompt": "怎樣拒絕才不會只剩下生硬的 No？", "expectedEvidence": "能先表達感謝或遺憾，提供必要簡短原因，並在適合時提出替代方案。"}, {"prompt": "求助或提供幫助如何保留對方自主？", "expectedEvidence": "能使用具體問題或 Would you like some help?，讓對方知道任務並保留選擇。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "依關係、場合與社交目的選擇自然禮貌的生活用語，並讓對話能繼續。", "scenario": "學生在一天的校園與社區生活中，輪流處理初次見面、道歉、感謝、邀請、問路、婉拒、祝賀與提供幫助的情境。", "variables": [{"symbol": "c", "meaning": "關係、時間、地點與場合"}, {"symbol": "p", "meaning": "問候、道歉、邀請、拒絕、求助或祝賀目的"}, {"symbol": "n", "meaning": "理由、確認、替代方案與下一步"}], "steps": [{"id": "step-1", "prompt": "You meet your host family for the first time at 7 p.m. Which greeting is most appropriate?", "options": ["Good evening. It is nice to meet you.", "See you tomorrow; I am leaving now.", "Give me the room key."], "answer": "A", "feedback": "A fits the evening, first meeting, and welcoming purpose; the other choices do not perform an appropriate greeting."}, {"id": "step-2", "prompt": "You cannot attend a friend's birthday dinner because of a family event. Which reply is most considerate?", "options": ["I am sorry, I cannot come because of a family event. Could we meet another day?", "No. Do not ask me again.", "I like birthdays, so the dinner is expensive."], "answer": "A", "feedback": "A shows regret, gives a brief reason, and offers a possible next step without oversharing."}, {"id": "step-3", "prompt": "A neighbor is carrying several heavy boxes. You want to offer help. Which sentence is best?", "options": ["Would you like some help with those boxes?", "Give me every box now.", "The boxes are heavy, so I will walk away."], "answer": "A", "feedback": "A offers specific help while leaving the neighbor the choice to accept or decline."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語生活用語、問候與情境溝通定位；核讀 2026-09-21。", ["在生活情境中使用基本問候、請求、道歉與回應。", "依對象和目的進行簡易英語互動。"], ["寄宿家庭、朋友、商店、交通、邀請、拒絕與祝賀。"], "只記一個禮貌詞，沒有完成實際溝通目的。", "重視生活對話、禮貌表達與情境回應。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語聽說、角色扮演與日常任務定位；核讀 2026-09-21。", ["透過角色、圖片和日常任務使用生活用語。", "依關係、場合與後續行動調整回應。"], ["初見、道歉、感謝、邀請、問路、拒絕、恭喜與幫助。"], "把對朋友的直白說法直接套給陌生人或長輩。", "評量主要訊息、禮貌、角色互動與功能性表達。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語日常溝通功能與情境評量定位；核讀 2026-09-21。", ["從對話目的、關係和語氣選擇自然生活用語。", "以簡短理由、確認與替代方案延續互動。"], ["greeting、apology、thanks、invitation、refusal、directions、congratulation、offer。"], "將禮貌等同過度正式，或婉拒時加入不必要的私人細節。", "評量語意功能、情境適切性、禮貌與對話延續。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持生活用語、日常對話、角色互動與禮貌表達。", "自然用語需同時符合關係、時間、地點、目的、語氣與下一步。", "從選句到實際對話可用角色卡、替換關係與同伴重述驗證。"], "versionDifferences": ["南一較突顯生活問候與情境口語；康軒較突顯角色、圖片、日常任務與互動；翰林較突顯語意功能、關係、語氣、理由與對話延續評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Who、Purpose、Tone、Next move 四格分析生活用語。", "用寄宿家庭、商店、車站、生日與鄰里原創情境練習禮貌目的。", "以改換關係和同伴重述檢查句子是否自然、清楚且保留自主。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織問候、道歉、感謝、邀請、拒絕、求助、祝賀、問路與提供幫助的情境語用。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 四格卡完成後請把同一句核心目的換成朋友與陌生人兩種版本，觀察 Tone 和資訊量如何改變；句型不是固定答案，而是受情境約束的工具。"
    data["teaching"]["body"][4]["body"] += " 改換關係時保留必要任務資訊，避免只把句子變長；對方能否正確採取下一步，比句子看起來是否正式更重要。"
    data["teaching"]["body"][5]["body"] += " 若同伴只能說你很客氣卻說不出你的請求，補上動作、時間或地點；若同伴感到被命令，改用疑問句並保留拒絕的空間。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "2-Ⅳ-2：依社交情境選擇自然、禮貌的生活用語", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 2-iv-2")


if __name__ == "__main__":
    main()
