import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-2-iv-6.json"
REPORT = ROOT / "implementation/reports/english-performance-2-iv-6-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創通知、時間表、地點線索、物品辨識、原因與事件順序，承接公開課程的人事時地物理解與簡易回答方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-2-iv-6"
    data["title"] = "2-Ⅳ-6：從句子線索完整回答人、事、時、地、物與原因"
    data["content"] = {"summary": "回答 Who、What、When、Where、Which、Why 或 What happened next 時，不能只抓句子裡最醒目的名詞；要先找問題焦點，再把人物、動作、時間、地點、物品、原因與順序配對。本課用原創校門、圖書館、社團時間、失物箱、藝術社、室內會議、表單流程與科展公告，練習從一句或數句訊息抽取必要欄位，排除位置介系詞、時間格式、物品特徵與因果順序的混淆，最後用完整但不多加內容的英文回答。", "sections": [{"heading": "先圈問題焦點再回句子找答案", "body": "Where is the science fair? 需要地點，Who is waiting? 需要人物；即使同一句同時含有時間和物品，也不能把所有資訊堆在回答裡。先圈問句中的疑問詞，再在文本找同一欄位，能避免答非所問。"}, {"heading": "介系詞和時間詞改變答案", "body": "under the bench 與 on the bench 不同，beside the school gate 與 inside the gate 也不同；at 4:10 p.m.、on Wednesday 和 behind the cafeteria 分別回答時間、日期與位置。回答前把介系詞短語連回正確欄位，不要只抄名詞。"}, {"heading": "物品辨識需要多個特徵", "body": "small silver key with a red tag marked Lab 2 的物件要同時符合大小、顏色、形狀、標籤；只符合 silver 或 red 的選項不夠。將描述拆成特徵清單，再逐項核對，才能避免看到一個相同顏色就提前選答。"}, {"heading": "Why 和 after 要保留關係", "body": "Nora moved the meeting indoors because strong wind began，原因是強風，不是室內本身；Ken printed、signed、placed 的順序則要求找 after printing 的下一步。將 because 接原因、then／after 接時間順序，回答才不會把結果和理由對調。"}]}
    data["studyHighlights"] = ["先依疑問詞定位人、事、時、地、物或原因欄位。", "將介系詞、時間詞、特徵與動詞連回正確資訊。", "以多個物品特徵交叉核對，避免只憑單一醒目細節。", "用 because、then、after 保留因果與事件順序。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "回答越長越完整嗎？", "body": "給出完全自編的科展公告，學生先用一句話回答 Where，再有人把人物、時間、原因全部塞進答案。請聽者指出哪個回答最快解決問題，讓學生看見完整不等於堆滿所有資訊，而是精準提供疑問詞要求的欄位。"}, {"id": "explain", "phase": "explain", "heading": "人事時地物七欄卡", "body": "建立 Who、What、When、Where、Which、Why、Next 七欄。先在問句圈疑問詞，再從文本把片語貼入對應欄，最後只取回答需要的欄位；若問 why，必須追到 because 或事件原因，不能拿地點或結果代替。"}, {"id": "worked-example", "phase": "worked-example", "heading": "用介系詞定位物品", "body": "以 The blue backpack is under the bench, not on it. 示範：先找物品，再比較 under 和 on 的空間關係，最後在答案中保留 under the bench。把圖片中的長椅和背包位置移動一次，讓學生驗證介系詞改變時答案也必須改變。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "從特徵清單找唯一物品", "body": "給出四把外觀相近的原創鑰匙卡，問題描述 small、silver、red tag、Lab 2。學生先逐項打勾，再用完整句回答 Which object；交換後同伴刪掉一個特徵，作者說明是否還能唯一辨認，理解答案品質取決於證據足夠。"}, {"id": "transfer", "phase": "transfer", "heading": "把同一段訊息回答成不同問題", "body": "輪換社團時間、失物箱、室內會議、表單流程、校門人物與科展地點。每組用同一段文字抽出三個不同疑問詞，先寫最短準確答案，再加一句必要的完整句；同伴檢查每句是否只回答所問，並保留原因或順序關係。"}, {"id": "reflect", "phase": "reflect", "heading": "我是不是答對欄位卻答錯關係？", "body": "回看答案，將錯誤分成疑問詞錯配、介系詞錯配、特徵不足、原因結果對調、順序漏步驟五類。修訂時只改造成錯的欄位，重新回指原句，避免用更多未證實的內容掩蓋真正缺口。"}], "summary": ["用七欄卡將疑問詞連結到必要資訊。", "辨認介系詞、時間格式與動詞順序的精確差異。", "用多特徵清單辨認唯一物品或人物。", "以 because、then、after 保留原因、結果與先後。"], "exitCheck": [{"prompt": "回答疑問句前為什麼要先圈疑問詞？", "expectedEvidence": "能指出疑問詞決定要取人物、動作、時間、地點、物品、原因或下一步哪一欄。"}, {"prompt": "如何避免把 under 和 on 的位置混淆？", "expectedEvidence": "能回到介系詞短語與圖像或文字位置，說明回答要保留正確空間關係。"}, {"prompt": "Why 和 after 的答案各要保留什麼？", "expectedEvidence": "能用 because 或原因回答 why，用 then／after 指出正確的下一步順序。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "從原創訊息中精確定位人、事、時、地、物、原因與順序，回答符合疑問詞的英文句子。", "scenario": "學生擔任校園資訊台助理，要根據失物、社團、科展與活動訊息，替不同提問者快速提供不多不少的答案。", "variables": [{"symbol": "q", "meaning": "疑問詞與問題焦點"}, {"symbol": "e", "meaning": "人物、動作、時地、特徵與原因證據"}, {"symbol": "r", "meaning": "精準答案、因果與事件順序"}], "steps": [{"id": "step-1", "prompt": "Mia is carrying a yellow umbrella and waiting beside the school gate. Who is waiting there?", "options": ["Mia is waiting there.", "A yellow umbrella is waiting there.", "The school gate is waiting there."], "answer": "A", "feedback": "Who asks for the person; the action and location add evidence but do not replace Mia as the answer."}, {"id": "step-2", "prompt": "The art club meets every Wednesday at 4:10 p.m. When does it meet?", "options": ["It meets every Wednesday at 4:10 p.m.", "It meets next to the nurse's office.", "It meets because the wind is strong."], "answer": "A", "feedback": "A includes both the recurring day and exact time required by When; the other choices answer place or reason."}, {"id": "step-3", "prompt": "Nora moved the meeting indoors because strong wind began. Why did she move it?", "options": ["Because strong wind began.", "Because the meeting was behind the cafeteria.", "Because she printed the form first."], "answer": "A", "feedback": "Why asks for the cause, and A directly preserves the because relationship in the notice."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語人事時地物、生活訊息與問答定位；核讀 2026-09-21。", ["由生活短句和公告理解人物、事件、時間、地點與物品。", "以疑問詞、圖片和情境支持基本回答。"], ["人物、動作、時間、地點、物品、原因與順序。"], "看到一個名詞就回答，沒有核對疑問詞要求的欄位。", "重視主要內容、細節定位與簡易回答。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語聽讀、圖像、時間地點與任務定位；核讀 2026-09-21。", ["透過圖像、文字和生活任務抓住人事時地物。", "依順序、位置、特徵和原因完成回應。"], ["校門、圖書館、社團時間、失物、會議與科展。"], "把時間、地點、原因或結果互相替換，形成答非所問。", "評量主要訊息、細節、順序與功能性回應。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語資訊定位、疑問詞與情境評量定位；核讀 2026-09-21。", ["從句子線索、疑問詞和事件關係形成精確理解。", "以完整短句回答人事時地物、原因與下一步。"], ["who、what、when、where、which、why、after、because。"], "只摘錄片語，沒有保留介系詞、特徵、因果或先後關係。", "評量資訊定位、細節、因果、順序與簡易摘要。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持人事時地物、生活訊息、疑問詞理解與簡易回答。", "精確回答需整合問題焦點、介系詞、時間、物品特徵、因果與順序。", "從資訊抽取到完整短句可用七欄卡、位置移動、特徵核對與角色任務驗證。"], "versionDifferences": ["南一較突顯生活短句與基本疑問詞；康軒較突顯圖像、時間地點、任務與順序；翰林較突顯資訊定位、介系詞、因果、順序與完整回答評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Who、What、When、Where、Which、Why、Next 七欄定位回答範圍。", "用校門、失物、社團、表單、會議與科展原創資訊練習欄位配對。", "以位置移動、特徵刪除和陌生提問者檢查答案是否精準可執行。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織人物、動作、時間、地點、物品、特徵、原因、結果與事件順序的問答策略。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 七欄不是要每題都填滿，而是先用疑問詞選欄，再從原句取足以回答的資訊；多餘欄位若造成混淆，應刪去而不是硬塞進答案。"
    data["teaching"]["body"][4]["body"] += " 同一段訊息換疑問詞時，保留原有證據關係但縮放答案範圍；若問題改成 Why，不可把原本的 Where 片語直接搬過去。"
    data["teaching"]["body"][5]["body"] += " 修訂後請讓陌生同伴只讀答案指出位置、時間或原因；若他仍需回看全文，補的是必要欄位，不是任意增加背景故事。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "2-Ⅳ-6：從句子線索完整回答人、事、時、地、物與原因", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 2-iv-6")


if __name__ == "__main__":
    main()
