import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-performance-pc-iv-2.json"; REPORT=ROOT/"implementation/reports/science-performance-pc-iv-2-first-pass-review.json"
URLS={"nani":"https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf","kanghsuan":"https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110","hanlin":"https://drive.google.com/uc?id=1gMUVcDjfXmqIapg-fNnfPuLFaK98dxGX&export=download"}
def rec(p,c,r,m,a): return {"publisher":p,"edition":f"{p} 公立校方自然課程計畫章節級證據","sourceType":"public-web","sourceLocator":f"{URLS[p]}；探究表達、資料溝通與評量欄位；核讀 2026-09-21。","reviewedAt":"2026-09-21","findings":{"concepts":[c,"公開課程結構支持依受眾、問題、資料與證據選擇圖表、文字、口頭或模型等表達形式。"],"representations":[r],"examplesOrEvidence":["本課的河川簡報、植物圖表與噪音海報皆為原創表達情境，只承接公開課程所示的能力方向。"],"misconceptions":[m],"assessmentEmphasis":[a]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。"}
def main():
 d=json.loads(LESSON.read_text(encoding="utf-8")); assert d["id"]=="lesson-science-performance-pc-iv-2" and d["reviewStatus"]=="draft"
 d["title"]="pc-Ⅳ-2：以多種形式完整表達探究過程與成果——讓不同讀者看懂證據"
 d["content"]={"summary":"完整表達探究成果不是把文字塞滿投影片，而是讓讀者沿著問題、方法、資料、分析、結論和限制理解證據如何形成。圖表適合呈現比較與變化，文字可交代背景和限制，口頭說明能回應問題，模型或流程圖能展示機制；形式要配合受眾與目的，所有形式都不能省略資料來源、不確定性和未回答的問題。本課用河川簡報、植物圖表與噪音海報設計原創表達任務。","sections":[{"heading":"先決定讀者要理解什麼","body":"給同學看的方法卡、給居民看的河川說明和給研究小組的技術報告，重點與詞彙不同。先寫受眾、核心問題和希望讀者做的判斷，再選擇圖表、文字、口頭或模型，避免形式先行。"},{"heading":"每種形式都有證據責任","body":"圖表要有標題、軸、單位、分母和資料來源；文字要區分觀察、推論與限制；口頭報告要能回答追問；模型要寫假設和適用範圍。好看的設計不能替代可追溯資料。"},{"heading":"讓結論和資料連在一起","body":"用『主張—證據—推理—限制』檢查每一段。不要只報告最高值，也要顯示變異、異常、樣本與未測量因素。若圖表不能支持結論，就改寫結論或補資料，不要改色彩掩蓋。"},{"heading":"可理解也要可檢查","body":"合理的字級、色彩對比、替代文字、圖例和口頭描述，能讓更多人讀取證據；引用來源、版本和日期則讓讀者追查。表達完整包括承認不知道，以及說明下一步如何驗證。"}]}
 d["studyHighlights"]=["依受眾、問題與目的選擇圖表、文字、口頭、模型或流程圖。","讓每種形式保留資料來源、單位、變異、限制與不確定性。","用主張—證據—推理—限制檢查成果是否支持結論。","兼顧可讀性、可及性、引用、追溯與下一步。"]
 d["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"同一份資料要做三種報告","body":"河川水質資料要分別給國中生、居民和研究小組閱讀。請比較一張圖、三分鐘口頭說明和技術表格各自能回答什麼，再指出三者都不能省略的資料來源、單位、時間和限制。形式應服務理解，不是裝飾。"},{"id":"explain","phase":"explain","heading":"成果表達六欄骨架","body":"用問題、方法、資料、分析、結論、限制六欄搭骨架，再依受眾改變語氣和視覺。每個主張都回接一項證據和推理；若某欄沒有資料，就標示缺口，不能用更大的標題補足。"},{"id":"worked-example","phase":"worked-example","heading":"植物圖表的完整標註","body":"比較兩種光照下植物高度時，圖表要標示時間、單位、樣本數、平均與變異；文字再說明控制條件、異常和不能推及的範圍。只畫兩條粗線會讓讀者看不出樣本差異，也無法檢查因果。"},{"id":"guided-practice","phase":"guided-practice","heading":"噪音海報的讀者測試","body":"學生把噪音比較做成海報，卻只有紅綠色和『很吵』。學習者補上座標、分貝單位、地點、時間、資料來源、替代文字和條件式結論，再請不同讀者指出哪裡仍無法理解或追查。"},{"id":"transfer","phase":"transfer","heading":"同資料換一種形式","body":"每組把一份河川觀察資料改成圖表、口頭摘要和一頁海報三種版本；保留相同主張、證據與限制，說明哪些訊息因形式改變而更清楚、哪些可能被誤解，並附來源與日期。"},{"id":"reflect","phase":"reflect","heading":"修正兩個表達迷思","body":"請修正『圖表越漂亮就越有說服力』與『把所有資料放上去就叫完整』。完整是證據鏈、限制、來源和受眾都對齊；設計要提高理解與可及性，不能隱藏變異或替結論加戲。"}],"summary":["先界定受眾、問題與目的，再選擇表達形式。","圖表、文字、口頭與模型都要保留證據責任。","用主張、證據、推理和限制連結成果。","兼顧可讀性、可及性、來源追溯與不確定性。"],"exitCheck":[{"prompt":"為什麼同一資料要依受眾改變表達？","expectedEvidence":"不同讀者需要不同詞彙、背景和形式，但核心證據、來源與限制不能被刪除。"},{"prompt":"植物圖表至少要標示什麼？","expectedEvidence":"標題、軸、單位、時間、樣本數、平均／變異、資料來源與必要控制條件。"},{"prompt":"什麼叫做完整表達？","expectedEvidence":"問題、方法、資料、分析、結論、限制、來源、可及性與下一步彼此對齊，而非資料越多越好。"}]}
 d["interactive"]={"type":"guided-choice","goal":"依受眾選擇表達形式，並保留問題、證據、推理、限制與來源。","scenario":"把河川、植物與噪音探究資料改成圖表、口頭說明與海報，逐步檢查可理解性與可追溯性。","variables":[{"symbol":"a","meaning":"受眾與目的"},{"symbol":"f","meaning":"表達形式"},{"symbol":"e","meaning":"證據與限制"}],"steps":[{"id":"step-1","prompt":"給居民看河川水質結果，先考量什麼？","options":["受眾要理解的問題、必要背景與可讀形式，再保留單位、來源和限制","只選最華麗的動畫","刪掉不利結果讓訊息簡單"],"answer":"A","feedback":"A 讓形式服務理解，且不犧牲證據完整性。"},{"id":"step-2","prompt":"植物圖表缺少哪些項目時最難檢查？","options":["座標、單位、時間、樣本數、變異與資料來源","只缺少裝飾圖片","只缺少大標題","只缺少背景音樂"],"answer":"A","feedback":"A 是讀者重建比較與判斷所需的核心資訊。"},{"id":"step-3","prompt":"海報寫『很吵』，最好的改善是什麼？","options":["補上分貝定義、地點時間、圖表、來源、替代文字與條件式結論","把『很吵』放大並加紅色","刪除所有異常值","只增加口號"],"answer":"A","feedback":"A 同時改善證據、可讀性、可及性和結論界線。"}]}
 d["teaching"]["body"][1]["body"]="用問題、方法、資料、分析、結論、限制六欄搭骨架，再依受眾改變語氣和視覺。每個主張都回接一項證據和推理；若某欄沒有資料，就標示缺口，不能用更大的標題補足，還要讓讀者知道下一步如何查證。"
 d["teaching"]["body"][3]["body"]="學生把噪音比較做成海報，卻只有紅綠色和『很吵』。學習者補上座標、分貝單位、地點、時間、資料來源、替代文字和條件式結論，再請不同讀者指出哪裡仍無法理解或追查，並依回饋修正圖例與文字。"
 d["teaching"]["body"][4]["body"]="每組把一份河川觀察資料改成圖表、口頭摘要和一頁海報三種版本；保留相同主張、證據與限制，說明哪些訊息因形式改變而更清楚、哪些可能被誤解，並附來源與日期，最後比較三種版本的查證難度。"
 d["teaching"]["body"][5]["body"]="請修正『圖表越漂亮就越有說服力』與『把所有資料放上去就叫完整』，並各舉一個反例。完整是證據鏈、限制、來源和受眾都對齊；設計要提高理解與可及性，不能隱藏變異或替結論加戲。"
 d["teaching"]["exitCheck"][2]["prompt"]="什麼條件下才能稱為完整的探究成果表達？"
 d["authoringStandard"]="version-fused-v1"
 d["versionResearch"]=[rec("nani","以觀察、資料整理與科學表達讓探究成果可理解和檢核。","問題、圖表、文字、口頭、來源與限制。","把圖表美化或資料堆疊當成完整表達。","重視資料對齊、溝通對象與證據界線。"),rec("kanghsuan","透過實作、討論與多種媒介表達探究過程及成果。","受眾、簡報、海報、模型、同儕回饋與修正。","只重形式、不標單位來源，或把口頭自信當成證據。","評量表達清楚、資料正確與回應質疑。"),rec("hanlin","連結環境、生活與社群溝通，要求成果可追溯、可及與負責任。","河川、植物、噪音、圖表、可及性、引用與不確定性。","忽略讀者背景、替代文字與限制，或用設計隱藏變異。","要求多形式轉譯、來源透明、倫理與下一步。")]
 d["fusionRecord"]={"commonCore":["三版本公開結構共同支持以多種形式完整表達探究過程與成果。","受眾、問題、方法、資料、圖表、結論、限制與來源是共同要求。","表達形式可改變但證據責任、可檢查性與誠實限制不能省略。"],"versionDifferences":["南一證據較突顯觀察、資料整理與基本表達；康軒較突顯實作、討論、多媒介與同儕回饋；翰林較突顯環境社群、可及性、引用與責任溝通。這是公開課程計畫層級差異，不宣稱完整教材差異。"],"originalAdditions":["以河川資料針對三種受眾選擇不同表達形式。","以植物圖表練習平均、變異、樣本與控制條件標註。","以噪音海報導入替代文字、色彩可及性與條件式結論。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織受眾、形式、問題、方法、資料、主張、證據、推理、限制、可及性與來源追溯。正文、原創情境、互動步驟、錯誤回饋與檢核均為本專案重寫，未複製任何教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
 d["updatedAt"]="2026-09-21"; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"pc-Ⅳ-2：以多種形式完整表達探究過程與成果","lessonId":d["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 print("pc-iv-2 lesson authored")
if __name__=="__main__": main()
