import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-2-iv-4.json"
REPORT = ROOT / "implementation/reports/english-performance-2-iv-4-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創家人朋友描述、外貌、個性、習慣、分工、比較與關係維繫情境，承接公開課程的人物介紹與尊重表達方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-2-iv-4"
    data["title"] = "2-Ⅳ-4：以具體、尊重的英語描述家人與朋友"
    data["content"] = {"summary": "描述家人和朋友不只是列出身高、髮色或親屬稱謂；完整介紹要選擇與目的有關的外貌、個性、習慣、能力、分工與相處證據，並避免把短暫行為誇大成固定標籤。本課以姊妹、表兄弟、祖父、同學、手足、阿姨與朋友等原創人物卡，練習使用 be、have、like、prefer、比較句、頻率與時間片語，最後把細節組成自然段落，讓讀者看見人物如何行動以及關係如何維持。", "sections": [{"heading": "先分辨外貌和個性", "body": "Maya has short hair and wears glasses 是可觀察的外貌；Jordan listens before answering 則是由多次互動支持的行為特徵。描述時先標記看見、聽見或文本明確說出的內容，再決定用 is、has、wears 或 likes，避免把一次安靜直接寫成 shy forever。"}, {"heading": "習慣要帶時間或頻率", "body": "Nina practices before breakfast on weekdays，和我 after dinner 練習，差異不在誰比較努力，而在時間安排。always、usually、on Saturdays、before dinner 等片語讓讀者知道行為何時發生，也能支撐比較與人物生活節奏。"}, {"heading": "從行動提出有邊界的個性描述", "body": "Tom 每週幫祖父搬雜貨，Sara 等同伴說完、微笑並鼓勵重試，這些行動支持 helpful 或 patient 等概括；摘要仍應保留證據，不必把人物封成永遠完美。描述個性時可用 He is careful with his words because …，把形容詞接回行動。"}, {"heading": "關係描述要包含持續互動", "body": "Aunt moved to a new city 後，主角每週打電話並傳花園照片，主旨是用固定行動維持關係，而不是只報告搬家。家人分工、共同興趣與互相支持也要用 who does what、when、why 組成，讓人物介紹有生活脈絡。"}]}
    data["studyHighlights"] = ["分開描述外貌、個性、習慣、能力、分工與關係證據。", "用 be、have、like、prefer、比較與時間片語組織人物資訊。", "從重複或具體行動提出有邊界的個性概括。", "以持續互動、分工與共同活動表達家人朋友關係。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "只知道髮色就算介紹一個人嗎？", "body": "展示兩張完全自編的人物卡：一張只有 short hair、glasses、tall，另一張加入每週習慣、興趣和對同伴的行動。學生先讓同伴根據卡片猜人物，再比較哪張能預測更多生活情境，發現完整描述要選與目的相關的證據。"}, {"id": "explain", "phase": "explain", "heading": "人物描述六欄圖", "body": "建立 Who、Looks、Acts、Habits、Relationships、Evidence 六欄。先把外貌與可重複行動分開，再補時間或頻率，最後寫出人物和他人的互動；每個 personality adjective 後面要貼一張行動證據卡，避免只列空泛形容詞。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從行動寫出有邊界的個性", "body": "以 Sara 在同伴報告出錯時等待、微笑、鼓勵重試為例，先寫 She waits and encourages her friend. 再寫 She is patient and supportive because …；比較若只寫 She is nice，讀者少了哪些可以核對的行動與情境。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "把人物卡組成自然段落", "body": "給姊妹、表兄弟、祖父、朋友與手足五張原創卡，學生先用句型分類 looks、likes、practices、helps、compares，再選三類組成四句介紹。交換後同伴圈出每句的證據與時間詞，若形容詞沒有行動支援就改寫。"}, {"id": "transfer", "phase": "transfer", "heading": "為不同讀者調整人物介紹", "body": "同一人物分別介紹給新同學、交換學生、家庭相簿讀者與社團隊友。學生保留真實且必要的資訊，調整正式程度與細節比例；涉及身高、外貌或個性時用尊重、非嘲弄的語句，並加入讀者真正需要知道的共同活動或合作方式。"}, {"id": "reflect", "phase": "reflect", "heading": "我的描述有證據也有尊重嗎？", "body": "回看段落，將每句標成 observation、repeated action、comparison、relationship 或 unsupported label。刪掉把一次事件變成永久性格的字，補上時間、頻率或具體行動，再請同伴用人物卡找回原始證據，檢查描述沒有超出資料。"}], "summary": ["用 Who、Looks、Acts、Habits、Relationships、Evidence 六欄組織介紹。", "將個性形容詞接回重複或具體行動，避免固定標籤。", "用時間、頻率、比較和分工句型增加人物脈絡。", "依讀者調整資訊，維持真實、必要與尊重的描述。"], "exitCheck": [{"prompt": "外貌、個性和習慣的證據有何不同？", "expectedEvidence": "能分別指出可觀察特徵、由行動推得的特質與帶有時間或頻率的重複行為。"}, {"prompt": "如何避免把一次行為誇大成固定標籤？", "expectedEvidence": "能回到多次或明確行動，加入時間與情境限制，或改用較保留的描述。"}, {"prompt": "如何把人物介紹寫得符合讀者需要？", "expectedEvidence": "能依讀者保留必要外貌、興趣、分工或互動資訊，並使用尊重、不嘲弄的語句。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "從人物卡的外貌、行動、習慣、比較與關係證據，組成清楚、尊重且有脈絡的英文描述。", "scenario": "學生製作一面家庭與朋友介紹牆，要替不同讀者挑選必要細節，並用證據避免把一次行為變成固定標籤。", "variables": [{"symbol": "d", "meaning": "人物描述欄位與讀者目的"}, {"symbol": "e", "meaning": "外貌、行動、習慣與關係證據"}, {"symbol": "r", "meaning": "比較、尊重語氣與人物關係"}], "steps": [{"id": "step-1", "prompt": "Maya is my older sister. She has short hair, wears glasses, and loves drawing animals. Which statement is correct?", "options": ["Maya is older than the speaker, wears glasses, and enjoys drawing animals.", "Maya is younger than the speaker and dislikes all art.", "Maya practices the violin before breakfast every weekday."], "answer": "A", "feedback": "A combines the relationship, observable detail, and stated interest without adding information."}, {"id": "step-2", "prompt": "Nina practices before breakfast on weekdays, while I practice after dinner. What is different?", "options": ["We practice at different times of day.", "Nina practices only once a year.", "I never practice any instrument."], "answer": "A", "feedback": "A uses the time phrases in the description; it does not invent a frequency or deny an activity."}, {"id": "step-3", "prompt": "Sara waits, smiles, and encourages a friend who made a mistake. What quality does Sara show?", "options": ["She is patient and supportive.", "She is careless because she leaves the room.", "She is angry because she refuses to listen."], "answer": "A", "feedback": "A is supported by several respectful actions and stays within the evidence of the situation."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語人物、家人朋友與生活描述定位；核讀 2026-09-21。", ["以簡易英語介紹家人、朋友和生活中的人物。", "用外貌、興趣、活動與互動支持口語表達。"], ["家人、朋友、外貌、個性、習慣、興趣與分工。"], "只列外貌或親屬名稱，沒有人物行動和關係脈絡。", "重視人物介紹、生活口語與尊重表達。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語聽說、人物卡與生活任務定位；核讀 2026-09-21。", ["透過圖片、角色與生活活動描述人物。", "依時間、興趣、能力和互動組織簡短介紹。"], ["姊妹、表親、朋友、手足、家庭分工與共同活動。"], "把個人偏好或一次行為說成完整固定的性格。", "評量主要內容、描述細節、比較與人際互動。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語人物描述、比較與情境評量定位；核讀 2026-09-21。", ["從人物資料、行動和語境形成完整描述。", "以簡短句型、比較和證據表達人物特徵及關係。"], ["looks、acts、habits、preferences、comparisons、relationships、evidence。"], "用單一標籤或不尊重外貌形容詞取代有資料的描述。", "評量人物主要資訊、細節、比較、推論與適切表達。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持家人朋友、人物介紹、生活活動與口語表達。", "人物描述需整合外貌、行動、習慣、興趣、分工、比較與關係證據。", "從人物卡到段落介紹可用讀者任務、同伴回指證據與尊重檢查驗證。"], "versionDifferences": ["南一較突顯家人朋友與生活人物介紹；康軒較突顯圖片、角色、活動與時間資訊；翰林較突顯人物資料、比較、證據與適切表達評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Who、Looks、Acts、Habits、Relationships、Evidence 六欄組織人物描述。", "用姊妹、表親、祖父、朋友與手足原創人物卡連結個性、習慣與分工。", "以不同讀者的人物介紹和同伴證據回指檢查尊重與資訊邊界。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織家人朋友的外貌、個性、習慣、興趣、能力、比較、分工與關係描述。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 六欄填完後請用箭頭連結 adjective 與 evidence；若一個形容詞找不到重複行動或明確語句，改成較保留的觀察句，不以想像補足人物。"
    data["teaching"]["body"][4]["body"] += " 改寫給不同讀者時不能任意放大敏感外貌或個人資訊，應優先保留共同活動、合作方式與讀者完成任務真正需要的內容。"
    data["teaching"]["body"][5]["body"] += " 同伴若無法從介紹找回人物卡的證據，回到 looks、acts、habits 或 relationships 欄修訂；若句子造成嘲笑感，改用中性、具體且與任務相關的描述。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "2-Ⅳ-4：以具體、尊重的英語描述家人與朋友", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 2-iv-4")


if __name__ == "__main__":
    main()
