"""Id-Ⅳ-2：太陽高度角與季節變化第一輪來源融合、題庫重寫與來源審查。"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-content-id-iv-2.json"; REPORT=ROOT/"implementation/reports/science-content-id-iv-2-first-pass-review.json"; QDIR=ROOT/"questions/science"; TODAY="2026-09-23"
SOURCES=[
 {"url":"https://www.grow22.com/download/114/114_cp/05_114P_Nature.pdf","title":"114 年國中教育會考自然科公開試題","year":"114","locator":"太陽高度角、日照、影長、季節與地表受熱資料判讀","pattern":"取由太陽高度、入射角、影子、季節與地表能量資料推論日照差異的能力方向。"},
 {"url":"https://www.hkjh.hc.edu.tw/uploads/1661481260739sfuB4gG2.pdf","title":"新竹市立新科國中公開康軒版自然課程計畫","year":"公開課程計畫","locator":"太陽高度、四季、日照與地表受熱","pattern":"取太陽高度角、照射角度、影長、季節、能量分布與觀測模型的教學及評量方向。"},
 {"url":"https://lgt.ntpc.edu.tw/TeachPlanFile_Upload/2022/plan/641_plan.pdf","title":"新北市文山區安康高中國中部公開翰林版自然簡案","year":"公開課程計畫","locator":"日照資料、影子模型與季節證據","pattern":"取同時刻影長比較、入射面積、地表吸收、緯度季節差異與控制變因的能力方向。"},
]
REFS=[{**s,"subject":"science","observedPattern":s["pattern"],"reuseDecision":"pattern-only","status":"recorded","locatorLevel":"paper"} for s in SOURCES]
def q(n,prompt,opts,ans,exp,strat,steps,d="medium"):
 return {"id":f"question-science-content-id-iv-2-{n}","subject":"science","type":"single-choice","prompt":prompt,"options":[{"id":k,"text":v} for k,v in zip("ABCD",opts)],"knowledgeIds":["kg-science-content-id-iv-2"],"difficulty":d,"answer":{"value":ans,"explanation":exp},"provenance":{"origin":"original","license":"All rights reserved","sourceUrl":SOURCES[0]["url"],"sourceLocator":"三筆公立學校／公開自然科試題與課程資料的太陽高度、影長、季節、入射角及地表受熱判讀能力方向；本題只作 pattern-only 改寫來源。","authoringNote":"依公開資料能力方向獨立改寫；題幹、選項、答案、解析與五步解法均依 Id-Ⅳ-2 單元重新撰寫，未複製原題、圖表或答案；待第二輪 AI／Terra 內容複核。"},"reviewStatus":"draft","updatedAt":TODAY,"lessonId":"lesson-science-content-id-iv-2","examPatternRefs":REFS,"solutionStrategy":strat,"solutionSteps":steps}
Q=[
q(1,"同一地點正午用竿子測影長，夏至附近影子較短，最合理的解釋是？",["太陽高度角較大，光線較接近直射","太陽離地球一定更近","地球停止自轉","影子與太陽位置無關"],"A","太陽高度角較大時，光線較接近垂直入射，竿子的影子通常較短；季節差異不是由地球停止自轉造成。","把影長與太陽高度角建立幾何關係。",["固定竿高、地點與測量時間。","比較影長和太陽在天空中的高度。","高度角大時，影子投影距離較短。","B、C、D 與觀測證據不符。","答案為 A。"],"easy"),
q(2,"相同面積的地面接收同樣能量時，太陽光以較斜角度照射，能量通常如何分布？",["分散到較大面積，單位面積接收較少","集中到零面積，單位面積無限大","完全不會被地面吸收","只會改變光的顏色"],"A","斜射會使同一束能量分散到較大的地表面積，單位面積接收的能量通常較少。","由入射角比較能量在地表的分布面積。",["確認比較的是同一束或相近能量。","畫出直射與斜射在地面的投影範圍。","斜射投影面積較大，單位面積能量較低。","B、C、D 都不符合能量分布關係。","所以 A 正確。"],"easy"),
q(3,"若要比較兩地太陽高度角造成的受熱差異，哪項資料設計較公平？",["同一日期、相同時間測量兩地太陽高度、影長與地表溫度","一地在清晨測量，另一地在正午測量","只比較兩地一天中最高溫，不記錄雲量","一地用黑色表面，另一地用白色表面且不校正"],"A","控制日期和時間，並同步記錄太陽高度、影長與地表條件，較能把差異連到入射角而非混淆因素。","先控制時間尺度與表面條件，再比較幾何和溫度資料。",["列出日期、時間、雲量、表面材質等變因。","固定能固定的條件並同步測量。","比較影長和高度角，再對照地表溫度。","B、C、D 都引入未控制變因或缺少關鍵資料。","答案為 A。"],"medium"),
q(4,"北半球中緯度地區冬季正午太陽高度通常比夏季低，最直接的觀測證據是？",["同一竿子同一時間冬季影子較長","冬季所有地區都沒有日照","夏季月相一定較亮","冬季風速一定較小"],"A","在同一地點同一時刻，太陽高度較低會使影子較長，因此影長可作為高度角的間接證據。","用可量測影長作為太陽高度的幾何指標。",["固定地點、竿高和測量時刻。","比較冬夏影長。","影長較長表示太陽高度角較低。","B、C、D 不是這個幾何關係的直接證據。","所以 A 最能支持結論。"],"easy"),
q(5,"太陽高度角相同時，地表吸收能量仍可能不同，哪項因素最需要一併記錄？",["地表材質與反照率","月球的表面坑洞","地球磁場顏色","觀察者姓名"],"A","不同地表的反照率、材質和含水狀態會影響反射與吸收，即使入射角相同也可能產生不同升溫。","把日照幾何因素和地表性質分開控制。",["確認題目已固定太陽高度角。","列出會影響吸收的地表性質。","比較反照率、材質和含水等條件。","B、C、D 無法解釋地表吸收差異。","答案為 A。"],"medium"),
q(6,"用手電筒和紙板模擬直射、斜射時，哪項做法最能支持入射角的判讀？",["固定光源距離與亮度，只改變紙板傾角並量測同一面積的照度","同時改變光源距離、亮度和紙板角度","只看肉眼覺得哪片較亮","不記錄角度和面積"],"A","固定光源條件，只改變紙板傾角並量測照度，可較清楚檢查入射角對單位面積能量的影響。","用控制變因與可量測指標建立模型。",["指定紙板傾角為主要自變因。","固定距離、亮度、紙板材質與測量位置。","記錄角度、受光面積和照度。","B、C、D 無法把結果歸因於入射角。","因此 A 最可靠。"],"medium"),
q(7,"若兩地緯度不同，在相同日期與時間測得太陽高度不同，哪項解釋較合理？",["地球曲率與地軸傾角使兩地接收日照幾何不同","太陽會在不同地點變成不同大小","只有雲量能造成太陽高度差","緯度不會影響日照角度"],"A","地球是曲面且地軸傾斜，地點緯度和日期會影響太陽在天空中的高度與日照角度。","將觀測地點、日期和地球幾何模型連結。",["確認兩地同日期同時間的比較條件。","辨認緯度改變觀測者所在的地球表面方向。","利用地球曲率和地軸傾角解釋高度差。","B、C、D 都否認或錯置日照幾何。","答案為 A。"],"medium"),
q(8,"一天中地表溫度最高時間不一定正好是太陽高度最高的正午，最合理的原因是？",["地表吸熱與散熱有時間延遲，還受風、雲和濕度影響","太陽在正午停止放熱","地表溫度完全與日照無關","溫度計只在夜間才準確"],"A","地表有熱容量，吸收與散熱存在時間延遲，且風、雲、濕度會改變能量收支，因此最高溫可能晚於正午。","區分日照幾何峰值與地表熱平衡的時間反應。",["比較太陽高度峰值和溫度峰值的時間。","列出熱容量、散熱、風、雲和濕度等因素。","把日照作為能量輸入，將溫度視為延遲反應。","B、C、D 都不符合熱平衡觀察。","所以 A 正確。"],"medium"),
q(9,"若觀察到同一地點四季正午影長有規律變化，哪項結論最適當？",["影長可作為太陽高度季節變化的間接證據，但要固定測量條件","影長能直接測出太陽到地球的距離","影長變化證明地球停止公轉","一次影長就能代表全年規律"],"A","固定地點、竿高與時間的長期影長資料可支持太陽高度的季節變化，但不能由影長直接測出日地距離或只靠一次觀測概括全年。","確認代理指標的可用範圍與資料時間序列。",["確認影長和太陽高度角有幾何關係。","蒐集四季同條件的重複資料。","用影長作為高度角的間接而非直接測量。","B、C、D 都超出資料能支持的範圍。","答案為 A。"],"medium"),
q(10,"比較城市熱島效應與太陽高度角對地表溫度的影響時，哪項設計最能避免混淆？",["選擇相近日期與時間、相同材質測點，記錄影長、雲量、風和地表溫度並重複測量","只比較兩城市某一天的最高溫","一城市測柏油路，另一城市測草地且不記錄日照","看到市區較熱就直接歸因於太陽高度"],"A","同時記錄日照幾何和城市表面、雲量、風等條件，才能把熱島與太陽高度的作用分開比較。","先列出日照、地表和大氣條件，再設計分層比較。",["辨認太陽高度、地表材質與城市結構都是可能因素。","固定或記錄日期、時間、測點材質、雲量和風。","用影長與溫度的重複資料分辨日照幾何和熱島效應。","B、C、D 缺乏時間、控制或多項證據。","因此 A 最能支持因果判讀。"],"medium"),
]
def main():
 lesson=json.loads(LESSON.read_text(encoding="utf-8")); lesson["updatedAt"]=TODAY; lesson["reviewStatus"]="draft"; lesson["fusionRecord"]={"commonCore":["三版本公開線索共同支持以太陽高度角、入射角、影長和季節資料理解日照及地表受熱。","地球曲率與地軸傾角、能量面積分布、地表反照率、熱延遲、控制變因與長期觀測是共同能力核心。"],"versionDifferences":["南一公開定位偏向日照角度與季節；康軒線索偏向太陽高度、影長、地表能量；翰林線索偏向模型、緯度、測點材質、長期資料與熱島比較。公開資料不足以宣稱取得完整教材內容。"],"originalAdditions":["以正午影長、手電筒紙板模型、緯度比較、地表反照率、日溫延遲和城市熱島建立單元專屬證據鏈。","把觀察月面亮部當成太陽高度證據、夏季每天都比冬季熱、影長直接等於日地距離列為單元迷思診斷。"],"llmSynthesisNote":"依官方課綱、本單元 KG、南一／康軒／翰林公開版本線索與三筆公立學校／公開試題資料的能力方向，重新組織太陽高度角、影長、入射角、季節、地表吸收、熱延遲與控制變因；原先 10 題為觀察月面亮部的重複且錯題套題，已逐題改寫為 10 題太陽日照單元專屬問題，均具唯一答案、解析與五步解法，未複製教材或試題文字、圖表與答案。Terra 第二輪與正式發布審查尚未完成，維持 draft。"}
 for e in lesson.get("versionResearch",[])+lesson.get("publisherResearch",[]): e["reviewedAt"]=TODAY
 for x in Q: (QDIR/f"question-science-content-id-iv-2-{x['id'].rsplit('-',1)[-1]}.json").write_text(json.dumps(x,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"Id-Ⅳ-2：太陽高度角與季節變化","lessonId":lesson["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checkedQuestions":10,"checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"threePublicSchoolExamPatternSources":True,"answersAndDetailedSteps":True,"interactivePredictionManipulationExplanation":True,"terraSecondPass":"pending"},"reviewedAt":TODAY,"note":"原有 10 題為觀察月面亮部的重複且錯題套題，已逐題改寫為 10 題太陽高度與季節專屬問題；每題有唯一答案、解析與五步解法，三筆公開試題／課程資料僅作 pattern-only 來源，正式發布前仍須第二輪 AI／Terra 內容複核。"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 LESSON.write_text(json.dumps(lesson,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); print("authored science content id iv 2")
if __name__=="__main__": main()
