import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-2-iv-11.json"
REPORT = ROOT / "implementation/reports/english-performance-2-iv-11-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創短劇腳本、角色目標、舞台指示、道具、衝突、停頓與結局，承接公開課程的戲劇閱讀與表演理解方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-2-iv-11"
    data["title"] = "2-Ⅳ-11：從簡易短劇的角色、舞台指示與結局理解情節"
    data["content"] = {"summary": "短劇同時用對話和舞台指示說故事：角色說出目標與關係，括號中的動作、燈光、聲音和道具推動事件，衝突在選擇或協商中改變，結局則顯示問題如何被處理。本課以尋找走失小狗、故事結束、地圖分工、帽子衝突、鬧鐘道具、灑出的顏料、暖座位、思考停頓、借書歸還與暴風雨改場等原創短劇，練習用事件線理解誰要做什麼、下一步發生什麼及舞台選擇如何影響觀眾。", "sections": [{"heading": "角色目標讓對話有方向", "body": "Nina holds a map and says I will find the missing puppy，角色是尋找者，目標是找到小狗；Lia 分配畫地圖與寫標籤，顯示她在有限時間內組織合作。先圈角色、動作和目標，再判斷台詞是在介紹、計畫、衝突還是解決。"}, {"heading": "舞台指示是情節證據", "body": "[The lights become dim.]、[A storm sound begins.]、[Mia enters, sees the spilled paint …] 都不是可有可無的裝飾；它們標示時間、氣氛、危險或下一個動作。回答 immediately after 時要照指示順序，不可跳到後來的結果。"}, {"heading": "道具和停頓替觀眾傳遞資訊", "body": "響起的鬧鐘讓演員跑向門口，成為觸發情節的道具；問題後的 pause 則留出思考時間，使觀眾注意線索。分析道具時問它何時出現、引發誰的行動、結尾是否再次回收，不只描述它放在哪裡。"}, {"heading": "結局顯示衝突或關係的變化", "body": "紅藍帽子的協商把兩人的需求分開，借書歸還並道謝則顯示責任被完成、關係得到修復。暴風雨中把戶外演出移到室內，顯示角色依安全條件改變計畫。結局摘要要連回起始問題與中間選擇，不能只抄最後一句。"}]}
    data["studyHighlights"] = ["從角色、動作與台詞辨認目標、分工、衝突與情節方向。", "依舞台指示、燈光、聲音與動作的順序定位事件。", "分析道具如何觸發行動、停頓如何引導觀眾理解。", "用起始問題、中間選擇與結局變化概括短劇結果。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "括號裡的字也在說故事嗎？", "body": "播放一段完全自編的無對話短劇，只演燈光變暗、鬧鐘響、角色跑門口三個舞台指示，讓學生先猜發生什麼。再加入台詞比較，指出舞台指示如何補上時間、觸發和情緒，並非排演時可以忽略的備註。"}, {"id": "explain", "phase": "explain", "heading": "短劇六格事件卡", "body": "建立 Role、Goal、Stage clue、Action、Conflict、Outcome 六格。先標角色和目標，再按舞台指示與對話排動作，找出需求衝突，最後用結局檢查誰改變了計畫或完成了責任；每一格都要能回指腳本位置。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從帽子衝突讀出協商", "body": "以 Ben 想要紅帽、Kai 需要紅帽演角色、導演安排藍帽和紅帽分用的原創片段示範。先列兩個需求，再指出解決方案如何分配道具；答案不是誰贏了，而是衝突如何透過安排讓兩人都能完成角色。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "照舞台指示找下一步", "body": "給 Mia 看見灑漆、呼叫抹布、清理地板的腳本卡，學生先遮住後兩步，只回答 immediately after；再打開檢查。換成暴風雨聲、搬椅子與燈光變化，讓同伴指出哪個聲音或動作改變了情節方向。"}, {"id": "transfer", "phase": "transfer", "heading": "為不同觀眾改寫演出提示", "body": "輪換小狗、借書、暖座位、室內演出、鬧鐘與地圖分工短劇。學生為低年級觀眾、沒有字幕的觀眾或只看舞台不聽台詞的觀眾，選擇要加強動作、道具、停頓或旁白，並說明哪些情節證據不能刪掉。"}, {"id": "reflect", "phase": "reflect", "heading": "我有把結局連回問題嗎？", "body": "回看摘要，標出 opening problem、choice、stage evidence、outcome 和 relationship change。若只說角色最後做了什麼，補回衝突與原因；若把演員想像的內心當腳本事實，改成由台詞或舞台指示支持的保留推論。"}], "summary": ["以 Role、Goal、Stage clue、Action、Conflict、Outcome 六格讀短劇。", "按照舞台指示與對話順序判斷下一個事件。", "把道具、停頓、燈光與聲音連到觀眾理解和角色行動。", "用問題、選擇與結局變化概括短劇而不只抄最後一句。"], "exitCheck": [{"prompt": "舞台指示如何成為情節證據？", "expectedEvidence": "能指出燈光、聲音、動作或道具標示時間、氣氛、觸發與下一步，並依順序回答。"}, {"prompt": "短劇中的衝突如何判斷已被處理？", "expectedEvidence": "能比較角色需求、協商或選擇與結局，說明計畫、責任或關係發生何種變化。"}, {"prompt": "如何讓短劇摘要不只重述最後一句？", "expectedEvidence": "能保留起始問題、中間行動或舞台證據，以及結局如何回應問題。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "從短劇角色、目標、舞台指示、道具、衝突與結局理解情節並選擇下一個事件。", "scenario": "學生擔任校園短劇導演助理，要替演員排出動作、處理道具衝突，並為觀眾寫出有證據的情節摘要。", "variables": [{"symbol": "r", "meaning": "角色、關係與目標"}, {"symbol": "s", "meaning": "舞台指示、道具、聲音與動作順序"}, {"symbol": "o", "meaning": "衝突解決、結局與觀眾理解"}], "steps": [{"id": "step-1", "prompt": "Nina holds a map and says, 'I will find the missing puppy.' Which role and goal are clear?", "options": ["Nina is the finder, and her goal is to find the puppy.", "Nina is the puppy, and her goal is to close the theater.", "Nina is the audience, and her goal is to sell a red hat."], "answer": "A", "feedback": "A connects the stage action and line with Nina's role and stated goal without adding events."}, {"id": "step-2", "prompt": "Mia enters, sees spilled paint, calls for a cloth, and cleans the floor. What happens immediately after she sees the paint?", "options": ["She calls for a cloth.", "She finishes cleaning the floor.", "She returns a borrowed book."], "answer": "A", "feedback": "A follows the script order; cleaning happens later and the book belongs to a different scene."}, {"id": "step-3", "prompt": "The director says, 'Pause after the question so the audience can think.' Why is the pause used?", "options": ["It gives the audience time to consider the question.", "It tells the actors to end every scene immediately.", "It hides which character is speaking."], "answer": "A", "feedback": "A states the director's purpose and connects the pause to audience understanding."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語短劇、角色與表演理解定位；核讀 2026-09-21。", ["以簡易短劇、角色與舞台活動理解生活故事。", "透過對話、動作和表演完成英語互動。"], ["角色、目標、舞台指示、道具、衝突、停頓與結局。"], "只讀角色台詞，忽略舞台指示、道具和事件順序。", "重視短劇主要內容、角色互動與表演表達。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語聽說、角色扮演與短劇活動定位；核讀 2026-09-21。", ["透過角色、動作、聲音與合作排演理解情節。", "依順序、衝突、分工與結局完成表演任務。"], ["尋找、分工、道具、衝突、暴風雨、借還與安全。"], "把道具當背景，或把最後畫面和整個情節混為一談。", "評量主要內容、順序、角色、衝突與演出互動。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語短劇閱讀、舞台線索與情境評量定位；核讀 2026-09-21。", ["從台詞、舞台指示和情節結果形成完整理解。", "以角色目標、道具、停頓與結局表達短劇摘要。"], ["role、goal、stage direction、prop、conflict、pause、outcome。"], "將演員未說出的心理當成腳本事實，或漏掉衝突如何被解決。", "評量短劇主旨、事件順序、舞台線索、推論與表達。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持簡易短劇、角色互動、舞台線索與情節理解。", "短劇理解需整合角色目標、對話、舞台指示、道具、衝突、停頓與結局。", "從腳本閱讀到演出摘要可用事件卡、遮蔽下一步、角色排演與觀眾回饋驗證。"], "versionDifferences": ["南一較突顯短劇與角色表演；康軒較突顯動作、聲音、合作和情節順序；翰林較突顯台詞、舞台指示、道具、停頓、衝突與結局評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Role、Goal、Stage clue、Action、Conflict、Outcome 六格事件卡閱讀短劇。", "用小狗、帽子、鬧鐘、灑漆、借書與暴風雨改場原創情境連結舞台線索。", "以不同觀眾和遮蔽下一步的排演任務檢查情節證據與結局理解。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織角色、目標、舞台指示、道具、對話、衝突、停頓、結局與觀眾理解。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 六格依腳本順序填寫，再讓另一組只看摘要重排事件；如果對方無法知道衝突或結局，補的是舞台證據或角色目標，不是任意增加心理描寫。"
    data["teaching"]["body"][4]["body"] += " 為不同觀眾改提示時保留觸發動作、角色目標和結局關鍵，改變的是視覺、聲音或旁白支持，不是把劇情改成另一個故事。"
    data["teaching"]["body"][5]["body"] += " 若摘要把舞台推論說成事實，回到方括號指示或台詞找證據；若結局沒有回應開場問題，標記為尚未解決而不是自行補寫圓滿結果。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "2-Ⅳ-11：從簡易短劇的角色、舞台指示與結局理解情節", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 2-iv-11")


if __name__ == "__main__":
    main()
