#!/usr/bin/env python3
"""Independent first-pass authoring for math f-IV-3."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/'lessons/math/lesson-math-performance-f-iv-3.json'
REPORT=ROOT/'implementation/reports/math-performance-f-iv-3-first-pass-review.json'
URLS={'nani':'https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf','kanghsuan':'https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110','hanlin':'https://www.cp.ptc.edu.tw/storage/134513/134513_112_B-1_9A.pdf'}
def rec(p,c,r,m,a):
 return {'publisher':p,'edition':f'{p} 公立校方數學課程計畫章節級證據','sourceType':'public-web','sourceLocator':f'{URLS[p]}；二次函數標準式、極值與圖形評量欄位；核讀 2026-09-21。','reviewedAt':'2026-09-21','findings':{'concepts':[c,'公開結構支持以完成平方、頂點式與圖形理解二次函數的極值與位置。'],'representations':[r],'examplesOrEvidence':['本課的圍欄、收益與拋物線資料均為原創，只承接公開課程的能力方向。'],'misconceptions':[m],'assessmentEmphasis':[a]},'licenseBoundary':'只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。'}
def main():
 d=json.loads(LESSON.read_text(encoding='utf-8')); assert d['id']=='lesson-math-performance-f-iv-3' and d['reviewStatus']=='draft'
 d['title']='f-Ⅳ-3：用標準式定位二次函數極值'
 d['content']={'summary':'二次函數的最大值與最小值不是只看圖形高低，而要先把式子整理到能直接讀出頂點的形式。本課以固定周長圍欄面積與收益模型為入口，練習完成平方、辨認頂點式的水平與垂直平移，再依開口方向判斷極值，最後把連續數學解與整數或實際範圍分開檢查。','sections':[{'heading':'完成平方改變閱讀角度','body':'x²−6x+5 可整理成 (x−3)²−4；同一個函數換成頂點式後，對稱軸 x=3 與最低值 −4 便直接可見。這不是改變函數，而是改變表達角度。'},{'heading':'開口方向決定極值種類','body':'a>0 時圖形向上，頂點提供最小值；a<0 時圖形向下，頂點提供最大值。先看 a 的正負，再談極值，避免把所有頂點都叫最大值。'},{'heading':'情境限制會篩選頂點','body':'圍欄長度、時間或數量可能只允許一段定義域；頂點若落在範圍外，不能直接採用，而要比較端點與內部候選值。連續模型得到的最佳點也可能要面對整數限制。'},{'heading':'不同形式各有任務','body':'一般式適合代入與整理，頂點式適合讀取極值與對稱軸，因式分解形式適合找零點。選形式要配合問題，不是把所有式子都轉成同一格式。'}]}
 d['studyHighlights']=['先看二次項係數正負，再判斷極值方向。','用完成平方把一般式轉成能直接讀頂點的形式。','把頂點與定義域、端點及整數限制一起檢查。','依任務選一般式、頂點式或因式分解形式。']
 d['teaching']={'body':[{'id':'hook','phase':'hook','heading':'同樣的圍欄怎麼圍最大面積','body':'給一段 20 公尺圍欄靠牆形成矩形，請學生試算不同寬度的面積並猜哪個最大。把寬度 x 與面積寫成二次函數，讓極值問題從資料與限制自然出現。'},{'id':'explain','phase':'explain','heading':'從一般式看到頂點','body':'將 A(x)=x(20−2x) 整理為 −2x²+20x，再完成平方得到 −2(x−5)²+50。學生標記開口方向、對稱軸、最大面積與可行的 0≤x≤10。'},{'id':'worked-example','phase':'worked-example','heading':'極值與端點比較','body':'對 R(t)=−(t−4)²+12，先讀出頂點 (4,12) 與最大值 12；若時間限制改為 0≤t≤3，頂點不在可行範圍，就要比較 t=0、t=3 的輸出，不能硬採 12。'},{'id':'guided-practice','phase':'guided-practice','heading':'完成平方每一步留理由','body':'處理 x²+8x+1，學生先補成 (x+4)²−15，再在每個步驟標記加減的平衡來源。完成後用 x=0 回算一般式與頂點式相同，避免只看括號外觀。'},{'id':'transfer','phase':'transfer','heading':'連續最佳點與整數選擇','body':'收益模型的最佳投入量得到 x=6.5，但實際投入只能是整數；學生比較 x=6 與 x=7 的收益，說明連續頂點如何提供候選、整數限制如何完成最後決策。'},{'id':'reflect','phase':'reflect','heading':'極值結論的條件','body':'出口題要求學生寫出開口方向、頂點、定義域與是否需要端點比較；再指出若把最大值誤讀成最小值，哪個係數或圖形證據可以推翻它。'}],'summary':['完成平方將一般式轉成可讀頂點的形式。','先看開口方向，決定頂點是最大或最小。','把頂點、端點、定義域與整數限制一起檢查。','選擇最適合任務的代數形式並用回算驗證。'],'exitCheck':[{'prompt':'−2(x−5)²+50 的極值是什麼？','expectedEvidence':'開口向下，頂點 x=5，最大值 50。'},{'prompt':'頂點不在定義域內時怎麼辦？','expectedEvidence':'比較允許範圍的端點或其他候選值，不能直接使用頂點。'},{'prompt':'為什麼完成平方前後是同一函數？','expectedEvidence':'每一步是等值整理，可用代入同一 x 回算確認。'}]}
 d['interactive']={'type':'guided-choice','goal':'以完成平方、頂點與定義域判斷二次函數極值。','scenario':'調整圍欄或收益模型的係數與可行範圍，觀察頂點與最佳值是否仍可採用。','variables':[{'symbol':'x','meaning':'可調整的寬度或投入量'},{'symbol':'a','meaning':'面積或收益輸出'}],'steps':[{'id':'step-1','prompt':'A(x)=−2(x−5)²+50 的開口方向？','options':['向下','向上','沒有圖形'],'answer':'A','feedback':'二次項係數為負，頂點提供最大值。'},{'id':'step-2','prompt':'頂點的 x 值在最佳化中代表什麼？','options':['對稱軸位置與連續模型的候選最佳輸入','一定是端點','輸出單位'],'answer':'A','feedback':'頂點的輸入位置要再和定義域及離散限制核對。'},{'id':'step-3','prompt':'若頂點超出可行範圍，怎麼辦？','options':['比較範圍內的端點或整數候選','仍直接採頂點','刪掉整個函數'],'answer':'A','feedback':'最佳解必須符合實際限制，頂點只是連續模型的候選。'}]}
 for i, extra in enumerate(['並請學生把寬度限制與面積最大值寫在同一張表，說明候選範圍從何而來。','再用一個輸入值回算一般式與頂點式，確認完成平方沒有改變函數。','並將頂點、定義域端點與整數候選分開標記，避免把形式轉換當成答案。','完成後比較 x=6 與 x=7 的實際收益，寫出為何連續最佳點不能直接使用。','再說明若最佳點落在範圍外，端點比較如何取代頂點判斷。','最後把開口、頂點和限制的證據各寫一項，說明最大或最小結論如何成立。']):
  d['teaching']['body'][i]['body'] += ' ' + extra
 d['authoringStandard']='version-fused-v1'; d['versionResearch']=[rec('nani','以完成平方、頂點式與二次模型理解極值','一般式、頂點式、表格與圖形的互相轉換','只看係數絕對值或忘記開口方向的判斷理由','完整檢查完成平方、頂點讀取與限制條件'),rec('kanghsuan','以操作與圖形表徵比較平移、對稱及極值','滑動頂點、對稱軸與數值點的同步變化','頂點超出定義域仍直接採用，忽略端點比較','操作後完整解釋極值與端點比較的證據'),rec('hanlin','在面積與收益情境中選擇表示法與可行解','圍欄、投入、連續與整數限制的情境模型','把連續最佳點當成實際唯一答案而不檢查整數性','評估模型選擇、極值條件與決策理由是否完整')]
 d['fusionRecord']={'commonCore':['三版本公開結構共同支持完成平方、頂點式與圖形極值的連結。','開口方向、對稱軸與頂點是判斷最大最小的核心證據。','情境定義域與整數限制會影響最後可採用的答案。'],'versionDifferences':['南一證據較突顯代數整理與頂點式；康軒較突顯操作與圖形平移；翰林較突顯情境最佳化、範圍與決策限制。這是公開課程計畫層級差異，不宣稱完整教材差異。'],'originalAdditions':['用原創靠牆圍欄情境建立完成平方與面積極值。','設計頂點超出定義域及整數最佳點的診斷。','將一般式、頂點式與因式形式依任務分工並要求回算。'],'llmSynthesisNote':'本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG 重新設計二次函數標準式、頂點與情境極值。正文、例題、互動與回饋均為原創，未複製教材；Terra 第二輪與正式發布審查尚未完成，維持 draft。'}
 d['updatedAt']='2026-09-21'; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 REPORT.write_text(json.dumps({'unit':'f-Ⅳ-3：用標準式定位二次函數極值','lessonId':d['id'],'status':'first-pass-ai-review-complete','reviewStatus':'draft','checks':{'unitSpecificOriginalContent':True,'threeVersionResearchRecords':True,'fusionRecordPresent':True,'interactivePredictionManipulationExplanation':True,'terraSecondPass':'pending'},'reviewedAt':'2026-09-21'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps({'lesson':str(LESSON.relative_to(ROOT)),'reviewStatus':d['reviewStatus']},ensure_ascii=False))
if __name__=='__main__': main()
