import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-4-iv-1.json"
REPORT = ROOT / "implementation/reports/english-performance-4-iv-1-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "basic word spelling, context, word class, and proofreading"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "spelling in sentence context, meaning, suffix, and usage"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "word form, collocation, proofreading, and functional vocabulary"),
    ]
    return [{"url": u, "title": f"{t}；僅取國中基本字詞拼寫、語境與校對能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以句子語境、詞性、搭配、字尾與拼寫辨識測量基本字詞書寫；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-4-iv-1"
    data["title"] = "4-Ⅳ-1：用語境、詞性與字母順序校對國中基本單字"
    data["content"] = {"summary": "正確拼寫不是只靠字母外形記憶，而是將聲音、字母順序、詞性、字尾、搭配與句意一起校對。本課以關窗、博物館展覽、橋梁檢查、週末報告、清楚指示、休息建議、公布結果、表單簽名、實驗結果不同與種樹等原創句子，練習辨識容易混淆的拼寫，並建立看錯誤位置、分音節、回填句意與再次朗讀的校對流程。", "sections": [{"heading": "先用句意縮小字詞候選", "body": "Please ___ the window 需要動作 close；museum has a new ___ 需要名詞 exhibit；instructions are very ___ 需要形容詞 clear。先判斷語境與詞性，再檢查字母，比單獨背拼法更穩定。"}, {"heading": "把長字拆成可檢查區塊", "body": "exhibit、inspect、announce、different 等字可依音節或字尾分段，逐段核對母音、雙子音與字母位置。若只從發音直接拼，可能漏掉不發音字母或把相近字混在一起。"}, {"heading": "拼寫和搭配要一起讀", "body": "give advice、sign your name、plant a tree 是語意與搭配同時成立的組合。即使字拼得像，若放回句子詞性不對或搭配不自然，也要回頭修訂，不把拼寫題當成孤立字母題。"}, {"heading": "校對要留下錯誤位置", "body": "把候選字寫出來後，圈出可能錯的母音、字尾或重複字母，再用遮住—默寫—對照流程確認。最後將字放回原句朗讀，驗證拼寫、詞性與句意三者一致。"}]}
    data["studyHighlights"] = ["先由句意、詞性與搭配判斷需要哪一個基本單字。", "拆音節或字母區塊，逐一檢查母音、子音、字尾與字母順序。", "將拼寫放回原句朗讀，確認詞性與語意，不只比對外形。", "用圈錯誤位置、遮住默寫與回填句意完成校對。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "字母看起來像對，句子卻不通嗎？", "body": "展示原創句子 The instructions are very ___，提供 clear、cleer、clearly 三個候選。學生先判斷詞性，再校對拼寫，發現語境能先排除部分錯誤。"}, {"id": "explain", "phase": "explain", "heading": "語境—詞性—字母三步卡", "body": "建立 Meaning、Part of speech、Sound chunks、Letter order 四欄。先確定句意和詞性，再分音節或字母區塊，最後從句首到句尾逐字母檢查。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從搭配校對 advice", "body": "以 The nurse gave me good advice 示範：good 後需要名詞，give advice 是固定搭配；再比較 advize、advise 與 advice 的字尾和詞性，說明不能只靠發音決定拼法。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "十個校園情境十種校對焦點", "body": "輪換關窗、展覽、橋梁、報告、指示、休息、結果、簽名、實驗與種樹句子。學生先標詞性，再圈容易錯的位置，交換後用原句回讀驗證。"}, {"id": "transfer", "phase": "transfer", "heading": "建立自己的易錯字卡", "body": "學生從校園公告或學習單挑三個易錯字，記錄正確拼法、詞性、搭配與一個新句子。交換字卡後遮住單字默寫，再用句意和字母順序雙重核對。"}, {"id": "reflect", "phase": "reflect", "heading": "我錯在字母還是語境？", "body": "回看答案，標記母音、子音、字尾、詞性、搭配或句意錯誤。修訂時不能只抄正解，要寫出錯誤位置和下一次會用哪個線索校對。"}], "summary": ["以 Meaning、Part of speech、Sound chunks、Letter order 四欄校對單字。", "先判斷句意與詞性，再檢查字母順序、字尾與音節。", "利用搭配、遮住默寫與原句朗讀避免只靠外形記憶。", "記錄錯誤位置和校對策略，將單字遷移到新句子。"], "exitCheck": [{"prompt": "為什麼拼寫題要先看詞性與句意？", "expectedEvidence": "能以名詞、動詞或形容詞的例子說明語境先縮小候選字，再校對字母。"}, {"prompt": "遇到長字或發音不穩的字，如何分段校對？", "expectedEvidence": "能按音節或字母區塊檢查母音、子音、字尾與順序。"}, {"prompt": "完成拼寫後如何確認不是只背出字形？", "expectedEvidence": "能將字放回新句子朗讀，核對詞性、搭配與句意，並指出錯誤位置。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "從句意、詞性、搭配與字母區塊選出正確拼寫，並用校對證據說明答案。", "scenario": "學生擔任校刊校對員，要修正公告、展覽、實驗與表單中的基本單字拼寫。", "variables": [{"symbol": "m", "meaning": "句意與詞性"}, {"symbol": "s", "meaning": "音節、字母順序與字尾"}, {"symbol": "c", "meaning": "搭配、朗讀與新句驗證"}], "steps": [{"id": "step-1", "prompt": "Please ___ the window before class. Which spelling fits the action?", "options": ["close", "cloze", "cloes"], "answer": "A", "feedback": "句子需要動詞 close，並以字母順序逐字核對。"}, {"id": "step-2", "prompt": "The nurse gave me good ___. Which spelling fits the noun and collocation?", "options": ["advice", "advise", "adivce"], "answer": "A", "feedback": "good 後需要名詞，give advice 是合適搭配，字尾也要校對。"}, {"id": "step-3", "prompt": "The two results are ___, so we checked the experiment again.", "options": ["different", "diffrent", "differant"], "answer": "A", "feedback": "句意需要形容詞 different，將母音與雙子音位置逐段檢查。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；基本字詞、句型與生活書寫定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由生活句子辨識基本字詞與拼寫。", "以人物、物件、行動與句意校對字形。"], "representations": ["公告、展覽、報告、表單、實驗與校園活動。"], "examplesOrEvidence": ["本課以關窗、橋梁、展覽、簽名與種樹原創句子承接公開結構。"], "misconceptions": ["只背字母外形，不看詞性與句意。"], "assessmentEmphasis": ["重視基本字詞拼寫、語境與書寫正確。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖文、核心字彙與拼寫任務定位；核讀 2026-09-21。", "findings": {"concepts": ["透過圖片、情境與句型使用基本字詞。", "依詞性、搭配與字母區塊完成校對。"], "representations": ["字卡、生活表單、醫療、實驗與活動資訊。"], "examplesOrEvidence": ["本課以語境—詞性—字母三步卡重新設計拼寫活動。"], "misconceptions": ["發音相同就選相同拼法，忽略詞性與搭配。"], "assessmentEmphasis": ["評量字形、語意、拼寫與基本應用。"], "misconceptions": ["發音相同就選相同拼法，忽略詞性與搭配。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；字詞形式、上下文與校對定位；核讀 2026-09-21。", "findings": {"concepts": ["從句意、詞性與上下文選擇正確字詞形式。", "以字母順序、字尾、搭配與自我校對確認。"], "representations": ["meaning、part of speech、sound chunks、letter order、proofreading。"], "examplesOrEvidence": ["本課以 advice、different、exhibit 等原創易錯字建立校對鏈。"], "misconceptions": ["只抄答案，不留下錯誤位置與校對方法。"], "assessmentEmphasis": ["評量拼寫正確、句意、搭配與修訂策略。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持基本字詞、生活句子與正確書寫。", "可靠拼寫需整合句意、詞性、音節、字母順序與搭配。", "可用三步卡、易錯字卡、遮住默寫與回填朗讀完成遷移。"], "versionDifferences": ["南一較突顯生活句子與基本字詞；康軒較突顯圖文、情境、字卡與任務；翰林較突顯形式、上下文、搭配與校對修訂。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Meaning、Part of speech、Sound chunks、Letter order 四欄校對單字。", "用展覽、橋梁、報告、醫療、表單、實驗與種樹原創句子練習。", "以易錯位置、遮住默寫和新句朗讀檢查拼寫是否真正可用。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織基本字詞拼寫、語境、詞性、搭配、字母區塊與校對修訂。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-4-iv-1-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先由句意和詞性判斷字詞，再按音節、字母順序、字尾與搭配校對，最後放回新句驗證。"; q["solutionSteps"] = ["先讀完整句，圈出需要的意義與詞性。", "列出候選字並分音節或字母區塊檢查。", "逐一核對母音、子音、字尾與字母順序。", "將候選字放回搭配和句意，排除形式像但功能錯的選項。", "重新朗讀或用新句默寫確認，並記下錯誤位置與校對策略。" ]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的基本字詞拼寫、語境、詞性與校對模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 4-iv-1")


if __name__ == "__main__":
    main()
