import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/chinese/lesson-chinese-performance-6-iv-4.json"
REPORT=ROOT/"implementation/reports/chinese-performance-6-iv-4-first-pass-review.json"

def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher":name,"edition":f"{name} 公立校方國文課程計畫章節級證據","sourceType":"public-web","sourceLocator":locator,"reviewedAt":"2026-09-21","findings":{"concepts":concepts,"representations":forms,"examplesOrEvidence":["本課以原創通知、申請、邀請、報告、規則與分眾防災文字，承接公開課程的實用寫作、讀者適切與資訊組織方向。"],"misconceptions":[misconception],"assessmentEmphasis":[assessment]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}

def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-chinese-performance-6-iv-4"
    data["title"]="6-Ⅳ-4：依讀者、目的與情境完成可使用的各類文本"
    data["content"]={"summary":"實用文本的好壞不在於文句多華麗，而在於讀者能否在需要的時間找到正確資訊、知道下一步並採取適當行動。本課比較通知、申請、邀請、回覆、調查報告、規則與說明文字，先界定讀者、目的、情境、必備資訊與格式，再安排標題、欄位、段落、列表與語氣。相同內容給幼兒、家長、同學或行政單位時，資訊核心相同，表達層級和說明方式必須改變。", "sections":[{"heading":"先寫出文本任務與使用情境","body":"動筆前回答五個問題：誰要讀、讀完要做什麼、何時何地使用、哪些資訊不可缺、要用什麼格式保存或發布。通知缺日期時間地點就無法行動，申請缺目的與需求就無法審核，報告缺資料來源與範圍就無法判讀；文本種類是任務的工具。"},{"heading":"資訊排序要服務讀者查找","body":"通知先放事件與行動，申請先交代對象、目的與需求，報告先給問題與資料再呈現結果，規則則用條列和條件讓使用者快速查詢。不是每篇都要用相同順序；先想讀者最急著找什麼，再決定標題、欄位、段落和表格。"},{"heading":"語氣和細節要符合關係","body":"正式申請需要清楚、禮貌、可核准的資訊，給低年級的說明需要短句、例子、圖示或步驟，給家長的防災文字則要補上判斷條件與安全提醒。得體不等於含糊，簡單也不等於刪掉必要風險；要測試讀者能否重述和執行。"},{"heading":"發布前做內容與風險檢查","body":"逐項檢查人名、日期、時間、地點、聯絡方式、權責、附件、數字與隱私，再從讀者角度找歧義或漏步驟。群組公告若把草稿、個資或未確認資訊一起送出，之後很難收回；保留版本、發布範圍和修訂紀錄，是實用寫作的一部分。"}]}
    data["studyHighlights"]=["先界定讀者、目的、情境、必備資訊與格式。","依文本任務安排通知、申請、報告與規則的資訊順序。","調整語氣、細節與說明層級以符合讀者。","發布前核對事實、風險、個資、附件與版本。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"資訊都有，為什麼還是不能用？","body":"展示一張自編教室更換通知：內容包含日期、時間和新教室，卻把行動要求藏在長段落中，還漏了聯絡方式。請學習者用讀者任務測試：同學能否在十秒內說出何時去哪裡、遇到問題問誰，再依結果重排資訊，建立格式服務使用的入口。"},{"id":"explain","phase":"explain","heading":"各類文本的任務設計卡","body":"先填讀者、目的、情境、必備資訊與格式，再選擇資訊順序。通知突出行動，申請突出請求與理由，邀請突出時間地點與回覆，報告突出問題、方法、結果與限制，規則突出條件與例外；每一類都要讓讀者知道下一步。"},{"id":"worked-example","phase":"worked-example","heading":"把剩食資料組成一頁可讀報告","body":"示範用標題交代問題，接著寫資料期間與方法，以表格或數字呈現結果，再補一段解釋、限制與建議。避免只貼一串數字或直接宣布原因；讀者要能分辨觀察到什麼、推論到哪裡，以及下一步如何改善。"},{"id":"guided-practice","phase":"guided-practice","heading":"同一防災資訊分給幼兒與家長","body":"小組把自編地震避難資訊分成幼兒版與家長版：幼兒版用短句、動作順序與圖像提示，家長版補上集合點、聯絡方式、特殊需求與判斷條件。交換後請讀者實際重述流程，若幼兒版少了安全關鍵或家長版過度簡化，就回補對應資訊。"},{"id":"transfer","phase":"transfer","heading":"從邀請到正式申請切換文體","body":"把同一場成果展先寫給家長，再寫成借用場地申請。固定活動事實，改變稱呼、目的、資訊欄位、語氣與附件；申請要讓審核者能判斷需求與責任，邀請要讓參與者知道時間、地點、回覆方式，不能只換開頭稱謂。"},{"id":"reflect","phase":"reflect","heading":"檢查文本是否真的能被使用","body":"請一位沒有看過草稿的人完成文本要求，記錄他停頓、提問或做錯的地方。再將問題分成缺資訊、順序不清、語氣不合、格式難找或事實未核對，逐項修正並保留版本；若只是自己覺得順眼，還不足以證明文本有效。"}],"summary":["用任務卡界定讀者、目的、情境、必備資訊與格式。","依通知、申請、邀請、報告、規則等功能安排資訊。","按讀者年齡、關係與風險調整語氣和細節。","以真實查找、重述與執行測試發布品質。"],"exitCheck":[{"prompt":"通知和申請為何不能使用完全相同的資訊順序？","expectedEvidence":"能比較兩種文本的讀者任務，說明通知突出行動與時間，申請突出請求、理由、責任與審核資訊。"},{"prompt":"給幼兒與家長的同一防災資訊如何調整？","expectedEvidence":"能保留核心安全動作，分別調整句長、步驟、圖示、判斷條件、集合與聯絡資訊。"},{"prompt":"發布群組公告前除了錯字還要檢查什麼？","expectedEvidence":"能核對日期、時間、地點、聯絡、權責、附件、個資、版本與未確認資訊。"}]}
    data["interactive"]={"type":"guided-choice","goal":"依讀者、目的、情境與格式完成能被查找、理解和執行的實用文本。","scenario":"學生要完成教室通知、場地申請與成果展邀請，依序填任務卡、安排資訊、調整語氣，再用讀者執行測試修訂。","variables":[{"symbol":"t","meaning":"文本任務與必備資訊"},{"symbol":"a","meaning":"讀者、格式與語氣"},{"symbol":"u","meaning":"查找、執行與發布檢查"}],"steps":[{"id":"step-1","prompt":"要通知同學下週更換教室，哪項內容最不可缺少？","options":["更換日期、時間、新教室位置與遇到問題的聯絡方式","只寫『下週換教室』，細節讓同學自行詢問","先寫很長的背景故事，行動資訊可以省略"],"answer":"A","feedback":"A 讓讀者能在正確時間到正確地點並知道如何處理疑問。"},{"id":"step-2","prompt":"寫社團場地申請時，哪種表達最符合正式文書需求？","options":["只寫『拜託借場地，很好玩』，不必交代責任","清楚列出申請對象、活動目的、日期時段、使用需求、維護責任與聯絡方式","用大量感嘆號要求對方一定核准"],"answer":"B","feedback":"B 提供審核所需資訊與責任邊界，語氣正式而可執行。"},{"id":"step-3","prompt":"同一防災資訊給幼兒與家長閱讀，哪項原則正確？","options":["兩版完全相同，因為讀者不影響寫作","核心安全動作相同，但依年齡調整句長、步驟、圖示、判斷條件與聯絡資訊","幼兒版刪掉所有安全細節，家長版只放口號"],"answer":"B","feedback":"B 保留安全核心並依讀者能力與責任調整表達層級。"}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；國語文實用寫作、應用文本與表達定位；核讀 2026-09-21。",["依生活需求選擇文本形式與內容。","以清楚、適切與實用完成溝通，使讀者能找到資訊並採取正確行動。"],["通知、申請、邀請、報告、規則與說明。"],"把所有文本寫成同一種文章，只換稱呼。","重視讀者、目的、格式與資訊完整。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；國語文書寫、句段組織與實作評量定位；核讀 2026-09-21。",["透過實作、比較與回饋改善各類文本。","依讀者、情境與任務調整語氣及結構。"],["公告、申請、邀請、調查報告、條列規則與分眾改寫。"],"只校對錯字，忽略使用者能否找資訊和採取行動。","要求格式可查找、內容可執行、修訂有證據。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；國文各類文本、實用溝通與評量定位；核讀 2026-09-21。",["從目的、對象與需求完成各類實用文本。","以資訊組織、語氣與發布責任檢核成品。"],["通知、申請、報告、說明、家長文本、格式與版本。"],"把簡潔理解成刪除必要風險與責任資訊。","評量文本功能、資訊完整、讀者適切與發布安全。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持各類實用文本、讀者適切、資訊組織與生活溝通。","文本形式要由讀者、目的、情境與格式需求決定。","成品需以查找、理解、執行與發布風險檢查。"],"versionDifferences":["南一較突顯生活需求與應用表達；康軒較突顯實作、比較、回饋與句段組織；翰林較突顯各類文本、資訊完整、分眾與發布責任。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以文本任務卡決定通知、申請、報告與規則的資訊順序。","用幼兒／家長雙版本測試同一安全資訊的分眾層級。","以陌生讀者查找、重述與執行測試取代只看文句順眼。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織實用文本、通知申請報告規則、讀者分眾、資訊組織與發布檢查。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 每個格式選擇都要回到讀者要完成的任務，並在草稿旁標出刪掉或延後的資訊；必要資訊不能為了看起來簡短而消失。"
    data["teaching"]["body"][4]["body"] += " 比較不同文本時固定活動事實，再調整稱呼、目的、欄位、證據、語氣與附件；若兩種文本都能使用相同段落，回頭檢查是否還沒有真正寫出任務差異。"
    data["teaching"]["body"][5]["body"] += " 將讀者的停頓與提問當成資料，按缺資訊、順序、語氣、格式和事實風險分類，再逐項修正而非一次大改造成新的錯誤。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"6-Ⅳ-4：依讀者、目的與情境完成可使用的各類文本","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored chinese performance 6-iv-4")

if __name__=="__main__": main()
