#!/usr/bin/env python3
"""Independent first-pass authoring for math d-IV-1."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/'lessons/math/lesson-math-performance-d-iv-1.json'
REPORT=ROOT/'implementation/reports/math-performance-d-iv-1-first-pass-review.json'
URLS={'nani':'https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf','kanghsuan':'https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110','hanlin':'https://www.cp.ptc.edu.tw/storage/134513/134513_112_B-1_9A.pdf'}
def rec(p,c,r,m,a):
 return {'publisher':p,'edition':f'{p} 公立校方數學課程計畫章節級證據','sourceType':'public-web','sourceLocator':f'{URLS[p]}；統計圖表、統計量與資料分析評量欄位；核讀 2026-09-21。','reviewedAt':'2026-09-21','findings':{'concepts':[c,'公開結構支持先辨識資料型態與分布，再選擇合適統計量與圖表說明。'],'representations':[r],'examplesOrEvidence':['本課的通勤時間、盒鬚圖與抽樣資料均為原創，僅承接公開課程的能力方向。'],'misconceptions':[m],'assessmentEmphasis':[a]},'licenseBoundary':'只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。'}
def main():
 d=json.loads(LESSON.read_text(encoding='utf-8')); assert d['id']=='lesson-math-performance-d-iv-1' and d['reviewStatus']=='draft'
 d['title']='d-Ⅳ-1：從資料分布到合理統計量'
 d['content']={'summary':'統計不是把資料丟進計算機就結束，而是先問資料在說什麼。本課以班級通勤時間為原創資料，讓學生比較平均數、中位數與眾數受極端值影響的差異，並把表格、直方圖與盒鬚圖互相對照；最後檢查統計量是否能回答問題，以及樣本是否足以支持結論。','sections':[{'heading':'先看資料的來源與單位','body':'通勤時間的數字若沒有分鐘、調查日期與對象範圍，就不能直接比較。整理前先確認每筆觀測代表誰、量的是什麼，以及遺漏值是否會改變分布。'},{'heading':'平均數與中位數回答不同問題','body':'平均數把所有數值的總量平均分配，中位數則把排序後的中間位置當作代表。當少數人通勤特別久時，平均數會被拉動，中位數可能更能描述典型個案。'},{'heading':'圖表要保留分布訊息','body':'直方圖適合觀察數值落在哪些區間，盒鬚圖可以比較中位數、四分位數與離群值。圖表的組距、刻度與樣本數若被省略，讀者可能誤判差距。'},{'heading':'結論必須和資料範圍相稱','body':'一個班級的調查可以描述這個班級，不一定能代表全校；相關也不自動等於因果。寫結論時要標示對象、時間、樣本限制與仍需查證的地方。'}]}
 d['studyHighlights']=['先查資料來源、單位、樣本與缺漏，再開始計算。','平均數、中位數與眾數各有用途，選統計量要回應問題。','圖表刻度、組距、四分位數與離群值都是證據，不只看柱子高低。','結論要限制在資料支持的範圍，避免把樣本描述誇大成普遍因果。']
 d['teaching']={'body':[{'id':'hook','phase':'hook','heading':'哪個數字像班級日常','body':'展示十筆通勤分鐘數，其中一筆因轉車延誤特別大，請學生先投票平均數或中位數哪個較像多數人的經驗。先排序並圈出極端值，讓統計量的選擇從問題需求開始。'},{'id':'explain','phase':'explain','heading':'三種中心量的角色','body':'用同一組資料逐步算眾數、平均數與中位數，再讓學生改變一筆最大值觀察哪個量改變最多。每次計算旁邊寫上它回答的是常見值、平衡值還是排序中間位置。'},{'id':'worked-example','phase':'worked-example','heading':'表格與盒鬚圖互讀','body':'將原創的兩組社團活動時間排成表格，畫出五數摘要與盒鬚圖；學生找出中位數、四分位距與可能離群值，再回到原始資料核對圖上的位置，避免把最大值誤當第三四分位數。'},{'id':'guided-practice','phase':'guided-practice','heading':'極端值改變了什麼','body':'把一筆 18 分鐘改成 80 分鐘，學生重新算平均數與中位數，並在圖表上標記分布改變。系統要求學生說明哪個統計量被拉動，以及這是否改變對典型通勤者的描述。'},{'id':'transfer','phase':'transfer','heading':'從班級推論到學校','body':'給兩班各自的抽樣資料，要求學生比較中心與分散程度，再判斷能否宣稱全校學生的通勤差異。學生必須提出樣本數、抽樣方式與時間範圍至少一項限制，不能只引用平均數。'},{'id':'reflect','phase':'reflect','heading':'統計結論的安全邊界','body':'出口題給出一張刻度不等距的柱狀圖，學生先指出圖表可能造成的誤讀，再用一句帶有對象與時間限制的句子重寫結論。最後說明資料支持、推測與尚未證明的因果各是哪一層。'}],'summary':['先確認資料來源、單位、樣本與圖表刻度。','比較中心量對極端值的敏感度，再選能回答問題的統計量。','把原始資料、摘要與圖表互相回查，保留分布訊息。','結論必須標示適用範圍，不把樣本或相關誇大成因果。'],'exitCheck':[{'prompt':'為什麼極端值可能讓平均數改變很多？','expectedEvidence':'平均數使用每一筆數值的總和，極端值會拉動總和；並能和中位數比較。'},{'prompt':'盒鬚圖中的中位數和最大值有什麼不同？','expectedEvidence':'中位數是排序中間位置，最大值是資料中最高觀測，位置與意義不同。'},{'prompt':'一班資料能不能直接代表全校？','expectedEvidence':'不能，需檢查樣本數、抽樣方式、時間與代表性限制。'}]}
 d['interactive']={'type':'guided-choice','goal':'操作資料與極端值，觀察統計量及圖表分布同步變化。','scenario':'調整一筆通勤時間，讓表格、平均數、中位數與盒鬚圖同步更新。','variables':[{'symbol':'n','meaning':'資料筆數'},{'symbol':'x','meaning':'其中一筆通勤分鐘數'}],'steps':[{'id':'step-1','prompt':'要先做哪件事才能比較中心量？','options':['確認單位並排序資料','直接看最大值','刪掉不喜歡的數字'],'answer':'A','feedback':'單位與排序是正確計算平均數和中位數的基礎。'},{'id':'step-2','prompt':'把一筆資料從 18 改成 80，哪個量通常較容易被拉動？','options':['平均數','中位數一定相同','眾數一定增加'],'answer':'A','feedback':'平均數使用總和，極端值會明顯改變它。'},{'id':'step-3','prompt':'如何避免把班級結果誇大成全校結論？','options':['標示樣本、時間與抽樣限制','只保留最漂亮的圖','刪除不符合期待的資料'],'answer':'A','feedback':'結論範圍要和資料來源與代表性相稱。'}]}
 for i, extra in enumerate(['並請學生把極端值與單位寫在資料卡上，說明選統計量前需要哪些資訊。','再把每個中心量的數字和它代表的問題寫在同一欄，避免只比較大小。','同時核對五數摘要與原始排序，說明四分位距不是最大值減最小值。','再用一句完整語句說明分布改變是否影響典型描述，不能只報新的平均數。','最後限制推論對象與時間，並說明樣本代表性不足時結論要如何降級。','並把支持結論的資料、合理推測與尚未證明的因果分成三欄記錄。']):
  d['teaching']['body'][i]['body'] += ' ' + extra
 d['authoringStandard']='version-fused-v1'; d['versionResearch']=[rec('nani','從資料整理、統計量到圖表閱讀建立統計推理','原始表格、排序、中心量與圖表互換','只看平均數或把最大值誤當成典型值','核對資料來源、計算過程、圖表訊息與結論範圍'),rec('kanghsuan','以操作與圖表表徵比較分布及統計量敏感度','直方圖、盒鬚圖與極端值的同步變化','忽略組距、刻度或離群值對判讀的影響','操作後完整解釋分布與數值變化如何互相支持'),rec('hanlin','在情境資料中判斷代表性、限制與推論界線','抽樣、五數摘要與資料敘述的互相核對','把一班資料推廣全校或把相關說成因果','評估證據強度、樣本限制與結論表達是否相稱')]
 d['fusionRecord']={'commonCore':['三版本公開結構共同支持資料整理、統計量與圖表判讀的連結。','統計量的選擇要依資料分布與問題目的，而非固定使用平均數。','結論要受樣本、時間、單位與代表性限制。'],'versionDifferences':['南一證據較突顯計算與圖表基礎；康軒較突顯操作與分布表徵；翰林較突顯資料情境、抽樣與推論界線。這是公開課程計畫層級差異，不宣稱完整教材差異。'],'originalAdditions':['以通勤資料與極端值操作比較中心量。','用刻度錯置與組距資訊診斷圖表誤讀。','加入從班級推論全校的代表性限制轉移題。'],'llmSynthesisNote':'本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG 重新設計統計量、圖表、分布與推論界線。正文、資料、互動與回饋均為原創，未複製教材；Terra 第二輪與正式發布審查尚未完成，維持 draft。'}
 d['updatedAt']='2026-09-21'; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 REPORT.write_text(json.dumps({'unit':'d-Ⅳ-1：從資料分布到合理統計量','lessonId':d['id'],'status':'first-pass-ai-review-complete','reviewStatus':'draft','checks':{'unitSpecificOriginalContent':True,'threeVersionResearchRecords':True,'fusionRecordPresent':True,'interactivePredictionManipulationExplanation':True,'terraSecondPass':'pending'},'reviewedAt':'2026-09-21'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps({'lesson':str(LESSON.relative_to(ROOT)),'reviewStatus':d['reviewStatus']},ensure_ascii=False))
if __name__=='__main__': main()
