import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-10.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-10-first-pass-review.json"


def refs():
    data = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "story elements, setting, character, conflict, and theme"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "narrative viewpoint, motive, symbol, clue, and change"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "story structure, obstacle, climax, foreshadowing, and theme"),
    ]
    return [{"url": u, "title": f"{t}；僅取故事要素與敘事理解能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以場景、角色動機、衝突、觀點、象徵、線索、轉折與主題測量故事要素理解；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in data]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-3-iv-10"
    data["title"] = "3-Ⅳ-10：用故事要素與敘事線索解讀人物、衝突與主題"
    data["content"] = {"summary": "辨識故事要素不是把 setting、character、conflict 當成名詞配對，而是理解它們如何共同推動敘事。本課以社區鐘、霧港、歌唱比賽、藏信、河畔兄弟、上鎖證物箱、破裂羅盤、發明分享、暴風雨前兆與腳踏車賽等原創故事，練習場景、人物動機、敘事觀點、人物關係、高潮、象徵、角色改變、伏筆與主題，並用文本線索區分直接資訊與合理推論。", "sections": [{"heading": "要素要放回故事功能", "body": "setting 不只回答在哪裡，也可能創造霧、河流或港口的限制；character 不只回答誰，還要看目標與選擇；conflict 是阻礙如何與目標相撞。先辨認要素，再問它對情節做了什麼。"}, {"heading": "動機與觀點要有說話位置", "body": "I hid the letter 透露第一人稱角色的內在資訊，但不代表所有人物都知道信件。秘密修鐘、害怕忘詞或拒絕分享，都要從角色行動和內心線索推回 motive，不能用作者或讀者的知識取代角色視角。"}, {"heading": "線索、高潮與象徵形成結構", "body": "黑雲與低飛鳥是暴風雨前的 foreshadowing；打開上鎖箱揭露證物是轉折或高潮；一路攜帶的裂羅盤可能象徵艱難選擇，但必須回看它在故事中的反覆功能，不能只因物件特別就任意賦予意義。"}, {"heading": "主題要由多個要素交叉支持", "body": "自行車賽中的對手變隊友、破輪、修復與共同完成，能支持合作或改變對立的主題。主題不是故事元素的同義詞，而是由角色選擇、衝突結果與反覆線索歸納出的可遷移意義。"}]}
    data["studyHighlights"] = ["以 Setting、Character、Goal、Conflict、Clue、Change 六欄辨識故事要素功能。", "由角色行動、語氣與內在語句推回動機與敘事觀點。", "用伏筆、高潮、象徵與反覆物件連結前後線索。", "主題需由角色選擇、衝突結果與多個要素共同支持。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "一個破羅盤只代表方向嗎？", "body": "展示原創故事中的 cracked compass，請學生先回答它是道具、線索還是象徵，再回看角色每次拿起它的選擇。比較只說『一個羅盤』與說明它如何連結困難選擇的差異，建立要素功能的概念。"}, {"id": "explain", "phase": "explain", "heading": "故事要素功能卡", "body": "建立 Setting、Character、Goal、Conflict、Clue、Change 六欄。每欄先寫明示資訊，再補一欄『對情節的作用』；若是推論，必須附上至少兩個原文線索。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從前兆推測但不過度預言", "body": "以 dark clouds 和 birds flying low 示範 foreshadowing：線索預告 storm 可能接近，但不能直接說暴風雨已造成某個未發生的損害。把 prediction 與 confirmed event 分開記錄。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一故事換成不同要素問題", "body": "輪換港口、歌唱比賽、河畔兄弟、證物箱、發明與自行車賽六組原創故事，依序標 setting、motive、viewpoint、conflict、climax、theme；同伴必須圈出支持判斷的動作或語句。"}, {"id": "transfer", "phase": "transfer", "heading": "把要素表轉成一段解讀", "body": "學生選一個角色，寫三句：他想要什麼、什麼阻礙他、哪個選擇造成改變。再加一句主題，並用兩個故事要素說明它如何被支持，避免只列名詞。"}, {"id": "reflect", "phase": "reflect", "heading": "我有把要素和功能連起來嗎？", "body": "回看作答，標記把場景當主題、把線索當結果、把角色觀點當全知資訊、把象徵當裝飾或把單一事件當普遍道理的地方。修訂時補上要素對情節的作用與證據範圍。"}], "summary": ["用六欄表把故事要素與它對情節的作用連起來。", "從角色語句、行動與觀點判斷動機，不把讀者知識套進角色。", "以伏筆、高潮、象徵與前後線索解釋故事結構。", "用多個要素交叉歸納主題，標出直接資訊和推論界線。"], "exitCheck": [{"prompt": "辨識故事要素後為什麼還要問它的功能？", "expectedEvidence": "能說明場景、角色或物件如何造成限制、推動選擇或支持主題，並引用故事線索。"}, {"prompt": "如何分辨伏筆和已發生的結果？", "expectedEvidence": "能指出前段線索只預告可能事件，並與後段明示結果分開，不把推測寫成確定事實。"}, {"prompt": "主題要如何避免變成單一名詞？", "expectedEvidence": "能由角色目標、衝突、選擇、結果與反覆線索組成可遷移的完整主張。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "用故事要素、敘事線索與證據範圍解釋人物動機、衝突、高潮、改變與主題。", "scenario": "學生擔任故事編輯，要為讀者標出故事場景、角色目標、關鍵線索與可由文本支持的主題。", "variables": [{"symbol": "e", "meaning": "場景、角色、目標、衝突與敘事觀點"}, {"symbol": "c", "meaning": "線索、象徵、高潮、伏筆與結果"}, {"symbol": "t", "meaning": "角色改變、主題與推論範圍"}], "steps": [{"id": "step-1", "prompt": "Jun secretly repairs the community clock because he wants younger children to enjoy it. What motivates him?", "options": ["He wants to help younger children enjoy the clock.", "He wants to hide every clock forever.", "He is repairing it only to win a race."], "answer": "A", "feedback": "由 because 後的目的回推動機，不把秘密行動誤讀成相反目的。"}, {"id": "step-2", "prompt": "Dark clouds and birds flying low appear before a storm. What story element are they?", "options": ["Foreshadowing clues.", "The final solution.", "A character's name."], "answer": "A", "feedback": "前段自然線索預告可能的風暴，屬於 foreshadowing，尚不是結果本身。"}, {"id": "step-3", "prompt": "A rival becomes a teammate, a wheel breaks, and the racers repair it together. What theme is supported?", "options": ["Cooperation can change competition into teamwork.", "Winning always requires working alone.", "Bicycles cannot be repaired."], "answer": "A", "feedback": "角色關係改變、障礙與共同修理三項線索共同支持合作主題。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；故事人物、場景與主要情節定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由故事理解人物、場景與主要情節。", "以動作、順序與結果整理敘事。"], "representations": ["港口、比賽、社區、家庭與校園故事。"], "examplesOrEvidence": ["本課以鐘、霧港、歌唱、河畔與自行車原創故事承接公開結構。"], "misconceptions": ["把故事中的名詞直接當成主旨或主題。"], "assessmentEmphasis": ["重視故事要素、情節與主要內容。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖像故事、角色任務與衝突定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["透過情節、圖像與任務辨識角色目標和障礙。", "依選擇、結果與線索理解故事。"], "representations": ["發明、花園、信件、證物、比賽與角色關係。"], "examplesOrEvidence": ["本課以要素功能卡重新設計敘事任務。"], "misconceptions": ["把衝突、高潮、方案與主題混成同一欄。"], "assessmentEmphasis": ["評量衝突、人物、線索與解決。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；敘事觀點、象徵、伏筆與主題定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["從觀點、角色動機、前後線索形成敘事理解。", "以象徵、伏筆、高潮、改變與主題表達解讀。"], "representations": ["viewpoint、motive、symbol、foreshadowing、climax、theme。"], "examplesOrEvidence": ["本課以羅盤、暴風雨前兆、秘密信件與對手轉隊重新設計推論。"], "misconceptions": ["只因物件特別就任意指定象徵意義，或由一個線索預言完整結局。"], "assessmentEmphasis": ["評量故事要素功能、證據與推論界線。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持故事人物、場景、情節與主要內容理解。", "可靠要素解讀需整合目標、衝突、觀點、線索、結果與主題。", "可用要素功能卡、前兆／結果對照與主題證據鏈完成遷移。"], "versionDifferences": ["南一較突顯人物、場景與情節；康軒較突顯圖像故事、目標、障礙與選擇；翰林較突顯觀點、象徵、伏筆、高潮與主題證據。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Setting、Character、Goal、Conflict、Clue、Change 六欄標記要素功能。", "用社區鐘、霧港、歌唱、信件、證物、羅盤、發明、暴風雨與自行車原創故事練習。", "以 prediction／confirmed event 與主題證據鏈檢查推論範圍。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織故事要素、敘事觀點、動機、衝突、象徵、伏筆、高潮、人物改變與主題。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    explanations = ["because 子句直接說明 Jun 修鐘是為了讓年幼孩子享受鐘。", "霧港與漁船離開是故事開頭的 harbor setting。", "角色想參賽但怕忘詞，忘詞恐懼是主要 obstacle。", "第一人稱 I hid 顯示敘事者只呈現自己的觀點與內心。", "開頭交代河畔生活與兄弟未交談，是人物關係與背景。", "打開上鎖箱並發現證物是故事的揭露高潮。", "裂羅盤反覆陪伴困難選擇，可象徵方向與決定的不確定。", "分享發明前後的行為改變支持由保留轉向合作。", "黑雲和低飛鳥在暴風雨前提供 foreshadowing。", "對手變隊友、破輪與共同修理共同支持合作主題。"]
    paths = sorted(ROOT.glob("questions/english/question-english-performance-3-iv-10-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for i, p in enumerate(paths):
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["answer"]["explanation"] = explanations[i] + f" 正確答案：{q['answer']['value']}"; q["solutionStrategy"] = "先標記故事要素及其功能，再用前後線索判斷動機、衝突、觀點、高潮、象徵、伏筆或主題。"; q["solutionSteps"] = ["先讀完整情境，標記場景、角色目標與主要阻礙。", "圈出能直接支持題目所問要素的動作、語句或前後線索。", "將要素放回故事功能，分辨明示資訊和受控推論。", "用至少兩個線索核對答案，排除只看名詞或過度擴張的選項。", "把答案改述成包含要素與作用的完整句，確認證據範圍沒有超出故事。"]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的故事要素、角色、衝突、線索與主題模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-10")


if __name__ == "__main__":
    main()
