#!/usr/bin/env python3
"""Independent first-pass authoring for math g-IV-1."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/'lessons/math/lesson-math-performance-g-iv-1.json'
REPORT=ROOT/'implementation/reports/math-performance-g-iv-1-first-pass-review.json'
URLS={'nani':'https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf','kanghsuan':'https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110','hanlin':'https://www.cp.ptc.edu.tw/storage/134513/134513_112_B-1_9A.pdf'}
def rec(p,c,r,m,a):
 return {'publisher':p,'edition':f'{p} 公立校方數學課程計畫章節級證據','sourceType':'public-web','sourceLocator':f'{URLS[p]}；直角坐標、點位與距離評量欄位；核讀 2026-09-21。','reviewedAt':'2026-09-21','findings':{'concepts':[c,'公開結構支持以坐標位置、軸向與距離公式建立平面幾何的可驗證表示。'],'representations':[r],'examplesOrEvidence':['本課的地圖格線、座標點與距離情境均為原創，只承接公開課程的能力方向。'],'misconceptions':[m],'assessmentEmphasis':[a]},'licenseBoundary':'只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。'}
def main():
 d=json.loads(LESSON.read_text(encoding='utf-8')); assert d['id']=='lesson-math-performance-g-iv-1' and d['reviewStatus']=='draft'
 d['title']='g-Ⅳ-1：用直角坐標定位點與距離'
 d['content']={'summary':'坐標平面把位置翻譯成有方向的數字，但讀點之前要先確認 x 軸、y 軸、象限與比例。本課以校園地圖格線為原創入口，讓學生在點位、水平／垂直位移與兩點距離之間轉換，並用平方距離與勾股關係驗證結果，避免把坐標順序顛倒或把距離當成位移分量。','sections':[{'heading':'先讀軸與順序','body':'點 (3,−2) 的第一個數是水平位置，第二個數是垂直位置；負號代表位於軸的另一側。標示點前先看原點、刻度與軸名，不能只看數字大小。'},{'heading':'水平與垂直位移','body':'若兩點 y 相同，距離是 x 坐標差的絕對值；若 x 相同，距離是 y 坐標差。這兩種特殊情況能先用格線直接檢查，再進入一般距離公式。'},{'heading':'距離公式來自直角三角形','body':'兩點的水平差與垂直差形成直角三角形，距離平方等於兩個分量平方和。平方會消除正負方向，但最後的距離仍取非負值。'},{'heading':'坐標模型要保留尺度','body':'地圖每格可能代表 10 公尺，坐標距離算出的是格數，還要依比例換成實際距離；若軸向比例不同，不能直接把格數當真實長度。'}]}
 d['studyHighlights']=['先確認原點、軸向、刻度與坐標順序。','先判斷是否為水平或垂直特殊情況，再使用距離公式。','把水平差、垂直差與實際距離分開標記。','用平方距離、圖上格線與單位換算互相檢查。']
 d['teaching']={'body':[{'id':'hook','phase':'hook','heading':'校園地圖上的兩個集合點','body':'給出帶有原點與比例的原創校園格線圖，請學生先預測集合點 A、B 位於哪個象限，以及走最短直線距離是否等於水平差加垂直差。先處理方向和尺度，再談公式。'},{'id':'explain','phase':'explain','heading':'坐標是有順序的地址','body':'示範點 (−2,3) 與 (3,−2) 的位置不同，要求學生先沿 x 軸再沿 y 軸定位。用同一格線標上坐標、象限與單位，讓負號成為方向證據。'},{'id':'worked-example','phase':'worked-example','heading':'從直角三角形求距離','body':'對 A(1,2)、B(5,5)，水平差 4、垂直差 3，因此距離為 √(4²+3²)=5。先在圖上畫出 3-4-5 直角三角形，再代入公式，最後確認距離單位。'},{'id':'guided-practice','phase':'guided-practice','heading':'抓出坐標順序錯誤','body':'提供三個候選點與一張地圖，學生先選出符合「向右 4、向下 2」的坐標，再以水平與垂直差回查。若把 (x,y) 寫反，回饋要求重新沿軸移動而非只改負號。'},{'id':'transfer','phase':'transfer','heading':'從格數換成公尺','body':'地圖每格代表 10 公尺，兩個點的坐標距離為 7 格；學生計算實際距離並說明若 x 軸每格 10、公尺而 y 軸每格 20，為何要先換算兩個分量再套模型。'},{'id':'reflect','phase':'reflect','heading':'距離答案的四項檢查','body':'出口題要求學生圈出坐標順序、象限方向、平方根非負性與單位比例；再指出一個看似合理但尺度錯誤的答案，寫出哪一項證據能推翻它。'}],'summary':['先讀坐標軸、原點、刻度與順序。','把水平與垂直差視為直角三角形兩股。','距離取非負並依比例換算實際單位。','用圖、公式、位移與尺度四種證據回查。'],'exitCheck':[{'prompt':'(−2,3) 與 (3,−2) 為什麼不是同一點？','expectedEvidence':'坐標順序不同，水平與垂直位置互換後位置改變。'},{'prompt':'兩點水平差 4、垂直差 3，距離如何求？','expectedEvidence':'用勾股關係 √(4²+3²)=5，並說明單位。'},{'prompt':'格數和公尺何時不能直接畫等號？','expectedEvidence':'地圖有比例或兩軸尺度不同時，必須先換算實際長度。'}]}
 d['interactive']={'type':'guided-choice','goal':'在坐標、格線、位移與距離公式間同步驗證點位。','scenario':'拖曳地圖上的點，觀察坐標、水平／垂直差與距離同步更新。','variables':[{'symbol':'x','meaning':'水平坐標或水平差'},{'symbol':'y','meaning':'垂直坐標或垂直差'}],'steps':[{'id':'step-1','prompt':'點 (−2,3) 要先沿哪個方向定位？','options':['先水平到 −2，再垂直到 3','先垂直到 −2，再水平到 3','只看第二個數'],'answer':'A','feedback':'坐標順序是 (x,y)，先讀水平再讀垂直。'},{'id':'step-2','prompt':'水平差 4、垂直差 3 時距離是多少？','options':['5','7','1'],'answer':'A','feedback':'用直角三角形 √(4²+3²)=5。'},{'id':'step-3','prompt':'每格代表 10 公尺時，公式算出的 5 代表什麼？','options':['5 格，實際距離為 50 公尺','50 格','5 公尺'],'answer':'A','feedback':'先確認公式結果的格數，再套用地圖比例。'}]}
 for i, extra in enumerate(['並請學生把象限、比例與兩個坐標寫在圖例旁，說明最短距離的方向假設。','再讓學生交換兩個數字重新定位，說出哪個軸向和負號造成位置改變。','同時計算平方距離與圖上直角邊，確認根號結果和單位一致。','最後要求學生畫出正確路徑並標示水平、垂直分量，讓錯誤可定位。','再分別換算兩軸的實際長度，說明不能把不同尺度的格數直接相加。','並將錯誤答案與原點、刻度及比例逐項比對，寫出最先發現的矛盾。']):
  d['teaching']['body'][i]['body'] += ' ' + extra
 d['authoringStandard']='version-fused-v1'; d['versionResearch']=[rec('nani','以坐標軸、點位與距離建立平面位置表徵','格線、坐標、位移與距離公式的互相轉換','顛倒 x、y 或忽略負號所代表的方向','完整核對點位、距離、比例與單位回查結果'),rec('kanghsuan','以操作和圖形表徵理解水平垂直差與勾股','拖曳點、直角三角形與坐標的同步變化','把水平差加垂直差誤當成直線距離','操作後解釋圖形與公式如何互相支持'),rec('hanlin','在地圖情境中處理尺度與實際距離','格數、比例、象限與路徑限制的情境表徵','把格數直接當公尺或忽略兩軸比例差異','評估模型選擇、尺度換算與證據表達是否完整')]
 d['fusionRecord']={'commonCore':['三版本公開結構共同支持以直角坐標表示平面位置。','水平與垂直差可形成直角三角形並導向距離公式。','坐標尺度、單位與方向是解讀答案的必要條件。'],'versionDifferences':['南一證據較突顯坐標與距離基礎；康軒較突顯操作、圖形與勾股表徵；翰林較突顯地圖尺度、單位與情境限制。這是公開課程計畫層級差異，不宣稱完整教材差異。'],'originalAdditions':['以校園地圖格線引出坐標順序與象限。','設計坐標顛倒、格數誤當公尺的診斷。','加入兩軸比例不同時的分量換算活動。'],'llmSynthesisNote':'本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG 重新設計直角坐標、距離與尺度判讀。正文、例題、互動與回饋均為原創，未複製教材；Terra 第二輪與正式發布審查尚未完成，維持 draft。'}
 d['updatedAt']='2026-09-21'; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 REPORT.write_text(json.dumps({'unit':'g-Ⅳ-1：用直角坐標定位點與距離','lessonId':d['id'],'status':'first-pass-ai-review-complete','reviewStatus':'draft','checks':{'unitSpecificOriginalContent':True,'threeVersionResearchRecords':True,'fusionRecordPresent':True,'interactivePredictionManipulationExplanation':True,'terraSecondPass':'pending'},'reviewedAt':'2026-09-21'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps({'lesson':str(LESSON.relative_to(ROOT)),'reviewStatus':d['reviewStatus']},ensure_ascii=False))
if __name__=='__main__': main()
