import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-4-iv-3.json"
REPORT = ROOT / "implementation/reports/english-performance-4-iv-3-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "capitalization, punctuation, dates, time, email, and paragraph format"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "written format, audience, quotation, list, and clarity"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "notice, email, address, report organization, and punctuation"),
    ]
    return [{"url": u, "title": f"{t}；僅取英文書寫格式、讀者、標點與組織能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以通知、email、書信、報告與規則要求學生辨識大小寫、標點、日期、時間、引號、清單與段落格式；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-4-iv-3"
    data["title"] = "4-Ⅳ-3：依讀者與文本目的正確使用英文書寫格式"
    data["content"] = {"summary": "正確格式不是表面排版，而是讓讀者能辨認句子邊界、時間、收信人、規則層級與報告結構。本課以校園通知、問句、活動時間與日期、給老師的 email、安全規則、直接引語、書信地址、報告連接與班級花園段落等原創素材，練習大小寫、句末標點、日期時間、稱呼、清單、引號、地址與段落安排，並依讀者和目的修訂。", "sections": [{"heading": "格式要服務讀者任務", "body": "句首與專有名詞大寫幫助辨認句子和名稱；問句用問號；通知需清楚日期時間；email 要有稱呼和目的；安全規則用平行清單；報告用段落和連接詞。先判斷讀者要找什麼，再選格式。"}, {"heading": "時間日期要避免雙重解讀", "body": "活動通知可寫 Saturday, October 12, at 9:00 a.m.，將星期、月份、日期與時間分開，並保持同一格式。若只寫 10/12，跨地區讀者可能誤讀月份與日期，格式清楚比省字更重要。"}, {"heading": "標點和引號標示語意邊界", "body": "直接引用角色原話時用 quotation marks，句末標點與引用範圍要一致；兩個相關想法可用 because、so 或分號連接，不能讓讀者猜句子在哪裡結束。"}, {"heading": "段落與清單讓資訊可掃讀", "body": "三項安全規則各自一行、形式平行，讀者能快速核對；短報告可用開頭主題句、證據／活動細節和結尾結果。格式改變的是讀取路徑，不是把內容切碎而失去關係。"}]}
    data["studyHighlights"] = ["先判斷讀者、目的與資訊層級，再選大小寫、標點和版面格式。", "用一致的日期、時間、稱呼、地址與引號格式減少歧義。", "以平行清單、連接詞與段落讓規則和報告可掃讀。", "完成後從陌生讀者角度檢查句界、順序、收件人與可執行資訊。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "同樣的內容，為什麼有一版比較好用？", "body": "比較兩張原創活動通知：一張把日期、時間、地點塞在一行，另一張分行並標上 Saturday, October 12, 9:00 a.m.。學生先找容易誤讀處，再用讀者任務說明格式如何降低負擔。"}, {"id": "explain", "phase": "explain", "heading": "格式—目的—讀者三欄卡", "body": "建立 Format、Purpose、Audience 三欄。先判斷是問句、通知、email、規則、引用或報告，再核對大小寫、標點、時間日期、稱呼、清單、引號與段落。"}, {"id": "worked-example", "phase": "worked-example", "heading": "把安全規則排成可掃讀清單", "body": "將 Wear goggles、Do not run、Wash your hands 改成三行平行規則，保留相同動詞形式與句末標點。示範清單不是任意換行，而是讓讀者逐項執行與核對。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一訊息換成不同文本", "body": "輪換通知、email、書信、報告與對話引用五組原創內容。學生先標讀者和目的，再修訂大小寫、標點、日期、稱呼、引號或段落；同伴從陌生讀者角度測讀。"}, {"id": "transfer", "phase": "transfer", "heading": "從內容草稿到可發布版本", "body": "學生把班級花園資料做成一封 email、一張公告和一段短報告，保留共同事實但調整稱呼、資訊順序、格式與句子長度。交換後檢查讀者能否找出下一步。"}, {"id": "reflect", "phase": "reflect", "heading": "格式是裝飾還是證據？", "body": "回看答案，標記大寫漏失、問句無問號、日期歧義、稱呼不合、清單不平行、引號界線或段落跳接。修訂時寫出讀者可能遇到的誤讀，再選格式修正。"}], "summary": ["以 Format、Purpose、Audience 三欄決定書寫格式。", "用大小寫、標點、日期時間、稱呼與引號標示語意邊界。", "用平行清單、連接詞與段落提升通知和報告的可掃讀性。", "以陌生讀者測讀驗證格式是否支持下一步行動。"], "exitCheck": [{"prompt": "為什麼正確格式要從讀者和目的開始？", "expectedEvidence": "能說明通知、email、規則、引用和報告的格式需求不同，並舉例。"}, {"prompt": "如何降低英文日期與時間的歧義？", "expectedEvidence": "能使用清楚、完整且一致的月份、日期、星期與時間格式。"}, {"prompt": "清單或段落如何幫助讀者執行任務？", "expectedEvidence": "能說明平行項目、資訊層級和連接詞如何讓讀者掃讀、排序和回查。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "依讀者與文本目的修訂大小寫、標點、日期時間、稱呼、清單、引號與段落格式。", "scenario": "學生擔任校園文書編輯，要把草稿改成讀者能快速理解並採取行動的公告、email 與報告。", "variables": [{"symbol": "f", "meaning": "格式：大小寫、標點、日期、時間、引號與段落"}, {"symbol": "p", "meaning": "文本目的與資訊層級"}, {"symbol": "a", "meaning": "讀者、歧義、掃讀與下一步"}], "steps": [{"id": "step-1", "prompt": "Which sentence uses capitalization correctly?", "options": ["Our English class meets on Monday.", "our english class meets on monday.", "Our english Class meets on monday."], "answer": "A", "feedback": "句首、English 與 Monday 需要大寫，格式同時標示句子和專有名稱。"}, {"id": "step-2", "prompt": "Which written form is clearest for an event notice?", "options": ["Saturday, October 12, at 9:00 a.m.", "10/12 9", "Saturday october twelve maybe morning"], "answer": "A", "feedback": "A 分開星期、月份日期與時間，讀者較不會誤讀。"}, {"id": "step-3", "prompt": "Which layout organizes three safety rules most clearly?", "options": ["Wear goggles.\nDo not run.\nWash your hands.", "Wear goggles do not run wash your hands all in one line.", "Goggles, running, hands maybe."], "answer": "A", "feedback": "A 使用平行、分行且可逐項執行的規則格式。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；生活書寫、句型與主要訊息定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由生活書面文本理解格式、句意與主要訊息。", "以大小寫、標點、日期與稱呼完成清楚書寫。"], "representations": ["公告、email、書信、表單與校園報告。"], "examplesOrEvidence": ["本課以活動通知、規則、花園報告與教師 email 原創素材承接公開結構。"], "misconceptions": ["把格式當裝飾，沒有考慮讀者是否誤讀。"], "assessmentEmphasis": ["重視句子正確、格式與生活書寫應用。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖文、任務與書寫格式定位；核讀 2026-09-21。", "findings": {"concepts": ["透過圖文與任務選擇適當書寫格式。", "依讀者、目的、日期與資訊層級完成文本。"], "representations": ["通知、清單、引號、地址、email 與短報告。"], "examplesOrEvidence": ["本課以格式—目的—讀者卡重新設計書寫修訂。"], "misconceptions": ["日期、稱呼、清單與段落形式不一致。"], "assessmentEmphasis": ["評量格式、清晰度、語意與可用性。"], "misconceptions": ["日期、稱呼、清單與段落形式不一致。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；書面文本、格式與讀者理解定位；核讀 2026-09-21。", "findings": {"concepts": ["從書面目的、讀者與版面形成格式判斷。", "以引號、清單、連接詞、段落與日期降低歧義。"], "representations": ["format、audience、quotation、list、paragraph、clarity。"], "examplesOrEvidence": ["本課以校園文書三版本重新設計陌生讀者測讀。"], "misconceptions": ["只看文法，忽略段落、資訊層級與可掃讀。"], "assessmentEmphasis": ["評量格式、目的、段落與清楚表達。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持生活書面文本、句子與正確格式。", "可靠書寫需整合讀者、目的、資訊層級與格式功能。", "可用格式—目的—讀者卡、陌生讀者測讀與多版本改寫完成遷移。"], "versionDifferences": ["南一較突顯生活書寫與基本句型；康軒較突顯圖文、任務、清單與文本格式；翰林較突顯讀者、段落、引號、連接與清晰度。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Format、Purpose、Audience 三欄決定書寫格式。", "用活動通知、email、規則、書信、引語、地址與班級花園報告原創素材練習。", "以陌生讀者測讀和同一內容三種文本檢查格式是否支持行動。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織大小寫、標點、日期時間、稱呼、清單、引號、地址、連接詞與段落格式。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-4-iv-3-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先判斷文本目的與讀者，再檢查句界、大小寫、日期時間、稱呼、引號、清單與段落，最後以陌生讀者測讀。"; q["solutionSteps"] = ["先辨認是問句、通知、email、規則、引用或報告。", "找出讀者需要快速辨認的名稱、句界、日期、時間、收件人或行動。", "套用相應格式：大小寫、標點、稱呼、清單、引號、連接詞或段落。", "檢查格式是否一致、平行且沒有歧義，排除只看表面整齊的選項。", "從陌生讀者角度重讀，確認能找到下一步且內容關係沒有被排版切斷。" ]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的書寫格式、通知、email、引號、清單與段落模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 4-iv-3")


if __name__ == "__main__":
    main()
