import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-4-iv-2.json"
REPORT = ROOT / "implementation/reports/english-performance-4-iv-2-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "charts, tables, maps, process, comparison, and sentence writing"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "visual information, location, sequence, trend, and evidence"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "chart description, comparison, superlative, and summary"),
    ]
    return [{"url": u, "title": f"{t}；僅取依圖示圖表寫句子的能力、資料型態與表達方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以表格、圖示、地圖、流程、折線、長條與調查資料要求學生定位、比較、排序並寫出符合證據的句子；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-4-iv-2"
    data["title"] = "4-Ⅳ-2：把圖示、圖表與位置關係寫成有證據的英文句子"
    data["content"] = {"summary": "依圖示圖表寫句子，先讀資料的標題、單位、方向、順序與比較關係，再選擇能準確表達的句型。本文以借書、天氣圖示、社團比例、地圖位置、泡茶流程、用水折線、交通時間、教室平面圖、通學調查與修訂分數等原創資料，練習 there is／are、介系詞、比較級、最高級、順序詞、趨勢與摘要句，並防止把圖形印象或未提供的原因寫進答案。", "sections": [{"heading": "先把圖形轉成資料欄位", "body": "表格要看類別與數值，天氣圖示要看日期與符號，地圖要看方向和相對位置，流程要看箭頭順序。寫句子前先用 words、numbers、place、order 四欄轉錄，避免漏掉單位或方向。"}, {"heading": "句型要承接資料關係", "body": "The library is north of the park 表達位置，Sports was the most popular club 表達最高比例，Water use fell from 80 to 45 litres 表達趨勢。先判斷資料關係，再選介系詞、比較級或動詞。"}, {"heading": "比較和摘要不能超過圖表", "body": "若圖表只顯示修訂前後分數，可以說 score increased from 6 to 9，但不能說某一方法一定造成進步。調查能支持 walk 10、bus 22、bicycle 8 的比較，不代表所有學生永遠都搭公車。"}, {"heading": "寫完要回填圖表驗證", "body": "句子完成後逐項檢查日期、數值、方向、順序、主詞和單位；再把英文句子回翻成資料。若回翻找不到來源欄位，就刪除或改寫超出的部分。"}]}
    data["studyHighlights"] = ["先讀標題、類別、數值、方向、順序與單位，再組句。", "用 there is／are、介系詞、比較級、最高級、趨勢與順序詞表達資料關係。", "摘要只寫圖表支持的比較或變化，不自行補原因和普遍結論。", "完成句子後回填資料欄位，逐項核對數字、位置、時間與單位。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "柱子高就能直接寫答案嗎？", "body": "展示原創借書表與長條圖，學生先寫 Tuesday is highest，再回看 18 books 的數值與單位，發現圖形印象要轉成完整、有證據的句子。"}, {"id": "explain", "phase": "explain", "heading": "資料—關係—句型三欄卡", "body": "建立 Data、Relation、Sentence frame 三欄。Data 記錄類別與數值，Relation 判斷位置、順序、比較或趨勢，Sentence frame 再選 there is／are、is north of、more than、fell from 或 after。"}, {"id": "worked-example", "phase": "worked-example", "heading": "把折線變成趨勢句", "body": "以 water use 80→60→45 示範：先讀月份與單位，再寫 Water use fell from 80 litres in April to 45 in June。不能把下降原因寫成圖表沒有提供的政策效果。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "圖表換句型不換證據", "body": "輪換表格、天氣、圓餅圖、地圖、流程、折線、交通、平面圖、調查與前後分數十組原創資料。學生先口述關係，再寫句子，互伴用螢光筆回填每個數字或位置來源。"}, {"id": "transfer", "phase": "transfer", "heading": "為不同讀者寫同一張圖", "body": "將一張通學調查分別寫成給同學的比較句、給校方的摘要句與給海報讀者的短句。保留相同數據，調整資訊量與語氣，避免改變結論。"}, {"id": "reflect", "phase": "reflect", "heading": "我的英文句子有回到圖表嗎？", "body": "回看答案，標記漏單位、方向反了、比較詞錯、順序顛倒、圖示誤讀或自行加入原因。修訂時畫箭頭連回資料欄位，再重新朗讀句子。"}], "summary": ["用 Data、Relation、Sentence frame 三欄把視覺資料轉成句子。", "先判斷位置、順序、比較或趨勢，再選符合功能的英文句型。", "回填數值、單位、方向與類別，避免超出圖表的因果和普遍結論。", "依不同讀者調整句子長度，但保留原始證據與關係。"], "exitCheck": [{"prompt": "圖示圖表寫句子前為什麼要先記錄資料欄位？", "expectedEvidence": "能指出類別、數值、位置、順序與單位，說明它們如何支持句子。"}, {"prompt": "如何分辨『下降』和『造成下降的原因』？", "expectedEvidence": "能寫出圖表直接顯示的時間—數值變化，並標記原因需要額外資料。"}, {"prompt": "完成英文句子後如何確認沒有讀錯圖？", "expectedEvidence": "能回填日期、數字、方向、單位與關係，指出句子每部分的來源。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "讀取圖示圖表的資料與關係，寫出位置、順序、比較或趨勢均正確的英文句子。", "scenario": "學生擔任校園資料編輯，要把表格、地圖、流程與圖表轉成讀者能直接理解的英文摘要。", "variables": [{"symbol": "d", "meaning": "類別、數值、日期、單位與圖示"}, {"symbol": "r", "meaning": "位置、順序、比較、趨勢與前後變化"}, {"symbol": "s", "meaning": "there is／are、介系詞、比較級、順序詞與摘要句"}], "steps": [{"id": "step-1", "prompt": "Books borrowed were Monday 12, Tuesday 18, and Wednesday 15. Which sentence is correct?", "options": ["Tuesday had the most borrowed books, with 18.", "Monday had the most, with 18.", "Wednesday had fewer than Monday, with 20."], "answer": "A", "feedback": "A 同時正確表達最高日、數值與單位。"}, {"id": "step-2", "prompt": "The library is north of the park, and the café is east of the library. Which sentence is supported?", "options": ["The café is east of the library.", "The park is north of the library.", "The café is west of the park."], "answer": "A", "feedback": "A 直接回述地圖提供的方向關係，不交換主詞或方向。"}, {"id": "step-3", "prompt": "Water use fell from 80 litres in April to 45 in June. Which sentence is accurate?", "options": ["Water use decreased from April to June.", "Water use increased because of a new rule.", "Water use stayed at 80 litres."], "answer": "A", "feedback": "A 描述圖表直接顯示的下降；原因沒有由圖表提供。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；生活圖表、句型與主要訊息定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由表格、圖示與生活資料理解主要訊息。", "以數量、位置、順序與變化完成句子。"], "representations": ["借閱、天氣、交通、流程與校園調查。"], "examplesOrEvidence": ["本課以借書、泡茶、通學與教室資料承接公開結構。"], "misconceptions": ["只看圖形外觀，不記單位或資料欄位。"], "assessmentEmphasis": ["重視圖表主要內容、細節與生活表達。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖像、表格、任務與句型定位；核讀 2026-09-21。", "findings": {"concepts": ["透過圖像、地圖與任務寫出基本句子。", "依方向、步驟、比較與趨勢完成表達。"], "representations": ["圓餅、地圖、流程、折線、平面圖與前後分數。"], "examplesOrEvidence": ["本課以資料—關係—句型卡重新設計圖表寫作。"], "misconceptions": ["把數字、方向或流程順序互換。"], "assessmentEmphasis": ["評量資料定位、句型正確與語意。"], "misconceptions": ["把數字、方向或流程順序互換。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；圖文整合、比較與證據句定位；核讀 2026-09-21。", "findings": {"concepts": ["從圖表、地圖與流程形成有證據的句子。", "以比較、趨勢、位置與限制檢查表達。"], "representations": ["data、relation、sentence frame、trend、unit、limit。"], "examplesOrEvidence": ["本課以折線、圖示和混合資料重新設計回填檢查。"], "misconceptions": ["把圖表顯示的變化誤寫成確定原因。"], "assessmentEmphasis": ["評量視覺資料、句型、比較與摘要。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持圖表、圖示、地圖、流程與生活資料表達。", "可靠句子需整合資料欄位、關係、單位與適合的英文句型。", "可用資料—關係—句型卡、回填來源與讀者改寫完成遷移。"], "versionDifferences": ["南一較突顯生活圖表與基本句型；康軒較突顯圖像、地圖、流程與任務；翰林較突顯圖文整合、比較、趨勢與證據限制。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Data、Relation、Sentence frame 三欄把視覺資料轉成句子。", "用借閱、天氣、社團、地圖、泡茶、用水、交通、平面圖與調查原創資料練習。", "以回填欄位與讀者版本改寫檢查數字、方向、單位與因果界線。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織圖示圖表、位置、順序、比較、趨勢與有證據句子。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-4-iv-2-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先轉錄圖表資料，再判斷位置、順序、比較或趨勢關係，最後選句型並回填核對。"; q["solutionSteps"] = ["先讀標題、類別、數值、方向、順序與單位。", "判斷題目要表達位置、流程、比較、最高最低、趨勢或摘要。", "選擇符合關係的英文句型與介系詞。", "逐項核對主詞、數字、單位、方向和時間，排除交換或過度推論。", "將句子回填到圖表並朗讀，確認每個資訊都有來源且語意完整。" ]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的圖表、圖示、地圖、流程與資料句模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 4-iv-2")


if __name__ == "__main__":
    main()
