#!/usr/bin/env python3
"""Independent first-pass authoring for math a-IV-6."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/'lessons/math/lesson-math-performance-a-iv-6.json'
REPORT=ROOT/'implementation/reports/math-performance-a-iv-6-first-pass-review.json'
URLS={'nani':'https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf','kanghsuan':'https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110','hanlin':'https://www.cp.ptc.edu.tw/storage/134513/134513_112_B-1_9A.pdf'}
def rec(p,c,r,m,a):
 return {'publisher':p,'edition':f'{p} 公立校方數學課程計畫章節級證據','sourceType':'public-web','sourceLocator':f'{URLS[p]}；一元二次方程、根與圖形評量欄位；核讀 2026-09-21。','reviewedAt':'2026-09-21','findings':{'concepts':[c,'公開結構支持以因式分解、公式或圖形理解二次方程的解，並檢查解是否符合題目限制。'],'representations':[r],'examplesOrEvidence':['本課的拋物線、面積與數值例子均為原創，只研究公開能力方向。'],'misconceptions':[m],'assessmentEmphasis':[a]},'licenseBoundary':'只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。'}
def main():
 d=json.loads(LESSON.read_text(encoding='utf-8')); assert d['id']=='lesson-math-performance-a-iv-6' and d['reviewStatus']=='draft'
 d['title']='a-Ⅳ-6：二次方程的根與圖形交會'
 d['content']={'summary':'二次方程的解不是公式輸出的兩個數字，而是讓多項式等於零的輸入值。本課從矩形面積與拋物線穿越 x 軸的情境開始，讓學生比較因式分解、配方法與公式的適用條件，並以代回、根的個數與情境範圍檢查結果，避免漏掉負根、誤用平方根或把頂點當成解。','sections':[{'heading':'根是讓式子歸零的值','body':'若 x²−5x+6=0，根是代入後使左邊等於 0 的 x。先把方程整理為標準形式，再理解解是輸入值而非圖上的任意高度。'},{'heading':'因式分解揭示兩個可能','body':'x²−5x+6=(x−2)(x−3)，乘積為零表示 x−2=0 或 x−3=0，因此根為 2、3。每個根都要代回原方程確認，不能只看括號。'},{'heading':'判斷根的個數與圖形','body':'拋物線與 x 軸交兩次、相切一次或不相交，分別對應兩個、重根或沒有實數根。圖形提供解的數量線索，但精確值仍需代數求出。'},{'heading':'情境會篩選數學解','body':'面積、長度或時間通常要求非負；代數上成立的負根，放回原情境可能必須排除。排除時要寫出限制與理由，不可只說答案不合理。'}]}
 d['studyHighlights']=['先把方程整理成等於零，明確根的定義。','能因式分解時用零乘積理解每個可能根。','用圖形交點判斷根的數量，但不把頂點或高度當成根。','每個根都代回原式，並檢查長度、時間等情境限制。']
 d['teaching']={'body':[{'id':'hook','phase':'hook','heading':'兩個可能的長度','body':'一個長方形面積為 6，兩邊相差 1；請學生列出可能的邊長並預測是否有兩組。把問題轉成 x(x+1)=6，讓二次方程從面積關係出現，而不是先丟公式。'},{'id':'explain','phase':'explain','heading':'把方程整理為零','body':'由 x(x+1)=6 得 x²+x−6=0，再因式分解為 (x+3)(x−2)=0。先解出 −3 與 2，再回到長度限制排除 −3，明確區分代數根與情境可行解。'},{'id':'worked-example','phase':'worked-example','heading':'因式分解與代回','body':'對 x²−5x+6=0，找兩個乘積為 6、和為 −5 的數 −2、−3，得到 (x−2)(x−3)=0。分別代回原式，確認 2 與 3 都是根，並在數線標示兩個輸入值。'},{'id':'guided-practice','phase':'guided-practice','heading':'讀取圖形的交點','body':'給三條原創拋物線資料：一條穿越兩次、一條剛好相切、一條在 x 軸上方。學生先判斷實數根個數，再選擇可用的代數方法，最後用一個計算值核對圖形預測。'},{'id':'transfer','phase':'transfer','heading':'比較不同方法的適用性','body':'對無法立即因式分解的 2x²+3x−2=0，學生可用公式求根，並把判別式 25 解釋成有兩個實根；再比較若判別式為 0 或負數，圖形與解的數量如何改變。'},{'id':'reflect','phase':'reflect','heading':'代數根與情境解的界線','body':'出口題給出一個含負根的面積模型，學生要列出兩個代數根、指出哪個違反長度限制，並寫出代回與圖形檢查的順序；最後說明為何保留或排除每個根。'}],'summary':['根是使整理後的多項式等於零的輸入值。','因式分解用零乘積找候選根，不能省略代回。','圖形交點能預測實根數量，但精確值仍要計算。','情境限制會從代數根中篩選可行解，理由必須明寫。'],'exitCheck':[{'prompt':'為什麼先要把方程整理成等於零？','expectedEvidence':'根的定義是使多項式值為零，整理後才能使用因式分解或公式。'},{'prompt':'(x−2)(x−3)=0 的根有哪些？','expectedEvidence':'由零乘積得到 x=2 或 x=3，並能代回確認。'},{'prompt':'面積題出現負根時如何處理？','expectedEvidence':'保留它作為代數候選，再依長度非負的情境限制排除並說明原因。'}]}
 d['interactive']={'type':'algebra-expression-builder','goal':'以因式、圖形與代回檢查理解二次方程的根。','scenario':'調整二次式係數，觀察拋物線與 x 軸交點數量及候選根同步改變。','variables':[{'symbol':'a','meaning':'二次項係數'},{'symbol':'d','meaning':'判斷實根數量的判別式'}],'steps':[{'id':'step-1','prompt':'x²−5x+6=0 可分解成什麼？','options':['(x−2)(x−3)=0','(x+2)(x+3)=0','(x−5)(x+6)=0'],'answer':'A','feedback':'兩數乘積 6、和為 −5，因此是 −2 與 −3 的相反號括號。'},{'id':'step-2','prompt':'如何由乘積為零找根？','options':['令 x−2=0 或 x−3=0','兩括號相加','只取較大的括號'],'answer':'A','feedback':'零乘積表示至少一個因子為零。'},{'id':'step-3','prompt':'得到根後最重要的檢查是什麼？','options':['代回原式並檢查情境限制','只看圖形高度','把負根自動刪除'],'answer':'A','feedback':'先確認代數正確，再依長度或時間等限制判斷可行性。'}]}
 for i, extra in enumerate(['再讓學生標出長度必須為正的限制，說明這個限制如何篩選代數候選根。','並將兩個括號分別對應到兩個可能的 x 值，避免只記住答案。','完成後將兩個根逐一代回原方程，將根的位置和數線標記互相對照。','要求學生把圖形交點數量、代數方法與一個計算值寫在同一張檢查表。','再用判別式正、零、負三種情形畫出預測，並說明實根數量的限制。','最後區分「代數上是根」與「情境中可採用的解」，每個排除都要附條件。']):
  d['teaching']['body'][i]['body'] += ' ' + extra
 d['authoringStandard']='version-fused-v1'; d['versionResearch']=[rec('nani','以二次式、因式分解與方程求根建立代數路徑','面積模型、因式、代回與數線標根','把頂點或係數誤當成方程的根，忽略代入後應為零','完整檢查整理、求根、代回與情境篩選的順序'),rec('kanghsuan','以圖形與操作表徵呈現拋物線交軸及根的數量','拋物線、x 軸交點與代數式同步','看到圖形高度就把頂點當根，或忽略重根的意義','要求圖形預測與代數精算互相驗證並說明根的數量'),rec('hanlin','比較不同解法並處理實根數量與情境限制','因式分解、公式、判別式與生活範圍','負根一律刪除或不檢查判別式條件','評估方法選擇、根的個數與可行解理由是否完整')]
 d['fusionRecord']={'commonCore':['三版本公開結構共同支持二次方程的整理、求根與代回驗證。','圖形或模型可幫助理解根的數量，但不能取代精確推理。','情境限制與代數候選根必須分開判斷並說明。'],'versionDifferences':['南一證據較突顯代數求根與式子結構；康軒較突顯圖形表徵與交點；翰林較突顯方法比較、判別式與情境可行性。這是公開課程計畫層級差異，不宣稱完整教材差異。'],'originalAdditions':['以面積模型引出負根與可行解的區分。','以三種拋物線圖形診斷根的數量與頂點迷思。','把判別式、公式與生活限制放進同一個轉移任務。'],'llmSynthesisNote':'本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG 重新設計二次方程的根、圖形、方法選擇與情境篩選。正文、例題、互動與回饋均為原創，未複製教材；Terra 第二輪與正式發布審查尚未完成，維持 draft。'}
 d['updatedAt']='2026-09-21'; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 REPORT.write_text(json.dumps({'unit':'a-Ⅳ-6：二次方程的根與圖形交會','lessonId':d['id'],'status':'first-pass-ai-review-complete','reviewStatus':'draft','checks':{'unitSpecificOriginalContent':True,'threeVersionResearchRecords':True,'fusionRecordPresent':True,'interactivePredictionManipulationExplanation':True,'terraSecondPass':'pending'},'reviewedAt':'2026-09-21'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps({'lesson':str(LESSON.relative_to(ROOT)),'reviewStatus':d['reviewStatus']},ensure_ascii=False))
if __name__=='__main__': main()
