import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/chinese/lesson-chinese-performance-5-iv-5.json"
REPORT=ROOT/"implementation/reports/chinese-performance-5-iv-5-first-pass-review.json"

def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher":name,"edition":f"{name} 公立校方國文課程計畫章節級證據","sourceType":"public-web","sourceLocator":locator,"reviewedAt":"2026-09-21","findings":{"concepts":concepts,"representations":forms,"examplesOrEvidence":["本課以原創地方議題、不同立場文章、社群資訊與生活行動卡，承接公開課程的多元閱讀、議題探究與公民表達方向。"],"misconceptions":[misconception],"assessmentEmphasis":[assessment]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}

def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-chinese-performance-5-iv-5"
    data["title"]="5-Ⅳ-5：在多元閱讀中連結生活議題與社會行動"
    data["content"]={"summary":"多元閱讀不只是讀不同題材，而是辨認不同作者、群體與資料位置如何描述同一議題，並把文化、環境、政策、資源與日常經驗放在同一張問題地圖上。本課以公園改造、傳統市場、共享單車、老街觀光、圖書館開放與食物浪費等自編材料，練習比較立場、查核來源、補足被忽略的聲音、處理價值衝突，最後把閱讀轉成有指標、可回饋、可修正的生活行動。", "sections":[{"heading":"先看誰在說、誰沒被說到","body":"同一座公園，居民可能在意樹蔭與安靜，規劃者可能關心安全、維護與人流；兩者不是誰必然正確，而是承擔的條件不同。閱讀時標記作者身分、受影響群體、使用的資料和沒有出現的聲音，避免把單一立場誤當成公共議題全貌。"},{"heading":"文化與環境不能被切成二選一","body":"傳統市場的價值可能同時在飲食、語言、互助與地方記憶；共享單車的便利也可能和停放秩序、無障礙通行、維修資源相衝。好的理解會把價值、成本、受益者與承擔者放在一起，比較方案條件，而不是只找一句支持自己喜好的話。"},{"heading":"來源可信度與觀點公平要一起查","body":"看到『專家說』或社群貼文，先查姓名、機構、原始資料、日期和引用是否可回溯；看到調查結果，也要問誰被調查、誰沒有回答、問題如何設計。補充視角不是為了把所有意見當成同等證據，而是讓讀者知道哪些主張還需要核對。"},{"heading":"把閱讀轉成小而可測的行動","body":"面對食物浪費或圖書館開放等議題，不必立刻喊出最大的政策口號。先寫一個可在生活中試行的改變，設定時間、基準、觀察指標和回饋方式，再依結果調整；行動若傷害了另一群人的安全或可近性，也要把修正責任放回方案中。"}]}
    data["studyHighlights"]=["辨認作者、利害關係人、資料位置與缺席聲音。","同時比較文化價值、環境代價、資源與可近性。","查核專家引述、調查樣本、原始連結與時間。","把閱讀轉為有指標、能回饋且可調整的生活行動。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"同一座公園，誰的『改善』？","body":"提供兩篇自編短文：居民希望保留老樹與安靜角落，規劃者提出照明、無障礙路徑與活動空間。請學習者用不同顏色標出各自的需求、證據、受益者與可能成本，再找出文章沒有談到的使用者，先建立多元閱讀不是選邊站的入口。"},{"id":"explain","phase":"explain","heading":"多元議題四格閱讀圖","body":"第一格定位作者與立場；第二格整理主張、證據與受影響者；第三格比較價值、成本、資源與可近性；第四格列出缺席聲音、來源限制與下一個查證問題。完成後才形成自己的回應，並明確區分文本說法、資料支持與個人判斷。"},{"id":"worked-example","phase":"worked-example","heading":"從共享單車便利讀到公共空間責任","body":"以自編文章示範：先承認共享單車降低短程移動門檻，再讀出亂停可能阻擋輪椅與推車，最後檢查文章是否提出停放、維護與責任分配。回應不只說支持或反對，而是指定條件、受影響者與可追蹤指標，示範如何讓不同價值進入同一討論。"},{"id":"guided-practice","phase":"guided-practice","heading":"拆穿沒有來源的『專家說』","body":"給出含匿名專家引述的自編社群貼文，請學習者列出姓名、機構、原始連結、日期與資料方法五項查核欄。若找不到，將句子改寫成未驗證的說法，不轉傳為事實；再補一個能代表受影響但原文缺席的訪談對象。"},{"id":"transfer","phase":"transfer","heading":"讓地方議題變成可測試的行動","body":"小組從圖書館夜間開放或校園食物浪費擇一，先比較支持與疑慮，再設計兩週小試行：寫清楚基準、行動、指標、風險與回饋。若結果改善一項卻讓另一群人更不安全或不方便，必須調整方案而不是把反對聲音刪掉。"},{"id":"reflect","phase":"reflect","heading":"檢查我是否只讀到自己的立場","body":"回看閱讀札記，圈出只引用同意者、未查來源或把少數經驗擴大成普遍結論的句子。補寫至少一個缺席聲音、一項資料限制和一個可驗證的小行動，並說明哪些部分仍是價值選擇而非文本事實。"}],"summary":["定位不同作者、群體、資料與缺席聲音。","把文化、環境、成本、資源與可近性放入同一問題地圖。","查核來源、樣本與原始資料，避免匿名權威與單一立場。","用指標、回饋與風險把閱讀轉成可調整的生活行動。"],"exitCheck":[{"prompt":"比較多元立場時，為什麼不能只問誰對誰錯？","expectedEvidence":"能指出各立場承擔的條件、受益者與成本，並補查缺席群體與資料限制。"},{"prompt":"看到『專家說』時，至少要查哪些資訊？","expectedEvidence":"能列出姓名、機構、原始資料、日期與方法，並在查不到時降低主張確定性。"},{"prompt":"如何讓生活行動可檢驗而不是口號？","expectedEvidence":"能設定基準、時間、指標、風險與回饋，並說明結果不理想時如何修正。"}]}
    data["interactive"]={"type":"guided-choice","goal":"比較多元立場與來源，補足缺席聲音，並把閱讀轉為可測試、可修正的生活行動。","scenario":"學生閱讀公園改造、共享單車與校園浪費的多篇材料，依序畫出利害關係人地圖、查核來源、比較取捨，再設計小規模行動。","variables":[{"symbol":"v","meaning":"立場與受影響者"},{"symbol":"s","meaning":"來源與證據"},{"symbol":"a","meaning":"行動指標與回饋"}],"steps":[{"id":"step-1","prompt":"兩篇文章分別從居民與規劃者角度談公園改造，最重要的閱讀策略是什麼？","options":["標出各自需求、證據、受益者與成本，再補找缺席的使用者，不急著把一方當成全部答案","只選語氣較有說服力的一篇","把兩篇平均句數相加就能得到公共利益"],"answer":"A","feedback":"A 將立場放回條件與受影響者比較，並注意文章沒有呈現的聲音。"},{"id":"step-2","prompt":"社群貼文只有『專家說』沒有姓名、機構與原始連結，讀者應如何處理？","options":["先查證來源與方法；查不到時標成未驗證主張，不把它當成確定事實轉傳","因為寫了專家就直接接受","只要內容符合自己的立場就不必查"],"answer":"A","feedback":"A 同時尊重可能的資訊價值與來源責任，避免匿名權威取代證據。"},{"id":"step-3","prompt":"要把校園食物浪費的閱讀轉成生活改變，哪項行動最可檢驗？","options":["宣告大家以後都不能浪費，成效不用量測","先記錄一週剩食基準，再試行兩週減量方案，追蹤重量與參與情況，依安全與回饋修正","只要求少數同學改變，結果不好就歸咎個人"],"answer":"B","feedback":"B 有基準、時間、指標與修正回路，能把閱讀理解轉成可觀察的行動。"}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；國語文多元閱讀、生活議題與表達定位；核讀 2026-09-21。",["由多元文本理解生活與社會議題。","以閱讀、表達與行動連結公共經驗。"],["地方文化、環境、政策、社群資訊與生活提案。"],"只選同意自己的文章或把個案當成普遍事實。","重視多元觀點、來源理解與生活應用。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；國語文閱讀、議題探究與文本形式定位；核讀 2026-09-21。",["透過比較、討論與探究理解不同群體的議題。","依資料來源、立場與受影響者修正回應。"],["地方議題、訪談、調查、社群訊息與行動方案。"],"把所有意見當成同等證據，或忽略缺席的群體。","要求回應有來源、有取捨且能接受回饋。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；國文多元閱讀、社會議題與評量定位；核讀 2026-09-21。",["從不同文本、觀點與證據理解社會生活。","以文化、環境、資源與公共責任形成有範圍的判斷。"],["公園、市場、交通、觀光、媒體查核與生活行動。"],"把閱讀立場直接變成政策唯一答案，忽略成本與可近性。","評量觀點比較、證據查核、公共表達與行動反思。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持多元閱讀、生活社會議題、觀點比較與表達行動。","文化、環境、資源與可近性要連同受影響者與資料來源一起閱讀。","閱讀回應需能查核、說明取捨並依回饋修正。"],"versionDifferences":["南一較突顯生活議題與閱讀表達；康軒較突顯比較、討論、探究與來源；翰林較突顯多元觀點、公共責任與行動反思。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["用利害關係人地圖整理立場、成本與缺席聲音。","以匿名專家引述卡練習來源查核。","用兩週小試行把閱讀轉成帶指標與回饋的生活行動。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織多元文本、公共議題、來源查核、價值取捨與生活行動。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 每張立場卡都要附上作者身分、受影響者與資料來源，並把『同理理解』和『證據強度』分開記錄，避免因同情某群體就跳過查證。"
    data["teaching"]["body"][4]["body"] += " 行動設計先確認不會把成本轉嫁給更弱勢的使用者，再設定可量測指標與回饋入口；結果不理想時修正方案，不把責任簡化成個人態度。"
    data["teaching"]["body"][5]["body"] += " 將文章中的肯定語、全稱詞與權威引述圈出，逐一檢查樣本、來源與缺席聲音，讓自己的回應同時保留價值立場與證據謙抑。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"5-Ⅳ-5：在多元閱讀中連結生活議題與社會行動","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored chinese performance 5-iv-5")

if __name__=="__main__": main()
