import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-2-iv-10.json"
REPORT = ROOT / "implementation/reports/english-performance-2-iv-10-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創圖片場景、位置、數量、顏色、人物動作、前後變化、缺少物品與下一步預測，承接公開課程的圖像描述與情境表達方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-2-iv-10"
    data["title"] = "2-Ⅳ-10：用位置、數量與動作完整描述圖片場景"
    data["content"] = {"summary": "圖片描述要把看見的資訊組織成讀者能在腦中定位的句子：先確認場景，再描述人物與物件的位置、數量、顏色、動作、關係與前後變化。只說 There is a cat 不足以回答 under the table；只數黃色雨傘也不能概括雨天街景。本課以原創貓與桌子、雨傘腳踏車、海報製作、書本交接、植物入盆、野餐桌、冷藏室與播種連續畫面，練習 There is／are、介系詞、現在進行式、數量、顏色、比較與 after／next 預測，最後檢查描述是否完整、可核對且沒有把猜測當成畫面事實。", "sections": [{"heading": "先建立場景，再定位物件", "body": "看圖第一遍先回答 Where are we?，第二遍才把人物和物件放進位置網。A cat is under the table 與 a bowl is on the table 的介系詞不同；描述若只列 cat、table，讀者仍不能重建空間關係。"}, {"heading": "數量和特徵要與名詞配對", "body": "Three yellow umbrellas stand beside two blue bicycles 同時提供數字、顏色和位置。回答 How many bicycles? 只取 two；回答 Which object is yellow? 才取顏色。先圈問題焦點，再從圖片資料取必要資訊，避免把所有細節混成一句。"}, {"heading": "動作描述要看誰在做什麼", "body": "A boy is holding a brush，a girl is hanging a finished poster；人物、動作與物件要互相配對。Anna gives a book to Ben，Ben puts it into his backpack 則要區分 giver、receiver 和後續動作，不能因為兩人都在畫面中就互換角色。"}, {"heading": "連續圖片支援變化與合理下一步", "body": "植物從盆旁到盆內且附近有水，重點是位置與狀態改變；女孩播種、覆土、澆水後，最合理的下一步是等待發芽或繼續照顧，不是立刻宣稱已長成大樹。預測要接在最後畫面證據上，保留合理範圍。"}]}
    data["studyHighlights"] = ["先建立場景，再用介系詞定位人物與物件。", "依問題焦點取數量、顏色、位置或缺少物品。", "將人物、動作、物件與角色關係正確配對。", "從連續圖片的最後狀態提出有界線的下一步預測。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "一句 There is enough描述圖片嗎？", "body": "展示完全自編的雨天街景，學生先只說一個名詞，再讓同伴依句子在空白紙上畫圖。比較只說 dog、bus stop 與補上 yellow umbrella、near、Route 6、behind 的差異，讓學生看見圖片描述的目標是讓聽者能定位與核對。"}, {"id": "explain", "phase": "explain", "heading": "圖片六欄觀察卡", "body": "建立 Setting、People、Objects、Positions、Actions、Change／Next 六欄。先寫可見事實，再把介系詞、數量、顏色與現在進行式放到對應欄；連續圖最後才寫 change 或 next，避免把先前畫面或想像混入當下描述。"}, {"id": "worked-example", "phase": "worked-example", "heading": "用位置介系詞讓讀者找得到貓", "body": "以 cat under the table、bowl on the table 示範：先圈問題 Where is the cat?，再只取 under the table；把貓移到 beside 或 behind 後重說句子，讓學生驗證介系詞會改變讀者在空間中的搜尋路徑。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "把動作和人物配對", "body": "給出男孩拿刷子、女孩掛海報、Anna 給書、Ben 放入背包四張原創畫面卡。學生先用箭頭連人物與動詞，再補 object 和 receiver；同伴只看描述指出畫面中的人、物與動作，若角色被換掉就回到箭頭修正。"}, {"id": "transfer", "phase": "transfer", "heading": "從單張圖到三格變化", "body": "輪換植物入盆、女孩播種、冷藏室關門與野餐桌缺水等場景。學生先寫單張圖完整描述，再比較 before／after，最後提出 immediately after 或 next 的合理句子；預測必須標記為可能，不把未出現結果寫成已發生事實。"}, {"id": "reflect", "phase": "reflect", "heading": "我描述的是看見的還是猜到的？", "body": "回看段落，將每句標成 visible fact、relationship、change 或 prediction。檢查數量、顏色、介系詞、動作主體與物件角色是否能回指畫面；對預測加上 may 或 will likely，刪掉畫面沒有支持的心理和結果。"}], "summary": ["以 Setting、People、Objects、Positions、Actions、Change／Next 六欄組織圖片描述。", "用問題焦點選取必要的數量、顏色、位置或缺少物品。", "以箭頭配對人物、動作、物件與接收者。", "區分可見事實、前後變化與有界線的下一步預測。"], "exitCheck": [{"prompt": "完整圖片描述為何不能只列名詞？", "expectedEvidence": "能指出還要加入位置、數量、顏色、動作或人物關係，讓聽者可以定位與核對。"}, {"prompt": "如何避免把人物動作或接收者配錯？", "expectedEvidence": "能以箭頭將人物、動詞、物件和 receiver 對回畫面，再組成句子。"}, {"prompt": "連續圖片的下一步預測要遵守什麼界線？", "expectedEvidence": "能從最後畫面提出合理可能，使用 may 或 likely，並避免宣稱尚未出現的結果已經發生。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "用位置、數量、顏色、動作、人物關係與前後變化，完成可核對的英文圖片描述。", "scenario": "學生擔任無文字圖卡導覽員，要讓同伴只聽描述就能找到物件、理解動作，並對連續畫面提出有界線的下一步。", "variables": [{"symbol": "s", "meaning": "場景、人物與物件"}, {"symbol": "l", "meaning": "位置、數量、顏色、動作與關係"}, {"symbol": "t", "meaning": "前後變化、缺少資訊與下一步預測"}], "steps": [{"id": "step-1", "prompt": "A cat is under the table, while a bowl is on the table. Where is the cat?", "options": ["The cat is under the table.", "The cat is on the bowl.", "The cat is behind the school gate."], "answer": "A", "feedback": "A preserves the cat's subject and the precise position phrase under the table."}, {"id": "step-2", "prompt": "A boy is holding a brush, and a girl is hanging a finished poster. What is the boy doing?", "options": ["He is holding a brush.", "He is hanging the finished poster.", "He is watering seeds under the table."], "answer": "A", "feedback": "A matches the boy with his visible action; the poster action belongs to the girl."}, {"id": "step-3", "prompt": "A girl drops seeds, covers them with soil, and waters the spot. What will most likely happen immediately after the last frame?", "options": ["The seeds will remain in the soil and may begin to grow later.", "The seeds have already become a large tree in the last frame.", "The girl will immediately ride a blue bicycle."], "answer": "A", "feedback": "A makes a cautious prediction from the final action; it does not claim an unseen result has already happened."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語圖片、位置、數量與生活描述定位；核讀 2026-09-21。", ["以圖片與生活情境理解並描述人物、物件與動作。", "用基本句型、介系詞和數量完成英語表達。"], ["圖片場景、顏色、位置、數量、動作與前後變化。"], "只列圖片物件，沒有描述位置、動作或人物關係。", "重視圖片理解、生活描述與簡易表達。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語圖像、動作與情境任務定位；核讀 2026-09-21。", ["透過圖片、角色和活動描述生活場景。", "依數量、位置、順序和物件特徵完成回應。"], ["雨天街景、海報、植物、野餐、冷藏室與連續圖。"], "把畫面沒有的心理或結果當成已知事實，或混淆人物動作。", "評量主要內容、細節、位置、順序與圖像表達。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語圖片描述、比較與情境評量定位；核讀 2026-09-21。", ["從圖片線索、句子結構與前後畫面形成完整理解。", "以介系詞、進行式、數量和預測表達圖像資訊。"], ["setting、people、objects、positions、actions、change、prediction。"], "用單一顏色或名詞作全文描述，或把推測結果說成畫面直接顯示。", "評量圖片主旨、細節、人物關係、變化與簡易摘要。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持圖片理解、生活描述、位置動作與簡易英語表達。", "完整描述需整合場景、人物、物件、位置、數量、顏色、動作、變化與預測界線。", "從觀察卡到同伴找圖可用位置移動、角色箭頭與連續畫面驗證。"], "versionDifferences": ["南一較突顯圖片、生活場景與基本句型；康軒較突顯圖像、角色、動作、順序與任務；翰林較突顯介系詞、進行式、人物關係、變化與預測評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Setting、People、Objects、Positions、Actions、Change／Next 六欄組織描述。", "用雨天街景、植物、海報、野餐、冷藏室與播種連續圖練習事實與預測。", "以同伴只聽描述找物件和回指畫面檢查語句的可核對性。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織圖片場景、人物、物件、位置、數量、顏色、動作、角色關係、變化與合理預測。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 六欄填完後先用描述讓同伴畫出位置，再用原圖核對；若對方畫錯，先查介系詞、數量或動作主體，不用增加無關形容詞。"
    data["teaching"]["body"][4]["body"] += " 連續圖的預測要明確接在最後一格，並用 may、likely 或 immediately after 表示推論程度；看不到的細節不能因故事好聽而變成事實。"
    data["teaching"]["body"][5]["body"] += " 若同伴把 prediction 當成 visible fact，回到最後畫面圈出證據並改寫語氣；若找不到人物或物件，檢查句子中的主詞與介系詞是否互換。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "2-Ⅳ-10：用位置、數量與動作完整描述圖片場景", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 2-iv-10")


if __name__ == "__main__":
    main()
