import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-6.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-6-first-pass-review.json"


def refs():
    return [
        {"url": "https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "title": "高雄市立鹽埕國民中學公開英文段考；僅取句型、時態、功能語意與情境判讀方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": "sentence patterns, tense, functions, and context", "observedPattern": "公開英文評量以公告、生活事件、位置、比較、規則與原因測量句型在語境中的功能；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"},
        {"url": "https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "title": "新北市立北投國民中學公開定期評量試題頁；僅取句型選擇、上下文與語意完整方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": "grammar in context, sentence completion, and meaning", "observedPattern": "公開英文評量將文法形式放進公告、對話、位置、時間與行動情境中判讀；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"},
        {"url": "https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "title": "新北市立新埔國民中學公開段考試題頁；僅取基本句型、連接詞、比較與表達目的能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": "basic patterns, connectors, comparison, and purpose", "observedPattern": "公開英文評量要求學生以句型形式表達時間、位置、比較、規則、目的與原因；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"},
    ]


def make_q(base, prompt, options, answer, explanation, strategy, steps):
    q = json.loads(json.dumps(base))
    q.update({"prompt": prompt, "options": [{"id": k, "text": v} for k, v in options], "answer": {"value": answer, "explanation": explanation + f" 正確答案：{answer}"}, "examPatternRefs": refs(), "solutionStrategy": strategy, "solutionSteps": steps, "reviewStatus": "draft", "updatedAt": "2026-09-21"})
    q["provenance"]["sourceUrl"] = refs()[0]["url"]
    q["provenance"]["sourceLocator"] = "公立學校公開英文評量的基本句型與語境判讀模式；本題只改寫能力、資料型態與推理層次。"
    q["provenance"]["authoringNote"] = "依官方課綱、本單元 KG 與三所公立學校公開英文評量模式獨立改寫；題幹、選項、答案、解析與互動任務均未複製來源。"
    return q


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-3-iv-6"
    data["title"] = "3-Ⅳ-6：用基本重要句型把時間、位置、比較與原因說完整"
    data["content"] = {"summary": "基本句型不是孤立的文法填空；同一個動詞形式會因時間、主詞、句型目的與上下文而改變。本課以校園公告、專題提交、地圖位置、路線比較、實驗室規則、學習目的、天氣原因與正在進行的模型製作，整理現在式、過去式、there is／are、疑問句、比較級、情態動詞、to V、because 與現在進行式，要求學生先找線索再組成語意完整的句子。", "sections": [{"heading": "先找句子的任務", "body": "公告是在說固定行程，事件是在說已完成的動作，地圖是在定位，規則是在表達必要性，句型不能只靠背誦。先問句子要回答時間、位置、比較、規則、目的還是原因，再決定骨架。"}, {"heading": "時間線決定動詞形式", "body": "every Thursday 指重複習慣，yesterday 指已發生，Look! 與 now 指正在進行。主詞與時間線同時核對，才能在 meets、presented、is making 等形式中選出與情境一致的答案。"}, {"heading": "句型骨架要保留關係", "body": "there is／are 說明某處有什麼，Where is... 問位置，比較級說明兩條路的關係，must 表示規則；換掉字詞後仍要保留主詞、動詞、受詞、介系詞或連接詞的功能。"}, {"heading": "連接詞讓理由和目的不走失", "body": "to find a quiet place 表達目的，because heavy rain covered the field 表達原因。先分辨哪一件事是行動、哪一件事是目的或原因，再檢查句子是否完整，不把 because 當成任意裝飾。"}]}
    data["studyHighlights"] = ["先圈時間、主詞、位置、比較對象、規則、目的與原因線索。", "用句子任務選骨架，再核對動詞形式、主詞一致與介系詞。", "區分 there is／are、疑問句、比較、情態、to V、because 與進行式的功能。", "朗讀完整句並回翻語意，確認形式改變沒有破壞原本關係。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "同一個動詞為什麼不能到處套？", "body": "給學生三張原創校園卡：The club meets every Thursday、Mia presented yesterday、Look! They are building now。學生先用顏色標時間線，再比較動詞形式，從差異中發現句型是由情境任務驅動。"}, {"id": "explain", "phase": "explain", "heading": "句型任務六格卡", "body": "建立 Task、Time、Subject、Core verb、Relation、Connector 六格。先判斷要描述習慣、過去事件、位置、比較、規則、目的或原因，再填入句型骨架；最後以中文回翻和英文朗讀檢查語意。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從地圖問題組出完整句", "body": "以 Where is the meeting? 為例，先鎖定疑問詞問 location，再保留 be 動詞與地點介系詞，不能改成陳述句或只寫 building。接著用 there is／are 和比較句對照，讓形式與功能一一對應。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "把同一校園資料換成不同任務", "body": "學生輪換公告、專題、地圖、路線、實驗室、雨天、模型七組原創資料；每次先標線索，再選句型，最後由同伴指出主詞、時間或連接詞證據。若答案通順但任務錯誤，必須回到句型功能重修。"}, {"id": "transfer", "phase": "transfer", "heading": "從選項移到自己的句子", "body": "把圖書館、社團、校外教學與天氣資料改寫成一句公告、一個問題和一個理由句。學生更換主詞或時間後重新變化動詞，並說明哪些部分必須跟著變、哪些關係不能變。"}, {"id": "reflect", "phase": "reflect", "heading": "形式正確還要語意正確", "body": "回看作答，分別標記時間錯、主詞錯、句型任務錯、連接詞錯與資訊漏失。朗讀後若聽起來像在問位置卻用了比較句，或原因被寫成目的，就依 Task—Evidence—Revision 三欄修訂。"}], "summary": ["以 Task、Time、Subject、Core verb、Relation、Connector 六格選句型。", "把時間線、主詞與句型功能一起核對，不以熟悉字形猜答案。", "用地圖、公告、規則、比較與理由情境檢查句子關係。", "改寫新主詞或新時間後，重新檢查動詞與句型骨架。"], "exitCheck": [{"prompt": "為什麼 every Thursday、yesterday、now 會導向不同動詞形式？", "expectedEvidence": "能說明重複習慣、已完成事件與進行中的時間線，並各舉一個正確句型。"}, {"prompt": "如何分辨 to V 是目的而不是另一個主要事件？", "expectedEvidence": "能指出主句行動與 to V 的目的關係，並用新情境改寫完整句。"}, {"prompt": "句型選對但句子仍不完整時，要檢查哪些欄位？", "expectedEvidence": "能回查主詞、動詞、受詞／位置、介系詞與連接詞，指出漏失如何改變語意。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "依時間、主詞與句型任務，組出能準確表達位置、比較、規則、目的與原因的英文句子。", "scenario": "學生擔任校園英文公告編輯，要把社團、地圖、實驗室、天氣與模型製作資料改寫成可執行的句子。", "variables": [{"symbol": "t", "meaning": "時間線與主詞"}, {"symbol": "f", "meaning": "句型功能：習慣、過去、位置、比較、規則、目的或原因"}, {"symbol": "r", "meaning": "句子中的關係、介系詞與連接詞"}], "steps": [{"id": "step-1", "prompt": "The science club meets every Thursday. Which verb form completes the notice?", "options": ["meets", "met yesterday", "is meet"], "answer": "A", "feedback": "every Thursday 表示固定習慣，第三人稱單數主詞 science club 使用 meets。"}, {"id": "step-2", "prompt": "Lena went to the library ___ a quiet place to study.", "options": ["to find", "because finding", "finds yesterday"], "answer": "A", "feedback": "to find 說明 went to the library 的目的，保留主要行動與目的的關係。"}, {"id": "step-3", "prompt": "Look! The students ___ a model of the bridge now.", "options": ["are making", "made every day", "make yesterday"], "answer": "A", "feedback": "Look 與 now 指正在進行，複數 students 使用 are making。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；基本句型、生活文本與時間表達定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由生活文本理解基本句型與主要訊息。", "以時間、人物、位置與簡短理由完成表達。"], "representations": ["公告、地圖、比較、規則與事件句。"], "examplesOrEvidence": ["本課以校園公告、專題、地圖與天氣原創資料承接公開結構。"], "misconceptions": ["只背動詞形式，不看時間與主詞。"], "assessmentEmphasis": ["重視句型主要內容、細節與語意完整。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖像、核心句型與任務表達定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["透過圖片、情境與任務使用基本句型。", "依順序、比較、規則與原因完成句子。"], "representations": ["圖像提示、位置、路線、比較、情境任務。"], "examplesOrEvidence": ["本課以地圖、路線、實驗室與活動任務重新設計例證。"], "misconceptions": ["把 to V、because、must 和比較句混成同一種功能。"], "assessmentEmphasis": ["評量句型在情境中的功能與語意。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；生活溝通文本與句型理解定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["從上下文、時態與句型關係形成理解。", "以位置、比較、規則、目的與原因表達資訊。"], "representations": ["context、tense、there is／are、question、comparison、modal、purpose、cause。"], "examplesOrEvidence": ["本課將公告、專題、服務與天氣資料組成全新句型鏈。"], "misconceptions": ["形式看似正確卻未完成題目要求的句型任務。"], "assessmentEmphasis": ["評量時間、語意連貫、功能與基本句型運用。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持基本句型、生活文本與情境表達。", "可靠句型理解需整合時間、主詞、功能、關係與連接詞。", "從選形式到產出可用句子可用六格卡、改寫、朗讀與同伴回指驗證。"], "versionDifferences": ["南一較突顯生活文本與時間表達；康軒較突顯圖像、核心句型與任務；翰林較突顯上下文、句型關係與功能性表達。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Task、Time、Subject、Core verb、Relation、Connector 六格選句型。", "用公告、專題、地圖、路線、規則、目的、原因與現在進行式原創資料串聯。", "以改變主詞或時間後的再驗證檢查學生是否真正理解句型功能。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織基本重要句型的時間、主詞、位置、比較、規則、目的與原因。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    specs = [
        ("The notice says, 'The science club ___ every Thursday.' Which form completes it?", [("A", "meets"), ("B", "met"), ("C", "is meet"), ("D", "meeting")], "A", "every Thursday marks a repeated schedule, so the singular club takes meets.", "先抓時間線與主詞，再用現在簡單式表達固定行程。", ["圈 every Thursday，判斷是習慣而非一次過去事件。", "確認主詞 science club 是單數。", "選現在式第三人稱單數 meets。", "排除過去式、錯誤 be 結構與缺少動詞的選項。", "朗讀公告並回翻成固定每週活動，確認時間與形式一致。"]),
        ("Yesterday, Mia ___ her project to the teacher before lunch.", [("A", "presented"), ("B", "presents"), ("C", "is presenting"), ("D", "present")], "A", "Yesterday places the completed action in the past, so presented fits.", "以 yesterday 鎖定過去式，再核對動作已完成。", ["圈 yesterday 與 before lunch，找出過去時間線。", "確認 Mia 是單數主詞，事件已完成。", "選 presented 作為過去式動詞。", "排除現在式、進行式與原形。", "將句子回述為午餐前已完成展示，檢查語意完整。"]),
        ("Which sentence correctly tells a visitor that one map is on the wall?", [("A", "There is a map on the wall."), ("B", "There are a map on the wall."), ("C", "A map are on the wall."), ("D", "There map is wall.")], "A", "One map is singular, so There is correctly introduces it and its location.", "以數量決定 there is／are，再檢查地點介系詞。", ["找出名詞 map 的數量是 one。", "選單數存在句 There is。", "保留 a map 與 on the wall 的位置關係。", "排除複數 be、主詞動詞不一致與缺少介系詞。", "用訪客能理解的完整句回指地圖位置。"]),
        ("Which question correctly asks about the location of the meeting?", [("A", "Where is the meeting?"), ("B", "Where the meeting is?"), ("C", "What is the meeting where?"), ("D", "Is where meeting?")], "A", "Where is the meeting? uses the correct question order for location.", "先辨識問題要問地點，再使用疑問詞加 be 動詞的語序。", ["確認任務是 location，不是時間或原因。", "以 Where 開頭，接 be 動詞 is。", "把主詞 the meeting 放在 be 動詞後。", "排除陳述語序與疑問詞位置錯誤。", "朗讀問句並想像回答在 the library，確認問答相配。"]),
        ("The blue route is shorter than the red route. Which sentence has the same meaning?", [("A", "The red route is longer than the blue route."), ("B", "The blue route is longer than the red route."), ("C", "Both routes are the same length."), ("D", "The routes are beside the color.")], "A", "Reversing the comparison keeps the same length relationship: red is longer than blue.", "固定兩個比較對象與關係，再反轉主詞和比較形容詞。", ["找出原句關係：blue shorter than red。", "若改以 red 作主詞，關係要變成 longer than blue。", "A 保留同一長短事實。", "排除反向錯誤、相等與無意義句子。", "畫兩條路線做口頭回述，確認 A 不改變比較結果。"]),
        ("The laboratory sign says students ___ wear safety glasses.", [("A", "must"), ("B", "might to"), ("C", "are must"), ("D", "must wearing")], "A", "A laboratory safety sign states a requirement, so must is the suitable modal.", "把標示的安全規則轉成必要性情態動詞。", ["辨識 sign 的功能是 rule，不是可能性或習慣。", "選能表達必要性的 must。", "確認 must 後接原形 wear。", "排除錯誤 to、be 與 -ing 結構。", "回讀成學生必須戴護目鏡，確認規則強度與行動一致。"]),
        ("Lena went to the library ___ a quiet place to study.", [("A", "to find"), ("B", "because finding"), ("C", "finds"), ("D", "to finding")], "A", "to find explains the purpose of going to the library.", "分辨主要行動與目的，使用 to + 原形動詞。", ["找出主要動作 went to the library。", "問『為了什麼？』得到 find a quiet place。", "用 to find 連接目的。", "排除 because、第三人稱動詞與錯誤 -ing。", "回翻為去圖書館是為了找安靜地方，確認目的關係。"]),
        ("The game moved indoors ___ heavy rain covered the field.", [("A", "because"), ("B", "to"), ("C", "and to"), ("D", "where to")], "A", "because introduces the reason for moving the game indoors.", "先找事件與原因，再用 because 連接完整子句。", ["辨識主要事件是 game moved indoors。", "找出原因 heavy rain covered the field。", "because 能把原因子句接在主要事件後。", "排除只接原形或位置的連接方式。", "朗讀兩部分，確認雨下大是原因而不是目的或地點。"]),
        ("Look! The students ___ a model of the bridge now.", [("A", "are making"), ("B", "made"), ("C", "make yesterday"), ("D", "is make")], "A", "Look and now show an action in progress, and plural students takes are making.", "同時核對現在進行式的時間線與複數主詞。", ["圈 Look 與 now，判斷動作正在發生。", "確認 students 是複數主詞。", "選 are + making。", "排除過去式、混合時間副詞與錯誤 be 動詞。", "想像正在看到模型製作，確認句子描述的是當下畫面。"]),
        ("Which sentence correctly tells a friend that you finished the task, explains why, and gives the next action?", [("A", "I finished the task because I checked the data, so I'll send it now."), ("B", "I finish yesterday because data is send."), ("C", "The task finished me, and now why."), ("D", "I am finished the task because send.")], "A", "A has a completed action, a because reason, and a clear next action.", "拆成已完成、原因與下一步三段，再檢查各自的句型。", ["圈 finished 找到已完成的主要事件。", "核對 because 後有完整理由 I checked the data。", "檢查 so 後的 next action I'll send it now。", "排除時態、主詞、被動與缺少動詞的錯誤。", "朗讀整句並確認三段資訊都服務同一個任務，沒有語意跳接。"]),
    ]
    for i, spec in enumerate(specs, 1):
        p = ROOT / f"questions/english/question-english-performance-3-iv-6-{i}.json"
        q = make_q(json.loads(p.read_text(encoding="utf-8")), *spec)
        p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-6")


if __name__ == "__main__":
    main()
