"""INa-Ⅳ-5：能源開發、利用與永續性第一輪原創題庫。"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-content-ina-iv-5.json"; REPORT=ROOT/"implementation/reports/science-content-ina-iv-5-first-pass-review.json"; QDIR=ROOT/"questions/science"; TODAY="2026-09-23"
SOURCES=[
 {"url":"https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%87%AA%E7%84%B6.pdf","title":"高雄市立鹽埕國民中學 114 學年度第 2 學期第 1 次段考自然科公開試題","year":"114","locator":"能源開發、資源利用、環境影響與資料判讀","pattern":"取由能源供需、資源條件與環境資料評估開發方案的能力方向。"},
 {"url":"https://www.grow22.com/download/114/114_cp/05_114P_Nature.pdf","title":"114 年國中教育會考自然科公開試題","year":"114","locator":"能源、環境、效率與永續生活決策","pattern":"取從圖表、系統資料與生活情境判斷永續方案及其限制的能力方向。"},
 {"url":"https://www.hkjh.hc.edu.tw/uploads/1661481260739sfuB4gG2.pdf","title":"新竹市立新科國中公開康軒版自然課程計畫","year":"公開課程計畫","locator":"能源開發、利用、環境承載與永續性探究","pattern":"取比較開發效益、資源再生、環境承載、風險與世代公平的教學與評量方向。"},
]
REFS=[{**s,"subject":"science","observedPattern":s["pattern"],"reuseDecision":"pattern-only","status":"recorded","locatorLevel":"paper"} for s in SOURCES]
def q(n,prompt,opts,ans,exp,strat,steps,d="medium"):
 return {"id":f"question-science-content-ina-iv-5-{n}","subject":"science","type":"single-choice","prompt":prompt,"options":[{"id":k,"text":v} for k,v in zip("ABCD",opts)],"knowledgeIds":["kg-science-content-ina-iv-5"],"difficulty":d,"answer":{"value":ans,"explanation":exp},"provenance":{"origin":"original","license":"All rights reserved","sourceUrl":SOURCES[0]["url"],"sourceLocator":"三筆公立學校／公開自然科試題與課程資料的能源開發、供需管理、環境承載及永續決策能力方向；本題只作 pattern-only 改寫來源。","authoringNote":"依公開資料能力方向獨立改寫；題幹、選項、答案、解析與五步解法均依 INa-Ⅳ-5 單元重新撰寫，未複製原題、圖表或答案；待第二輪 AI／Terra 內容複核。"},"reviewStatus":"draft","updatedAt":TODAY,"lessonId":"lesson-science-content-ina-iv-5","examPatternRefs":REFS,"solutionStrategy":strat,"solutionSteps":steps}
Q=[
q(1,"夏季傍晚用電量快速上升，若要減少新增發電設施的壓力，哪項屬於需求管理？",["以尖峰時段電價、儲能或移轉用電鼓勵降低尖峰需求","只在尖峰時段增加路燈亮度","把所有用電資料刪除","宣稱尖峰需求不會影響電網"],"A","需求管理是改變用電時間、降低尖峰或以儲能移轉負載，不只是無限增加供給。","先辨認問題是總量不足還是時間分布造成尖峰。",["畫出一天的用電曲線。","找出尖峰與離峰時段。","檢查移轉用電、儲能或價格措施能否降低尖峰。","B、C、D 沒有處理需求分布或否認系統限制。","答案為 A。"],"medium"),
q(2,"某地計畫開發水力發電，哪項資料最需要和預估發電量一起評估？",["河川流量季節變化、下游生態、居民搬遷與泥砂影響","只看水壩外觀","只比較施工海報的顏色","只記錄某日中午的水面反光"],"A","水力開發的效益受流量變化影響，也可能改變河川連續性、生態、泥砂與居民生活，不能只看發電量。","把能源效益與開發造成的外部影響放在同一系統。",["蒐集全年流量與預估發電資料。","列出河川、生態、泥砂與社會影響。","以相同時間尺度比較收益與代價。","B、C、D 無法代表開發方案的實際影響。","因此 A 最完整。"],"hard"),
q(3,"若要判斷節能改造是否真的降低一棟校舍的能源使用，哪種比較最可靠？",["以改造前後相近季節的單位面積用電量比較，並記錄人數、天氣與使用時間","只比較改造後某一天的電費","改造後看到新設備就宣稱有效","只比較校舍牆面顏色"],"A","單位面積、相近季節與使用條件的前後比較，可降低規模、天氣與人數差異造成的混淆。","建立可比基準並記錄可能影響能源需求的背景變因。",["確認改造前後的觀測期間。","換算單位面積用電量。","記錄人數、空調時間與氣溫等條件。","B、C、D 缺乏公平基準或沒有能源證據。","答案為 A。"],"medium"),
q(4,"開採電池所需金屬可能增加再生能源儲能能力，但也可能造成環境壓力；最完整的評估是？",["納入礦區水土、能源使用、運輸、材料回收與供應鏈勞動條件","只看電池可儲存多少電","只要材料稀有就禁止所有研究","只引用廠商的回收百分比而不查條件"],"A","資源開採的永續性涉及開採地環境、製造與運輸、回收效率以及社會條件，單一容量或宣稱不足。","沿生命週期與供應鏈追蹤資源的收益和代價。",["列出採礦、製造、運輸、使用及回收階段。","蒐集各階段能源、污染和社會條件。","比較儲能效益與資源代價。","B、C、D 都縮小系統邊界或過度推論。","所以 A 最完整。"],"hard"),
q(5,"判斷一項能源方案是否永續時，哪項指標最不能單獨取代其他指標？",["某一年的發電量，因為還需要資源補充、排放、生態與世代公平資料","所有指標都不必量測","設備的廣告評分","一位使用者的印象"],"A","單一年發電量只代表短期產出，不能說明資源是否可持續、環境代價或不同世代的影響。","區分短期產出指標與長期系統永續性。",["確認發電量測量的時間範圍。","列出資源、排放、生態與公平性指標。","檢查方案在長期是否仍能維持服務。","B、C、D 不是足以判斷永續性的證據。","答案為 A。"],"medium"),
q(6,"偏遠地區常因燃料運輸中斷而停電；哪項能源規劃較能提升韌性？",["分散式再生能源、儲能與備援系統搭配，並依地方資源設計","只建一座更大的單一發電廠且不設備援","完全不記錄停電原因","把所有設備集中在最遠處"],"A","分散來源與儲能可降低單一運輸線或設備故障的風險，但必須依地方資源和維修能力規劃。","從能源供應鏈的脆弱點推論備援與分散化效果。",["找出燃料運輸與單一設備的故障風險。","盤點地方日照、風、水與維修條件。","比較分散能源、儲能和備援的可靠度。","B、C、D 增加單點故障或缺少資料。","因此 A 最合理。"],"medium"),
q(7,"某方案可降低全國平均碳排，但需要在少數鄉鎮設大型設施；永續評估還應特別詢問什麼？",["設施風險、土地使用、居民負擔與收益是否公平分配","平均碳排下降後就不必詢問地方居民","只要全國多數人同意即可忽略少數人的安全","只看設施建造速度"],"A","永續不只看總量效益，也要檢查風險、土地與利益是否集中由特定社群承擔，這涉及程序與分配公平。","把總體效益和地方承擔的風險分開分析。",["確認全國平均效益的計算範圍。","標出設施所在地的風險和土地變化。","比較不同群體承擔與獲益的比例。","B、C、D 都把總體平均或多數決當成完整正當性。","答案為 A。"],"hard"),
q(8,"若一項節能政策讓家庭用電下降，但低收入家庭因設備成本無法參與，哪項補充措施較符合永續與公平？",["提供補助、租賃或公共服務，讓不同家庭都能取得節能設備","只提高所有家庭的電價","只獎勵已經買得起設備的人","宣稱參與率不影響政策結果"],"A","若成本阻礙特定群體參與，補助、租賃或公共服務可降低進入門檻，使節能效益和成本分配更公平。","檢查政策成效是否被收入差異分配，而不是只看平均節電量。",["比較不同家庭的設備成本與用電負擔。","找出無法參與的原因。","設計補助、租賃或公共服務並追蹤成效。","B、C、D 會擴大或掩蓋參與差距。","所以 A 較符合永續決策。"],"medium"),
q(9,"若某地風力發電量逐年增加，但同時鳥類碰撞事件也增加，下一步最適合怎麼做？",["用相同季節與對照地點長期監測，評估位置、風速、遷徙與防護措施的關係","只因發電量增加就否認鳥類資料","只觀察一次並立刻拆除全部設備","只選沒有事件的日期報告"],"A","長期、對照和多變量監測能辨認事件是否集中於特定位置、季節或風況，並比較調整措施是否有效。","把能源產出與生態影響放在同一時間序列及對照設計。",["建立設備周邊與相近無設備地點的基線。","按季節記錄鳥類、風速、遷徙和碰撞。","比較防護措施前後的事件率與發電變化。","B、C、D 都否認資料、缺少基線或選擇性報告。","答案為 A。"],"hard"),
q(10,"要向居民報告能源計畫是否朝永續方向前進，哪組指標最完整？",["服務可靠度、單位能源排放、資源使用、生態影響、成本分配與世代負擔的長期趨勢","只報告建成多少座設備","只報告第一年產電量","只引用支持計畫的意見"],"A","永續是長期、多面向的系統表現，需同時追蹤能源服務、環境、資源、經濟與公平，而非單一建設量。","用多指標與時間序列檢查目標是否真的持續。",["把永續主張拆成能源、環境、經濟和公平面向。","為每面向指定可重複量測的指標。","追蹤多年趨勢並檢查不同群體的影響。","B、C、D 只提供單一或選擇性證據。","因此 A 最完整。"],"hard"),
]
def main():
 lesson=json.loads(LESSON.read_text(encoding="utf-8")); lesson["updatedAt"]=TODAY; lesson["reviewStatus"]="draft"
 lesson["fusionRecord"]={"commonCore":["三版本公開線索共同支持以供需、資源、效率、環境承載、韌性與公平性評估能源開發與利用。","永續不能由單一年度發電量或平均數判定，必須用長期、多指標、生命週期和不同群體影響的證據檢驗。"],"versionDifferences":["公立段考與會考公開題型提供能源開發、環境資料與生活決策方向；康軒公開課程線索偏向資源再生、環境承載、風險與世代公平。公開資料不足以宣稱取得完整教材內容。"],"originalAdditions":["以尖峰需求、水力河川、電池金屬開採、校舍節能、偏遠電網、風場鳥類、能源公平與永續指標建立本單元專屬證據鏈。","把『再生能源建越多就一定永續』、『全國平均效益代表每個地區都適用』與『總發電量可取代所有指標』列為迷思診斷。"],"llmSynthesisNote":"依官方課綱、本單元 KG、南一／康軒／翰林公開版本線索與三筆公立學校／公開自然科試題及課程資料的能力方向，重新撰寫能源開發、需求管理、電網韌性、資源開採、生命週期、環境承載、公平與永續指標。原有 10 題為泛用研究句型套題，已逐題改寫為能源永續專屬題，均具唯一答案、解析與五步解法，未複製教材或試題文字、圖表與答案；Terra 第二輪與正式發布審查尚未完成，維持 draft。"}
 for e in lesson.get("versionResearch",[])+lesson.get("publisherResearch",[]): e["reviewedAt"]=TODAY
 for x in Q: (QDIR/f"question-science-content-ina-iv-5-{x['id'].rsplit('-',1)[-1]}.json").write_text(json.dumps(x,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"INa-Ⅳ-5：能源開發、利用與永續性","lessonId":lesson["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checkedQuestions":10,"checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"threePublicSchoolExamPatternSources":True,"answersAndDetailedSteps":True,"interactivePredictionManipulationExplanation":True,"terraSecondPass":"pending"},"reviewedAt":TODAY,"note":"原有 10 題為泛用研究句型套題，已逐題改寫為能源開發、利用與永續性專屬問題；每題有唯一答案、解析與五步解法，三筆公開試題／課程資料僅作 pattern-only 來源，正式發布前仍須第二輪 AI／Terra 內容複核。"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 LESSON.write_text(json.dumps(lesson,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); print("authored science content ina iv 5")
if __name__=="__main__": main()
