import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-performance-tc-iv-1.json"; REPORT=ROOT/"implementation/reports/science-performance-tc-iv-1-first-pass-review.json"
URLS={"nani":"https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf","kanghsuan":"https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110","hanlin":"https://drive.google.com/uc?id=1gMUVcDjfXmqIapg-fNnfPuLFaK98dxGX&export=download"}
def rec(p,c,r,m,a): return {"publisher":p,"edition":f"{p} 公立校方自然課程計畫章節級證據","sourceType":"public-web","sourceLocator":f"{URLS[p]}；數據懷疑、資訊解釋與評量欄位；核讀 2026-09-21。","reviewedAt":"2026-09-21","findings":{"concepts":[c,"公開課程結構支持從來源、定義、測量、樣本、異常與替代解釋評估科學資訊。"],"representations":[r],"examplesOrEvidence":["本課的雨量表、手機感測器與食品標示皆為原創情境，只承接公開課程所示的能力方向。"],"misconceptions":[m],"assessmentEmphasis":[a]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。"}
def main():
 d=json.loads(LESSON.read_text(encoding="utf-8")); assert d["id"]=="lesson-science-performance-tc-iv-1" and d["reviewStatus"]=="draft"
 d["title"]="tc-Ⅳ-1：對科學數據與資訊提出合理懷疑與解釋——先問資料怎麼來"
 d["content"]={"summary":"懷疑科學數據不是把所有資訊都說成假的，而是問資料如何產生、代表什麼、缺少什麼。雨量表突然出現極端值，手機感測器顯示室內溫度異常，食品標示寫著『天然所以安全』，都需要分辨觀察、測量誤差、定義、樣本、推論和價值語句。本課用三個原創情境練習提出合理疑問、找替代解釋、查證來源，並在證據不足時保留多個可能性。","sections":[{"heading":"先描述異常，不急著解釋","body":"看到一個突出的數字，先確認它和哪些資料比較、單位與時間是否一致，再寫出可觀察的差異。『一定有人造假』是解釋，不是觀察；異常可能來自真實變化、器材、輸入或整理。"},{"heading":"資料要帶著產生條件","body":"測量地點、器材、校正、樣本、缺值處理、定義和時間都會改變解讀。沒有背景資訊的圖表不能自動支撐強結論，應先列出要補查的欄位。"},{"heading":"替代解釋要能比較","body":"合理懷疑不是無限猜測，而是提出幾個符合現有資料的解釋，為每個解釋找能區分的觀察或資料。若兩種解釋預測相同，就要承認目前資料不足。"},{"heading":"解釋強度跟證據走","body":"把結論分成資料直接顯示、合理推論、尚待查證和缺乏支持。查證後仍有不確定性時，寫出條件式說法和下一步，不用語氣或權威掩蓋缺口。"}]}
 d["studyHighlights"]=["先描述數據差異，再區分觀察、測量與解釋。","查來源、單位、時間、器材、校正、樣本與缺值處理。","提出可比較的替代解釋與能區分它們的下一步資料。","依證據強度表達合理懷疑、限制與條件式結論。"]
 d["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"雨量表的 0 和 300 哪個更值得查？","body":"校園雨量表連續幾天記錄 0，某天突然出現 300 毫米。有人說一定是暴雨，有人說一定是故障。先不選答案，列出日期、位置、單位、附近氣象站、器材狀態和降雨痕跡，再判斷哪些資料能區分兩種解釋。"},{"id":"explain","phase":"explain","heading":"合理懷疑五步法","body":"第一步重述資料，第二步查產生條件，第三步列至少兩個解釋，第四步找可區分的證據，第五步用目前強度寫結論。每一步都要避免把缺資料直接填成自己偏好的故事。"},{"id":"worked-example","phase":"worked-example","heading":"手機感測器的室內高溫","body":"兩支手機同時顯示不同溫度，先檢查放置位置、外殼、陽光、感測器類型、校正和讀值時間，再用標準溫度計於多點重測。若重測仍不同，才能進一步討論器材差異；一次畫面不能證明房間真的有兩個溫度。"},{"id":"guided-practice","phase":"guided-practice","heading":"天然所以安全嗎？","body":"食品標示把『天然』和『安全』連在一起。學習者先拆開定義，查成分、劑量、適用者、研究來源與風險，再寫出資料能支持的部分和不能支持的部分，避免把價值語句當成毒理證據。"},{"id":"transfer","phase":"transfer","heading":"資料偵探報告","body":"小組挑一個異常圖表，完成觀察、來源條件、兩個替代解釋、區分證據、目前結論和未知欄位。交換後同學只能提出能改變判斷的查證問題，禁止用『我覺得』取代資料。"},{"id":"reflect","phase":"reflect","heading":"修正兩個懷疑迷思","body":"請修正『懷疑就是不相信任何資料』與『找到一個可能解釋就等於證明』。合理懷疑要依來源和方法提出可查證問題；多個解釋並存時，必須用新資料比較，並承認尚未決定的部分。"}],"summary":["先描述異常並查資料產生條件，不急著貼標籤。","區分測量、整理、推論與價值語句。","提出替代解釋並設計能區分它們的查證。","依證據強度寫條件式結論和未知。"],"exitCheck":[{"prompt":"極端雨量值出現時為何不能立刻說故障？","expectedEvidence":"要查單位、時間、位置、器材、校正與附近資料，也可能是真實極端事件。"},{"prompt":"兩支手機溫度不同先查什麼？","expectedEvidence":"查位置、陽光、外殼、感測器、校正與時間，再用標準工具重測。"},{"prompt":"合理懷疑和任意不相信差在哪？","expectedEvidence":"合理懷疑提出有根據、可查證、能區分解釋的問題，而不是拒絕所有資料。"}]}
 d["interactive"]={"type":"guided-choice","goal":"從異常數據、來源條件與替代解釋提出可查證的合理懷疑。","scenario":"調查雨量表、手機溫度與食品標示資訊，逐步區分觀察、解釋和證據缺口。","variables":[{"symbol":"o","meaning":"觀察與異常"},{"symbol":"h","meaning":"替代解釋"},{"symbol":"v","meaning":"查證證據"}],"steps":[{"id":"step-1","prompt":"雨量突然極端時先做什麼？","options":["確認單位、時間、位置、器材與附近資料，再列可能解釋","直接宣布一定故障","直接宣布一定是真暴雨"],"answer":"A","feedback":"A 先保留多個解釋並查資料條件。"},{"id":"step-2","prompt":"兩支手機溫度不同如何查證？","options":["比較位置與感測器條件，再用標準工具多點重測","只相信較高的數字","把兩數平均後當真值"],"answer":"A","feedback":"A 能區分環境差異、器材差異與測量問題。"},{"id":"step-3","prompt":"『天然所以安全』應如何處理？","options":["拆開天然與安全的定義，查成分、劑量、適用者與研究證據","把天然直接當安全證明","因為是廣告就完全不必查"],"answer":"A","feedback":"A 把語意主張轉成可查證的風險與證據問題。"}]}
 d["teaching"]["body"][1]["body"]="第一步重述資料，第二步查產生條件，第三步列至少兩個解釋，第四步找可區分的證據，第五步用目前強度寫結論。每一步都要避免把缺資料直接填成自己偏好的故事，並留下下一個可重做的查證紀錄。"
 d["teaching"]["body"][4]["body"]="小組挑一個異常圖表，完成觀察、來源條件、兩個替代解釋、區分證據、目前結論和未知欄位。交換後同學只能提出能改變判斷的查證問題，禁止用『我覺得』取代資料，並說明若結果不同將如何修正結論。"
 d["authoringStandard"]="version-fused-v1"
 d["versionResearch"]=[rec("nani","以資料、觀察與探究方法對科學資訊提出合理疑問。","異常、來源、測量、單位、樣本與替代解釋。","把異常直接當造假或把一個故事當證明。","重視資料條件、查證與結論界線。"),rec("kanghsuan","透過討論、實作與資料比較檢查資訊可信度和解釋。","重測、校正、多個假設、證據缺口與同儕檢核。","只相信直覺或權威，忽略器材和方法。","評量合理懷疑、替代解釋與查證設計。"),rec("hanlin","連結生活數據、健康資訊與媒體語句，區分資料與價值主張。","雨量、感測器、食品、定義、風險與責任。","把天然、熱門或單一反例當成科學證據。","要求來源透明、風險判讀與條件式結論。")]
 d["fusionRecord"]={"commonCore":["三版本公開結構共同支持對科學數據與資訊提出合理懷疑與解釋。","來源、定義、測量、樣本、異常、替代解釋與查證是共同要求。","懷疑應轉成可比較證據，不是任意不相信或急著下結論。"],"versionDifferences":["南一證據較突顯資料、觀察與基本疑問；康軒較突顯實作、重測、校正與多假設；翰林較突顯生活數據、健康資訊、定義與責任。這是公開課程計畫層級差異，不宣稱完整教材差異。"],"originalAdditions":["以校園雨量表異常檢查單位、位置、器材與替代解釋。","以手機溫度差異設計標準工具重測和感測器查核。","以『天然所以安全』拆解定義、劑量、適用者與風險證據。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織異常、來源、測量、定義、樣本、替代解釋、重測、風險與條件式結論。正文、原創情境、互動步驟、錯誤回饋與檢核均為本專案重寫，未複製任何教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
 d["updatedAt"]="2026-09-21"; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"tc-Ⅳ-1：對科學數據與資訊提出合理懷疑與解釋","lessonId":d["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 print("tc-iv-1 lesson authored")
if __name__=="__main__": main()
