#!/usr/bin/env python3
"""Author the original English 8-IV-3 lesson and exam-pattern rewrites."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON_ID = "lesson-english-performance-8-iv-3"
LESSON_PATH = ROOT / "lessons/english/lesson-english-performance-8-iv-3.json"
CURRICULUM = "https://www.naer.edu.tw/upload/1/16/doc/812/(%E7%99%BC%E5%B8%83%E7%89%88)%E5%9C%8B%E6%B0%91%E4%B8%AD%E5%B0%8F%E5%AD%B8%E6%9A%A8%E6%99%AE%E9%80%9A%E5%9E%8B%E9%AB%98%E7%B4%9A%E4%B8%AD%E7%AD%89%E5%AD%B8%E6%A0%A1-%E8%AA%9E%E6%96%87%E9%A0%98%E5%9F%9F-%E8%8B%B1%E6%96%87%E8%AA%B2%E7%A8%8B%E7%B6%B1%E8%A6%81.pdf"
TAIWAN_FESTIVALS = "https://eng.taiwan.net.tw/m1.aspx?sNo=0002020"
INDIA_HOLI = "https://www.incredibleindia.gov.in/en/festivals-and-events/holi"
HANLIN_RESOURCE = "https://material.hle.com.tw/wp-content/uploads/2021/04/%E5%9C%8B%E4%B8%AD%E8%8B%B1%E8%AA%9E-%E5%BD%88%E6%80%A7%E7%8E%A9%E5%BE%88%E5%A4%A7%E4%BD%B5%E6%AA%94.pdf"
NAER_RESEARCH = "https://etalk.naer.edu.tw/trends/single/sn/199"
EXAMS = [
    {
        "url": "https://www.nhjh.tp.edu.tw/uploads/1675417163713PBpnsLYp.pdf",
        "title": "臺北市立內湖國中111學年度第一學期九年級第二次段考英語試卷（翰林版）",
        "year": "111-1",
        "subject": "english",
        "locator": "PDF p.3, questions 44-46: vocabulary in context, information not stated, and supported inference from a Holi festival report",
        "observedPattern": "以節慶資料卡加短文，考查詞義、是否明載、以及只能由文字推出的結論；本題重新撰寫新資料與選項。",
    },
    {
        "url": "https://www.kcjh.kh.edu.tw/upload/190/104_34764/1-%E8%8B%B1%E6%96%87.pdf",
        "title": "高雄市立國昌國中113學年度第二學期第二次段考一年級英語試題",
        "year": "113-2",
        "subject": "english",
        "locator": "PDF p.4, questions 30-32: locate a festival date range, infer a phrase from context, and select a statement supported by the reading",
        "observedPattern": "節慶閱讀題以日期定位、上下文推詞義及逐項核對事實為主；本題使用全新短文資料及選項。",
    },
]

SECTIONS = [
    ("先別說哪個節日比較熱鬧", "校刊要做一頁「節日放在一起看」。有人提議把龍舟賽和灑彩粉的照片排在一起，再問哪邊比較有趣。這樣看似在比較，其實沒有說明比的是什麼，也把個人喜好當成文化結論。比較要先立共同問題，例如：人們做什麼、何時做、活動和哪些故事或季節相連、資料來自哪裡。"),
    ("替兩邊放上同一把尺", "把筆記分成「日期／曆法」「活動」「故事或意義」「地區與來源」四欄。臺灣觀光署列出的端午習俗包括龍舟競賽與吃粽子，日期依農曆五月初五；印度觀光部資料把 Holi 放在印度曆 Phalguna 月的滿月，通常落在三月，並介紹迎春和灑色粉等活動。相同欄位讓差異可比；沒有資料的格子先留白，不用想像補齊。"),
    ("例子：日期相近不等於同一節日", "資料可以支持這樣的英文比較：Dragon Boat Festival is on the fifth day of the fifth lunar month. Holi is linked to the full moon in Phalguna, usually in March. 兩句都在說日期，但曆法標記和月份線索不同。若把它們都改成固定的西曆日期，就抹掉每年可能移動的線索。比較後可以寫「兩者都依曆法線索定位」，但不能因此推論它們同源。"),
    ("差異要連到證據，不連到高低", "先逐格找依據，再寫相同與不同。龍舟競賽和撒彩粉是可觀察的活動差異；端午資料把習俗連到屈原故事，Holi 資料說明迎春與多種文化意義。可寫「資料呈現的活動不同」，不可寫「哪種文化比較進步」。一個官方介紹也不代表每個地方、家庭或參與者都完全相同；若來源只談某地，就把地名或範圍一併保留。"),
    ("讀者看表格，也要看來源", "寫英文摘要前，在每項資料旁記下來源與原文定位。some communities、in this region、according to the tourism page 這類範圍詞，能提醒讀者敘述有邊界。若照片只拍到一艘龍舟，它證明照片中有龍舟，不會單獨證明所有臺灣居民都划船。事實欄、解釋欄和個人感想分開，文章就不會把觀察偷換成全體習俗。"),
    ("引導練習：先比，再寫兩句", "讀資料卡：A：臺灣觀光署介紹端午節，列出龍舟競賽、粽子與農曆五月初五。B：印度觀光部介紹 Holi，列出 Phalguna 月滿月、通常在三月及迎春活動。先選一個共同欄位，分別抄錄兩邊可以支持的短語；接著用Both descriptions…寫一項有證據的共同點，再用while或but寫一項具體差異。每一部分都要能回指到某個來源。"),
    ("遷移：換節慶，方法不換成刻板印象", "再比較一組你自己查到的節慶資料。先確認來源、地區、日期如何標示，再用兩個以上相同欄位整理；找不到共同證據的欄位就註明「資料未提供」。最後寫一段英文：先交代兩者的比較基準，再說一個相同點、一個差異，並用來源支持。交給同學檢查：有沒有把一地說成全國？有沒有把差異排成優劣？這兩項都要修正。"),
]

STEPS = [
    {"id": "step-1", "prompt": "The Taiwan card lists dragon boat races and zongzi. The Holi card lists colored powder and spring. Which shared category lets us compare them fairly?", "text": "先找兩張卡都能填資料的同一欄，不要預設它們有相同活動。", "options": ["Activities people do during each festival", "Which country has the better festival", "The exact Gregorian date every year"], "answer": "A", "retryHint": "找兩邊都明確列出資訊的欄位；一邊沒有固定西曆日期。", "feedback": "答案A。兩張卡都列出活動，可以在同一欄比較；沒有資料支持哪個節日較好或固定西曆日期。"},
    {"id": "step-2", "prompt": "Taiwan's tourism page lists dragon boat races and zongzi for Dragon Boat Festival. India's tourism page describes colored powder and spring for Holi. Which sentence stays within both sources?", "text": "把兩邊明載內容各自保留，避免把其中一邊的資料移到另一邊。", "options": ["Both festivals are celebrated in exactly the same way.", "The descriptions show different activities: boat races and zongzi in one, colors and spring in the other.", "Everyone in Taiwan and India joins every activity."], "answer": "B", "retryHint": "逐一對照兩邊的活動欄，保留資料中的地區與描述範圍。", "feedback": "答案B。它並列來源分別記載的活動，沒有把差異說成完全相同，也沒有擴大成人人參與。"},
    {"id": "step-3", "prompt": "One card dates Dragon Boat Festival by the fifth day of the fifth lunar month. The other links Holi to the full moon of Phalguna, usually in March. What is the safest comparison?", "text": "比較日期時，也要比較日期依據；農曆線索不能直接換成每年固定的西曆日。", "options": ["Both festivals always happen on the same Gregorian date.", "Both cards give a fixed Gregorian date for every year.", "Both use calendar clues, but the named lunar markers differ."], "answer": "C", "retryHint": "查看兩張卡用什麼曆法詞，不要自行推算未提供的固定日期。", "feedback": "答案C。兩份資料都用曆法線索定位，但一個是農曆五月初五，另一個是Phalguna滿月。"},
    {"id": "step-4", "prompt": "A visitor sees one photo of a dragon boat race in Taiwan. Which conclusion is supported by the photo alone?", "text": "影像直接呈現的是畫面中的活動，不是全體居民的行為。", "options": ["Every family in Taiwan races a boat.", "The photo shows a dragon boat race; broader participation needs more evidence.", "The photo proves the race has the same meaning to everyone."], "answer": "B", "retryHint": "把眼睛直接看到的內容和需要其他資料才能知道的事分開。", "feedback": "答案B。照片能支持「畫面中有龍舟賽」，不能代表每個家庭都參加或有相同理解。"},
]

QUESTION_DATA = [
    {"prompt": "Card A: Taiwan's Dragon Boat Festival includes boat races. Card B: Holi in India includes colored powder and welcomes spring. Which is the fairest shared comparison category?", "options": ["Activities described for each celebration", "Which culture is more modern", "The same fixed date every year", "Whether both stories have one identical hero"], "answer": "A", "target": "選擇共同比較欄位", "strategy": "先驗兩份資料是否都有可比較的活動，再把價值判斷與缺乏證據的共同點排除。", "explanation": "兩張卡都提供活動資訊，能用同一欄對照；資料沒有說哪個文化較現代，也沒有證明日期或故事完全相同。", "steps": ["先圈出題目要求：找兩個節日都能使用的比較面向。", "讀A卡，記下明載的boat races。", "讀B卡，記下colored powder與welcomes spring。", "檢查選項A確實涵蓋兩邊；其餘選項加入價值排序、固定日期或未給出的共同故事。", "因此選A，並把它寫成比較欄名Activities；不能把它寫成優劣排名。"]},
    {"prompt": "A Taiwan Tourism card says Dragon Boat Festival activities include races and zongzi. An India Tourism card says Holi includes colored powder and welcomes spring. Which sentence is supported?", "options": ["Both festivals use the same activities.", "The two descriptions list different activities.", "All people in both countries join every activity.", "The cards prove that the festivals began in the same year."], "answer": "B", "target": "比對明載活動", "strategy": "將敘述拆成兩部分，分別回到卡片找證據，特別排除all、same等超出來源的字。", "explanation": "端午卡列出龍舟賽和粽子；Holi卡列出彩粉與迎春。它們確實是兩組不同描述，沒有證據支持人人參加或同年起源。", "steps": ["把句子拆成台灣端午活動與Holi活動兩部分。", "在第一張卡找到races and zongzi。", "在第二張卡找到colored powder and welcomes spring。", "對照B的different activities，兩邊都有直接支持。", "A、C、D各自把不同說成相同、把部分擴大為全體，或添加卡片未提供的年代，因此選B。"]},
    {"prompt": "Card A dates Dragon Boat Festival as the fifth day of the fifth lunar month. Card B links Holi to the full moon of Phalguna, usually in March. What can a reader conclude?", "options": ["They always fall on the same date.", "Both have an exact Gregorian date listed for every year.", "The cards use different lunar-calendar markers.", "Holi is always before the fifth lunar month."], "answer": "C", "target": "判讀日期依據", "strategy": "比對原文的時間標記，不把通常月份、農曆日期和每年固定西曆日混為一談。", "explanation": "一張卡用農曆五月初五，另一張用Phalguna月滿月；兩者提供不同的曆法標記，並未列出每年固定西曆日。", "steps": ["找出A卡的日期字串：fifth day of the fifth lunar month。", "找出B卡的日期字串：full moon of Phalguna，並注意usually in March。", "兩者都指向曆法條件，但名稱和月份標記不同。", "題目沒有提供逐年換算日期，所以不能選固定日期、同一天或先後恆定的說法。", "選C，因為它只總結兩段文字實際列出的不同曆法標記。"]},
    {"prompt": "A student sees one photo of a dragon boat race in Taiwan. Which claim is justified by the photo alone?", "options": ["Every Taiwanese family races a boat.", "The photo shows a dragon boat race; participation beyond the photo needs more evidence.", "All viewers give the race the same meaning.", "Every town holds the race on the same day."], "answer": "B", "target": "影像證據範圍", "strategy": "區分直接可見物、需要額外來源支持的群體比例、主觀意義與時間概括。", "explanation": "照片能支持畫面有龍舟賽；它不能單獨代表每個家庭、所有人的理解或每個城鎮的日期。", "steps": ["描述照片中直接可見的主體：一場龍舟賽。", "找出A把單張照片擴大成every family，超出畫面。", "C談每個人相同的感受，照片無法證明。", "D談所有城鎮的日期，也需要各地資料。", "保留畫面範圍並標出待查部分，故選B。"]},
    {"prompt": "A note says Holi is linked to the full moon of Phalguna, usually in March. Which revision avoids turning a usual time into an exact yearly date?", "options": ["Holi is always on March 1.", "Holi is on the same day as Dragon Boat Festival.", "Holi usually falls in March and follows a lunar-calendar marker.", "Holi never changes its date."], "answer": "C", "target": "校正節慶日期敘述", "strategy": "保留usually與曆法條件，避免將概略季節資訊改成精確但未證實的日子。", "explanation": "來源只說通常在三月並以Phalguna滿月定位，沒有說固定在三月一日、與端午同日或日期不變。", "steps": ["圈出來源的限定詞usually，代表通常而非每年固定。", "圈出full moon of Phalguna，這是曆法依據。", "檢查選項C是否保留概略月份和曆法線索。", "A、B、D都加入來源沒有說的固定日期、同日或永不改變。", "所以選C；需要某一年的確切日期時，還要查該年日曆。"]},
    {"prompt": "Two short reports describe a festival's food and activities, but only one gives a founding story. Which comparison note is best?", "options": ["Both festivals have the same origin.", "The reports differ in what they explain; mark the missing origin as not stated.", "The festival without a story has no history.", "Food proves why every person celebrates."], "answer": "B", "target": "區分未提供與不存在", "strategy": "追蹤兩份文字各自涵蓋的欄位，把沉默記為not stated，不推成事實不存在。", "explanation": "若只有一篇介紹起源，合理結論是兩份資料提供的內容不同；不能由沒寫起源推論節日沒有歷史。", "steps": ["先列比較表欄位：food、activities、origin。", "逐篇檢查哪一篇實際談到origin。", "只有一篇提到起源，表示這兩篇資料的涵蓋範圍不同。", "沒有提到不等於證明不存在，因此用not stated標記空格。", "B忠實表達資料邊界；A、C、D都把不足資訊改成未經支持的結論。"]},
    {"prompt": "A source says a festival is celebrated in several places, with local traditions varying. Which wording is most accurate for a student report?", "options": ["Every person in the country follows one identical custom.", "The source describes some local practices; customs may vary by place.", "The country has no shared festival practices.", "One local example explains every community."], "answer": "B", "target": "保留地方差異與範圍", "strategy": "對照來源的some、several或region等範圍詞，避免all、every等絕對化。", "explanation": "來源明示有些地區的做法不同，最準確的改寫要保留地方範圍和變異可能。", "steps": ["找出來源限定範圍的字，例如some places或regional traditions。", "將它保留在英文報告，避免換成every或all。", "選項B既說明部分地方做法，也提醒習俗可能有地區差異。", "A與D把單一或部分例子擴成全國一致，C則反向否定所有共同性。", "因此選B，並在需要時補上地區名稱與來源。"]},
    {"prompt": "A class chart has columns for calendar clue, activity, and source. Which entry is matched correctly?", "options": ["Dragon Boat Festival — Holi's Phalguna full moon — Taiwan Tourism", "Holi — fifth day of the fifth lunar month — Taiwan Tourism", "Dragon Boat Festival — dragon boat races — Taiwan Tourism", "Holi — zongzi — India Tourism"], "answer": "C", "target": "配對資料與來源", "strategy": "逐列查對節日、事實欄和來源，不能因同屬節慶就交換兩邊資訊。", "explanation": "臺灣觀光署端午節資料列出龍舟賽；Phalguna滿月與彩粉屬印度觀光部Holi資料，粽子則不是Holi卡片內容。", "steps": ["讀選項C的節日名稱：Dragon Boat Festival。", "回查臺灣觀光署資料，確認其列出dragon boat races。", "確認該活動和來源欄配對正確。", "A、B把印度日期線索配給端午或錯配來源；D把臺灣食物zongzi放入Holi。", "故選C；整理表格時每個格子都要能回指原始來源。"]},
    {"prompt": "A student writes, 'Holi is more meaningful than Taiwan's Dragon Boat Festival.' The two sources describe traditions but do not rank them. What is the best edit?", "options": ["Holi is better because it uses more colors.", "Both festivals have traditions described in their sources; their meanings should be compared with evidence, not ranked.", "Dragon Boat Festival is older, so it is more important.", "People in both countries celebrate for exactly the same reason."], "answer": "B", "target": "把價值排序改成證據比較", "strategy": "移除better、more meaningful等未定義的價值排序，改寫可由來源支持的比較主張。", "explanation": "來源呈現活動和意義，但沒有替兩種文化評高下。B改成有來源界線的描述，沒有自創共同原因。", "steps": ["圈出原句的more meaningful，這是沒有評量標準的價值排序。", "查看兩個來源真正提供的內容是各自的傳統和活動。", "把主張改成描述性比較，並要求每項意義都能連回來源。", "排除A、C的優劣判斷與未提供年代，並排除D的相同原因推測。", "選B，再補上具體證據即可形成可檢驗的比較。"]},
    {"prompt": "A reader wants to compare two festivals using only one photo from each. What extra information would make the comparison stronger?", "options": ["The photographer's favorite color only", "A matching written source for each place explaining the pictured activity and its context", "A guess about what every participant believes", "A ranking of which photo looks happier"], "answer": "B", "target": "補足照片脈絡與來源", "strategy": "辨認影像缺少的時間、地點、活動意義，再尋找兩邊可對照的可靠文字資料。", "explanation": "相同類型的文字來源可補上照片的地點與活動脈絡；個人喜好、群體信念猜測和照片美感排名都不能完成文化比較。", "steps": ["先列出照片能看見的部分：畫面中的物件和人。", "指出仍未知的資訊：地點、活動名稱、日期和在當地的脈絡。", "為兩個節日各找可查證的文字來源，並用相同欄位摘記。", "選項B提供兩邊對等、與影像活動有關的上下文資料。", "因此選B；新資料仍要注明地區和來源，不可推測所有參與者的信念。"]},
]

def ref_row(exam: dict, question_no: str) -> dict:
    return {**exam, "locator": f"{exam['locator']}; relevant item(s): {question_no}", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "page"}


def main() -> None:
    inventory_path = ROOT / "implementation/reports/authored-fusion-writing-inventory.json"
    inventory = json.loads(inventory_path.read_text(encoding="utf-8"))
    if LESSON_ID in set(inventory.get("authoredFusionDraftIds", [])):
        raise SystemExit(f"Refusing to rewrite already registered manuscript: {LESSON_ID}")

    lesson = json.loads(LESSON_PATH.read_text(encoding="utf-8"))
    assert lesson["id"] == LESSON_ID
    headings = [row[0] for row in SECTIONS]
    lesson["content"] = {"summary": "比較節慶不是替文化排名，而是先選相同基準、查清來源，再用證據說出相同處、差異與資料邊界。", "sections": [{"heading": h, "body": b} for h, b in SECTIONS]}
    lesson["studyHighlights"] = ["用日期／曆法、活動、故事或意義、地區與來源四欄建立共同比較基準。", "每個相同點或差異都回指兩邊的資料；資料未提供就註明未知。", "使用usually、some places等範圍詞，不把單一例子擴大成全體文化。", "英文摘要先交代比較欄位，再寫有證據的共同點與差異，避免優劣排名。"]
    lesson["studyReferences"] = [CURRICULUM, TAIWAN_FESTIVALS, INDIA_HOLI, "https://theme.npm.edu.tw/NPMDragonBoatFestival/en", NAER_RESEARCH, HANLIN_RESOURCE, "https://www.jlsh.mlc.edu.tw/var/file/12/1012/img/110-3-8-2.pdf"]
    lesson["updatedAt"] = "2026-09-28"
    lesson["authoringStandard"] = "version-fused-v1"
    lesson["publisherResearch"] = [
        {"publisher": "hanlin", "edition": "publisher-domain public flexible-learning resource; year/edition of target textbook not established", "subject": "english", "chapterLocator": "Hanlin-domain PDF search text describes comparing Halloween and Zhongyuan Festival using images, shared questions, customs and meanings; exact textbook chapter/page is not given.", "sourceUrl": HANLIN_RESOURCE, "access": "public-open", "reviewedAt": "2026-09-28", "researchScope": ["concept-progression", "activity-pattern", "unit-curriculum-placement"], "outcome": "Directly read the public resource description for a festival-comparison activity. It supports an image-to-question-to-compare teaching route, not a claim about the current grade-8 textbook chapter. This lesson independently designs source cards and a comparison matrix.", "copyrightBoundary": "Only the instructional pattern and high-level comparison dimensions are recorded; no publisher wording, images, worksheet, question, or answer was reused."},
        {"publisher": "nani", "edition": "No target-unit Nan-I student-text edition verified in this run", "subject": "english", "chapterLocator": "A public third-party lesson plan page labels B3 L4 Holiday and references 8-IV-3; uploader, publisher attribution, edition, page locator and rights are unverified.", "sourceUrl": "https://www.scribd.com/document/966228867/7G-Lesson-Plan", "access": "public-open", "reviewedAt": "2026-09-28", "researchScope": ["unit-curriculum-placement"], "outcome": "The page is treated only as an unverified public lesson-plan label, not as Nan-I textbook content or evidence for publisher-specific methods. The full target Nan-I student chapter remains unknown.", "copyrightBoundary": "No document text, exercise, wording, or answer was reproduced."},
        {"publisher": "kanghsuan", "edition": "112 school-year public school plan identifying Kang Hsuan English materials; target edition is grade 9 volumes 5-6", "subject": "english", "chapterLocator": "Daji Junior High school plan PDF pp.46-47 records a Kang Hsuan grade-9 food-culture unit with pre-/while-/post-reading and compare/classify/sort objectives; not the target grade-8 festival chapter.", "sourceUrl": "https://course.cyc.edu.tw/upfile/course112/sub1/15343601527825912.pdf", "access": "public-open", "reviewedAt": "2026-09-28", "researchScope": ["teaching-sequence", "concept-progression"], "outcome": "Read the public school plan and used only its general sequence of preparing, reading, and post-reading comparison as a broad design clue; it does not establish Kang Hsuan grade-8 lesson content or festival examples.", "copyrightBoundary": "No school plan wording, textbook text, assessment, or answer was reproduced."}
    ]
    lesson["versionResearch"] = [
        {"publisher": "hanlin", "edition": "Publisher-domain flexible-learning resource; target textbook year/edition unverified", "sourceType": "public-web", "sourceLocator": "Hanlin-domain public PDF description compares Halloween and Zhongyuan by images/shared questions; exact PDF page is not verified and this is not a textbook chapter.", "reviewedAt": "2026-09-28", "findings": {"concepts": ["The resource frames two festivals as a pair for explicit comparison.", "Shared questions invite learners to identify common and differing customs."], "representations": ["Festival images are paired with common comparison questions."], "examplesOrEvidence": ["Halloween and Zhongyuan are named as paired image prompts in the public description."], "misconceptions": ["A pictured symbol should not be treated as the complete meaning of a festival."], "assessmentEmphasis": ["Learners explain what the images show and what the two festivals share."]}, "licenseBoundary": "Only a high-level activity pattern is recorded; no publisher wording, image, worksheet, question, or answer is copied."},
        {"publisher": "kanghsuan", "edition": "Daji JHS 112 plan labels Kang Hsuan grade-9 volumes 5-6; not target grade-8 chapter", "sourceType": "public-web", "sourceLocator": "Daji JHS 112 plan PDF pp.46-47: grade-9 food-culture unit, pre-/while-/post-reading and compare/classify/sort; indirect cross-grade context only.", "reviewedAt": "2026-09-28", "findings": {"concepts": ["Retrieve and organize information across a short reading.", "Compare and classify multiple pieces of information using shared categories."], "representations": ["A sequence of pre-reading, reading, and post-reading classroom tasks."], "examplesOrEvidence": ["The plan lists food-culture reading followed by comparison/classification and sorting activities."], "misconceptions": ["One detail in a reading should not stand in for the entire text."], "assessmentEmphasis": ["Discussion, oral presentation, listening, and written tasks are listed."]}, "licenseBoundary": "The school-plan sequence is summarized at a high level; no textbook passage, assessment item, or answer is copied."},
        {"publisher": "nani", "edition": "No target-unit Nan-I student-text edition verified in this run", "sourceType": "public-web", "sourceLocator": "Third-party public page labels B3 L4 Holiday and includes 8-IV-3; uploader, publisher authorship, edition, page locator, and rights are unverified.", "reviewedAt": "2026-09-28", "findings": {"concepts": ["The public label associates a holiday topic with the 8-IV-3 indicator.", "The available snippet cannot establish any publisher-specific teaching method."], "representations": ["Only a search-visible text summary is available; no verified lesson representation can be described."], "examplesOrEvidence": ["The page summary mentions a holiday/festival context without a verifiable chapter locator."], "misconceptions": ["An uploader's publisher label is not verified publisher provenance."], "assessmentEmphasis": ["Accessible evidence is insufficient to characterize assessment emphasis."]}, "licenseBoundary": "No document text, exercise, wording, or answer is reproduced; this entry is explicitly not treated as Nan-I textbook evidence."}
    ]
    lesson["fusionRecord"] = {"commonCore": ["Compare domestic and international festival customs using the same explicit criterion.", "Support statements about activities and dates with traceable evidence.", "Respect cultural differences and limit claims to the scope stated in each source."], "versionDifferences": ["The Hanlin-domain item is a publisher-hosted teaching resource rather than a verified current textbook chapter; the Kang Hsuan-labelled school plan is a cross-grade food-culture example; the third-party Nan-I label is unverified. These sources do not establish three comparable grade-8 textbook treatments."], "originalAdditions": ["A four-column evidence matrix for calendar, activity, meaning, and place/source.", "A distinction among directly stated fact, source explanation, and information not provided.", "Scope words and checks against cultural overgeneralization or value ranking.", "Original Taiwan Dragon Boat Festival and Holi evidence tasks with source cards."], "llmSynthesisNote": "本課依官方課綱8-Ⅳ-3與KG設計，僅把可讀到的翰林網域節慶比較教學線索及康軒標示跨年級校方計畫的比較策略作有限參考；南一頁面只保留未驗證標籤，不當作出版社教材證據。另以臺灣觀光署、印度觀光部及故宮公開文化資料核對自編例證，重新組織為「共同比較欄—逐項找來源—標示資料範圍—尊重差異」的單元教學。正文、資料卡、例句、互動與題目均為原創。尚未取得三家當前八年級課本章節，不宣稱逐頁三版融合；教材維持draft供使用者ChatGPT審查。"}
    lesson["interactive"] = {"type": "guided-choice", "goal": "以同一比較基準分析兩項節慶資料，並用來源證據表達差異及主張範圍。", "steps": STEPS}
    lesson["teaching"] = {"body": [{"id": f"stage-{i+1}", "phase": phase, "heading": h, "body": b} for i, ((h,b), phase) in enumerate(zip(SECTIONS, ["hook","explain","worked-example","explain","guided-practice","guided-practice","transfer"]))], "summary": ["先選共同比較基準，不用喜好排名。", "逐欄摘記日期、活動、意義及來源，未知處保留空白。", "同時檢查地區範圍與曆法線索，避免把單一案例推成全體。", "用英文先報比較基準，再提出有來源支持的相同點和差異。"], "exitCheck": [{"prompt":"用一個相同欄位比較兩項節慶，各指出一項來源證據。","expectedEvidence":"比較欄位一致，兩邊主張均可回到來源，沒有文化高下排序。"},{"prompt":"來源只談某地或通常月份時，英文句子怎麼保留限制？","expectedEvidence":"使用some places、in this region、usually等範圍詞；不把概略資訊改成每年固定日期或全體習俗。"},{"prompt":"如果一篇介紹沒有說節慶起源，你能下什麼結論？","expectedEvidence":"只能說這份資料未提到；不能推論該節日沒有起源或歷史。"}]}
    lesson["provenance"]["authoringNote"] = "Original unit-specific lesson based on the official curriculum, KG, a directly consulted Hanlin-domain teaching resource, limited version-labelled school/third-party context with disclosed uncertainty, and public cultural fact sources. Publisher chapter text for the current grade remains unavailable; no textbook passage, exam question, or publisher wording is reproduced. Lesson remains draft for the user's ChatGPT review."

    for index, item in enumerate(QUESTION_DATA, 1):
        question_id = f"question-english-performance-8-iv-3-{index}"
        path = ROOT / f"questions/english/{question_id}.json"
        question = json.loads(path.read_text(encoding="utf-8"))
        key = item["answer"]
        correct = item["options"][ord(key)-65]
        question.update({"prompt": item["prompt"], "options": [{"id": chr(65+i), "text": text} for i,text in enumerate(item["options"])], "knowledgeIds": ["kg-english-performance-8-iv-3"], "lessonId": LESSON_ID, "difficulty": "medium", "answer": {"value": key, "explanation": f"正確答案是{key}。{item['explanation']}"}, "updatedAt": "2026-09-28", "studyReferences": [CURRICULUM, TAIWAN_FESTIVALS, INDIA_HOLI], "solutionStrategy": item["strategy"], "solutionSteps": item["steps"], "provenance": {"origin":"original","license":"All rights reserved","sourceUrl": EXAMS[0]["url"],"sourceLocator":"原創改寫；參照鹽埕國中公開英語評量的節慶雙資料比較型態，僅借題型方向，不使用原卷題文／選項。","authoringNote":"獨立撰寫；答案、繁中詳解、策略和步驟均為新作。公校試題只作pattern-only題型參照；最終題庫內容判讀另依專案流程。"}, "examPatternRefs": [ref_row(EXAMS[0], "44-46"), ref_row(EXAMS[1], "30-32")]})
        assert question["options"][ord(key)-65]["id"] == question["answer"]["value"]
        path.write_text(json.dumps(question, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    assert len(QUESTION_DATA) == 10
    LESSON_PATH.write_text(json.dumps(lesson, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("Authored English 8-IV-3 seven-section manuscript, four interactive steps, and ten independently written solved items.")


if __name__ == "__main__":
    main()
