import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-3.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-3-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創門禁、出口、開放時間、濕地警告、急救、回收、社區活動、咖啡店流程與安靜區標示，承接公開課程的生活標示閱讀與行動理解方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-3-iv-3"
    data["title"] = "3-Ⅳ-3：從英文標示、符號與時間資訊判斷應採取的行動"
    data["content"] = {"summary": "生活標示把長篇規則壓縮成文字、箭頭、圖示、時間和地點；理解 NO ENTRY、EXIT、CLOSED、PAPER ONLY、SILENT ZONE 或活動公告時，要分辨禁止、方向、時間範圍、警告、服務、分類、流程與事件資訊。本課用原創公共場所標示，先找標示對象與關鍵動詞，再將符號和文字合併，最後回答人應去哪裡、何時到、先做什麼、哪些物品符合或哪些行為要避免，建立讀標示即能安全行動的策略。", "sections": [{"heading": "標示的第一個問題是要你做什麼", "body": "NO ENTRY 禁止進入，EXIT 加箭頭指示出口方向，wet floor 要求放慢、避開或遵循替代路線；先找禁止、指示、提醒或要求的功能，再看地點與對象。只翻譯名詞而沒有轉成行動，仍未理解標示。"}, {"heading": "時間範圍和事件細節要一起讀", "body": "CLOSED 12:00-1:00 表示特定時段關閉，不是全天不開；Community Clean-up: Gate B, 8:30 Saturday 同時提供地點、時間與活動。看見數字時先標 date、time、place 或 duration，避免把 8:30 誤當 Gate B。"}, {"heading": "圖示和文字互相限制", "body": "SILENT ZONE 的劃掉手機圖示補充文字的行為範圍，PAPER ONLY 則把回收箱限制在紙類。若圖示與文字各提供一部分資訊，要合併成可執行規則，不擴大成標示沒有說的全部電子產品或所有垃圾。"}, {"heading": "流程標示有先後順序", "body": "Please order at the counter before taking a seat 不是兩個可任意交換的建議，而是先點餐、再找座位。標示閱讀要把 before、only、delayed、at、to 等小字視為行動條件；遇到火車延誤則更新原時間，不能照舊時刻行動。"}]}
    data["studyHighlights"] = ["分辨禁止、方向、開放時間、警告、服務與分類標示的功能。", "將箭頭、圖示、關鍵詞、時間、地點與對象合併理解。", "依 before、only、delayed 等條件判斷行動先後與限制。", "把標示資訊轉成安全、精確且可執行的下一步。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "看懂 EXIT 卻走錯方向，算理解嗎？", "body": "展示完全自編的 EXIT 箭頭與兩條走廊圖，先讓學生只看文字再選路，接著加入箭頭與另一個門禁標示。比較結果後，讓學生說出標示功能、方向和行動，發現符號不是裝飾而是限制選擇的重要證據。"}, {"id": "explain", "phase": "explain", "heading": "標示五欄行動卡", "body": "建立 Function、Audience、Key words／symbols、Time／place、Action or restriction 五欄。先判斷是禁止、指示、警告、服務或分類，再標對象和範圍，最後寫出要去哪裡、何時做什麼或必須避免什麼。"}, {"id": "worked-example", "phase": "worked-example", "heading": "把 before 讀成有順序的流程", "body": "以咖啡店 Please order at the counter before taking a seat. 示範：counter 是第一個地點與動作，seat 是後續行動；將順序卡打亂再讓學生依標示重排，理解 before 會限制行動先後，而非增加另一個可選建議。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "從標示組合成公共場所路線", "body": "給出出口箭頭、NO ENTRY、急救室、濕地、安靜區與回收箱六張原創卡，學生替不同角色規劃到出口、求助或分類的路線。交換後同伴只讀標示判斷下一步，若走入禁止區或把 PAPER ONLY 當成全部回收，回到文字和圖示找衝突。"}, {"id": "transfer", "phase": "transfer", "heading": "讀活動公告並準時到達", "body": "輪換社區清潔、車站、圖書館與咖啡店標示。學生先圈地點、日期、時間、延誤或先後條件，再寫一句給志工或旅客的行動摘要；標示有缺少資訊時提出具體問題，不用猜測補齊。"}, {"id": "reflect", "phase": "reflect", "heading": "我有把限制讀進行動嗎？", "body": "回看答案，將錯誤分成功能、範圍、時間、地點、順序或圖示整合。若只是翻譯標示卻沒有行動，補上 should、must、do not 或 before；若把局部規則擴大，回到 ONLY、時間範圍與圖示重新限定。"}], "summary": ["以 Function、Audience、Key words／symbols、Time／place、Action／restriction 五欄讀標示。", "整合文字、箭頭、圖示、時間與地點，而非只翻譯名詞。", "用 before、only、delayed 等小字判斷限制和流程。", "將禁止、方向、警告、服務與活動公告轉成安全行動。"], "exitCheck": [{"prompt": "讀英文標示時為什麼要先判斷功能？", "expectedEvidence": "能分辨禁止、方向、警告、服務、分類或公告，並說明功能決定行動。"}, {"prompt": "如何避免把活動公告的時間、地點和日期混淆？", "expectedEvidence": "能將數字與 date、time、place、duration 標記配對，再寫出完整集合地點與時間。"}, {"prompt": "PAPER ONLY 或 SILENT ZONE 的 ONLY、圖示有何作用？", "expectedEvidence": "能指出它們限制規則範圍，並合併文字與圖示，不擴大成標示沒有說的規定。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "從英文標示的文字、符號、箭頭、時間與地點，判斷規則功能並選擇安全可行的行動。", "scenario": "學生擔任公共場所導覽助理，要替訪客讀門禁、出口、回收、活動、車站與服務標示，規劃正確下一步。", "variables": [{"symbol": "f", "meaning": "禁止、方向、警告、服務、分類與公告功能"}, {"symbol": "i", "meaning": "文字、圖示、箭頭、時間、地點與對象"}, {"symbol": "a", "meaning": "行動、限制、順序與安全選擇"}], "steps": [{"id": "step-1", "prompt": "A door sign says 'NO ENTRY.' What does it tell visitors?", "options": ["Visitors must not enter through that door.", "Visitors should enter immediately through that door.", "Visitors should order food before sitting."], "answer": "A", "feedback": "A converts the prohibition into a direct action restriction; the other choices belong to different signs."}, {"id": "step-2", "prompt": "A café notice says 'Please order at the counter before taking a seat.' What is the required order?", "options": ["Order at the counter first, then take a seat.", "Take a seat first, then decide whether to order.", "Go to Platform 2 before the café opens."], "answer": "A", "feedback": "Before establishes the sequence: counter order comes before sitting down."}, {"id": "step-3", "prompt": "A station board says 'Platform 2: Train to Harbor Town, 10:15. Delayed 10 min.' What should a passenger conclude?", "options": ["The train is still for Platform 2, but it will leave about ten minutes later.", "The train will leave ten minutes earlier from every platform.", "The sign gives only the town's name and no time."], "answer": "A", "feedback": "A combines the platform, destination, original time, and delayed condition without ignoring the update."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語生活標示、公共場所與基本閱讀定位；核讀 2026-09-21。", ["由生活標示、圖示與簡易公告理解行動。", "以字詞、圖片、方向和時間支持英語閱讀。"], ["門禁、出口、開放時間、警告、急救、回收與活動公告。"], "只翻譯標示文字，沒有判斷禁止、方向或下一步。", "重視生活閱讀、主要訊息與安全行動。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語圖片、標示、指令與情境任務定位；核讀 2026-09-21。", ["透過圖片、符號、文字和公共任務理解標示。", "依方向、順序、時間、地點和規則完成行動。"], ["出口、濕地、回收、集合、車站、咖啡店與安靜區。"], "忽略箭頭、ONLY、before 或 delayed，將部分規則擴大或順序弄反。", "評量標示主要內容、細節、順序與功能性回應。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語標示、符號與功能閱讀評量定位；核讀 2026-09-21。", ["從文字、符號、圖像、時間和上下文形成標示理解。", "以分類、限制、公告細節與安全摘要表達。"], ["function、audience、symbol、direction、time、place、restriction。"], "把圖示和文字分開解讀，或把局部限制誤當成所有情境的規則。", "評量標示功能、資訊定位、限制、流程與安全行動。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持生活標示、圖示、公共場所閱讀與行動理解。", "標示理解需整合功能、對象、文字、箭頭、圖示、時間、地點、順序與限制。", "從讀字到安全行動可用路線卡、符號整合、活動公告與角色任務驗證。"], "versionDifferences": ["南一較突顯生活標示與基本閱讀；康軒較突顯圖片、符號、方向、時間與情境任務；翰林較突顯功能、限制、流程、公告細節與安全摘要評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Function、Audience、Key words／symbols、Time／place、Action／restriction 五欄讀標示。", "用門禁、出口、回收、車站、咖啡店、社區活動與安靜區原創標示規劃路線。", "以 ONLY、before、delayed、圖示與箭頭核對行動是否精準安全。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織英文標示的禁止、方向、時間、警告、服務、分類、流程、公告與安全行動。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 五欄填完後讓同伴只讀標示做選擇，再回看文字和圖示找證據；若行動超出範圍，優先檢查 ONLY、時間區間與箭頭方向。"
    data["teaching"]["body"][4]["body"] += " 活動公告改寫給不同訪客時保留日期、時間、地點與延誤資訊；若標示缺一項，提出 What time? 或 Where should we meet? 而不自行補數字。"
    data["teaching"]["body"][5]["body"] += " 若同伴只會翻譯卻不會行動，補上 must、should、do not 或 before；若把局部規則擴大，回到符號和文字共同限定範圍。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "3-Ⅳ-3：從英文標示、符號與時間資訊判斷應採取的行動", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-3")


if __name__ == "__main__":
    main()
