import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/chinese/lesson-chinese-performance-5-iv-3.json"
REPORT = ROOT / "implementation/reports/chinese-performance-5-iv-3-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方國文課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創敘事片段、書信、說明文字與形式對照卡，承接公開課程的文本理解與寫作特色分析方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-chinese-performance-5-iv-3"
    data["title"]="5-Ⅳ-3：從內容、形式與語言證據讀出文本特色"
    data["content"]={"summary":"分析文本特色，要把『寫了什麼』和『怎麼寫』放在同一條證據鏈上。內容包括人物、事件、觀點、資料與情感變化；形式則包含敘述視角、時間順序、段落安排、意象、對比、句式和文體。作者的選擇會改變讀者知道什麼、感受到什麼以及如何理解結尾。本課以自編敘事、書信、說明文與短句片段練習，先描述形式，再說明它如何服務內容，不把修辭名稱當成空泛評語。", "sections":[{"heading":"先分內容與形式兩條線","body":"讀第一遍時記錄人物、事件、資料或觀點的變化；第二遍圈出敘述者、時間切換、段落順序、反覆詞、對比和句子長短。兩條線交會處通常就是寫作特色：例如第一人稱限制資訊，會讓讀者跟著敘述者逐步發現；倒敘則可能先提出現在的疑問，再補回過去原因。"},{"heading":"形式不是裝飾而是閱讀安排","body":"同一事件用新聞摘要、日記或書信寫出，讀者獲得的距離、資訊量和情感溫度都不同。分析時先指出形式選擇，再說它造成的閱讀效果，最後回到內容確認是否真的支持；不能只寫『使用第一人稱所以生動』，而要說明讀者被限制在誰的視野中。"},{"heading":"用局部語言連到整體特色","body":"反覆出現的燈、鑰匙或窗等意象，必須觀察它每次出現時的情境是否改變；短句可能加快節奏，也可能製造停頓和壓力，需與事件進展一起看。引用兩個以上位置，比較前後功能，才能避免把單一詞語任意象徵化。"},{"heading":"說明特色要保留替代解釋","body":"好的分析不是替作者宣布唯一答案，而是提出最能被文本支持的解釋，並說明證據範圍。若結尾的鑰匙可能象徵責任，也可能只是情節中的物件，先看前文是否反覆鋪陳、人物是否因此改變，再用『可能』『暗示』控制語氣。"}]}
    data["studyHighlights"]=["分開記錄文本內容與形式選擇，再找兩者交會。","以敘述視角、時間安排、文體與段落結構說明閱讀效果。","比較反覆意象、對比與句式在不同位置的功能。","用多處證據和保留語氣支持寫作特色判讀。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"同一事件換一種形式，讀者知道的會一樣嗎？","body":"提供同一個自編社區修繕事件的日記版、新聞摘要版與書信版，請學習者先列出每版讀者知道的資訊，再圈出誰在說、何時說、哪些內容被省略。比較後才命名文體，讓形式分析從資訊與閱讀經驗出發，而不是先背名詞。"},{"id":"explain","phase":"explain","heading":"內容—形式—效果三段證據鏈","body":"第一欄記錄內容中的人物、事件、觀點或資料；第二欄記錄視角、順序、段落、意象、句式與文體；第三欄回答這項形式如何改變資訊取得、節奏、距離或情感。每個效果至少連回兩個位置，並檢查是否還有同樣合理的替代解釋。"},{"id":"worked-example","phase":"worked-example","heading":"從鑰匙的前後出現讀人物改變","body":"以自編小說片段為例：開頭人物把鑰匙放在口袋，結尾把它交給妹妹。先描述物件兩次出現的情境，再連到人物是否從保留、逃避轉向承擔；不直接宣布象徵意義，而是指出前文行動與結尾選擇如何共同支持這個閱讀。"},{"id":"guided-practice","phase":"guided-practice","heading":"用時間線拆開倒敘與現在時刻","body":"閱讀一段先寫多年後回到車站、再補童年離站的自編文字，先把事件按發生順序排卡，再按文章順序排卡。學習者說明兩條時間線的差異如何製造疑問、補充原因或改變情感距離，並指出如果改成順敘，哪種效果會減弱。"},{"id":"transfer","phase":"transfer","heading":"跨文體比較同一個公共議題","body":"將校園雨水回收寫成資料說明、倡議短文與人物訪談三種自編版本，固定議題後比較資料密度、作者位置、讀者任務與語氣。最後選一種用途最合適的形式，引用兩項文本特徵解釋選擇，而不是只說某種文體比較有趣。"},{"id":"reflect","phase":"reflect","heading":"檢查我是否把名詞當成分析","body":"回看自己的答案，將『很生動』『很有畫面』『象徵希望』等評語改寫成形式、位置與效果三部分。若一項解釋只靠一個詞或一個句子，補找第二處證據；若仍有兩種讀法，保留差異並說明哪種較能統攝全文。"}],"summary":["先分別整理內容資訊與形式選擇，再找兩者交會。","以視角、時間、文體、段落與句式解釋閱讀效果。","追蹤意象、對比與語言在前後位置的功能變化。","以多處證據、替代解釋和保留語氣完成特色分析。"],"exitCheck":[{"prompt":"內容分析與形式分析如何互相連結？","expectedEvidence":"能先指出文本寫了什麼，再指出如何安排視角、順序或語言，並說明形式如何改變讀者理解。"},{"prompt":"分析反覆意象時為何要比較至少兩個位置？","expectedEvidence":"能說明意象功能可能隨情境改變，需用前後位置與人物／事件變化支持，而不能只套固定象徵。"},{"prompt":"何時應使用『可能』『暗示』而非肯定句？","expectedEvidence":"能指出文本證據尚有替代解釋、作者意圖未明或單一位置不足時，要控制結論語氣。"}]}
    data["interactive"]={"type":"guided-choice","goal":"從內容與形式的交會處分析文本特色，並以多處證據控制解釋範圍。","scenario":"學生收到三種文體改寫的同一公共議題，依序建立內容—形式—效果表、比較時間與視角，再提出有證據的特色判讀。","variables":[{"symbol":"c","meaning":"內容資訊"},{"symbol":"f","meaning":"形式選擇"},{"symbol":"e","meaning":"閱讀效果與解釋界線"}],"steps":[{"id":"step-1","prompt":"分析文章的內容、形式與寫作特色，第一步最完整的做法是什麼？","options":["先整理人物／事件／觀點，再標記視角、順序、段落與語言，最後說明形式如何服務內容","先背出文體名稱，再把所有特色套進去","只摘錄最漂亮的句子，不用比較前後位置"],"answer":"A","feedback":"A 建立內容—形式—效果的證據鏈，避免名詞或單句取代整體分析。"},{"id":"step-2","prompt":"文章先寫多年後看見車站，再回到童年離站，這種安排主要帶來什麼效果？","options":["用倒敘先提出現在的情感或疑問，再補回過去原因，讓讀者重新理解回憶","保證故事完全沒有時間順序","只表示作者忘記先寫童年"],"answer":"A","feedback":"A 比較文章順序與事件順序，能說明倒敘如何安排資訊與情感。"},{"id":"step-3","prompt":"反覆出現的『窗邊一盞燈』在結尾改變情境，最負責任的分析是什麼？","options":["比較它前後出現的位置與人物行動，再提出可能的象徵或情感效果，保留替代解釋","看到燈就直接固定解釋成希望","只要作者沒有明說，就完全不能分析"],"answer":"A","feedback":"A 既使用文本中的反覆與變化，也不把單一象徵當成唯一答案。"}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；國語文文本理解、文體與寫作表達定位；核讀 2026-09-21。",["由內容、形式與語言理解文本特色。","以文體與寫作選擇支援閱讀表達。"],["敘事、書信、說明、視角、結構與意象。"],"只背文體名稱或把單一修辭固定成唯一效果。","重視文本證據、形式功能與特色分析。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；國語文閱讀、句段概念與文本形式定位；核讀 2026-09-21。",["透過閱讀、比較與討論理解內容和形式。","依段落安排、語言與文體說明閱讀效果。"],["倒敘、對比、短句、反覆意象、書信與資料說明。"],"把『生動』『有畫面』當成無需證據的分析。","要求效果回扣多處文本位置並能修正。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；國文文本形式、寫作特色與評量定位；核讀 2026-09-21。",["從內容、形式與寫作特色整合理解文本。","以敘述視角、結構與語言選擇形成有範圍的解釋。"],["第一人稱、時間安排、象徵、對比、句式、文體與結尾。"],"把作者意圖或象徵意義說成文本唯一事實。","評量形式辨識、效果分析、證據與替代解釋。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持文本內容、形式、文體與寫作特色理解。","視角、順序、段落、語言與意象要連回人物、事件或觀點。","特色分析需以多處證據並保留解釋範圍。"],"versionDifferences":["南一較突顯內容、文體與寫作表達；康軒較突顯閱讀、比較、討論與文本形式；翰林較突顯視角、結構、語言及證據界線。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以內容—形式—效果三段證據鏈分析文本。","用同一事件的三種文體比較資訊與情感距離。","追蹤反覆意象與倒敘時間線，保留替代解釋。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織文本內容、形式、文體、視角、結構、語言與寫作特色。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 要求每條效果判斷旁邊同時留下內容證據與形式證據；若兩者沒有交會，便把結論降為局部觀察，不冒充整篇特色。"
    data["teaching"]["body"][4]["body"] += " 比較時固定同一議題和核心事件，再觀察資訊密度、敘述位置、讀者距離與語氣的改變，才能說明形式差異而非題材差異。"
    data["teaching"]["body"][5]["body"] += " 將所有抽象評語改寫成『哪個形式、出現在哪裡、造成什麼可能效果』，並在找不到第二項證據時保留不確定性。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"5-Ⅳ-3：從內容、形式與語言證據讀出文本特色","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored chinese performance 5-iv-3")


if __name__ == "__main__": main()
