import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-2-iv-7.json"
REPORT = ROOT / "implementation/reports/english-performance-2-iv-7-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創博物館導覽、河川步行、社團、排演、交通、影片繳交與志工會議情境，承接公開課程的疑問詞、資訊詢問與溝通修補方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-2-iv-7"
    data["title"] = "2-Ⅳ-7：用疑問詞與禮貌句型詢問人、事、時、地、物與原因"
    data["content"] = {"summary": "好的問題會讓對方知道你缺哪一格資訊，也讓回答容易對準。Who、What、When、Where、Which、Why、How 不只是文法標籤；要配合人物、物品、時間、地點、選擇、原因或方法，並在聽不清楚時使用禮貌的澄清句。本課以博物館導覽、河川步行、社團時間、排演教室、山路公車、影片繳交、運動中心、志工會議與濕地操場等原創情境，練習從已知答案反推正確問句，組合完整資訊需求，避免用模糊或重複問題浪費對話。", "sections": [{"heading": "疑問詞先對準缺少的欄位", "body": "Ms. Lin will lead the museum tour 缺少人物資訊時問 Who will lead the tour?；3:40 是時間，問 When does the club start?；Room 204 是地點，問 Where will the rehearsal be? 先找答案類型，再選疑問詞，不能只看句子裡最熟的名詞。"}, {"heading": "Which 和 What 用在不同任務", "body": "當有兩輛公車且只有綠色車到運動中心，Which bus goes to the sports center? 能在有限選項中做選擇；What is the method for submitting the video? 則詢問方法或內容。問題要反映回答空間，選項存在時需要選擇詞，否則可用 what。"}, {"heading": "Why 和 How 問的是關係與方法", "body": "Because the field is wet 對應 Why is the game moved?，回答原因；影片繳交方式則問 How should we submit the video?，回答步驟或管道。把 why 當 where、把 how 當 what 會讓對話即使文法正確也無法取得需要的資訊。"}, {"heading": "禮貌重述讓溝通不斷線", "body": "沒有聽到時間時可問 Could you repeat the meeting time, please?，而不是只說 What?；若要一次取得志工會議的人、時、地，先列三個缺口，再組成 Who will attend, When is it, and Where will it be?。清楚、有禮貌且不重複的問題能降低對方負擔。"}]}
    data["studyHighlights"] = ["依缺少的人、事、時、地、物、選擇、原因或方法選疑問詞。", "區分有限選項的 Which 與開放資訊的 What。", "用 Why 問原因、How 問方法，保留答案的關係。", "以禮貌重述與多欄問題組合修補不完整資訊。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "問錯一個字，回答會去哪裡？", "body": "展示完全自編的志工公告，只遮住人物、時間或地點其中一欄，學生各自寫問題。交換後讓同伴依問題隨機回答，若問題問 When 卻回答地點，學生立刻看見疑問詞必須對準缺口，而不是只求句子看起來完整。"}, {"id": "explain", "phase": "explain", "heading": "資訊缺口七欄卡", "body": "建立 Person、Thing、Time、Place、Choice、Reason、Method 七欄，再加上 Polite repair。先把已知句子拆成欄位，圈出未知欄，選疑問詞，最後檢查句子是否包含主詞、助動詞與必要的場所或活動，避免漏掉真正要問的對象。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從答案反推問題功能", "body": "給出 Because the field is wet、In Room 204、At 3:40、By uploading it to the class folder 四個答案，學生分別反推 Why、Where、When、How 問句。比較 What 和 How 的回答差異，讓學生以答案類型驗證問題，而不是只靠背誦疑問詞表。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "把三個缺口組成一次有效詢問", "body": "給志工會議只知道活動名稱的卡片，學生要設計 person、time、place 三個問題，並用 and 組成一組自然詢問。交換後同伴只回答問句涵蓋的欄位，若仍缺少人、時或地，作者必須補問而不是假設答案。"}, {"id": "transfer", "phase": "transfer", "heading": "在不同場合調整問題長度與禮貌", "body": "輪換博物館導覽、社團、交通、影片、運動中心與濕地操場情境。學生先寫快速筆記版，再改成對老師、同學、陌生工作人員適用的句子，保留疑問焦點並加上 Could you …? 或 please；問題太寬或重複時，重新縮小缺口。"}, {"id": "reflect", "phase": "reflect", "heading": "我的問題真的能得到需要的答案嗎？", "body": "回看問句，標記疑問詞、助動詞、主題、活動與缺口欄位。若回答者必須反問你在問哪個時間、哪個地點或哪種方法，修正範圍；若問題已知資訊重複，刪掉多餘片語，讓對話更有效。"}], "summary": ["以七個資訊缺口欄位選擇疑問詞與句型。", "從答案類型反推 Why、Where、When 和 How 的功能。", "用 Which 處理有限選項，用 What 處理開放資訊。", "以禮貌重述和多問題組合修補不完整訊息。"], "exitCheck": [{"prompt": "如何從已知答案選擇疑問詞？", "expectedEvidence": "能將答案分類為人物、物品、時間、地點、選擇、原因或方法，再選相符疑問詞。"}, {"prompt": "Which 和 What 的資訊範圍有何不同？", "expectedEvidence": "能指出 Which 通常在有限選項中選擇，What 用於開放詢問事物或內容。"}, {"prompt": "聽不清楚時間時如何禮貌修補？", "expectedEvidence": "能用 Could you repeat the meeting time, please? 等句型，明確標出需要重述的欄位。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "依資訊缺口選擇疑問詞與禮貌句型，提出能取得人、事、時、地、物、原因或方法的有效問題。", "scenario": "學生擔任活動資訊台，要從公告中的已知線索設計問題，補齊導覽、交通、影片與志工會議的缺少資訊。", "variables": [{"symbol": "g", "meaning": "人物、物品、時間、地點、選擇、原因與方法缺口"}, {"symbol": "q", "meaning": "疑問詞、助動詞與問題範圍"}, {"symbol": "r", "meaning": "答案類型、禮貌修補與多欄詢問"}], "steps": [{"id": "step-1", "prompt": "The note says, 'Ms. Lin will lead the museum tour.' Which question asks about the person?", "options": ["Who will lead the museum tour?", "When will the museum tour begin?", "Where is the museum tour?"], "answer": "A", "feedback": "Who asks for the person; when and where would request different missing information."}, {"id": "step-2", "prompt": "The bus leaves earlier because the mountain road may close. Which question asks for the reason?", "options": ["Why does the bus leave earlier?", "Where does the bus leave from?", "Which bus is green?"], "answer": "A", "feedback": "Why matches the cause introduced by because; the other questions ask for place or a choice."}, {"id": "step-3", "prompt": "You did not hear the meeting time. Which question politely asks for repetition?", "options": ["Could you repeat the meeting time, please?", "Who is the meeting time?", "Why is the meeting time in Room 204?"], "answer": "A", "feedback": "A identifies the missing time and asks for repetition politely instead of guessing or asking an unrelated question."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語疑問詞、生活提問與溝通修補定位；核讀 2026-09-21。", ["在生活情境中使用疑問詞詢問人事時地物與原因。", "以對話、角色和澄清支持英語互動。"], ["who、what、when、where、which、why、how 與 repeat。"], "只背疑問詞，沒有先判斷答案類型或問題缺口。", "重視生活提問、聽說互動與功能性回應。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語聽說、角色任務與情境提問定位；核讀 2026-09-21。", ["透過角色、公告與任務設計有效問題。", "依選項、順序、時間地點和需要完成澄清。"], ["導覽、步行、社團、排演、交通、影片與會議。"], "把 What、Which、Why、How 互換，讓回答無法對準需要。", "評量主要訊息、疑問詞、禮貌與資訊修補。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語問題功能、疑問詞與情境評量定位；核讀 2026-09-21。", ["從答案類型、語境和對話目的選擇問題形式。", "以完整句型組合多個資訊缺口並維持禮貌。"], ["person、thing、time、place、choice、reason、method、repair。"], "問題文法看似正確，卻重複已知資訊或缺少真正需要的欄位。", "評量問題功能、資訊定位、因果、方法與互動延續。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持疑問詞、生活提問、角色互動與溝通修補。", "有效問題需將答案類型、資訊缺口、句型、禮貌與對話目的連結。", "從答案反推問題到多欄詢問可用公告卡、角色任務與同伴只能回答指定欄位驗證。"], "versionDifferences": ["南一較突顯生活疑問詞與澄清；康軒較突顯公告、角色、任務與時地資訊；翰林較突顯問題功能、答案類型、多欄組合與互動評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Person、Thing、Time、Place、Choice、Reason、Method 加 Polite repair 拆解問題。", "用導覽、交通、社團、影片、志工會議與濕地操場原創情境反推問句。", "以回答者只能填指定欄位檢查問題是否精準且不重複。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織疑問詞、答案類型、資訊缺口、選項、原因、方法、禮貌修補與多欄詢問。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 七欄完成後請把每個問句與預期答案卡配對；若一個問題能接受太多不同類型答案，縮小活動、對象或時間範圍，讓缺口變得可操作。"
    data["teaching"]["body"][4]["body"] += " 改換聽者時只調整禮貌與必要背景，不改疑問詞的核心功能；對陌生人要清楚說明活動，對同學則可省略雙方已知的內容。"
    data["teaching"]["body"][5]["body"] += " 若答案仍不精準，先檢查是否問到已知資訊，再查助動詞和疑問詞是否一致；不要用更長的句子掩蓋問題焦點不明。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "2-Ⅳ-7：用疑問詞與禮貌句型詢問人、事、時、地、物與原因", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 2-iv-7")


if __name__ == "__main__":
    main()
