import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-performance-an-iv-3.json"; REPORT=ROOT/"implementation/reports/science-performance-an-iv-3-first-pass-review.json"
URLS={"nani":"https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf","kanghsuan":"https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110","hanlin":"https://drive.google.com/uc?id=1gMUVcDjfXmqIapg-fNnfPuLFaK98dxGX&export=download"}
def rec(p,c,r,m,a): return {"publisher":p,"edition":f"{p} 公立校方自然課程計畫章節級證據","sourceType":"public-web","sourceLocator":f"{URLS[p]}；科學家、合作、證據與評量欄位；核讀 2026-09-21。","reviewedAt":"2026-09-21","findings":{"concepts":[c,"公開課程結構支持理解科學工作的多元背景、共同探究規範、合作分工與證據檢核。"],"representations":[r],"examplesOrEvidence":["本課的珊瑚觀測、城市熱島與實驗室合作皆為原創情境，只承接公開課程所示的能力方向。"],"misconceptions":[m],"assessmentEmphasis":[a]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。"}
def main():
 d=json.loads(LESSON.read_text(encoding="utf-8")); assert d["id"]=="lesson-science-performance-an-iv-3" and d["reviewStatus"]=="draft"
 d["title"]="an-Ⅳ-3：科學家的多元背景與共同科學特質——看見差異，也檢查方法"
 d["content"]={"summary":"科學家可能來自不同地區、家庭、語言、學科和人生經驗；這些差異能帶來不同問題、觀察角度與工具，但不會自動保證某個結論正確。共同的科學特質是願意提出可檢查問題、公開方法與資料、接受同儕質疑、依證據修正，並對研究對象與社群負責。本課用珊瑚觀測、城市熱島與跨實驗室合作的原創情境，區分人物背景、工作分工、證據品質與刻板印象。","sections":[{"heading":"背景影響問題入口，不決定答案","body":"住在海邊的人可能先注意潮間帶變化，熟悉城市交通的人可能先問熱島與空氣；這些經驗能帶來研究問題，但最後仍要靠方法和資料檢查。不能把族群、性別或職業直接當成能力或結論。"},{"heading":"共同特質是可檢查的工作方式","body":"提出問題、定義變因、記錄方法、分享資料、重複檢驗、回應質疑與修正解釋，是跨背景研究者可以共同遵守的規範。勇氣或天才形象不能取代可追溯證據。"},{"heading":"合作不是把責任平均分掉","body":"田野觀察、儀器校正、資料分析、社群溝通可能由不同人負責；每項工作都要標註方法、限制和貢獻。若結果不一致，先比較定義、樣本和程序，再協調下一次測量。"},{"heading":"尊重人與環境也是科學品質","body":"研究可能影響居民、病患、原住民族知識或生物棲地。取得同意、保護資料、降低干擾、回饋結果和承認知識來源，不只是禮貌，也是讓證據可信、可持續的條件。"}]}
 d["studyHighlights"]=["分辨背景帶來問題視角與證據支持之間的差異。","辨識跨背景研究者共同遵守的提問、紀錄、檢驗與修正規範。","理解合作分工、貢獻標註、資料衝突與同儕檢核。","把倫理、社群責任、環境保護納入科學工作品質。"]
 d["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"誰會先看見這個問題？","body":"三位研究者觀察同一片珊瑚礁：在地居民注意潮汐與魚群，影像分析者注意顏色變化，海洋生物學者注意物種。請先寫出每人的問題入口，再檢查哪一些觀察能用共同方法測量；背景可以帶來線索，不能直接替代證據。"},{"id":"explain","phase":"explain","heading":"人物故事的兩層閱讀","body":"讀科學人物時分成兩層：第一層看其生活、文化、訓練與合作如何影響問題；第二層看定義、資料、方法、重複與質疑如何支持結論。不要用英雄或天才標籤跳過第二層，也不要因背景不同就否定能力。"},{"id":"worked-example","phase":"worked-example","heading":"熱島研究的跨角色合作","body":"居民提供熱感受與地點線索，測量組固定時段校正感測器，分析組比較地表材質，溝通組回饋限制。若三組結果不合，先對照時間、位置、單位和取樣，再安排共同測量；不能以職稱或投票決定真相。"},{"id":"guided-practice","phase":"guided-practice","heading":"把刻板印象改成研究問題","body":"面對『某類人天生比較會做科學』的說法，學習者先指出它沒有定義能力和證據，再改寫為『不同教學資源如何影響學生使用測量程序的表現』，並規畫公平取樣、匿名資料與限制。"},{"id":"transfer","phase":"transfer","heading":"建立貢獻與證據地圖","body":"小組選一個環境議題，標出誰提出問題、誰蒐集資料、誰校正工具、誰分析、誰回饋社群；每條箭頭都附方法和可檢查產出。交換後找出被隱形的貢獻，以及可能造成傷害的研究步驟。"},{"id":"reflect","phase":"reflect","heading":"修正兩個人物迷思","body":"請修正『科學家都是孤獨天才』與『背景不同就不能共同使用科學方法』，並各舉一個合作研究例子說明。科學常由多角色合作完成；背景差異能擴大問題視角，共同標準則讓不同主張可以被比較、質疑和修正，也讓貢獻與責任更透明。"}],"summary":["背景能影響問題入口，但不能代替證據。","共同科學特質包含提問、紀錄、檢驗、公開與修正。","合作要標註分工、資料、限制與被忽略的貢獻。","倫理與社群責任是可信研究的一部分。"],"exitCheck":[{"prompt":"為什麼研究者背景不能直接決定答案？","expectedEvidence":"背景可能影響注意到的問題和視角，但答案仍需依公開方法、資料、重複和質疑檢查。"},{"prompt":"跨實驗室結果不同時先比較什麼？","expectedEvidence":"比較定義、樣本、時間、工具校正、單位與程序，再安排共同測量。"},{"prompt":"研究倫理為何也是科學品質？","expectedEvidence":"同意、資料保護、降低干擾與回饋能減少傷害、提高可信度並維持長期合作。"}]}
 d["interactive"]={"type":"guided-choice","goal":"從科學家背景、合作分工與共同方法中辨識證據、偏見和責任。","scenario":"分析珊瑚觀測、城市熱島與跨實驗室合作，逐步從人物故事回到可檢查方法。","variables":[{"symbol":"b","meaning":"背景與視角"},{"symbol":"c","meaning":"合作貢獻"},{"symbol":"e","meaning":"證據與倫理"}],"steps":[{"id":"step-1","prompt":"研究者背景最合理的作用是什麼？","options":["提供不同問題入口與觀察視角，再用共同方法檢查主張","直接決定誰的答案正確","用族群標籤取代測量"],"answer":"A","feedback":"背景能擴大問題視角，但證據仍須透過可檢查方法建立。"},{"id":"step-2","prompt":"跨團隊結果不一致時應如何處理？","options":["比較定義、樣本、時間、校正與程序，再共同重測","依職稱高低投票","刪除不合期待的資料"],"answer":"A","feedback":"方法對照和重測比權威或刪資料更能找出差異來源。"},{"id":"step-3","prompt":"哪項最完整地表現負責任的科學合作？","options":["標註貢獻、公開限制、取得同意並回饋受影響社群","只列最有名的人為作者","為了成果隱藏不利資料"],"answer":"A","feedback":"貢獻透明、證據誠實與社群責任共同構成可信研究。"}]}
 d["authoringStandard"]="version-fused-v1"
 d["versionResearch"]=[rec("nani","以科學家工作、探究合作與證據規範理解多元背景和共同特質。","問題入口、方法、資料、合作、質疑與修正。","把英雄形象、族群標籤或職稱當成證據。","重視人物脈絡、方法透明與證據責任。"),rec("kanghsuan","透過實作、討論與資料共享看見科學工作的分工和共同標準。","跨角色合作、貢獻、同儕檢核、重做與倫理。","把合作當成平均分工，忽略資料責任和被隱形的貢獻。","評量合作方法、證據檢查與責任溝通。"),rec("hanlin","連結環境、社群與生活議題，理解不同背景能拓展問題而需共同方法檢驗。","珊瑚、熱島、社群知識、資料保護與環境干擾。","因背景不同就否定共同標準，或忽略研究對象權益。","要求尊重多元、證據透明、安全與社群回饋。")]
 d["fusionRecord"]={"commonCore":["三版本公開結構共同支持理解科學家多元背景、共同探究規範與合作。","問題、方法、資料、同儕檢核、修正與責任是共同要求。","背景差異能提供視角，但不能取代證據或造成刻板推論。"],"versionDifferences":["南一證據較突顯科學家工作與基本探究特質；康軒較突顯實作、合作、資料共享與同儕檢核；翰林較突顯環境、社群、多元知識與責任。這是公開課程計畫層級差異，不宣稱完整教材差異。"],"originalAdditions":["以珊瑚礁多角色觀察區分背景視角與證據。","以城市熱島跨角色合作示範分工、校正、分析與回饋。","以刻板印象改寫和研究倫理練習公平取樣與資料責任。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織多元背景、共同科學特質、合作分工、證據檢核、刻板印象、倫理與社群責任。正文、原創情境、互動步驟、錯誤回饋與檢核均為本專案重寫，未複製任何教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
 d["updatedAt"]="2026-09-21"; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"an-Ⅳ-3：科學家的多元背景與共同科學特質","lessonId":d["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 print("an-iv-3 lesson authored")
if __name__=="__main__": main()
