import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-8.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-8-first-pass-review.json"


def refs():
    common = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "message, letter, email, notice, sequence, and purpose"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "short text details, audience, deadline, and action"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "daily written messages, sequence, solution, and inference"),
    ]
    return [{"url": u, "title": f"{t}；僅取短文／書信／訊息的理解能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以短文、書信、電子郵件、通知與便條測量讀者、目的、細節、期限、順序、替代方案與推論；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in common]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-3-iv-8"
    data["title"] = "3-Ⅳ-8：從短文、書信與訊息抓住目的、細節與行動"
    data["content"] = {"summary": "短文訊息的理解要先辨認文本是給誰、為了什麼、要求什麼行動，再依日期、地點、人物、順序、原因與限制回到原句找證據。本課比較簡訊、書信、電子郵件、便條、提醒與公告，以訓練主要內容、讀者、期限、步驟、替代方案、感謝語氣與跨句推論，並把讀到的資訊整理成能直接執行的行動清單。", "sections": [{"heading": "先辨認文本任務", "body": "practice moved、Dear Grandma、Please reply、Bring a hat 與 Use the paper form 分別在告知變更、辨認收信人、要求回覆、提醒準備與提供替代方案。先標文本類型、讀者與目的，再讀細節，避免把任何日期都當成答案。"}, {"heading": "主要內容要保留核心變化", "body": "一則通知若說場地維修所以改到星期五，主旨要同時保留變更與原因；只答星期五漏掉事件，只答維修又漏掉行動。摘要應短，但不能刪掉使讀者採取正確行動的關鍵。"}, {"heading": "細節與順序回到原文定位", "body": "register、print、show 是三個步驟；deadline、place、date 是不同欄位。先圈 first／then／finally、by、on、in 等線索，再依問題只取所需欄位，不用常識替換文本內容。"}, {"heading": "推論要連結不只一句", "body": "校園花園保存雨水、提供香草並吸引昆蟲，讀者可以推得它兼具資源與生態功能，但不能推成一定能供應全校。遇到替代方案與安全提醒，也要分清明示指示和自己添加的猜測。"}]}
    data["studyHighlights"] = ["先辨認文本類型、讀者、目的與需要採取的行動。", "用標題、稱呼、期限、日期、地點、順序詞和連接詞定位證據。", "摘要保留核心變化與原因，細節題只回答被問的欄位。", "跨句推論要有兩個以上可回指線索，沒有證據就不擴大結論。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "看到日期就能知道要做什麼嗎？", "body": "比較三則原創文字：Friday 的場地變更、Tuesday 前回覆的博物館邀請、Saturday 戶外課準備。學生先圈日期再寫行動，接著回查文本目的，發現日期只有放回任務中才有意義。"}, {"id": "explain", "phase": "explain", "heading": "短文六欄閱讀卡", "body": "建立 Genre、Audience、Purpose、Key detail、Sequence／limit、Action 六欄。先判斷是訊息、書信、郵件或通知，再依讀者需要整理資訊，最後把原文要求轉成可執行動作。"}, {"id": "worked-example", "phase": "worked-example", "heading": "把三步提醒轉成清單", "body": "以 register online、print the ticket、show it at the gate 示範：先標三個動詞，再確認順序與 it 的回指，最後寫成 1—2—3 清單。若只回答 print，說明漏掉前後限制。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一篇短文換不同讀者問題", "body": "用書信、社團郵件、花園說明與表單公告，輪流回答 who／why／when／where／what next。每次先在原文畫證據，再把答案改寫成一個動詞開頭的行動或一句受控摘要。"}, {"id": "transfer", "phase": "transfer", "heading": "從閱讀到行動版摘要", "body": "把教練郵件轉成隊員行前清單，再把表單故障通知改成櫃檯指示。學生交換清單，檢查日期、地點、物品、期限與替代方案是否足夠，不得加入原文沒有的規則。"}, {"id": "reflect", "phase": "reflect", "heading": "我漏了哪一種資訊？", "body": "回看答案，標記讀者錯、目的錯、期限／地點錯、順序錯、指代錯或推論過度。修訂時回到原句並說明刪掉或補回哪一項，讓每個行動都可追溯。"}], "summary": ["以 Genre、Audience、Purpose、Key detail、Sequence／limit、Action 六欄讀短文。", "把文本目的與讀者需求連起來，再定位日期、地點、期限與步驟。", "用行動清單保留順序、替代方案與安全限制。", "跨句推論要回指證據，不能把合理想像當成文章明示內容。"], "exitCheck": [{"prompt": "短文摘要為什麼不能只抄日期或地點？", "expectedEvidence": "能說明摘要必須保留文本目的、核心事件與讀者要採取的行動。"}, {"prompt": "如何由提醒中的 first／then／finally 建立正確清單？", "expectedEvidence": "能依序擷取三個動作，並說明代名詞或期限所限制的對象。"}, {"prompt": "如何判斷跨句推論沒有超出文章？", "expectedEvidence": "能指出至少兩個原文線索，並把沒有被支持的更大結論改成保留範圍的描述。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "從短文、書信、郵件與通知辨認讀者、目的、細節、順序與下一步，產出可追溯的行動摘要。", "scenario": "學生擔任校園資訊編輯，要把文字訊息整理成不同讀者都能照做的行動卡。", "variables": [{"symbol": "g", "meaning": "文本類型、讀者與目的"}, {"symbol": "d", "meaning": "日期、地點、期限、人物與關鍵細節"}, {"symbol": "a", "meaning": "順序、替代方案、安全限制與下一步"}], "steps": [{"id": "step-1", "prompt": "Practice is moved to Friday because the gym is being repaired. What is the main message?", "options": ["Practice changes to Friday because the gym needs repair.", "The gym is open every Friday.", "Students should stop practicing forever."], "answer": "A", "feedback": "A 同時保留變更與原因，符合通知的主要內容。"}, {"id": "step-2", "prompt": "First register online, then print the ticket, and finally show it at the gate. What comes second?", "options": ["Print the ticket.", "Show the ticket at the gate.", "Register after entering."], "answer": "A", "feedback": "依 first／then／finally 定位第二步，不能用最後一步取代。"}, {"id": "step-3", "prompt": "The online form is unavailable. What should people do instead?", "options": ["Use the paper form at the front desk.", "Wait at home without contacting anyone.", "Delete the event."], "answer": "A", "feedback": "instead 後的 paper form 是公告明示的替代方案。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；生活短文、書信與主要訊息定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由簡短文字理解主要訊息、細節與行動。", "以人物、日期、地點與順序整理文本。"], "representations": ["簡訊、書信、通知、便條與行動清單。"], "examplesOrEvidence": ["本課以場地變更、博物館、戶外課與表單公告原創資料承接公開結構。"], "misconceptions": ["只抓日期，沒有辨認文本目的與讀者。"], "assessmentEmphasis": ["重視短文主要內容、細節與生活應用。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖像、生活文本與步驟任務定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["透過短文、圖像提示與任務整合資訊。", "依期限、順序、替代方案與目的完成行動。"], "representations": ["郵件、提醒、表單、票券、校園活動與步驟。"], "examplesOrEvidence": ["本課以六欄閱讀卡與行動清單重新設計任務。"], "misconceptions": ["把第一個看到的動詞或日期當成完整答案。"], "assessmentEmphasis": ["評量資訊定位、順序與功能性回應。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；溝通文本、推論與書面理解定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["從文本類型、讀者與上下文形成理解。", "以主要內容、跨句線索、限制與替代方案表達結論。"], "representations": ["genre、audience、purpose、detail、sequence、inference、action。"], "examplesOrEvidence": ["本課將書信、郵件、公告與校園說明改寫成可驗證行動。"], "misconceptions": ["以常識擴大文章沒有明說的結果。"], "assessmentEmphasis": ["評量文本主旨、細節、順序、推論與行動。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持簡短書面文本、生活訊息與主要內容理解。", "可靠閱讀需整合文本類型、讀者、目的、細節、順序、限制與下一步。", "可用六欄閱讀卡、證據回指、行動清單與跨句推論完成遷移。"], "versionDifferences": ["南一較突顯生活短文與主要訊息；康軒較突顯圖像、步驟與任務；翰林較突顯文本類型、讀者、推論與行動界線。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Genre、Audience、Purpose、Key detail、Sequence／limit、Action 六欄讀短文。", "用場地變更、書信、博物館、戶外課、票券、花園與表單原創資料練習摘要與細節。", "以行動卡交換檢查日期、期限、替代方案與推論範圍。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織短文、書信、郵件與通知的目的、細節、順序、替代方案與推論界線。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    steps = [["先辨認文本類型與讀者，再找題目要求的目的或行動。", "圈出能支持答案的日期、地點、期限或連接詞。", "組合完整訊息，確認沒有只取單一細節。", "排除改變文本範圍或新增未提供條件的選項。", "把答案改寫成讀者可執行的句子，回查原文證據。"] for _ in range(10)]
    explanations = ["主旨需同時保留變更與原因。", "稱呼 Dear Grandma 直接指出收信人。", "reply by Tuesday 是收信者必須完成的行動與期限。", "帽子、水與相機是戶外課要帶的物品。", "三個順序詞明確建立登記、列印、入場出示的流程。", "Thank you 與 careful work 表達感謝及具體貢獻。", "May 6 與 language lab 是正確日期和地點。", "instead 後的紙本表單是明示替代方案。", "保存雨水、提供香草、吸引昆蟲共同支持資源與生態功能。", "郵件同時提供比賽時間、地點、準備要求與天氣資訊。"]
    paths = sorted(ROOT.glob("questions/english/question-english-performance-3-iv-8-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for i, p in enumerate(paths):
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["answer"]["explanation"] = explanations[i] + f" 正確答案：{q['answer']['value']}"; q["solutionStrategy"] = "先辨認文本類型、讀者與目的，再依題目分類定位細節，最後回查行動與限制。"; q["solutionSteps"] = steps[i]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的短文、書信、郵件、通知與便條理解模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-8")


if __name__ == "__main__":
    main()
