import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-4-iv-5.json"
REPORT = ROOT / "implementation/reports/english-performance-4-iv-5-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "sentence ordering, tense, negation, questions, modals, and connectors"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "prompted sentence, subject-verb agreement, time, place, and purpose"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "simple sentence writing, clause order, because, if, and there is/are"),
    ]
    return [{"url": u, "title": f"{t}；僅取提示組句、時態、否定、疑問與連接詞表達能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以提示字詞、時間線、主詞、句型功能與連接詞要求學生組成正確簡單句；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-4-iv-5"
    data["title"] = "4-Ⅳ-5：從提示、時間與句型功能組成正確簡單句"
    data["content"] = {"summary": "提示寫句不是把單字依出現順序串起來，而是先判斷主詞、動詞、時間、否定、疑問、情態、存在句與條件／原因關係，再安排英文語序。本課以每日閱讀、放學運動、星期日不上課、正在睡覺、昨日拜訪、工作地點、能力、下雨原因、桌上物品與提早完成的條件等原創情境，練習從提示詞組成有主詞、有動詞且語意完整的句子。", "sections": [{"heading": "先找句子骨架", "body": "Mia／read／novel／every night 要先組主詞 Mia、動詞 reads、受詞 a novel，再把時間放到句尾；提示詞不是固定排列，主詞數量與時間線會影響動詞形式。"}, {"heading": "否定、疑問和情態有自己的位置", "body": "not 需要放在適合的助動詞或 be 動詞後；Where does your brother work? 要將疑問詞、助動詞、主詞與原形動詞排好；can 後接原形。先辨認句型功能，再排字。"}, {"heading": "時間線改變動詞", "body": "every night 是習慣，now 是正在發生，yesterday 是過去；同一個動作提示在不同時間要變成 reads、is sleeping 或 visited。句子完成後要回翻時間意義。"}, {"heading": "連接詞保留兩個子句關係", "body": "because 說明原因，if 建立條件；There are three books 則表達存在和數量。連接詞不能只放在句中好看，要檢查前後子句、主詞、動詞和標點是否完整。"}]}
    data["studyHighlights"] = ["先找主詞、動詞、受詞／補語，再加入時間、地點與連接詞。", "依主詞數量與時間線變化動詞，檢查否定、疑問、情態與 there is／are。", "把 because、if 放回兩個完整語意關係，不用提示順序猜句子。", "完成後朗讀並回翻，確認語序、句型功能與原提示都保留。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "提示詞排好就一定是句子嗎？", "body": "給學生四組原創提示：Mia／read／novel／every night、now／cat／sleep、where／brother／work、if／finish／help。學生先排字，再標主詞、時間與句型功能，發現不同任務需要不同骨架。"}, {"id": "explain", "phase": "explain", "heading": "骨架—時間—功能三欄卡", "body": "建立 Sentence frame、Time／condition、Function 三欄。先判斷陳述、否定、疑問、能力、原因、條件或存在句，再依主詞與時間填入動詞和連接詞。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從提示完成因果句", "body": "以 I stayed home／because／it rained 示範：先完成主要句 I stayed home，再將完整原因 it rained 接上 because；兩個子句都要有主詞和動詞，不能只堆名詞。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一動作換時間與功能", "body": "輪換閱讀、打球、睡覺、拜訪、工作、游泳、留在家與幫忙八組提示，學生分別組成習慣、進行式、過去式、疑問、情態、原因或條件句，同伴標出骨架證據。"}, {"id": "transfer", "phase": "transfer", "heading": "把圖表或筆記變成句子", "body": "學生從日程表與天氣筆記挑兩組提示，寫一個陳述句和一個 because／if 句。交換後檢查時間、主詞、動詞、連接詞與標點，不能添加提示外的事件。"}, {"id": "reflect", "phase": "reflect", "heading": "錯在語序還是句型？", "body": "回看答案，標記主詞動詞不一致、時間錯、助動詞位置錯、原形錯、否定漏失、子句不完整或 there is／are 混用。修訂時畫句子骨架，再朗讀驗證。"}], "summary": ["用 Sentence frame、Time／condition、Function 三欄組織提示詞。", "先判斷句型任務，再安排主詞、動詞、受詞、助動詞和連接詞。", "依時間線和主詞數量調整動詞，保留否定、疑問、情態與存在關係。", "以朗讀、回翻和句骨架檢查提示是否完整保留。"], "exitCheck": [{"prompt": "提示寫句為什麼不能直接照提示順序排列？", "expectedEvidence": "能說明英文句子要依主詞、動詞、受詞與句型功能安排，並以提示例子示範。"}, {"prompt": "時間詞和主詞會改變哪些句子部分？", "expectedEvidence": "能比較習慣、現在進行、過去或複數情境中的動詞形式。"}, {"prompt": "because 或 if 句如何確認兩邊完整？", "expectedEvidence": "能指出每個子句的主詞與動詞，說明原因或條件關係沒有被截斷。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "依提示、主詞、時間與句型功能組成正確、完整且語意一致的英文簡單句。", "scenario": "學生擔任句子編輯，要把課堂筆記、日程、天氣與條件提示改寫成可讀的英文句子。", "variables": [{"symbol": "f", "meaning": "Sentence frame 與句型功能"}, {"symbol": "t", "meaning": "時間、條件與主詞數量"}, {"symbol": "c", "meaning": "否定、疑問、情態、because、if 與 there is/are"}], "steps": [{"id": "step-1", "prompt": "Mia / read / a novel / every night. Which sentence is correct?", "options": ["Mia reads a novel every night.", "Mia read a novel every night.", "Reads Mia novel a every night."], "answer": "A", "feedback": "單數主詞 Mia 在習慣句使用 reads，受詞與時間放在合適位置。"}, {"id": "step-2", "prompt": "Where / your brother / work? Which question is correctly formed?", "options": ["Where does your brother work?", "Where your brother does work?", "Does where work your brother?"], "answer": "A", "feedback": "疑問詞後接助動詞、主詞與原形動詞，語序完整。"}, {"id": "step-3", "prompt": "If / finish / early / I / help / my partner. Which sentence is correct?", "options": ["If I finish early, I will help my partner.", "If finish I early help my partner.", "I if will finish early partner help."], "answer": "A", "feedback": "if 子句和主要子句各有主詞動詞，並以條件關係連接。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；生活句型、書寫與主要訊息定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由提示與生活情境組成基本句子。", "以人物、時間、地點與行動表達主要訊息。"], "representations": ["閱讀、運動、家庭、天氣、課堂與日程句。"], "examplesOrEvidence": ["本課以閱讀、睡覺、拜訪與天氣原創提示承接公開結構。"], "misconceptions": ["照提示順序排列，不辨認句型骨架。"], "assessmentEmphasis": ["重視句型、時態與生活表達。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖文、任務與提示組句定位；核讀 2026-09-21。", "findings": {"concepts": ["透過圖文、提示與任務組成句子。", "依時間、主詞、否定、疑問與連接詞調整形式。"], "representations": ["提示字詞、日程、天氣、問句與條件。"], "examplesOrEvidence": ["本課以骨架—時間—功能卡重新設計組句活動。"], "misconceptions": ["漏掉助動詞、原形或連接子句。"], "assessmentEmphasis": ["評量句型正確、語序與語意。"], "misconceptions": ["漏掉助動詞、原形或連接子句。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；基本句型、時間、連接與書寫定位；核讀 2026-09-21。", "findings": {"concepts": ["從主詞、時間與句型功能組織句子。", "以否定、疑問、情態、because、if 與 there is/are 表達關係。"], "representations": ["sentence frame、tense、question、modal、connector、existence。"], "examplesOrEvidence": ["本課以提示編輯與朗讀回翻重新設計句型校對。"], "misconceptions": ["形式看似有字卻缺主詞、動詞或完整子句。"], "assessmentEmphasis": ["評量提示組句、句型功能與語意完整。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持提示組句、生活情境與基本句型。", "可靠句子需整合主詞、動詞、時間、功能、否定、疑問與連接關係。", "可用骨架卡、時間替換、句子朗讀與圖表筆記遷移完成應用。"], "versionDifferences": ["南一較突顯生活句型與主要訊息；康軒較突顯圖文、提示、任務與語序；翰林較突顯時間、句型功能、連接詞與句子完整。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Sentence frame、Time／condition、Function 三欄組織提示詞。", "用閱讀、運動、天氣、拜訪、工作、游泳、because 與 if 原創情境練習。", "以時間替換、句骨架和朗讀回翻檢查提示與語意。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織提示組句、主詞動詞、時態、否定、疑問、情態、存在句與連接詞。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-4-iv-5-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先判斷主詞、時間與句型功能，再組句骨架，最後檢查動詞形式、連接詞、標點與完整子句。"; q["solutionSteps"] = ["先讀提示，圈出主詞、主要動作、時間或條件。", "判斷是陳述、否定、疑問、情態、存在、原因或條件句。", "依句型安排主詞、助動詞、動詞、受詞、連接詞與標點。", "核對主詞數量、時間線、原形動詞與每個子句是否完整。", "朗讀並回翻成語意，確認所有提示保留且沒有增加不必要資訊。" ]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的提示組句、時態、否定、疑問、情態與連接詞模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 4-iv-5")


if __name__ == "__main__":
    main()
