import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/chinese/lesson-chinese-performance-5-iv-4.json"
REPORT=ROOT/"implementation/reports/chinese-performance-5-iv-4-first-pass-review.json"

def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher":name,"edition":f"{name} 公立校方國文課程計畫章節級證據","sourceType":"public-web","sourceLocator":locator,"reviewedAt":"2026-09-21","findings":{"concepts":concepts,"representations":forms,"examplesOrEvidence":["本課以原創說明文、圖表、地圖、年表與決策資料卡，承接公開課程的跨文本閱讀、資料判讀與問題解決方向。"],"misconceptions":[misconception],"assessmentEmphasis":[assessment]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}

def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-chinese-performance-5-iv-4"
    data["title"]="5-Ⅳ-4：整合文字、圖表與跨域知識完成有證據的解題"
    data["content"]={"summary":"跨域閱讀題不是把不同科目的名詞堆在一起，而是先辨認問題要比較、解釋、估算還是決策，再讓文字、圖表、地圖、年表與生活條件各自提供證據。本課以都市熱島、河川整治、校園減塑與校外教學路線等自編資料練習，建立『讀題—拆資料—統一單位—交叉核對—控制結論』的流程，並在資料矛盾或不足時明確保留限制。", "sections":[{"heading":"先拆題目要完成的任務","body":"把題目中的動詞圈出來：找出、比較、解釋、估算、評估或選擇。再列出答案必須包含的對象、時間、單位與條件；同一份資料可能支持不同任務，若沒有先界定問題，很容易把圖表最高值誤當成題目真正要找的答案。"},{"heading":"讓每種資料回到自己的功能","body":"文字通常交代概念與因果，表格提供精確數值，折線圖顯示變化，地圖呈現位置與距離，年表整理時間，生活情境則加入成本、風險或限制。讀跨域材料時先分別摘要，再核對它們是否談同一對象、同一時間與同一尺度，不要把不同欄位直接混算。"},{"heading":"證據要經過轉換才可比較","body":"讀圖後先確認座標、單位、基準年與樣本，再進行差值、比例或排序；把文字中的因果說法和圖表的相關變化分開。若要從晨讀與成績的同時上升推論效果，還要檢查其他差異，不能把關聯直接寫成唯一原因。"},{"heading":"答案要寫出範圍與限制","body":"完整解答不只給選項，還要指出使用了哪一列資料、哪個時間點或哪個條件。若兩份來源年份不同、記錄方法不同或資料不足，應說明可確定的部分與待查部分；跨域知識的價值在於更好地提問與核對，而不是讓結論看起來更大。"}]}
    data["studyHighlights"]=["先依動詞與條件拆解跨域問題。","分辨文字、圖表、地圖、年表與情境資料的功能。","統一對象、時間、單位與尺度後再比較或計算。","用證據範圍、替代解釋與資料限制控制答案。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"圖表最高點就是答案嗎？","body":"提供自編都市熱島短文與綠地比例折線圖，題目只問『哪區夜間降溫最明顯』。請學習者先圈題目動詞與比較對象，再在圖上標出需要的兩個數值；最後討論若只看最高溫、只讀文字或忽略時間點，會如何答錯，建立先拆任務的習慣。"},{"id":"explain","phase":"explain","heading":"跨域解題五格流程","body":"第一格寫任務與條件；第二格分別摘要文字、圖表、地圖或年表；第三格核對對象、時間、單位和尺度；第四格進行必要的排序、差值或因果檢查；第五格用資料位置與限制寫答案。每格都要留下可回讀的記號，讓計算和判斷不靠直覺跳步。"},{"id":"worked-example","phase":"worked-example","heading":"從斜率資料走到謹慎結論","body":"示範閱讀自編晨讀調查：先確認比較的是參加班與未參加班的平均成績，再寫出差值；接著列出教師、家庭支持與原本閱讀習慣等可能差異。結論可說兩組成績有關聯，但不能只靠這張表宣稱晨讀必然造成成績提升。"},{"id":"guided-practice","phase":"guided-practice","heading":"讓文字與圖表互相核對","body":"給出河川整治的兩篇短文、流量圖與年表，請學習者先各自寫出來源主張，再統一年份與測量指標。若結論不同，先找尺度、指標或時間差，不急著選一方為真；最後寫出哪些資料能支持、哪些仍需要補測。"},{"id":"transfer","phase":"transfer","heading":"把證據流程用在實際決策","body":"以校外教學路線卡為例，整合地圖、天氣、交通時刻與費用表。先設定安全、抵達時間與預算的優先順序，再淘汰不符條件的路線，對剩餘方案比較取捨；決策文字要寫出使用的資料和若天氣改變時的備案。"},{"id":"reflect","phase":"reflect","heading":"檢查我是否把跨域變成拼貼","body":"回看解答，將每一個結論旁標記它來自哪種資料、哪個單位與哪個時間。若一句話同時跳過圖表讀值、因果推論和價值判斷，拆成數句並標明推論；若資料不足，寫出下一個最有用的查證問題。"}],"summary":["以題目動詞與條件界定真正任務。","分別讀文字、圖表、地圖、年表與生活情境，再交叉核對。","統一對象、時間、單位與尺度後才計算或推論。","答案要附證據位置、替代解釋與資料限制。"],"exitCheck":[{"prompt":"跨域題為何要先圈出題目動詞？","expectedEvidence":"能說明比較、解釋、估算、評估與決策需要不同資料操作，並列出相應條件。"},{"prompt":"兩份資料結論不同時，第一個檢查方向是什麼？","expectedEvidence":"能比較對象、時間、指標、單位與尺度，先排除測量範圍不同，再判斷是否真的矛盾。"},{"prompt":"如何把跨域解題寫成有證據的答案？","expectedEvidence":"能指出資料位置與轉換步驟，區分觀察、推論、因果與價值選擇，並標示限制。"}]}
    data["interactive"]={"type":"guided-choice","goal":"整合文字、圖表與情境資料，完成可回溯、有限定的跨域解題。","scenario":"學生要為校外教學選路線，先從說明文與圖表抽取條件，再用地圖、天氣、交通與費用資料篩選方案，最後寫出證據和備案。","variables":[{"symbol":"t","meaning":"題目任務與條件"},{"symbol":"d","meaning":"資料對象、時間與單位"},{"symbol":"c","meaning":"比較、決策與限制"}],"steps":[{"id":"step-1","prompt":"面對結合說明文、表格與生活情境的跨域題，第一步應做什麼？","options":["圈出題目動詞、對象、時間、單位與限制，先確定要比較、解釋還是決策","先挑看起來數字最大的一欄","先用生活經驗猜答案，再回頭找支持句"],"answer":"A","feedback":"A 先界定任務與條件，避免把資料中最醒目的數字誤當成問題答案。"},{"id":"step-2","prompt":"調查顯示晨讀班平均成績較高，哪個結論最謹慎？","options":["兩組成績有關聯，但還要檢查原有閱讀習慣、教師與家庭等差異，不能直接證明晨讀造成提升","晨讀一定是唯一原因，其他因素都不必考慮","因為不是實驗，所以資料完全沒有價值"],"answer":"A","feedback":"A 同時使用調查資料並保留因果限制，避免把相關當成唯一原因。"},{"id":"step-3","prompt":"地圖、天氣、交通與費用表要用來選校外教學路線，哪套流程完整？","options":["先設定安全、時間與預算條件，淘汰不合者，再比較剩餘方案並準備天氣變化的備案","只選最便宜路線，不用看天氣與交通","只看地圖距離，其他資料和決策無關"],"answer":"A","feedback":"A 將不同資料放入同一決策條件，並把不確定性轉成備案。"}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；國語文跨文本閱讀、資料理解與表達定位；核讀 2026-09-21。",["整合文字、圖表與生活資料以理解跨域問題，並辨認題目要求的比較或解釋任務。","以閱讀策略支援分析、表達與問題解決。"],["說明文、圖表、地圖、年表、摘要與決策。"],"只讀文字或只抓圖表最大值，忽略任務條件。","重視資料轉換、證據範圍與整合表達。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；國語文閱讀、資訊判讀與文本形式定位；核讀 2026-09-21。",["透過比較、討論與跨文本策略理解資料。","依資料來源、測量尺度、時間範圍與閱讀目的修正解釋，避免直接混算。"],["熱島圖表、河川資料、歷史年表、公共議題與路線決策。"],"把不同年份、單位或尺度的資料直接混合。","要求步驟可重做、資料可核對、結論有界線。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；國文閱讀策略、跨域資料與評量定位；核讀 2026-09-21。",["從文字、圖表與情境資料形成跨域判斷。","區分觀察、推論、因果與決策價值。"],["圖表讀值、因果限制、單位換算、地圖、年表與方案比較。"],"把相關寫成因果，或把可行方案說成唯一正解。","評量資料整合、證據責任、問題解決與限制標示。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持跨文本閱讀、資料判讀、閱讀策略與問題解決。","文字、圖表、地圖、年表和情境資料要依功能分工並交叉核對。","答案需以資料轉換、證據範圍和限制支撐。"],"versionDifferences":["南一較突顯跨文本閱讀與表達；康軒較突顯比較、資訊判讀與策略調整；翰林較突顯跨域資料、因果界線與問題解決評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以跨域解題五格流程固定任務、資料與證據。","用河川與熱島資料練習統一時間、單位和尺度。","以路線選擇把閱讀證據轉成有備案的實際決策。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織跨文本閱讀、圖表地圖年表、資料轉換、因果限制與決策表達。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 每次從一種資料換到另一種資料時，都要記錄保留了哪個對象、時間與單位；若其中一項對不上，就先暫停比較並寫出需要補查的資料。"
    data["teaching"]["body"][4]["body"] += " 把方案的硬條件與可取捨條件分開，並在決策句後補一個資料改變時的備案，讓閱讀策略能承受真實情境的不確定性。"
    data["teaching"]["body"][5]["body"] += " 將每個答案中的『因此』『造成』『最好』圈出，分別檢查它是資料觀察、因果推論還是價值選擇，避免跨域名詞掩蓋推理跳躍。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"5-Ⅳ-4：整合文字、圖表與跨域知識完成有證據的解題","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored chinese performance 5-iv-4")

if __name__=="__main__": main()
