import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/science/lesson-science-performance-an-iv-1.json"
REPORT=ROOT/"implementation/reports/science-performance-an-iv-1-first-pass-review.json"
URLS={"nani":"https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf","kanghsuan":"https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110","hanlin":"https://drive.google.com/uc?id=1gMUVcDjfXmqIapg-fNnfPuLFaK98dxGX&export=download"}
def rec(p,c,r,m,a):
 return {"publisher":p,"edition":f"{p} 公立校方自然課程計畫章節級證據","sourceType":"public-web","sourceLocator":f"{URLS[p]}；觀察、測量、方法與評量欄位；核讀 2026-09-21。","reviewedAt":"2026-09-21","findings":{"concepts":[c,"公開課程結構支持以共同定義、測量程序、紀錄格式與可重複方法建立可比較的科學證據。"],"representations":[r],"examplesOrEvidence":["本課的紙橋承重、冷卻曲線與影子長度皆為原創情境，只承接公開課程所示的能力方向。"],"misconceptions":[m],"assessmentEmphasis":[a]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。"}
def main():
 d=json.loads(LESSON.read_text(encoding="utf-8")); assert d["id"]=="lesson-science-performance-an-iv-1" and d["reviewStatus"]=="draft"
 d["title"]="an-Ⅳ-1：科學觀察、測量與方法受共同標準規範——讓不同人量出可比較的證據"
 d["content"]={"summary":"同一個現象若由不同人用不同尺、不同起點或不同等待時間測量，數字可能無法直接比較。科學方法的共同標準不是把每個人變成機器，而是先說清楚觀察對象、操作型定義、單位、器材、步驟、紀錄與安全界線，讓別人能重做、檢查並指出限制。本課用紙橋承重、熱水冷卻與影子長度三個原創情境，練習把模糊描述改成可重複的測量方法。","sections":[{"heading":"觀察不是只用眼睛看","body":"觀察要說明看的是什麼、何時看、從哪個角度看，以及哪些現象算同一類。若只寫『紙橋很穩』，不同人可能用不同標準；改成承受多少克、持續幾秒，資料才有共同語言。"},{"heading":"測量結果要帶著單位和程序","body":"數字沒有單位就缺少意義，器材沒有量程與歸零檢查也可能造成系統誤差。固定讀值時刻、視線、起點與重複次數，能降低不必要差異，但不能保證完全沒有誤差。"},{"heading":"方法標準化不等於隱藏限制","body":"共同步驟讓資料可比較，也要記錄溫度、器材解析度、操作者與異常事件。若方法只適用於紙橋或某段時間，就應把結論限制在相同條件，不可擴大成所有情況。"},{"heading":"別人能重做才有檢查機會","body":"一份好紀錄包含材料、條件、順序、單位、原始值和改動理由。重做不是為了得到相同數字，而是檢查差異是否能由現象、方法或偶然波動解釋。"}]}
 d["studyHighlights"]=["用操作型定義把模糊觀察轉成可記錄現象。","統一器材、單位、起點、時間、視線與重複程序。","保留原始資料、異常與限制，區分系統與偶然差異。","讓另一位觀察者能依紀錄重做並檢查結論範圍。"]
 d["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"同一座紙橋為何有三個答案？","body":"三組同學測同一座紙橋：有人報告『很穩』，有人寫承重 420 克，有人把砝碼逐個加到橋塌才記錄。先比較三種紀錄缺少什麼，再共同訂出承重、失效、加重間隔與讀值時機的定義，體會共同標準是為了讓差異可追查。"},{"id":"explain","phase":"explain","heading":"方法共同標準五問","body":"每次觀察都問：對象如何定義？用什麼單位與器材？從哪個起點或角度讀值？何時停止與重複？哪些條件固定並如何記錄異常？五問能把『看起來差不多』變成別人可檢查的程序，也能在兩組結果不同時追溯差異究竟來自現象、器材還是操作方式。"},{"id":"worked-example","phase":"worked-example","heading":"冷卻曲線的程序卡","body":"研究熱水降溫時，固定水量、容器、起始溫度與放置位置，每隔兩分鐘讀取一次，視線與溫度計位置一致，記錄原始值和是否攪拌。若有人中途換杯或漏記，不能把數字補成漂亮曲線，應標註異常並限制比較。"},{"id":"guided-practice","phase":"guided-practice","heading":"影子長度的讀值爭議","body":"兩組量同一根旗桿影子，一組從桿底量到影尖，一組沿地面彎曲路徑量。學習者判斷哪個起點、方向、單位和時間要先統一，並設計拍照、重複量測與遮蔽物紀錄，避免把方法差異誤認成影子真的變化。"},{"id":"transfer","phase":"transfer","heading":"交換方法重做一次","body":"每人寫一張不含結果的程序卡，交給同學依卡操作紙橋或影子量測。操作者圈出無法判斷的詞語，作者補上定義、器材、單位、步驟與安全限制，再比較兩次資料哪些差異來自方法修正。"},{"id":"reflect","phase":"reflect","heading":"修正兩個測量迷思","body":"請修正『數字越精確就越科學』與『標準程序會消除所有誤差』，並用一次測量經驗說明。精確外觀不能取代正確定義與校正；標準化能提高可比較性，仍要報告解析度、環境、操作與抽樣限制，避免把方法的整齊誤當成證據的絕對可靠。"}],"summary":["把模糊觀察轉成操作型定義和可記錄結果。","統一單位、器材、起點、時間、視線與重複程序。","記錄原始資料、異常、解析度與限制，不補造漂亮數字。","用程序卡讓他人重做並檢查結論範圍。"],"exitCheck":[{"prompt":"為什麼『紙橋很穩』不是足夠的測量紀錄？","expectedEvidence":"缺少承重、失效定義、時間與單位；不同人可能用不同標準，無法直接比較。"},{"prompt":"冷卻測量要固定哪些程序？","expectedEvidence":"水量、容器、起始溫度、位置、讀值間隔、溫度計位置與是否攪拌，並記錄異常。"},{"prompt":"標準化能否消除所有誤差？","expectedEvidence":"不能；只能提高可比較性，仍要說明器材解析度、環境、操作與抽樣限制。"}]}
 d["interactive"]={"type":"guided-choice","goal":"把觀察與測量寫成可重做、可比較並誠實標示限制的方法。","scenario":"審查紙橋承重、熱水冷卻與影子長度的測量程序，逐步修正定義、單位、讀值和紀錄。","variables":[{"symbol":"o","meaning":"觀察對象"},{"symbol":"p","meaning":"程序標準"},{"symbol":"e","meaning":"誤差與限制"}],"steps":[{"id":"step-1","prompt":"哪項紀錄最可比較紙橋承重？","options":["固定加重間隔並以克記錄首次失效時的承重，註明橋型與時間","只寫紙橋很穩","挑出最漂亮的一次結果"],"answer":"A","feedback":"A 把現象、單位、停止條件與情境寫清楚，別人才能重做。"},{"id":"step-2","prompt":"量冷卻曲線時應優先統一什麼？","options":["水量、容器、起始溫度、讀值間隔、溫度計位置與視線","只統一最後的平均值","每次想量就量並刪掉不同數字"],"answer":"A","feedback":"A 讓時間序列與測量條件可比較，不能用事後平均掩蓋程序差異。"},{"id":"step-3","prompt":"發現器材解析度不足時應怎麼做？","options":["保留原始值並標註解析度與限制，必要時改用合適器材或縮小結論","把數字寫到更多小數位","補填看起來合理的讀值"],"answer":"A","feedback":"A 誠實呈現證據能力與限制；多寫小數或捏造資料不會增加準確度。"}]}
 d["authoringStandard"]="version-fused-v1"
 d["versionResearch"]=[rec("nani","以觀察、測量、紀錄和共同方法建立可比較的科學證據。","操作型定義、單位、器材、程序、重複與安全。","把印象、無單位數字或事後挑選資料當成測量。","重視定義、程序透明、原始紀錄與結論限制。"),rec("kanghsuan","透過實作、討論和重做檢查方法是否一致且可行。","程序卡、同儕重做、異常、誤差與資料比較。","以精確外觀代替校正，或把方法差異當成現象差異。","評量方法設計、資料品質、重複與修正。"),rec("hanlin","連結生活測量與科學探究，要求證據可追溯並說明限制。","紙橋、冷卻、影子、尺度、解析度、環境與安全。","認為標準化能消除所有誤差，忽略器材和情境界線。","要求觀察、測量、方法、結論與限制對齊。")]
 d["fusionRecord"]={"commonCore":["三版本公開結構共同支持以清楚定義、測量程序與紀錄建立可比較證據。","單位、器材、起點、時間、重複、異常與安全是共同方法檢核項目。","方法透明能讓他人重做並指出限制，不代表誤差會消失。"],"versionDifferences":["南一證據較突顯觀察、測量與基本方法；康軒較突顯實作、討論、重做與資料比較；翰林較突顯生活測量、尺度、解析度與限制。這是公開課程計畫層級差異，不宣稱完整教材差異。"],"originalAdditions":["以紙橋承重建立失效定義與共同讀值規則。","以熱水冷卻曲線示範時間序列、異常與原始資料。","以影子長度爭議練習起點、方向、單位與方法差異。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織觀察、操作型定義、測量、方法共同標準、原始紀錄、誤差、重做、安全與結論界線。正文、原創情境、互動步驟、錯誤回饋與檢核均為本專案重寫，未複製任何教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
 d["updatedAt"]="2026-09-21"; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"an-Ⅳ-1：科學觀察、測量與方法受共同標準規範","lessonId":d["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 print("an-iv-1 lesson authored")
if __name__=="__main__": main()
