import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-2.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-2-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創課堂指令、學習用品、合作分組、繳交、位置、時間、主旨、實驗與澄清情境，承接公開課程的課堂字詞理解方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-3-iv-2"
    data["title"] = "3-Ⅳ-2：從課堂指令與上下文辨識常用英語字詞"
    data["content"] = {"summary": "課堂字詞的意思要放回任務中理解：underline、circle、compare、hand in、in pairs、beside、before、main idea、pour into 與 repeat 都指向具體動作、關係、時間或學習目的。本課以原創工作單、文具、報告繳交、實驗量杯、段落閱讀與教師指令，練習從動詞、介系詞、時間詞、名詞搭配和前後步驟推斷意思，再用實際動作驗證，而不是只把單字翻成一個中文詞。聽不清楚時則學會請教師重述，維持學習安全與進度。", "sections": [{"heading": "指令字詞要連到動作", "body": "Please underline the sentence that gives the reason 要求找出理由句並畫線，circle two key words 則是圈出關鍵字；先找動詞，再找它作用的物件。若只記 underline 是『底線』而沒有辨認誰要做什麼，仍無法完成工作單。"}, {"heading": "片語和介系詞常改變任務", "body": "hand in the report 是把報告交給老師或指定位置，不是把手放在報告上；in pairs 是兩人一組，beside the notebook 是在筆記本旁邊。讀片語時保留動詞、名詞與介系詞的組合，不能把每個字分開猜。"}, {"heading": "時間和主旨詞連接學習目的", "body": "before Friday 提供期限，bell rings at the end of the period 指向準備離開的時點；main idea 則要求段落的核心訊息，不是任意抄一個細節。先問這個字詞讓學生決定什麼，再選答案或行動。"}, {"heading": "實驗動詞需要方向和容器", "body": "Pour the water into the beaker 中，water 是被倒出的物質，beaker 是接收它的容器；讀科學指令要同時辨認動作、物質、方向和目的地。若不懂或漏聽最後指令，使用 Could you repeat the last instruction? 比猜測安全。"}]}
    data["studyHighlights"] = ["從動詞和受詞配對理解 underline、circle、compare 等課堂指令。", "保留 hand in、in pairs、beside、before 等片語與介系詞關係。", "用期限、鐘聲與 main idea 判斷時間和學習目的。", "在實驗和澄清情境中辨認方向、容器與安全的下一步。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "知道單字翻譯就能完成工作單嗎？", "body": "給出完全自編的三步工作單，只把 underline、circle、compare 翻成詞義，不提供動作示範，觀察學生是否做錯。第二輪讓學生依動詞和受詞演出，再互換指令，讓字詞意義由可觀察任務而不是孤立翻譯建立。"}, {"id": "explain", "phase": "explain", "heading": "課堂字詞四欄卡", "body": "每個字詞填 Word or phrase、Action or relation、Object or place、Evidence in the sentence 四欄。動詞要連受詞，介系詞要連位置或方向，時間詞要連期限或時點，最後用實際動作或圖片檢查解釋是否可執行。"}, {"id": "worked-example", "phase": "worked-example", "heading": "把 hand in 和 hand on 分開", "body": "以 Please hand in your report before Friday. 示範：hand in 是繳交，before Friday 是期限；比較若把 in 讀成 on，工作結果會完全不同。學生用兩張角色卡演出繳交與放置，讓片語意思回到課堂任務和物件。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "從句子到正確物件", "body": "給出橡皮擦、量杯、筆記本、報告、段落與鐘聲六張材料卡，學生讀原創指令後選物件、排順序或標位置。交換後同伴只能依卡片執行，若做錯，作者要指出是動詞、介系詞、時間或主旨詞理解出了問題。"}, {"id": "transfer", "phase": "transfer", "heading": "把字詞策略帶到不同科目", "body": "輪換英文工作單、數學比較、自然倒水、社會段落與美術作品繳交。學生先圈動詞或片語，再寫最短可執行中文說明與英文例句；遇到新字詞時用前後步驟、圖片、搭配和同伴動作推測，不直接靠單字表猜。"}, {"id": "reflect", "phase": "reflect", "heading": "我理解的是字詞還是任務？", "body": "回看答案，將錯誤分成動作、受詞、位置、時間、主旨、順序或聽漏。若只能說中文詞義卻無法演出，補上句中搭配；若聽不清楚，改用澄清句取得原指令，不用猜測完成實驗或交件。"}], "summary": ["以 Word、Action、Object／place、Evidence 四欄理解課堂字詞。", "將動詞、片語與介系詞放回工作單或實驗任務。", "用時間、主旨和步驟判斷字詞在課堂中的功能。", "以實際動作、圖片與澄清句驗證理解是否足以執行。"], "exitCheck": [{"prompt": "理解課堂指令時為何要找動詞和受詞？", "expectedEvidence": "能指出動詞說明要做什麼，受詞說明對什麼做，兩者共同決定實際行動。"}, {"prompt": "如何理解 hand in、in pairs 或 beside 這類片語？", "expectedEvidence": "能保留片語與介系詞關係，並用繳交、兩人合作或位置示範意義。"}, {"prompt": "聽不清楚實驗指令時應如何處理？", "expectedEvidence": "能請求重述最後指令，確認動作、物質、容器或順序後再執行。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "從課堂句子的動詞、片語、介系詞、時間與上下文，辨識字詞功能並完成正確學習行動。", "scenario": "學生輪流完成工作單、合作閱讀、實驗倒水與報告繳交任務，遇到不懂或漏聽時使用澄清句。", "variables": [{"symbol": "w", "meaning": "課堂字詞、片語與搭配"}, {"symbol": "a", "meaning": "動作、物件、位置、時間與主旨"}, {"symbol": "v", "meaning": "圖片、步驟、實際動作與澄清驗證"}], "steps": [{"id": "step-1", "prompt": "The teacher says, 'Please underline the sentence that gives the reason.' What should students do?", "options": ["Draw a line under the sentence that gives the reason.", "Hand the report in before Friday.", "Pour water into the beaker."], "answer": "A", "feedback": "A connects underline with the target sentence and the reason; the other choices are different classroom tasks."}, {"id": "step-2", "prompt": "A worksheet says, 'Work in pairs and compare your answers.' What does 'in pairs' mean?", "options": ["Work with one other student.", "Work alone in a different room.", "Put the worksheet beside the notebook."], "answer": "A", "feedback": "In pairs describes a two-person grouping, while the other choices describe different arrangements or positions."}, {"id": "step-3", "prompt": "The experiment says, 'Pour the water into the beaker.' Which item receives the water?", "options": ["The beaker.", "The pencil case.", "The paragraph's main idea."], "answer": "A", "feedback": "Into identifies the destination container; the beaker receives the water in the instruction."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語課堂字詞、指令與基本閱讀定位；核讀 2026-09-21。", ["在課堂情境中理解並使用基本英語字詞和指令。", "透過學習用品、動作與任務支持字詞理解。"], ["工作單、文具、分組、繳交、位置、時間、主旨與實驗。"], "只背單字翻譯，沒有連結句中動作、物件或任務。", "重視課堂字詞、基本閱讀與可執行回應。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語字詞、圖片、課堂活動與任務定位；核讀 2026-09-21。", ["透過圖片、活動和課堂指令辨認字詞功能。", "依分組、順序、位置、時間和操作完成學習。"], ["underline、circle、compare、hand in、pairs、beside、before、pour。"], "把片語拆成單字或混淆介系詞、方向與合作人數。", "評量字詞主要內容、指令理解、位置與任務完成。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語課堂字詞、上下文與功能評量定位；核讀 2026-09-21。", ["從句子搭配、步驟、圖片和語境形成課堂字詞理解。", "以澄清、主旨、時間和實驗指令完成資訊處理。"], ["word、phrase、action、object、place、time、main idea、clarification。"], "文法看似懂但無法實際執行，或在聽漏時自行猜測安全指令。", "評量字詞功能、上下文、指令、主旨與澄清策略。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持課堂字詞、指令、基本閱讀與學習任務。", "字詞理解需整合動詞、受詞、片語、介系詞、時間、主旨與上下文。", "從詞義到任務執行可用材料卡、圖片、順序、動作示範與澄清驗證。"], "versionDifferences": ["南一較突顯課堂字詞與基本閱讀；康軒較突顯圖片、活動、分組、位置與操作；翰林較突顯句子搭配、主旨、實驗指令、澄清與功能評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Word or phrase、Action or relation、Object or place、Evidence 四欄理解課堂字詞。", "用工作單、文具、報告、實驗量杯、段落與鐘聲原創任務驗證片語功能。", "以實際動作和 Could you repeat the last instruction? 檢查可執行理解與安全。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織課堂指令、片語、介系詞、時間、主旨、實驗方向、合作與澄清。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 四欄完成後要求同伴只看英文句子執行動作；若需要額外翻譯，先檢查是否漏了受詞、介系詞或時間，而不是立刻把整句換成中文。"
    data["teaching"]["body"][4]["body"] += " 跨科替換時保留搭配和下一步，讓學生知道字詞意義會受任務改變；實驗場景若有任何不確定，澄清優先於速度。"
    data["teaching"]["body"][5]["body"] += " 若同伴能說出詞義卻做錯動作，回到句中受詞、方向和順序找缺口；若指令沒聽清楚，紀錄漏掉的片語並重新確認。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "3-Ⅳ-2：從課堂指令與上下文辨識常用英語字詞", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-2")


if __name__ == "__main__":
    main()
