import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-16.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-16-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "genre, purpose, structure, detail, and topic"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "narrative, expository, notice, letter, dialogue, and critical reading"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "purpose, headings, process, advertisement, chart, and webpage"),
    ]
    return [{"url": u, "title": f"{t}；僅取不同體裁、結構、目的與批判閱讀能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以故事、說明文、通知、書信、短劇、流程、廣告、圖表與網頁判讀文本目的、結構和主題；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-3-iv-16"
    data["title"] = "3-Ⅳ-16：辨認不同體裁的目的、結構與可靠閱讀方式"
    data["content"] = {"summary": "不同體裁會用不同方式組織資訊：故事透過人物與事件推進，說明文用原因與過程，通知列出可執行細節，書信建立收信人與交流目的，短劇結合台詞和舞台指示，廣告則可能使用誇張主張。本文以尋回狗、地下水、工作坊通知、旅行書信、校園花園、問題—證據—方案、劇本、食譜、飲料廣告與回收網頁等原創文本，練習依體裁切換閱讀問題並保留批判判斷。", "sections": [{"heading": "體裁先提示讀者要找什麼", "body": "故事先找角色、目標與結果；說明文找原因、階段與定義；通知找日期、地點、材料與聯絡人；書信找收信人和寫信目的。標題和格式不是裝飾，而是閱讀路線的入口。"}, {"heading": "結構詞要配合文本功能", "body": "Problem、Evidence、Possible Solution 是問題分析結構；first 在食譜可能標示步驟，在科學說明可能標示過程階段，要回看前後句和文本目的，不能靠單一詞固定解釋。"}, {"heading": "資訊文本可以交叉核對", "body": "回收網頁同時有說明、圖表和公告，讀者要先分辨哪個區塊回答概念、哪個提供日期、哪個提出限制；不能把圖表的收運日套到所有地區，也不能把通知當成背景說明。"}, {"heading": "不同體裁都需要批判閱讀", "body": "廣告說 best choice for everyone 是強烈主張，不等於有足夠證據；讀者要問誰說、為誰、依據是什麼、是否有例外。體裁辨識幫助找到答案，但不替讀者取消查證。"}]}
    data["studyHighlights"] = ["由格式、標題與內容判斷故事、說明、通知、書信、短劇、廣告或網頁。", "依體裁切換主旨、過程、行動、讀者、結構與可靠性問題。", "回看 first、heading、caption、stage direction 等線索，避免單字脫離功能。", "將文本主張、圖表資料與通知限制分開，必要時批判查證。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "同一個 first 在不同文章做同一件事嗎？", "body": "比較原創食譜與地下水說明中的 first，學生先猜功能，再讀後續句子確認一個是操作步驟、一個是過程階段，發現體裁與結構共同決定理解。"}, {"id": "explain", "phase": "explain", "heading": "體裁—目的—證據三欄卡", "body": "建立 Genre、Purpose、Structure、Key evidence 三欄。先辨認文本在敘事、解釋、指示、交流、表演或說服，再選擇相應的證據和問題，不把所有文章都當成找日期。"}, {"id": "worked-example", "phase": "worked-example", "heading": "拆開回收網頁的三種資訊", "body": "以 recycling explanation、collection-day chart、front-desk notice 示範：說明回答 why，圖表回答 when，公告回答 change or restriction。把三區資訊分開，再整合成可執行決定。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一主題換體裁", "body": "用校園花園分別寫成故事、科學說明、通知、廣告與網頁。學生標記每篇的讀者、目的、結構和證據，再交換回答主旨、行動或可信度問題。"}, {"id": "transfer", "phase": "transfer", "heading": "替讀者選對閱讀問題", "body": "學生拿到一則混合頁面，為故事段落、圖表、公告與廣告各寫一個不同問題，並說明不能用哪一種答案代替另一區。最後將資訊整理成有來源欄位的摘要。"}, {"id": "reflect", "phase": "reflect", "heading": "我辨認體裁後有真的改變讀法嗎？", "body": "回看作答，標記把通知當故事、把廣告主張當事實、把圖表日期當全文主旨或把 stage direction 當台詞。修訂時補上體裁、目的與證據，讓策略確實改變。"}], "summary": ["以 Genre、Purpose、Structure、Key evidence 四欄辨認體裁功能。", "故事、說明、通知、書信、短劇、廣告與網頁使用不同閱讀問題。", "把標題、格式、連接詞、圖表和公告限制放回文本功能。", "批判閱讀主張與資料來源，不因體裁名稱就停止查證。"], "exitCheck": [{"prompt": "體裁辨認如何幫助閱讀而不變成貼標籤？", "expectedEvidence": "能說明體裁提示目的與結構，並用原文證據選擇適合的閱讀問題。"}, {"prompt": "同一個 first 為何可能有不同功能？", "expectedEvidence": "能比較前後句、文本目的與後續資訊，分辨步驟與過程階段。"}, {"prompt": "如何批判廣告或混合網頁的主張？", "expectedEvidence": "能分開主張、資料、圖表與限制，指出需要查證的範圍與例外。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "辨認文本體裁與目的，選擇相應結構線索，並以證據和限制理解不同文章。", "scenario": "學生擔任校園資訊策展人，要把故事、說明、通知、短劇、廣告與網頁分區閱讀。", "variables": [{"symbol": "g", "meaning": "Genre：故事、說明、通知、書信、短劇、廣告或網頁"}, {"symbol": "p", "meaning": "Purpose 與讀者需要"}, {"symbol": "s", "meaning": "Structure、圖表、台詞、步驟與證據限制"}], "steps": [{"id": "step-1", "prompt": "A text has a date, room, required materials, and a contact person for a workshop. What genre is it most likely?", "options": ["A notice with practical event information.", "A fictional story about a character.", "A recipe with cooking steps."], "answer": "A", "feedback": "日期、地點、材料與聯絡人共同指向通知的行動資訊。"}, {"id": "step-2", "prompt": "A text has headings 'Problem,' 'Evidence,' and 'Possible Solution.' What structure does it use?", "options": ["A problem-analysis structure.", "A greeting and closing letter structure.", "A character dialogue only."], "answer": "A", "feedback": "三個標題直接建立問題、證據與方案的分析關係。"}, {"id": "step-3", "prompt": "An advertisement says a drink is 'the best choice for everyone.' What is a critical response?", "options": ["Ask what evidence supports the claim and whether exceptions exist.", "Accept it because the words sound positive.", "Assume every person has the same needs."], "answer": "A", "feedback": "A 把廣告主張與證據、受眾差異及例外分開，符合批判閱讀。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；生活文本、故事與主要訊息定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由故事、說明與生活文本理解主要訊息。", "依人物、過程、日期、地點與行動整理文本。"], "representations": ["故事、通知、說明、書信與活動文本。"], "examplesOrEvidence": ["本課以尋回狗、地下水、工作坊與旅行書信原創文本承接公開結構。"], "misconceptions": ["所有文本都用同一種讀法尋找細節。"], "assessmentEmphasis": ["重視不同文本的主要內容與生活應用。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖文、任務與文本結構定位；核讀 2026-09-21。", "findings": {"concepts": ["透過圖文、任務與格式辨識文本目的。", "依標題、步驟、圖表與聯絡資訊完成理解。"], "representations": ["流程、短劇、問題分析、廣告與網頁。"], "examplesOrEvidence": ["本課以體裁—目的—證據卡重新設計混合頁面活動。"], "misconceptions": ["看到相同單字便忽略文章功能和讀者。"], "assessmentEmphasis": ["評量結構、目的、細節與文本應用。"], "misconceptions": ["看到相同單字便忽略文章功能和讀者。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；閱讀策略、不同體裁與批判理解定位；核讀 2026-09-21。", "findings": {"concepts": ["從文本體裁、結構與目的形成理解。", "以證據、限制、圖表與主張檢查可靠性。"], "representations": ["genre、purpose、structure、chart、advertisement、webpage。"], "examplesOrEvidence": ["本課以回收混合網頁、廣告與同主題換體裁重新設計批判閱讀。"], "misconceptions": ["因文本看似正式就接受全部主張。"], "assessmentEmphasis": ["評量體裁、證據、目的與批判判斷。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持故事、說明、通知與生活文本理解。", "可靠閱讀需依體裁、目的與結構選擇不同證據。", "可用體裁—目的—證據卡、混合頁面分區與主張查證完成遷移。"], "versionDifferences": ["南一較突顯故事、說明與生活文本；康軒較突顯圖文、任務、步驟與格式；翰林較突顯不同體裁、結構、證據與批判閱讀。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Genre、Purpose、Structure、Key evidence 四欄辨認體裁功能。", "用尋回狗、地下水、通知、書信、短劇、廣告、回收網頁與食譜原創文本練習。", "以同主題換體裁和混合頁面分區檢查讀法轉換。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織不同體裁、文本目的、結構、證據、圖表與批判閱讀。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-3-iv-16-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先辨認體裁與讀者目的，再讀其結構線索，最後以文本證據和限制回答。"; q["solutionSteps"] = ["先觀察標題、格式、稱呼、段落標題、台詞或圖表，判斷文本體裁。", "判斷作者目的與讀者需要，決定要找故事、過程、行動、主張或資料。", "回到相應結構和關鍵證據定位答案。", "分開明示資訊、作者主張、圖表資料與需要查證的推論。", "用完整句說明體裁如何支持答案，確認沒有把另一區資訊錯套進來。" ]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的不同體裁、結構、目的與批判閱讀模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-16")


if __name__ == "__main__":
    main()
