#!/usr/bin/env python3
"""Independent first-pass authoring for science performance po-IV-1."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-performance-po-iv-1.json"; REPORT=ROOT/"implementation/reports/science-performance-po-iv-1-first-pass-review.json"
URLS={"nani":"https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf","kanghsuan":"https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110","hanlin":"https://drive.google.com/uc?id=1gMUVcDjfXmqIapg-fNnfPuLFaK98dxGX&export=download"}
def rec(p,c,r,m,a): return {"publisher":p,"edition":f"{p} 公立校方自然課程計畫章節級證據","sourceType":"public-web","sourceLocator":f"{URLS[p]}；多元來源、計畫觀察、問題察覺與評量欄位；核讀 2026-09-21。","reviewedAt":"2026-09-21","findings":{"concepts":[c,"公開課程結構支持從文字、圖表、影像、訪談與實地觀察交叉尋找現象，規畫觀察並察覺可探究問題。"],"representations":[r],"examplesOrEvidence":["本課的校園熱島、河川垃圾與候鳥資料皆為原創情境，只承接公開課程所示的能力方向。"],"misconceptions":[m],"assessmentEmphasis":[a]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。"}
def main():
 d=json.loads(LESSON.read_text(encoding="utf-8")); assert d["id"]=="lesson-science-performance-po-iv-1" and d["reviewStatus"]=="draft"
 d["title"]="po-Ⅳ-1：由多元來源進行有計畫觀察並察覺問題——把線索接成現象"
 d["content"]={"summary":"同一個科學問題常不會只出現在一種資料裡：校園熱島可能同時有地圖、溫度紀錄、照片和訪談；河川垃圾可從新聞、現場觀察、雨後影像與居民描述看見不同面向。多元來源不是把資料越堆越多，而是先判斷來源用途、時間、尺度、可信度與缺口，再設計有計畫的觀察，從線索中察覺值得探究的問題。本課以原創案例練習來源交叉、觀察表、異常辨識與問題形成。","sections":[{"heading":"每種來源看見不同部分","body":"地圖提供位置與範圍，照片保留外觀和時間線索，數據可以比較變化，訪談呈現經驗但可能受記憶和立場影響。先說明來源能回答什麼，不能把所有資料當同一種證據。"},{"heading":"先交叉再下判斷","body":"兩個來源一致不一定代表因果，但能增加察覺線索；若互相矛盾，要查日期、測量方法、樣本和定義。交叉的目的不是投票，而是找到需要補觀察的地方。"},{"heading":"計畫觀察要對準缺口","body":"察覺問題後，決定觀察對象、地點、時間、頻率、工具、紀錄欄位和安全界線。計畫不必一次解決全部疑問，但要能補上最關鍵的資料缺口。"},{"heading":"問題從異常和差異長出來","body":"某地溫度特別高、垃圾在雨後聚集或候鳥出現時間改變，都只是線索。把線索改寫成有對象、比較條件和可記錄結果的問題，才會成為後續探究的入口。"}]}
 d["studyHighlights"]=["辨識地圖、照片、數據、訪談與現場觀察各自的用途和限制。","交叉比對日期、尺度、定義、方法與矛盾資料。","依資料缺口規畫對象、地點、時間、頻率和記錄方式。","從異常、差異與變化形成可觀察、可探究問題。"]
 d["teaching"]={"body":[
 {"id":"hook","phase":"hook","heading":"校園哪裡真的比較熱？","body":"提供校園地圖、三張不同時間的地表照片、溫度表和學生訪談。每組先圈出各來源看見的線索，再標記互相矛盾的地方：照片陰影可能改變、訪談時間不明、數據測點很少。最後選一個缺口規畫明天的觀察。"},
 {"id":"explain","phase":"explain","heading":"多元來源四步讀法","body":"先辨識來源和製作時間，再問它測量或描述什麼；接著和其他來源對照尺度、定義與方法，最後列出一致、矛盾和未知。計畫觀察要優先補最會改變判斷的未知，而非盲目收集所有資料。"},
 {"id":"worked-example","phase":"worked-example","heading":"雨後河川垃圾的線索鏈","body":"新聞照片顯示橋下垃圾增加，居民說每次大雨後更嚴重，清潔紀錄卻只有晴天日期。先把三種來源分開，指出雨量、採樣位置和日期缺口，再設計雨前、雨後同一位置的垃圾數量和水位觀察；不要直接把居民說法當成完整因果證明。"},
 {"id":"guided-practice","phase":"guided-practice","heading":"候鳥資料的矛盾與補觀察","body":"望遠鏡紀錄說 10 月看到 12 隻，社群照片只顯示 5 隻，新聞卻寫大量出現。學習者先查觀察時間、視野、拍攝目的和數量定義，再設計固定時段、固定路線和重複計數，並記下天氣與干擾。"},
 {"id":"transfer","phase":"transfer","heading":"做一張問題察覺地圖","body":"把來源、線索、矛盾、缺口、觀察計畫和可探究問題連成一張圖。交換後請同學指出哪一條線索仍沒有來源、哪個問題太大或缺少比較條件，再共同改寫成下一週可執行的觀察。"},
 {"id":"reflect","phase":"reflect","heading":"修正兩個來源迷思","body":"請修正『網路上很多來源就一定可靠』與『不同來源不一致代表其中一個一定造假』。來源數量不等於品質，要查方法和利益；矛盾可能來自時間、尺度、定義或取樣差異，正好提示需要補觀察。"}
 ],"summary":["每種來源有不同用途、尺度、時間與限制。","交叉比對一致與矛盾，找出最重要的資料缺口。","依缺口規畫對象、地點、時間、頻率和安全觀察。","從異常與差異形成可操作的探究問題。"],"exitCheck":[{"prompt":"為什麼地圖、照片、數據和訪談不能直接相加成同一種證據？","expectedEvidence":"它們觀察的量、尺度、時間和可靠度不同，要先說明各自能回答與不能回答的問題。"},{"prompt":"河川垃圾資料互相矛盾時先查什麼？","expectedEvidence":"查日期、雨量、位置、樣本定義、測量方法和來源目的，再設計補觀察。"},{"prompt":"如何把『候鳥變少了』改成可執行問題？","expectedEvidence":"指定地點、固定時段和路線、計數方法、重複次數與比較期間。"}]}
 d["interactive"]={"type":"guided-choice","goal":"從多元來源交叉辨識線索、缺口與矛盾，規畫有目的觀察並形成問題。","scenario":"分析校園熱島、河川垃圾與候鳥資料，逐步選出能補上關鍵缺口的觀察方法。","variables":[{"symbol":"s","meaning":"資料來源"},{"symbol":"g","meaning":"觀察缺口"},{"symbol":"q","meaning":"可探究問題"}],"steps":[{"id":"step-1","prompt":"不同資料都提到校園某處較熱，下一步最適合做什麼？","options":["查時間、測點與方法，再用固定時段和位置補測","只把所有來源的數字平均","只相信轉傳最多的照片"],"answer":"A","feedback":"一致線索仍要確認尺度和方法，補測才能支持比較。"},{"id":"step-2","prompt":"新聞、訪談和清潔紀錄對河川垃圾說法不同時，應如何處理？","options":["列出日期、位置、定義與取樣差異，找最需要補的觀察","直接投票選最有名的來源","刪掉和多數不同的資料"],"answer":"A","feedback":"矛盾是查找資料缺口的入口，不是用票數決定真偽。"},{"id":"step-3","prompt":"哪個候鳥問題最適合先做？","options":["固定路線和時段比較兩週候鳥計數與天氣條件","候鳥為什麼在全世界移動","候鳥是不是永遠喜歡某一棵樹"],"answer":"A","feedback":"它有對象、時間、方法、比較和可記錄結果。"}]}
 d["teaching"]["body"][4]["body"]="把來源、線索、矛盾、缺口、觀察計畫和可探究問題連成一張圖。交換後請同學指出哪一條線索仍沒有來源、哪個問題太大或缺少比較條件，再共同改寫成下一週可執行的觀察，並加上觀察者、時間和安全提醒。"
 d["authoringStandard"]="version-fused-v1"
 d["versionResearch"]=[rec("nani","以多元資料和有目的觀察辨識自然現象、問題與探究方向。","地圖、照片、數據、訪談、觀察表、來源比較與缺口。","把來源數量或權威語氣當成品質，忽略時間和方法。","重視來源判讀、觀察計畫、證據交叉與問題形成。"),rec("kanghsuan","透過蒐集、比較、討論和實地觀察從線索形成可探究問題。","多來源資料、矛盾、現場紀錄、重複觀察與同儕檢核。","不同資料不一致就直接刪除，或只收集支持原想法的來源。","評量資料整合、缺口辨識、觀察設計與提問。"),rec("hanlin","連結校園、環境、生物與社會資訊，依尺度、立場和樣本規畫觀察。","熱島、河川、候鳥、地點、日期、訪談、照片與數據。","把訪談或照片直接當因果，忽略代表性、利益和定義。","要求來源透明、交叉檢核、安全、範圍與問題品質。")]
 d["fusionRecord"]={"commonCore":["三版本公開結構共同支持從多元來源辨識現象、資料缺口並規畫觀察。","來源用途、時間、尺度、方法、矛盾與問題可操作性是共同要求。","交叉檢核不是投票或刪除異常，而是找出最值得補測的未知。"],"versionDifferences":["南一證據較突顯多元資料、觀察與基本問題形成；康軒較突顯蒐集、比較、實地觀察與同儕檢核；翰林較突顯校園環境、生物、社會資訊、尺度與立場。這是公開課程計畫層級差異，不宣稱完整教材差異。"],"originalAdditions":["以校園地圖、照片、溫度表和訪談交叉辨識熱島缺口。","以雨後河川新聞、居民說法與清潔紀錄設計補觀察。","以候鳥望遠鏡、社群照片和新聞數量差異規畫固定路線計數。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織來源用途、時間、尺度、方法、交叉比對、矛盾、資料缺口、計畫觀察與問題形成。正文、原創多源情境、互動步驟、錯誤回饋與檢核均為本專案重寫，未複製任何教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
 d["updatedAt"]="2026-09-21"; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"po-Ⅳ-1：由多元來源進行有計畫觀察並察覺問題","lessonId":d["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 print(json.dumps({"lesson":str(LESSON.relative_to(ROOT)),"reviewStatus":d["reviewStatus"]},ensure_ascii=False))
if __name__=="__main__": main()
