import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-12.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-12-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "skimming, scanning, context clues, main idea, and evidence"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "reading purpose, reference, inference, detail, and support"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "paragraph topic, vocabulary context, sequence, and claim evaluation"),
    ]
    return [{"url": u, "title": f"{t}；僅取閱讀策略、文本證據與理解流程方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量要求學生依閱讀目的選擇略讀或尋讀，利用上下文、主旨、指代、推論與證據判斷文本；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-3-iv-12"
    data["title"] = "3-Ⅳ-12：依閱讀目的選策略、找證據並檢查理解"
    data["content"] = {"summary": "閱讀技巧不是固定順序的考試口訣，而是根據目的調整工具：先由標題與段落預測主題，快速掌握全文用 skimming，需要特定日期或人名用 scanning，陌生字靠上下文線索，主旨要整合段落，指代要回查名詞，主張則要比較證據。本文以蜜蜂與花園、活動公告、滑路、可重複水瓶、校園花園、野餐、博物館與洗手步驟等原創文本，練習讀前、讀中、讀後的可驗證流程。", "sections": [{"heading": "先決定讀這段文字要完成什麼", "body": "若只想知道長文大意，先略讀標題、首句與段落開頭；若只找活動時間，直接尋讀日期與時間格式；若要判斷主張是否成立，就要回到理由和證據。策略由任務決定，不由文章長短單獨決定。"}, {"heading": "陌生字要用周圍線索", "body": "slippery 可由 path、hikers moved slowly 與因果連接推知可能是容易滑倒；不要只看字根或選最熟悉的中文。上下文提供同義、例子、結果、對比或因果線索，應先說明是哪一種線索。"}, {"heading": "主旨與細節有不同證據範圍", "body": "可重複水瓶段落提到減少塑膠、節省金錢、方便攜帶，主旨應涵蓋推廣水瓶的多個理由，不只抄其中一項。找 event time 則只需定位時間，不能用整篇摘要取代答案。"}, {"heading": "讀後要驗證，不是停止在第一個猜測", "body": "推論、代名詞、作者目的與 claim support 都要回指原文。先提出暫時理解，再用句子、資料與連接詞核對；若證據不足，說明文本不能確定，而不是把常識填進去。"}]}
    data["studyHighlights"] = ["先判斷閱讀目的，再選 skimming、scanning、上下文推詞或證據比對。", "以標題、首句、段落、關鍵格式和連接詞定位資訊。", "主旨整合多個細節，細節題則只回應問題指定欄位。", "推論、指代與主張判斷都要回指文本證據並保留限制。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "同一篇文章可以用兩種讀法嗎？", "body": "給學生同一則戶外活動公告：第一次只問活動主題，第二次只問集合時間。學生比較先讀標題與首句和直接掃描時間格式的差異，理解策略要服從任務。"}, {"id": "explain", "phase": "explain", "heading": "目的—策略—證據三欄卡", "body": "建立 Purpose、Strategy、Text clue 三欄。先寫要找大意、特定細節、字義、指代、推論或證據，再選對應方法，最後記下實際回指的標題、句子、數字或連接詞。"}, {"id": "worked-example", "phase": "worked-example", "heading": "用上下文拆解陌生字", "body": "以 slippery path 示範：path 是路、hikers moved slowly 是結果、so 是因果線索；因此可推知滑溜危險，但不能把 slippery 延伸成路面破裂。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "六種問題換六種工具", "body": "用蜜蜂、公告、水瓶、校園花園、博物館與洗手流程六組原創文本，輪流處理主旨、時間、字義、證據、指代與作者目的。學生先選策略，再畫證據，最後檢查策略是否真的縮小了搜尋範圍。"}, {"id": "transfer", "phase": "transfer", "heading": "把閱讀流程教給下一位讀者", "body": "學生挑一段校園說明，為同伴設計一題主旨題與一題尋讀題，附上不同的讀法和證據位置。交換後檢查答案是否唯一、問題是否真的要求不同策略。"}, {"id": "reflect", "phase": "reflect", "heading": "我是在找證據還是在猜？", "body": "回看答案，標記策略不合目的、主旨過窄、字義無上下文、指代未回查、推論超出文本或主張無證據。修訂時在答案旁寫『我在哪一句看到？』，不能只寫我覺得。"}], "summary": ["用 Purpose、Strategy、Text clue 三欄選擇閱讀工具。", "略讀掌握全貌、尋讀定位細節、上下文推詞，依題目任務切換。", "主旨整合多個細節，推論和主張判斷需回指句子或資料。", "讀後以證據驗證理解，資訊不足時保留不能確定。"], "exitCheck": [{"prompt": "skimming 和 scanning 的目的如何不同？", "expectedEvidence": "能說明前者快速掌握大意，後者定位特定細節，並各舉出一個文本任務。"}, {"prompt": "遇到陌生字時，如何證明上下文推詞不是亂猜？", "expectedEvidence": "能指出至少兩個周圍線索及其關係，並保留字義推論的範圍。"}, {"prompt": "如何判斷作者主張有沒有被支持？", "expectedEvidence": "能把主張與理由、資料或例子逐一配對，說明證據是否直接相關且足夠。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "依閱讀目的選擇策略，從文本線索建立並驗證主旨、細節、字義、指代與證據判斷。", "scenario": "學生擔任閱讀策略教練，要協助同伴在文章、公告與說明中快速找對資訊並說出證據。", "variables": [{"symbol": "p", "meaning": "閱讀目的：大意、細節、字義、指代、推論或證據"}, {"symbol": "s", "meaning": "skimming、scanning、context clues 與回讀"}, {"symbol": "e", "meaning": "標題、句子、格式、連接詞與支持資料"}], "steps": [{"id": "step-1", "prompt": "You need only the time of an event in a long notice. Which strategy is best?", "options": ["Scan for the date and time format.", "Read every sentence slowly before looking for the time.", "Guess from the title alone."], "answer": "A", "feedback": "任務是特定細節，scanning 能快速定位日期與時間，而不是先完整精讀。"}, {"id": "step-2", "prompt": "The path was slippery, so hikers moved slowly. What does slippery most likely mean?", "options": ["Easy to slide on and not safe to walk quickly.", "Very bright and warm.", "Full of written instructions."], "answer": "A", "feedback": "path、moved slowly 與 so 共同提供因果線索，支持容易滑倒的字義。"}, {"id": "step-3", "prompt": "A paragraph says reusable bottles reduce plastic waste, save money, and are easy to carry. What is the main idea?", "options": ["Reusable bottles have several practical benefits.", "Bottles are always expensive.", "Plastic waste is impossible to reduce."], "answer": "A", "feedback": "A 整合段落列出的三個理由，不只複製其中一個細節。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；生活文本、主要訊息與閱讀策略定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由標題、短文與生活資料理解主要訊息。", "依閱讀目的定位人物、時間、地點與行動。"], "representations": ["公告、說明、步驟、環境與校園文本。"], "examplesOrEvidence": ["本課以蜜蜂、公告、水瓶與洗手原創文本承接公開結構。"], "misconceptions": ["所有文章都逐句精讀，沒有先判斷任務。"], "assessmentEmphasis": ["重視主要內容、細節與生活閱讀應用。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖像、任務與閱讀理解定位；核讀 2026-09-21。", "findings": {"concepts": ["透過圖文、任務與問題選擇閱讀方法。", "依順序、關鍵字、上下文與證據完成理解。"], "representations": ["圖表、公告、流程、校園花園與活動。"], "examplesOrEvidence": ["本課以目的—策略—證據卡重新設計閱讀活動。"], "misconceptions": ["看到關鍵字就選答案，沒有回讀完整句。"], "assessmentEmphasis": ["評量資訊定位、字義、主旨與推論。"], "misconceptions": ["看到關鍵字就選答案，沒有回讀完整句。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；閱讀策略、證據與推論定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["從閱讀目的選擇略讀、尋讀、上下文與回讀。", "以主旨、指代、推論與證據檢查理解。"], "representations": ["skimming、scanning、context clues、reference、inference、support。"], "examplesOrEvidence": ["本課以陌生字、代名詞與主張驗證重新設計策略鏈。"], "misconceptions": ["把常識或第一個猜測當成文本證據。"], "assessmentEmphasis": ["評量策略使用、文本證據與主張判斷。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持生活文本、主要訊息與閱讀策略。", "可靠理解需依目的選工具，再以標題、句子、格式與資料驗證。", "可用目的—策略—證據卡、上下文推詞、主旨整合與主張配對完成遷移。"], "versionDifferences": ["南一較突顯生活文本與主要訊息；康軒較突顯圖文、任務、關鍵字與上下文；翰林較突顯閱讀策略、指代、推論與證據檢查。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Purpose、Strategy、Text clue 三欄選擇閱讀工具。", "用蜜蜂、公告、滑路、水瓶、校園花園、野餐、博物館與洗手原創文本練習。", "以『我在哪一句看到？』回讀檢查策略和證據界線。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織略讀、尋讀、上下文推詞、主旨、指代、推論與主張證據。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-3-iv-12-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先判斷題目閱讀目的，再選 skimming、scanning、上下文推詞或證據回讀，最後用原文線索驗證。"; q["solutionSteps"] = ["先讀題目，圈出要找大意、特定細節、字義、指代、推論或支持。", "選擇與目的相配的閱讀策略，說明為何能縮小搜尋範圍。", "回到標題、句子、格式、連接詞或資料找直接證據。", "比較選項是否整合完整文本，排除只抓關鍵字或加入常識的答案。", "用自己的話重述答案並標出證據位置，若不足則保留不能確定。"]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的閱讀策略、主旨、字義、指代、推論與證據模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-12")


if __name__ == "__main__":
    main()
