import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-2-iv-9.json"
REPORT = ROOT / "implementation/reports/english-performance-2-iv-9-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創餐飲、圖書館、醫療、旅遊、校園公告、商店、邀請、地面安全與訪談角色扮演，承接公開課程的角色互動、功能語言與問題修補方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-2-iv-9"
    data["title"] = "2-Ⅳ-9：在角色扮演中依角色、目的與安全情境完成互動"
    data["content"] = {"summary": "角色扮演不是背對話，而是在指定身份、目的、限制與事件變化中做出合理回應。顧客要先指出飲料錯誤，圖書館員要問線索並帶路，病人要說明症狀，旅客要提供位置與目的，班代要完整公告改教室，店員要回應預算，夥伴誤解邀請時要修補，看到積水要先警告，訪談者問完要聽並追問。本課以角色卡、目的卡、限制卡和突發卡推動原創場景，讓學生練習維持角色、達成任務、確認理解與在安全需要時清楚升級。", "sections": [{"heading": "角色卡決定你要提供什麼", "body": "同一句 Can you help me? 放在圖書館員、旅客、病人或顧客身上，後續資訊不同。先讀角色、對象、目的和限制，再選第一句；角色扮演的答案不是最漂亮的句子，而是能讓當下任務往前走的句子。"}, {"heading": "第一句要處理最急的缺口", "body": "飲料訂錯先說問題與正確需求，病人先說 sore throat 和持續多久，旅客先說要找 train station；不要一開始塞入無關背景。把 first line 當成資訊入口，讓對方能提出下一個有用問題。"}, {"heading": "誤解時要修補而非硬演", "body": "夥伴把 Saturday invitation 聽成 Sunday 時，可說 Sorry, I mean Saturday.，再補時間或請對方重述。訪談者問完問題要停下來聽、接住答案並追問，不能連續念自己的問題。角色互動包含聽者責任。"}, {"heading": "安全場景要優先清楚行動", "body": "看到教室積水時先警告 Keep away from the wet floor.，再通知老師或設置標示；安全角色不應為了維持故事而忽略立即風險。角色卡若含缺少房卡、早餐時間或改教室，也要把兩個目的都說清楚，避免只完成一半。"}]}
    data["studyHighlights"] = ["從角色、對象、目的與限制選擇合適的第一句。", "先處理最急的資訊缺口，再補背景與細節。", "以重述、修正、追問與聆聽維持雙向互動。", "在安全場景優先說出避開、通知與求助的行動。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "角色換了，第一句要不要跟著換？", "body": "給同一張 Can you help me? 卡片，讓學生分別扮演圖書館員、迷路旅客和店員。觀察三組後續需要的資訊不同，再讓學生為每個角色補一個最有用的第一句，感受角色不是換名字，而是改變任務與語句選擇。"}, {"id": "explain", "phase": "explain", "heading": "角色扮演五欄任務卡", "body": "每個場景填 Role、Partner、Goal、Limit、Next response 五欄。先找角色可知道或必須詢問的內容，再標出時間、預算、安全或雙重目的限制，最後預測對方回答後要如何接續，避免只演自己的台詞。"}, {"id": "worked-example", "phase": "worked-example", "heading": "把錯誤邀請修補回正確時間", "body": "以原創邀請被聽成 Sunday 為例，先說 Sorry, I mean Saturday.，再補 We can meet after lunch.，最後請對方確認。比較直接重複 Saturday 與提供完整修補的差異，讓學生看到 repair 要讓對方能重新建立共同理解。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "突發卡讓角色保持彈性", "body": "給餐飲、圖書館、診所、旅遊、商店、校園積水與訪談七組角色卡，再隨機加入 wrong time、missing item、safety risk 或 misunderstood invitation。學生不能重開劇本，只能依 Role、Goal、Limit 選下一句，同伴用任務卡檢查是否仍在角色內。"}, {"id": "transfer", "phase": "transfer", "heading": "雙重目的不能只完成一半", "body": "輪換旅館缺房卡加問早餐時間、班代公告改教室、店員提供較便宜選項與採訪追問。學生演出後讓觀眾列出角色完成的目的，若少一項，重演時用 and、also、Could you tell me …? 補齊資訊而不增加無關對話。"}, {"id": "reflect", "phase": "reflect", "heading": "我是依角色回應還是在背台詞？", "body": "回看錄音，標記角色資訊、目的完成、限制處理、聽者修補與安全行動。刪掉不屬於角色或沒有推進任務的句子；若遇突發卡就停住，補寫能確認理解、求助或轉交給適當人物的句型。"}], "summary": ["以 Role、Partner、Goal、Limit、Next response 五欄設計角色任務。", "先說最急缺口，再依對方反應補充資訊。", "用修正、重述、追問與聆聽維持共同理解。", "以安全行動和雙重目的檢查角色扮演是否完整。"], "exitCheck": [{"prompt": "角色扮演第一句應根據哪些資訊選擇？", "expectedEvidence": "能指出角色、對象、目的與限制，並先處理最急的資訊缺口。"}, {"prompt": "夥伴誤解時間時如何修補？", "expectedEvidence": "能明確更正時間，補充必要背景或替代方案，並確認對方是否理解。"}, {"prompt": "安全角色扮演和一般情境有何優先差異？", "expectedEvidence": "能先說出避開危險、通知適當人物或求助的立即行動，再繼續非緊急對話。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "依角色、對象、目的與限制完成雙向角色扮演，遇到誤解或安全風險時能修補並採取行動。", "scenario": "學生進入餐飲、旅館、圖書館、校園與訪談五個原創場景，抽取突發卡後仍要完成角色任務。", "variables": [{"symbol": "r", "meaning": "角色、對象與可掌握資訊"}, {"symbol": "g", "meaning": "互動目的與限制條件"}, {"symbol": "n", "meaning": "下一句、修補、追問與安全行動"}], "steps": [{"id": "step-1", "prompt": "In a role-play, you are a customer whose drink order is wrong. What should your first line do?", "options": ["Clearly say what is wrong and what drink you ordered.", "Tell the server a long unrelated story.", "Leave without telling anyone what happened."], "answer": "A", "feedback": "A gives the partner the information needed to correct the order and continue the role-play."}, {"id": "step-2", "prompt": "Your partner misunderstands your invitation as Sunday, but you meant Saturday. What should you do?", "options": ["Say, 'Sorry, I mean Saturday,' and add the needed time.", "Pretend the misunderstanding did not happen.", "End the conversation without correcting it."], "answer": "A", "feedback": "A repairs the shared understanding with a clear correction and useful follow-up information."}, {"id": "step-3", "prompt": "You play a student who sees water on the classroom floor. Which line is safest?", "options": ["Keep away from the wet floor and tell the teacher.", "Run across it before anyone notices.", "Invite more students to stand in the water."], "answer": "A", "feedback": "A prioritizes immediate safety and escalation to an appropriate adult."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語角色扮演、生活情境與功能溝通定位；核讀 2026-09-21。", ["以角色和生活任務使用基本英語完成互動。", "透過問答、模擬與情境修補支持溝通。"], ["餐飲、圖書館、醫療、旅遊、商店、校園與訪談。"], "只背自己的台詞，沒有聽取角色夥伴或處理任務限制。", "重視生活溝通、角色互動與問題解決。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語聽說、角色任務與合作活動定位；核讀 2026-09-21。", ["透過角色、圖片與情境活動完成英語任務。", "依對象、順序、禮貌與安全需要回應。"], ["點餐、問路、店員、公告、邀請、訪談與求助。"], "角色名稱換了但句子不變，或忽略安全、時間與雙重目的。", "評量主要內容、互動、禮貌、策略與任務完成。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語角色扮演、修補與情境評量定位；核讀 2026-09-21。", ["從角色目的、對話反應和限制形成適切口語。", "以修正、追問、聆聽與安全行動維持共同理解。"], ["role、goal、limit、repair、follow-up、safety、interview。"], "把角色扮演當單人背誦，沒有確認對方理解或處理突發事件。", "評量語意功能、角色一致性、互動修補、原因與安全回應。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持角色扮演、生活情境、功能語言與雙向互動。", "角色任務需整合身份、對象、目的、限制、對方反應、修補與下一步。", "從台詞選擇到突發情境可用角色卡、任務卡、觀眾回指與安全檢查驗證。"], "versionDifferences": ["南一較突顯生活情境與模擬溝通；康軒較突顯角色、圖片、合作活動與禮貌安全；翰林較突顯角色目的、對話修補、追問、聆聽與任務評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Role、Partner、Goal、Limit、Next response 五欄設計角色任務。", "用點餐、圖書館、診所、旅館、店員、校園積水與訪談原創場景加入突發卡。", "以雙重目的、聽者重述與安全升級檢查角色互動是否真正完成任務。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織角色、對象、目的、限制、第一句、修補、追問、聆聽、安全與雙重任務。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 五欄填完後讓搭檔先讀 Goal 和 Limit，再決定第一句；如果同一句放到另一角色也完全不用改，回頭檢查是否真的使用了角色資訊。"
    data["teaching"]["body"][4]["body"] += " 雙重目的場景要在結束前逐項確認，安全場景則先驗證危險是否被隔離；流暢度不能掩蓋只完成一半或跳過求助的問題。"
    data["teaching"]["body"][5]["body"] += " 若遇突發卡停住，先用確認、修正或求助句保留共同理解，再繼續原任務；評量的是能否恢復互動，不是是否完全照原稿。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "2-Ⅳ-9：在角色扮演中依角色、目的與安全情境完成互動", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 2-iv-9")


if __name__ == "__main__":
    main()
