import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/chinese/lesson-chinese-performance-6-iv-1.json"
REPORT=ROOT/"implementation/reports/chinese-performance-6-iv-1-first-pass-review.json"

def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher":name,"edition":f"{name} 公立校方國文課程計畫章節級證據","sourceType":"public-web","sourceLocator":locator,"reviewedAt":"2026-09-21","findings":{"concepts":concepts,"representations":forms,"examplesOrEvidence":["本課以原創校園倡議、社區公告、訊息對話與標點改寫卡，承接公開課程的標點運用、情感表達與說服溝通方向。"],"misconceptions":[misconception],"assessmentEmphasis":[assessment]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}

def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-chinese-performance-6-iv-1"
    data["title"]="6-Ⅳ-1：讓標點同時支撐情感、語氣與說服理由"
    data["content"]={"summary":"標點會改變讀者如何分辨語意、感受情緒與接受一項主張，但它不能獨自替代理由。驚嘆號可以提高行動迫切感，問號可以邀請思考或形成反問，破折號能把補充或核心要求推到前景，省略號能留下遲疑與未完，引號可標出特定詞義或質疑距離，分號則能並列對照而不切斷關係。本課以自編倡議、公告與對話練習，讓學習者先確認讀者和目的，再選擇標點、文字與理由，並檢查語氣是否明確而不壓迫。", "sections":[{"heading":"先問讀者與溝通目的","body":"同一句話寫給朋友、社區居民或校長，所需的直接程度和情感距離不同。動筆前先決定要提醒、邀請、質疑、安慰或提出要求，再看哪些資訊需要分開、強調或留下餘地；標點是溝通設計的一部分，不是情緒貼紙。"},{"heading":"標點把語氣推向不同方向","body":"問號可以是真問題，也可以引導讀者思考；驚嘆號能表現強烈感受或行動呼籲，但連用可能讓人覺得命令。破折號可把後文變成焦點，省略號可呈現猶豫或話未說完，引號可保留距離；判讀時要連同詞語與上下文。"},{"heading":"情感要和理由一起出現","body":"有感染力的倡議先讓讀者看見受影響的人或情境，再提出可行行動與理由，最後用適量標點安排節奏。若只有驚嘆號而沒有對象、證據或方法，讀者可能感到被催促卻不知道如何回應；若只有冷冰冰數據，也可能缺少投入入口。"},{"heading":"明確不等於壓迫","body":"公告或倡議要清楚寫出行動、時間、範圍與理由，同時承認讀者的處境。把『你們最好不要』改成說明影響、提出具體替代做法並保留詢問管道，通常比增加驚嘆號更能維持合作。修訂後要請讀者說出自己理解的要求與理由，才算有效。"}]}
    data["studyHighlights"]=["先界定讀者、目的與需要的情感距離。","依上下文理解問號、驚嘆號、破折號、省略號、引號與分號。","讓情感標點和具體理由、行動方法互相支撐。","兼顧明確、尊重、可行與讀者能否正確回應。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"同一個要求，為什麼有人想合作、有人想反抗？","body":"提供兩張完全自編的社區公告：一張大量使用命令和驚嘆號，另一張說明停車影響、替代位置與聯絡方式。請學習者先寫出兩版讀者可能感受到的壓力與清楚度，再圈出標點、詞語和理由如何共同造成差異，建立標點與關係而非單純情緒的入口。"},{"id":"explain","phase":"explain","heading":"標點情感說服三層檢查","body":"第一層確認符號的語意功能；第二層觀察它如何改變停頓、重音、情感距離與讀者注意；第三層檢查主張是否仍有對象、理由、證據和可行行動。三層要互相一致：若只提高語氣卻沒有理由，就降低強度或補上內容，而不是再加符號。"},{"id":"worked-example","phase":"worked-example","heading":"用問句邀請思考而不是逼迫回答","body":"以自編倡議『如果每個人都願意多走十分鐘，我們的街道會不會更安靜？』示範先判斷它不是尋找單一資訊的問題，而是邀請讀者想像行動效果。接著補上步行路線與安全條件，讓問句的情感入口後面跟著可檢驗的理由。"},{"id":"guided-practice","phase":"guided-practice","heading":"把命令公告修成合作邀請","body":"小組抽取含『你們最好不要』或連續驚嘆號的自編公告，先標出明確要求，再補影響、替代方案、期限與回應管道。朗讀兩版並請聽者重述自己要做什麼、為什麼要做；若只記得壓力沒有記得理由，就回到語氣和內容一起修。"},{"id":"transfer","phase":"transfer","heading":"為不同讀者選擇不同的標點力度","body":"把同一項校園減塑倡議分別寫給同學、家長與校方：同學需要短而可行的邀請，家長需要安全與成本說明，校方需要資料、期限與責任分工。三版都要保留核心主張，但依讀者距離調整問句、分號、破折號與句號的比例。"},{"id":"reflect","phase":"reflect","heading":"檢查我是不是用標點代替論證","body":"回看自己的文字，圈出所有驚嘆號、問號和引號，逐一寫明它們的功能與支持的內容。若符號只讓語氣變大卻沒有增加理解或行動線索，刪減並補理由；若語氣太硬，改用清楚的影響、替代方案與回應管道恢復合作空間。"}],"summary":["依讀者與目的決定標點的語意和情感力度。","把問號、驚嘆號、破折號、省略號、引號與分號放回上下文。","讓情感入口後面跟著理由、證據與可行行動。","透過讀者重述檢驗明確與尊重是否同時成立。"],"exitCheck":[{"prompt":"為什麼驚嘆號不是越多越有說服力？","expectedEvidence":"能說明驚嘆號只改變語氣強度，若沒有主張、理由、對象與行動，可能造成壓迫而非理解。"},{"prompt":"問號在倡議文中可能有哪兩種功能？","expectedEvidence":"能區分真問題與邀請思考／反問，並依上下文說明句尾語氣和後續理由。"},{"prompt":"如何把明確公告改得更尊重？","expectedEvidence":"能保留行動、期限與影響，同時補替代方案、理由和回應管道，而非只刪掉所有標點。"}]}
    data["interactive"]={"type":"guided-choice","goal":"依讀者與目的安排標點、語氣、理由與行動，完成有情感且不壓迫的說服文字。","scenario":"學生要把校園減塑倡議改寫成給同學、家長與校方的三種版本，先辨認目的，再測試標點力度與讀者理解。","variables":[{"symbol":"a","meaning":"讀者與倡議目的"},{"symbol":"p","meaning":"標點、語氣與理由"},{"symbol":"r","meaning":"讀者回應與修訂"}],"steps":[{"id":"step-1","prompt":"倡議句『我們現在就能從校園少用一個塑膠袋開始！』的驚嘆號主要作用是什麼？","options":["加強立即行動的號召感，但仍需搭配具體方法與理由","證明所有讀者都已經同意","取代任何證據和行動說明"],"answer":"A","feedback":"A 正確保留情感力量的範圍，不把強烈符號誤當成論證。"},{"id":"step-2","prompt":"同一句『你真的要這樣做嗎！』同時使用問號和驚嘆號，最需要注意什麼？","options":["要看上下文判斷是疑問、驚訝、責備或強烈反問，避免符號造成語氣誤讀","只要兩種符號一起用就一定更有感情","直接把句尾全部改成句號，內容不必檢查"],"answer":"A","feedback":"A 將符號放回情境、角色和語氣距離中解讀。"},{"id":"step-3","prompt":"要兼顧社區公告的明確與尊重，哪項修訂較佳？","options":["只刪掉驚嘆號，其他內容不變","說明停車造成的影響，提出替代位置與期限，保留詢問或協助管道","把『最好不要』改成更強烈的命令並加三個驚嘆號"],"answer":"B","feedback":"B 同時補上理由、可行方法與回應空間，比單純調整符號更能促成合作。"}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；國語文標點、情感表達與實用溝通定位；核讀 2026-09-21。",["以標點與文字表達情感、語氣及溝通目的。","將書面語句轉成清楚而適切的表達。"],["倡議、公告、問句、引號、破折號與分號。"],"把標點當情緒裝飾或用增加符號替代理由。","重視語意、情感、說服與讀者適切性。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；國語文書寫、標點與表達實作定位；核讀 2026-09-21。",["透過觀察、改寫與討論理解標點的表達效果。","依讀者、文本形式與目的修正語氣。"],["校園倡議、社區公告、訊息對話、標點改寫與讀者回饋。"],"只改標點不改內容，或把強硬當成有說服力。","要求表達清楚、有理由並能接受回饋。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；國文標點、情感與說服評量定位；核讀 2026-09-21。",["從標點、語氣與文本目的理解情感與說服。","兼顧主張、理由、讀者關係與表達責任。"],["問號、驚嘆號、省略號、引號、分號、倡議與公告。"],"把問號、驚嘆號或省略號套用固定語氣公式。","評量標點功能、情感表達、說服理由與溝通尊重。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持標點運用、情感表達、說服溝通與讀者適切性。","標點功能要連同上下文、目的、理由與讀者關係理解。","情感力度不能取代證據、方法與尊重。"],"versionDifferences":["南一較突顯標點、情感與實用表達；康軒較突顯觀察、改寫、討論與讀者回饋；翰林較突顯標點功能、說服理由與溝通責任。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以標點情感說服三層檢查連結符號、語氣與論證。","用社區公告前後版本測試明確、尊重與可行性。","按同學、家長與校方調整相同倡議的語氣與理由。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織標點功能、情感距離、說服理由、讀者適切與修訂回饋。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 在每次改寫旁標明讀者、目的與預期回應，並把標點造成的聲音效果和文字提供的理由分開檢查，避免把語氣增大誤認為說服力增加。"
    data["teaching"]["body"][4]["body"] += " 比較三種版本時固定核心主張，再調整資訊順序、證據密度與標點力度；若讀者背景不同，優先補充他需要的理由而非只改情緒詞。"
    data["teaching"]["body"][5]["body"] += " 請讀者用一句話重述要求、理由和可以採取的行動，若只能重述情緒或壓力，就回到內容與語氣一起修訂。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"6-Ⅳ-1：讓標點同時支撐情感、語氣與說服理由","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored chinese performance 6-iv-1")

if __name__=="__main__": main()
