import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/english/lesson-english-performance-1-iv-5.json"
REPORT=ROOT/"implementation/reports/english-performance-1-iv-5-first-pass-review.json"

def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher":name,"edition":f"{name} 公立校方英語課程計畫章節級證據","sourceType":"public-web","sourceLocator":locator,"reviewedAt":"2026-09-21","findings":{"concepts":concepts,"representations":forms,"examplesOrEvidence":["本課以原創簡易歌謠、韻文、重複句與動作卡，承接公開課程的韻文理解、節奏音韻與生活情境表達方向。"],"misconceptions":[misconception],"assessmentEmphasis":[assessment]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}

def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-english-performance-1-iv-5"
    data["title"]="1-Ⅳ-5：從簡易歌謠與韻文的聲音線索理解主要內容"
    data["content"]={"summary":"理解簡易歌謠與韻文，不必先翻譯每個字，也不能只追逐押韻的聲音；要把重複、節奏、動作、順序、意象和結尾變化連到主要內容。本課以原創校園歌謠、花園任務、風箏修理、雨天改期、節慶街景和合作圈活動為材料，先聽或讀出反覆線索，再用圖片、動作和簡短英文摘要重建誰做什麼、事情如何變化以及作品想傳達的簡單訊息。", "sections":[{"heading":"先抓重複和主要動作","body":"歌謠中的重複句或短語通常幫助聽者記住主題，但真正的內容還要看每節出現的動作和對象。看到 *Wash, rinse, dry!*，先把它連到後文的清潔步驟，再判斷作品是在提醒程序、描述習慣或鼓勵合作，不要只回答『這些字重複很多』。"},{"heading":"節奏和押韻是線索不是答案","body":"押韻、拍手和相似句尾能讓作品容易跟唱，卻不會自動告訴我們主旨。用每行的動詞、人物、地點和順序卡整理內容；若最後一行出現轉折或結果，要把它和前面比較，因為韻文常用簡短結尾完成變化。"},{"heading":"用圖像和動作確認理解","body":"簡易韻文適合用圖片、手勢、排序和跟讀檢查。先把 *pack, take, help, grow* 排成任務順序，再用一句話說明誰在幫花園；若只能唱出聲音卻無法排出動作，表示音韻記憶尚未連到內容理解。"},{"heading":"摘要要短但不能漏掉結果","body":"作品摘要可以是一句簡單英文或中文，但要保留人物／對象、主要行動和結果或情感變化。遇到 *but, then, so, after* 等線索，不能把前半段和後半段拆成兩個無關事件；選項若只描述場景或押韻形式，通常不足以代表主要內容。"}]}
    data["studyHighlights"]=["以重複短語、動詞、人物與對象定位主題。","把押韻與節奏當成記憶線索，不代替內容判讀。","用圖片、動作和順序卡重建韻文事件。","用短摘要保留主要行動、結果與轉折。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"聽得出押韻就代表聽懂了嗎？","body":"播放或朗讀一段完全自編的花園韻文，請學習者先拍出重複節奏，再把 *pack, take, help, grow* 圖卡排成故事順序。比較只會跟唱和能說出誰做什麼、最後發生什麼的差異，建立聲音線索連到內容的入口。"},{"id":"explain","phase":"explain","heading":"歌謠韻文四格理解卡","body":"第一格圈出重複詞和押韻詞；第二格標人物、動詞、物件與地點；第三格用圖卡或動作排順序；第四格寫一句主旨摘要並檢查 but、then、so、after 等轉折。每格都要回到歌詞或韻文行句，避免只用歌曲氣氛猜答案。"},{"id":"worked-example","phase":"worked-example","heading":"從雨聲和改期讀出主要事件","body":"以自編韻文 *Rain taps softly on the roof. We move our picnic to the hall.* 示範：第一行建立天氣情境，第二行呈現因天氣而改變的計畫。押韻或聲音效果可以讓畫面更鮮明，但主旨要保留雨天、野餐和改到室內三項內容。"},{"id":"guided-practice","phase":"guided-practice","heading":"用節拍和動作理解程序歌謠","body":"小組練習含 *Wash, rinse, dry!* 的自編清潔歌謠，先跟著節拍朗讀，再把三張動作卡排好，最後用簡單英文告訴同伴下一步。若學生只重複聲音卻排錯順序，回到動詞與圖片，不用加快速度掩蓋理解缺口。"},{"id":"transfer","phase":"transfer","heading":"把韻文策略帶到不同主題","body":"輪換花園、風箏、節慶街景、班級圈和校外活動韻文，固定四格理解卡但改變人物、動作與結果。學生要選一張最能代表主要內容的圖，再說一個簡短摘要；若結尾改變了原計畫，必須在摘要中保留這個變化。"},{"id":"reflect","phase":"reflect","heading":"檢查我是否只記得聲音","body":"回看作品，將答案分成來自重複聲音、動作與事件、結尾結果或自己的想像。刪掉只描述節奏卻沒有內容證據的選項，補上至少一個動詞和一個結果；若不確定，用 *The rhyme is about...* 搭配作品中的詞句說明範圍。"}],"summary":["由重複、動詞、人物與結果建立韻文主線。","把押韻和節奏當記憶支架，不把形式當主旨。","用圖卡、動作與順序理解歌謠事件。","以短摘要保留轉折、結果和情感變化。"],"exitCheck":[{"prompt":"為什麼押韻不能直接等於韻文主旨？","expectedEvidence":"能說明押韻協助記憶和跟讀，主要內容仍要由人物、動作、順序與結果判斷。"},{"prompt":"如何用動作卡檢查是否聽懂簡易歌謠？","expectedEvidence":"能依歌詞動詞排出順序，再用簡短英文或中文說明任務如何完成。"},{"prompt":"摘要簡易韻文時哪些內容不能漏掉？","expectedEvidence":"能保留人物或對象、主要行動、結果／轉折與必要情境，而非只描述聲音。"}]}
    data["interactive"]={"type":"guided-choice","goal":"利用重複、節奏、動詞、順序與結尾變化理解簡易歌謠與韻文主要內容。","scenario":"學生要帶領同伴學唱一首自編校園韻文，先找聲音線索，再排動作卡、判斷結果並用短英文摘要。","variables":[{"symbol":"s","meaning":"重複、節奏與押韻"},{"symbol":"a","meaning":"動作、人物與順序"},{"symbol":"m","meaning":"主旨、結果與轉折"}],"steps":[{"id":"step-1","prompt":"Verse: 'Pack a seed and take a spade, / Help the little garden grow.' What is the main idea?","options":["A student helps start or care for a garden.","A student buys a new school uniform.","A student gets lost in a busy street."],"answer":"A","feedback":"A combines the actions and object in the verse; the rhyme describes helping a garden grow."},{"id":"step-2","prompt":"A chant repeats, 'Wash, rinse, dry!' What should the listener focus on?","options":["The three-step cleaning order.","Only the final rhyme sound.","A plan to move a picnic indoors."],"answer":"A","feedback":"A uses the repeated verbs as a procedure, not just as a sound pattern."},{"id":"step-3","prompt":"'Rain taps softly on the roof. We move our picnic to the hall.' What changes?","options":["The picnic plan changes because of the rain.","The students cancel every future activity.","The song changes only its rhyme, not its event."],"answer":"A","feedback":"A preserves the weather cause and the new indoor plan stated by the two lines."}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語歌謠韻文、音韻與生活情境定位；核讀 2026-09-21。",["由歌謠韻文的聲音與情境理解簡易內容。","以重複、節奏與動作支援英語學習。"],["歌謠、韻文、押韻、跟讀、動作與主旨。"],"只注意押韻或跟唱，忽略動作、順序與結果。","重視音韻、內容理解與情境使用。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語歌謠、韻文與課堂活動定位；核讀 2026-09-21。",["透過歌唱、節奏、圖片與活動理解韻文。","依重複詞、動詞與事件順序重建內容。"],["校園、花園、清潔、天氣、節慶與合作歌謠。"],"把歌曲氣氛或單一押韻詞當成主要內容。","要求跟讀、辨識、動作與簡短摘要。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語歌謠韻文、音韻理解與評量定位；核讀 2026-09-21。",["從聽讀活動掌握簡易歌謠韻文主要內容。","以聲音、語意、圖片與順序線索形成理解。"],["短歌、韻文、重複、押韻、主旨、細節與結果。"],"把聲音形式等同於內容理解，或只依熟悉字詞猜主旨。","評量主要內容、關鍵動作、順序與簡易推論。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持歌謠韻文、音韻節奏、圖片動作與簡易內容理解。","重複、押韻與節奏要連到動詞、人物、順序與結果。","從跟唱到主旨理解需要動作、圖像、排序與摘要。"],"versionDifferences":["南一較突顯歌謠韻文與生活情境；康軒較突顯歌唱、節奏、圖片與活動；翰林較突顯聽讀、音韻、語意與內容評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以花園、清潔與雨天改期韻文連結聲音和主要事件。","用四格理解卡將重複、動詞、順序與結果分開。","以英文短摘要和同伴動作驗證歌謠理解。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織簡易歌謠韻文的重複、押韻、節奏、動作、順序、主旨與結果。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 每一個主旨判斷旁都要貼回至少一個動詞和一個結果線索，並將純粹聲音效果標成記憶支架；若兩者混在一起，重新用圖卡重建事件。"
    data["teaching"]["body"][4]["body"] += " 更換主題時固定理解流程，再改變人物、動作、情緒與結尾結果，讓學生必須依每首韻文的新證據調整摘要。"
    data["teaching"]["body"][5]["body"] += " 請同伴只看你的英文摘要排動作卡，若無法重建順序或結果，回到作品找遺漏的 then、after、but 或核心動詞。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"1-Ⅳ-5：從簡易歌謠與韻文的聲音線索理解主要內容","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored english performance 1-iv-5")

if __name__=="__main__": main()
