#!/usr/bin/env python3
"""Independent first-pass authoring for math n-IV-2."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/'lessons/math/lesson-math-performance-n-iv-2.json'
REPORT=ROOT/'implementation/reports/math-performance-n-iv-2-first-pass-review.json'
URLS={'nani':'https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf','kanghsuan':'https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110','hanlin':'https://www.cp.ptc.edu.tw/storage/134513/134513_112_B-1_9A.pdf'}
def rec(p,c,r,m,a):
 return {'publisher':p,'edition':f'{p} 公立校方數學課程計畫章節級證據','sourceType':'public-web','sourceLocator':f'{URLS[p]}；負數數線與四則運算評量欄位；核讀 2026-09-21。','reviewedAt':'2026-09-21','findings':{'concepts':[c,'公開結構支持以數線方向、絕對值與運算規則理解正負數關係。'],'representations':[r],'examplesOrEvidence':['本課的溫度、帳戶與海拔情境均為原創，只承接公開課程的能力方向。'],'misconceptions':[m],'assessmentEmphasis':[a]},'licenseBoundary':'只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。'}
def main():
 d=json.loads(LESSON.read_text(encoding='utf-8')); assert d['id']=='lesson-math-performance-n-iv-2' and d['reviewStatus']=='draft'
 d['title']='n-Ⅳ-2：用數線理解負數四則運算'
 d['content']={'summary':'負數不是「比較小的數字」而已；它在數線上有方向，也會改變加減乘除的結果。本課以溫度升降與帳戶收支的原創情境，把相反數、絕對值、數線位移、乘除符號規則串起來，讓學生先預測方向，再計算並用估算與情境單位回查，避免只背負負得正。','sections':[{'heading':'數線上的位置與方向','body':'0 是參考點，正數在右、負數在左；相反數到 0 的距離相同但方向相反。比較負數時，越靠右越大，不能只看數字的絕對值。'},{'heading':'加減是位移','body':'在數線上加正數向右、加負數向左；減去一個數等於加上它的相反數。先畫方向再算符號，能看見 −3−(−5) 為何等於 2。'},{'heading':'乘除符號與量的大小','body':'同號相乘為正、異號相乘為負；先判斷符號，再處理絕對值大小。除法同樣要確認除數不為零，不能把符號和數值混在同一步。'},{'heading':'情境的正負要有基準','body':'溫度下降、欠款、海拔低於基準都要先選定 0 的意義。若基準換了，數字的正負可能改變，但相對差異與計算關係仍需保持一致。'}]}
 d['studyHighlights']=['先選基準點，再讀數線方向與正負。','減法改寫成加相反數，用位移檢查結果方向。','乘除先判斷符號，再計算絕對值與單位。','把負數結果回放到溫度、收支或高度情境驗證。']
 d['teaching']={'body':[{'id':'hook','phase':'hook','heading':'溫度先降再升','body':'原創天氣紀錄從 3°C 下降 7°C，再上升 4°C；學生先在數線上畫兩段箭頭，預測最後溫度。先以方向理解 −7 與 +4，再進入算式，避免符號只停留在記號。'},{'id':'explain','phase':'explain','heading':'減法的相反數','body':'從 −3−(−5) 開始，將減去 −5 改寫為加上 +5，數線從 −3 向右五格到 2。並比較 −3−5 的向左位移，讓括號與符號意義清楚分開。'},{'id':'worked-example','phase':'worked-example','heading':'先符號後大小','body':'計算 (−6)×(−4)=24 與 (−24)÷6=−4；先圈出同號或異號，再處理 6×4 或 24÷6。用帳戶欠款與還款情境回查正負是否合理。'},{'id':'guided-practice','phase':'guided-practice','heading':'找出符號錯誤','body':'提供三個運算結果，學生先不用計算絕對值，只選正或負，再用數線或估算核對大小。若把 −(−3) 寫成 −3，回饋要求指出相反數方向，而非直接公布答案。'},{'id':'transfer','phase':'transfer','heading':'海拔與帳戶的共同結構','body':'一個地點在海平面下 40 公尺，向上移動 15 公尺；另一個帳戶欠款 40 元，存入 15 元。學生用同一條數線模型說明兩個情境的結果與基準。'},{'id':'reflect','phase':'reflect','heading':'符號、方向、單位三檢查','body':'出口題要求學生圈出基準、運算方向與單位，並把一個負數結果翻成完整情境句。最後說明若只看絕對值，哪一步會失去方向資訊。'}],'summary':['先選基準與數線方向，再判斷正負。','減法改寫為加相反數，用位移驗證。','乘除先判斷同號異號，再計算絕對值。','用情境基準、方向與單位回查負數答案。'],'exitCheck':[{'prompt':'−3−(−5) 為什麼等於 2？','expectedEvidence':'減去負數等於加正數，數線從 −3 向右五格到 2。'},{'prompt':'(−6)×(−4) 的符號如何判斷？','expectedEvidence':'兩數同號相乘為正，再計算絕對值 24。'},{'prompt':'負海拔的負號代表什麼？','expectedEvidence':'相對於海平面基準的方向，不是單純表示數字錯誤。'}]}
 d['interactive']={'type':'guided-choice','goal':'以數線位移與符號規則完成負數四則運算。','scenario':'調整溫度升降或帳戶收支，觀察位置、方向、運算式與單位同步更新。','variables':[{'symbol':'x','meaning':'目前相對基準的數值'},{'symbol':'d','meaning':'變化量與方向'}],'steps':[{'id':'step-1','prompt':'在數線上加 −7 代表什麼方向？','options':['向左七格','向右七格','停在原點'],'answer':'A','feedback':'負數代表相對基準向左的位移。'},{'id':'step-2','prompt':'−3−(−5) 應改寫為什麼？','options':['−3+5','−3−5','3−5'],'answer':'A','feedback':'減去一個數等於加上它的相反數。'},{'id':'step-3','prompt':'(−6)×(−4) 的符號是什麼？','options':['正','負','零'],'answer':'A','feedback':'兩個負數同號相乘為正。'}]}
 for i, extra in enumerate(['並將每段箭頭的起點、方向與單位寫在圖上，說明預測如何轉成算式。','再用另一個數線起點回算，確認括號負號和相反數的方向沒有被省略。','最後把兩個答案翻成欠款或還款的完整句子，檢查符號和單位是否一致。','要求學生先說明是相反數錯誤還是絕對值錯誤，再選擇對應的修正證據。','並比較海平面與帳戶零元這兩個基準，說明同一數線規則如何換成不同語境。','最後把基準、方向、運算與單位各寫一項，形成可重做的檢查順序。']):
  d['teaching']['body'][i]['body'] += ' ' + extra
 d['authoringStandard']='version-fused-v1'; d['versionResearch']=[rec('nani','以數線、相反數與四則運算建立正負數關係','數線、位移、絕對值與運算式的互相轉換','只看絕對值或把減負數的方向誤判而未畫出位移','完整核對方向、符號規則、數值與單位回查'),rec('kanghsuan','以操作和情境表徵理解負數加減與乘除','溫度、數線箭頭與符號卡的同步呈現','同號異號規則混用或不看括號中的負號','操作後完整解釋方向與符號如何互相對應'),rec('hanlin','在收支、海拔與變化量情境中選擇基準','基準、正負、差異與單位限制的情境表徵','忽略基準意義或只翻譯數字而不翻譯方向','評估模型選擇、計算與情境句是否完整')]
 d['fusionRecord']={'commonCore':['三版本公開結構共同支持以數線與相反數理解正負數。','加減的方向與乘除的符號規則需要分開建構並回查。','負數結果要連結基準、單位與情境意義。'],'versionDifferences':['南一證據較突顯數線與運算規則；康軒較突顯操作、溫度與符號表徵；翰林較突顯收支、海拔與基準情境。這是公開課程計畫層級差異，不宣稱完整教材差異。'],'originalAdditions':['以溫度升降引出數線位移與相反數。','用欠款／還款診斷括號與乘除符號。','將海拔與帳戶轉移到共同基準模型。'],'llmSynthesisNote':'本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG 重新設計負數數線、四則運算與情境基準。正文、例題、互動與回饋均為原創，未複製教材；Terra 第二輪與正式發布審查尚未完成，維持 draft。'}
 d['updatedAt']='2026-09-21'; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 REPORT.write_text(json.dumps({'unit':'n-Ⅳ-2：用數線理解負數四則運算','lessonId':d['id'],'status':'first-pass-ai-review-complete','reviewStatus':'draft','checks':{'unitSpecificOriginalContent':True,'threeVersionResearchRecords':True,'fusionRecordPresent':True,'interactivePredictionManipulationExplanation':True,'terraSecondPass':'pending'},'reviewedAt':'2026-09-21'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps({'lesson':str(LESSON.relative_to(ROOT)),'reviewStatus':d['reviewStatus']},ensure_ascii=False))
if __name__=='__main__': main()
