import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-performance-ti-iv-1.json"; REPORT=ROOT/"implementation/reports/science-performance-ti-iv-1-first-pass-review.json"
URLS={"nani":"https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf","kanghsuan":"https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110","hanlin":"https://drive.google.com/uc?id=1gMUVcDjfXmqIapg-fNnfPuLFaK98dxGX&export=download"}
def rec(p,c,r,m,a): return {"publisher":p,"edition":f"{p} 公立校方自然課程計畫章節級證據","sourceType":"public-web","sourceLocator":f"{URLS[p]}；方法改變、創新推想與評量欄位；核讀 2026-09-21。","reviewedAt":"2026-09-21","findings":{"concepts":[c,"公開課程結構支持改變觀察或實驗方法前提出預測，考量控制條件、安全與可檢驗結果。"],"representations":[r],"examplesOrEvidence":["本課的紙橋、溶解速度與影子觀察皆為原創方法改變情境，只承接公開課程所示的能力方向。"],"misconceptions":[m],"assessmentEmphasis":[a]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。"}
def main():
 d=json.loads(LESSON.read_text(encoding="utf-8")); assert d["id"]=="lesson-science-performance-ti-iv-1" and d["reviewStatus"]=="draft"
 d["title"]="ti-Ⅳ-1：改變觀察或實驗方法的結果想像與創新——先預測，再讓方法接受檢驗"
 d["content"]={"summary":"改變實驗方法不是隨意換材料，而是先問『如果改變某個條件，結果可能如何不同？為什麼？』再保留能公平比較的條件、設計安全程序和可記錄指標。創新可以來自不同材料、觀察角度、取樣方式或資料呈現，但每個新想法都要說明預測、機制、限制與檢查方式。本課用紙橋、溶解速度和影子觀察三個原創情境，練習把想像轉成可測試方案。","sections":[{"heading":"改變一件事，先說會變什麼","body":"若紙橋把平面改成波浪形，預測承重可能改變，理由可能是受力分散；預測不是答案，而是讓結果能被比較。先指定改變項和要觀察的結果，避免一次改太多而無法解釋。"},{"heading":"創新仍需要公平比較","body":"新方法要保留材料量、測量時間、起始條件和停止標準等控制條件。若為了安全或可行性必須改變多項，就要承認比較限制，並設計分階段測試。"},{"heading":"從失敗結果找下一個想法","body":"結果不符合預測不代表創意沒有價值；可能揭露假設不完整、指標不適合或程序不穩定。記錄失敗條件，再提出能區分原因的第二版方法，比直接換成另一個故事更有用。"},{"heading":"創新要對人和環境負責","body":"新方法需檢查器材、重物、化學品、生物和場域風險。能省材料、減少干擾、提高可及性或讓資料更清楚的設計，才是有證據和責任的創新。"}]}
 d["studyHighlights"]=["對改變的條件、結果與理由提出可檢驗預測。","保留控制條件、停止標準、安全與公平比較。","從不符預測的結果定位假設、指標或程序缺口。","把創新連結資源、可及性、環境與責任。"]
 d["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"波浪紙橋一定比較強嗎？","body":"三組同學把紙張折成平面、波浪和管狀，卻同時改了紙張長度與砝碼加法。請先為每種形狀寫預測與理由，再圈出哪些條件必須固定，讓創新想法能和原方法公平比較，而不是只看最後最高數字。"},{"id":"explain","phase":"explain","heading":"方法創新四格表","body":"寫下改變什麼、預測結果、理由模型和如何檢查，再補控制條件、安全與失敗後的下一步。四格表迫使想像連到證據；沒有預測或檢查方式的點子仍只是主意。"},{"id":"worked-example","phase":"worked-example","heading":"溶解速度的新攪拌法","body":"原方法固定水溫和糖量，只改攪拌速度；創新版想用旋轉容器。先預測旋轉是否改變接觸面與溶解時間，再固定水量、溫度、糖粒和停止定義，分階段比較，避免把容器形狀和攪拌同時改掉。"},{"id":"guided-practice","phase":"guided-practice","heading":"影子觀察換角度","body":"把影子由地面尺量改成照片分析，可能提高保存性，也可能受相機角度和比例尺影響。學習者預測兩項結果，補上固定相機位置、比例尺、時間與校正步驟，再設計交叉檢查。"},{"id":"transfer","phase":"transfer","heading":"第二版方法設計會","body":"每組拿一個不符預測的結果，提出兩個可能原因和一個方法改變；同學只問能否區分原因、是否安全、哪些條件仍固定。最後寫出若第二版仍失敗，下一個要保留或放棄的假設。"},{"id":"reflect","phase":"reflect","heading":"修正兩個創新迷思","body":"請修正『越奇怪的點子越創新』與『結果不符預測就代表失敗』。創新要能改善問題、說明理由、接受比較並負責任；不符預測能揭露模型限制，提供下一輪設計線索。"}],"summary":["把方法改變寫成條件、結果、理由與可檢驗預測。","固定必要條件並設計公平、安全、可重做的比較。","從不符預測的資料修正假設或程序。","讓創新改善證據、資源、可及性與責任，而非只求奇特。"],"exitCheck":[{"prompt":"改變紙橋形狀時為何要固定紙量和加重方式？","expectedEvidence":"避免多個因素同時改變，才能把承重差異與形狀連結。"},{"prompt":"照片分析影子要補哪些控制？","expectedEvidence":"固定相機位置、比例尺、拍攝時間、光源條件與校正，並與尺量交叉檢查。"},{"prompt":"結果不符預測時如何繼續創新？","expectedEvidence":"檢查假設、指標和程序，提出能區分原因的第二版方法，而不是任意更換故事。"}]}
 d["interactive"]={"type":"guided-choice","goal":"把方法改變的想像轉為有預測、控制、安全與再測的創新方案。","scenario":"比較紙橋、溶解速度與影子觀察的新方法，逐步檢查公平性和可檢驗性。","variables":[{"symbol":"c","meaning":"改變條件"},{"symbol":"p","meaning":"預測與理由"},{"symbol":"t","meaning":"測試與安全"}],"steps":[{"id":"step-1","prompt":"創新改變紙橋時先寫什麼？","options":["指定改變形狀、預測承重與理由，再固定紙量和加重程序","只挑看起來最酷的形狀","同時換紙張、長度與砝碼"],"answer":"A","feedback":"A 讓想法能公平比較並回到受力理由。"},{"id":"step-2","prompt":"改用照片量影子要如何確保可比較？","options":["固定相機、比例尺、時間與光源，並用尺量交叉檢查","每次從不同角度拍照","只挑最清楚的照片","刪除照片中的陰影"],"answer":"A","feedback":"A 把新方法的偏差來源納入控制和校正。"},{"id":"step-3","prompt":"創新版方法仍不符預測時，最適合做什麼？","options":["檢查假設、指標和程序，提出能區分原因的下一版測試","直接宣布創新毫無價值","修改資料使預測成立","換一個完全無關的問題"],"answer":"A","feedback":"A 把不符預測轉成可用的設計線索。"}]}
 d["teaching"]["body"][1]["body"]="寫下改變什麼、預測結果、理由模型和如何檢查，再補控制條件、安全與失敗後的下一步。四格表迫使想像連到證據；沒有預測或檢查方式的點子仍只是主意，還要說明什麼結果會支持或削弱這個想法。"
 d["teaching"]["body"][3]["body"]="把影子由地面尺量改成照片分析，可能提高保存性，也可能受相機角度和比例尺影響。學習者預測兩項結果，補上固定相機位置、比例尺、時間與校正步驟，再設計交叉檢查，並寫出照片與尺量不一致時如何查原因。"
 d["teaching"]["body"][4]["body"]="每組拿一個不符預測的結果，提出兩個可能原因和一個方法改變；同學只問能否區分原因、是否安全、哪些條件仍固定。最後寫出若第二版仍失敗，下一個要保留或放棄的假設，以及要記錄的判斷依據。"
 d["teaching"]["body"][5]["body"]="請修正『越奇怪的點子越創新』與『結果不符預測就代表失敗』，並各舉一個方法例子。創新要能改善問題、說明理由、接受比較並負責任；不符預測能揭露模型限制，提供下一輪設計線索。"
 d["authoringStandard"]="version-fused-v1"
 d["versionResearch"]=[rec("nani","以觀察、實驗和方法變化想像結果並提出創新方案。","改變條件、預測、控制、測試、失敗與修正。","把新奇點子或不符預測當成創新完成。","重視可檢驗預測、方法公平與安全。"),rec("kanghsuan","透過實作、討論與修正探索不同方法的效果。","材料、程序、分階段測試、同儕回饋與再設計。","一次改很多條件，或用結果事後編理由。","評量預測、控制、創意理由與再測。"),rec("hanlin","連結生活實驗、工程與環境情境，將創新和責任、資源及可及性結合。","紙橋、溶解、影子、材料、安全、可逆與限制。","只追求奇特，忽略受影響者、風險與證據。","要求創新有目的、方法透明、資料支持與責任。")]
 d["fusionRecord"]={"commonCore":["三版本公開結構共同支持改變觀察或實驗方法、想像結果並提出創新。","預測、理由、控制、測試、安全、修正與溝通是共同要求。","創新不是奇特或成功一次，而是能改善問題並接受證據檢驗。"],"versionDifferences":["南一證據較突顯觀察、實驗與基本方法變化；康軒較突顯實作、分階段測試、同儕回饋與再設計；翰林較突顯生活工程、環境、資源、可及性與責任。這是公開課程計畫層級差異，不宣稱完整教材差異。"],"originalAdditions":["以平面、波浪、管狀紙橋建立預測和公平控制。","以旋轉容器改變攪拌方法示範分階段比較。","以照片量影子導入比例尺、角度、校正與交叉檢查。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織方法改變、預測、理由、控制、創新、失敗、修正、安全與責任。正文、原創情境、互動步驟、錯誤回饋與檢核均為本專案重寫，未複製任何教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
 d["updatedAt"]="2026-09-21"; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"ti-Ⅳ-1：改變觀察或實驗方法的結果想像與創新","lessonId":d["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 print("ti-iv-1 lesson authored")
if __name__=="__main__": main()
