#!/usr/bin/env python3
"""Independent first-pass authoring for math n-IV-1."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/'lessons/math/lesson-math-performance-n-iv-1.json'
REPORT=ROOT/'implementation/reports/math-performance-n-iv-1-first-pass-review.json'
URLS={'nani':'https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf','kanghsuan':'https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110','hanlin':'https://www.cp.ptc.edu.tw/storage/134513/134513_112_B-1_9A.pdf'}
def rec(p,c,r,m,a):
 return {'publisher':p,'edition':f'{p} 公立校方數學課程計畫章節級證據','sourceType':'public-web','sourceLocator':f'{URLS[p]}；因數、倍數、質數與最大／最小公倍公因數評量欄位；核讀 2026-09-21。','reviewedAt':'2026-09-21','findings':{'concepts':[c,'公開結構支持以質因數分解與整除關係處理公因數、公倍數及週期問題。'],'representations':[r],'examplesOrEvidence':['本課的燈號週期、分組與因數樹均為原創，只承接公開課程的能力方向。'],'misconceptions':[m],'assessmentEmphasis':[a]},'licenseBoundary':'只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。'}
def main():
 d=json.loads(LESSON.read_text(encoding='utf-8')); assert d['id']=='lesson-math-performance-n-iv-1' and d['reviewStatus']=='draft'
 d['title']='n-Ⅳ-1：用質因數分解整理整除關係'
 d['content']={'summary':'因數與倍數是一對從整除關係出發的語言；最大公因數找共同結構，最小公倍數找共同週期。本課以不同燈號同時閃爍與班級分組的原創情境，讓學生先列因數與倍數，再用質因數分解的指數取小／取大整理，最後檢查答案是否真的符合共同、最大或最小的條件。','sections':[{'heading':'因數與倍數的方向','body':'若 3×4=12，3 和 4 是 12 的因數，12 是 3 和 4 的倍數；兩個詞的方向相反。先說清楚正在找誰的因數或誰的倍數，才能避免名詞倒置。'},{'heading':'質因數分解拆出骨架','body':'把數寫成質數乘積，例如 60=2²×3×5，可以看見它由哪些基本因子組成。共同因數只保留兩數都出現的質因數與較小指數。'},{'heading':'最大公因數與最小公倍數用途不同','body':'最大公因數適合把物品分成最大且相同的組；最小公倍數適合找不同週期下一次同時發生的時間。先讀情境中的共同分組或共同週期，再選工具。'},{'heading':'答案要驗證條件','body':'求最大公因數後要確認能整除兩數且沒有更大的共同因數；求最小公倍數後要確認是兩數倍數且沒有更小的正共同倍數。'}]}
 d['studyHighlights']=['先辨認因數、倍數與整除方向。','用質因數分解看共同結構，再依最大或最小取指數。','分組問題常找最大公因數，週期問題常找最小公倍數。','把答案代回整除、共同與最小／最大條件驗證。']
 d['teaching']={'body':[{'id':'hook','phase':'hook','heading':'兩盞燈何時再一起亮','body':'一盞燈每 6 秒閃一次，另一盞每 8 秒閃一次，請學生列出前幾次閃爍時間並預測下一個共同時刻。讓最小公倍數從週期表格中自然出現，而不是先公布名稱。'},{'id':'explain','phase':'explain','heading':'用因數樹看共同質因數','body':'把 36 與 60 分別拆成質因數，圈出兩者共同的 2 與 3；取較小指數得到 12。再把 12 乘回兩數，確認它同時整除 36 與 60。'},{'id':'worked-example','phase':'worked-example','heading':'分組與週期的對照','body':'48 顆紅珠與 60 顆藍珠要分成最多且每組相同，求最大公因數 12；兩盞燈 6、8 秒同閃則求最小公倍數 24。比較兩題的語意與驗證方式。'},{'id':'guided-practice','phase':'guided-practice','heading':'指數取小或取大','body':'給 2³×3² 與 2²×3×5，學生先判斷找最大公因數或最小公倍數，再在每個質因數旁選較小或較大指數。最後用整除與倍數列表回查。'},{'id':'transfer','phase':'transfer','heading':'排班與包裝規格','body':'兩種物品每 9 件與每 12 件一包，倉庫要讓包裝數量同時整除兩種需求或找下一次同時補貨時間。學生先說明是共同分組還是共同週期，再選 GCD 或 LCM。'},{'id':'reflect','phase':'reflect','heading':'名稱與用途的最後檢查','body':'出口題給出一個把最大公因數與最小公倍數對調的解法，學生要圈出語意錯誤、寫出正確工具並用一個數值驗證，避免只靠關鍵字猜。'}],'summary':['先確認因數、倍數與題目方向。','質因數分解呈現共同結構，指數取小或取大取決於任務。','共同分組多用最大公因數，共同週期多用最小公倍數。','回查整除與倍數，確認最大或最小條件。'],'exitCheck':[{'prompt':'3 和 4 對 12 的關係是什麼？','expectedEvidence':'3、4 是 12 的因數，12 是它們的倍數。'},{'prompt':'什麼情境適合最大公因數？','expectedEvidence':'把不同數量分成最多且相同的組，並能說明整除條件。'},{'prompt':'最小公倍數答案要檢查什麼？','expectedEvidence':'是兩數共同倍數且為最小正值。'}]}
 d['interactive']={'type':'guided-choice','goal':'以質因數分解判斷最大公因數與最小公倍數用途。','scenario':'切換分組或週期任務，觀察質因數指數取小／取大與驗證條件同步變化。','variables':[{'symbol':'a','meaning':'第一個正整數'},{'symbol':'b','meaning':'第二個正整數'}],'steps':[{'id':'step-1','prompt':'最多且相同分組通常要找什麼？','options':['最大公因數','最小公倍數','任意倍數'],'answer':'A','feedback':'分組數量必須同時整除各數，並希望組數最大。'},{'id':'step-2','prompt':'質因數分解求最大公因數時指數怎麼取？','options':['共同質因數取較小指數','全部取較大指數','只取一個質數'],'answer':'A','feedback':'共同因數不能超過任一數的質因數次數。'},{'id':'step-3','prompt':'燈號週期要怎麼驗證最小公倍數？','options':['確認同時是兩個週期的倍數且沒有更小正值','只確認能整除一個週期','只看數字最大'],'answer':'A','feedback':'共同週期必須同時符合兩個倍數條件並取最小。'}]}
 for i, extra in enumerate(['並把 6 與 8 的倍數表標出共同位置，說明為何選最早而非最大。','再將每個質因數的指數寫在分解表中，指出取小後仍能整除兩個原數。','接著比較一題要最大分組、一題要最早同時時刻，明確寫出工具不同的原因。','最後將取小／取大結果分別代回整除與倍數條件，避免只看指數外觀。','再說明包裝數量和共同補貨週期的語意差異，並檢查答案單位。','並用另一組小數值反算，確認不是因為關鍵字位置才選到工具。']):
  d['teaching']['body'][i]['body'] += ' ' + extra
 d['teaching']['summary'][0] = '先確認因數、倍數與題目方向，再決定要找共同分組或共同週期。'
 d['authoringStandard']='version-fused-v1'; d['versionResearch']=[rec('nani','以整除、質因數分解與公因數公倍數建立數與量關係','因數樹、指數、倍數表與情境的互相轉換','把因數與倍數方向顛倒或只看數字大小','完整檢查分解、工具選擇與最大／最小條件回查'),rec('kanghsuan','以操作與表徵比較共同分組和共同週期','分組物件、週期表與質因數分支的同步呈現','分組題誤用最小公倍數或週期題誤用最大公因數','操作後完整解釋指數取小／取大及其用途'),rec('hanlin','在包裝、排班與週期情境中判斷工具','數量、週期、整除與倍數限制的情境表徵','只套關鍵字或不驗證最小／最大條件','評估模型選擇、計算與情境證據是否相稱')]
 d['fusionRecord']={'commonCore':['三版本公開結構共同支持以整除與質因數分解理解公因數、公倍數。','最大公因數與最小公倍數需連結情境用途與指數規則。','答案必須回查共同、最大或最小條件。'],'versionDifferences':['南一證據較突顯分解與整除基礎；康軒較突顯操作、分組與週期表徵；翰林較突顯包裝、排班與工具選擇。這是公開課程計畫層級差異，不宣稱完整教材差異。'],'originalAdditions':['以原創燈號週期表引出最小公倍數與最早共同時刻。','以珠子分組情境診斷最大公因數用途與整除條件。','加入包裝與補貨情境轉移共同分組及工具選擇。'],'llmSynthesisNote':'本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG 重新設計因數、倍數、質因數分解與最大／最小公因數公倍數。正文、例題、互動與回饋均為原創，未複製教材；Terra 第二輪與正式發布審查尚未完成，維持 draft。'}
 d['updatedAt']='2026-09-21'; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 REPORT.write_text(json.dumps({'unit':'n-Ⅳ-1：用質因數分解整理整除關係','lessonId':d['id'],'status':'first-pass-ai-review-complete','reviewStatus':'draft','checks':{'unitSpecificOriginalContent':True,'threeVersionResearchRecords':True,'fusionRecordPresent':True,'interactivePredictionManipulationExplanation':True,'terraSecondPass':'pending'},'reviewedAt':'2026-09-21'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps({'lesson':str(LESSON.relative_to(ROOT)),'reviewStatus':d['reviewStatus']},ensure_ascii=False))
if __name__=='__main__': main()
