import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-4-iv-7.json"
REPORT = ROOT / "implementation/reports/english-performance-4-iv-7-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "note, card, letter, email, audience, purpose, and detail"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "written message, recipient, time, place, request, and polite response"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "card, postcard, announcement, email purpose, and closing"),
    ]
    return [{"url": u, "title": f"{t}；僅取卡片、訊息、書信與電郵的目的、讀者與回應能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以簡短書面溝通辨識收件人、目的、時間、地點、請求、通知、情感與禮貌結尾；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-4-iv-7"
    data["title"] = "4-Ⅳ-7：依收件人與溝通目的讀寫簡單卡片、訊息、書信與電郵"
    data["content"] = {"summary": "卡片、訊息、書信與電郵都在傳遞資訊，但收件人、關係、目的與格式不同。本課以遺留物品、演唱會謝謝、生日卡、火車抵達、博物館地址、缺課詢問、圖書館公告、明信片、社團改教室與社區中心禮貌詢問等原創文本，練習找出誰寫給誰、為何寫、何時何地、需要什麼行動，以及如何用合適稱呼、結尾和語氣回應。", "sections": [{"heading": "先讀寫給誰與為何寫", "body": "Hi Leo 的便條可能是提醒朋友取物，Dear Aunt May 的信件以感謝為目的，To: Club members 的 email 是群體通知。先標 Sender、Recipient、Purpose，再讀日期、地點與下一步，避免只抓情緒詞。"}, {"heading": "格式透露關係和語氣", "body": "Hi、Dear、Greetings、Dear Staff 反映關係與正式程度；See you、Wish you were here、Sincerely 等結尾也提供互動方向。寫給社區中心要禮貌詢問，不能使用過度熟稔或命令語氣。"}, {"heading": "時間地點是可執行細節", "body": "6:20 train、Exit 2、Room 305、4:30 closing 等資訊直接改變行動。閱讀時將 date／time／place／action 四欄分開，若公告只改房間而時間不變，就要保留兩項不同訊息。"}, {"heading": "回應要承接原訊息", "body": "缺課學生問作業，回應應提供 work；博物館地址請求則需要 address；生日卡的 gift 在 front desk 要回答位置。每次回應都要對準目的、收件人和禮貌層級，不把不同訊息混在一起。"}]}
    data["studyHighlights"] = ["先辨認 Sender、Recipient、Purpose，再找日期、時間、地點與下一步。", "從稱呼、結尾與用字判斷關係和正式程度。", "將書面細節拆成 date／time／place／action，保留改變行動的資訊。", "回應要對準原訊息目的與收件人，並使用合適的禮貌格式。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "同一個請求可以用同一種語氣嗎？", "body": "比較給朋友的 Could you send me the address? 和給社區中心的 I would like to ask whether...。學生先標收件人與關係，再調整稱呼、請求句和結尾，理解格式服務溝通目的。"}, {"id": "explain", "phase": "explain", "heading": "書面溝通五欄卡", "body": "建立 Sender、Recipient、Purpose、Key details、Next response 五欄。先判斷便條、卡片、書信、email 或公告，再依讀者關係選稱呼、語氣與結尾。"}, {"id": "worked-example", "phase": "worked-example", "heading": "改教室通知要分清變與不變", "body": "以 meeting moved from Room 201 to Room 305，still begin at 3:00 示範：新地點變了，時間不變。將 change 與 unchanged 分開，避免把整個行程誤改。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一資訊換文本和讀者", "body": "輪換便條、感謝卡、生日卡、書信、詢問 email、缺課信、公告、明信片與社團通知。學生先填五欄，再回答 who／why／when／where／what next，互伴檢查稱呼和結尾。"}, {"id": "transfer", "phase": "transfer", "heading": "從收到訊息到寫出回應", "body": "學生選一則公告或請求，寫一封給不同讀者的回應，保留關鍵日期／地點／行動但改變正式程度。交換後只看回應，判斷收件人能否知道下一步。"}, {"id": "reflect", "phase": "reflect", "heading": "我漏了誰、為什麼或下一步？", "body": "回看答案，標記收件人誤判、目的錯、時間地點漏失、改變／不變混淆、語氣不合或結尾失配。修訂時回到五欄卡，不只抄一個關鍵字。"}], "summary": ["用 Sender、Recipient、Purpose、Key details、Next response 五欄讀寫短文本。", "依卡片、便條、書信、email 或公告和關係調整稱呼、語氣與結尾。", "拆開時間、地點、行動以及改變與不變的細節。", "寫回應時承接原目的，讓收件人能知道下一步。"], "exitCheck": [{"prompt": "讀卡片或電郵為什麼要先辨認收件人和目的？", "expectedEvidence": "能說明同一資訊對朋友、家人、老師或機構需要不同語氣與格式。"}, {"prompt": "如何避免把通知中的改變和不變混在一起？", "expectedEvidence": "能分列變更欄與保留欄，並用時間、地點或活動例子說明。"}, {"prompt": "一封合適回應要如何承接原訊息？", "expectedEvidence": "能對準請求或通知的目的，保留關鍵細節，使用合適稱呼、語氣與結尾。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "辨識簡短書面溝通的收件人、目的、關鍵細節與下一步，並選擇合適回應格式。", "scenario": "學生擔任校園訊息助理，要讀便條、卡片、書信、email 與公告並替不同收件人準備回覆。", "variables": [{"symbol": "p", "meaning": "Sender、Recipient、Purpose"}, {"symbol": "d", "meaning": "日期、時間、地點與行動細節"}, {"symbol": "r", "meaning": "語氣、稱呼、結尾與下一步回應"}], "steps": [{"id": "step-1", "prompt": "A note says Leo's science notebook is on the kitchen table and asks him to bring it tomorrow. What should Leo do?", "options": ["Bring the science notebook to school tomorrow.", "Leave it at the front desk today.", "Send a birthday card to the writer."], "answer": "A", "feedback": "A 同時保留物品、地點提供的取物資訊與 tomorrow 的行動。"}, {"id": "step-2", "prompt": "An email says the club meeting moved from Room 201 to Room 305 but still begins at 3:00. What changed?", "options": ["The room changed; the start time stayed the same.", "Both the room and time changed.", "The meeting was cancelled."], "answer": "A", "feedback": "from...to 指出地點變更，still 表示時間維持不變。"}, {"id": "step-3", "prompt": "Which closing is most polite for an email asking a community center about a program?", "options": ["Thank you for your help. I look forward to your reply.", "Reply now or forget it.", "See ya, stranger!"], "answer": "A", "feedback": "A 同時表達感謝與期待回覆，適合對機構的正式詢問。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；生活訊息、書信與主要內容定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由簡短書面訊息理解收件人、目的與行動。", "以人物、時間、地點與事件完成回應。"], "representations": ["便條、卡片、書信、email、明信片與公告。"], "examplesOrEvidence": ["本課以遺留物品、感謝、生日、旅行與社團原創文本承接公開結構。"], "misconceptions": ["只讀內容，不看收件人與格式。"], "assessmentEmphasis": ["重視書面主要內容、細節與生活溝通。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖文、任務與書面溝通定位；核讀 2026-09-21。", "findings": {"concepts": ["透過卡片、訊息與任務辨識目的和下一步。", "依時間、地點、請求、禮貌與關係完成回應。"], "representations": ["活動、缺課、圖書館、社團、服務與家庭訊息。"], "examplesOrEvidence": ["本課以五欄卡和不同讀者回應重新設計書面活動。"], "misconceptions": ["把朋友語氣直接套給機構，或漏掉改變的地點。"], "assessmentEmphasis": ["評量收件人、語氣、細節與可執行回覆。"], "misconceptions": ["把朋友語氣直接套給機構，或漏掉改變的地點。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；書面功能、讀者與回應格式定位；核讀 2026-09-21。", "findings": {"concepts": ["從書面目的、讀者、格式與細節形成理解。", "以稱呼、結尾、請求、通知與限制完成溝通。"], "representations": ["sender、recipient、purpose、key details、next response。"], "examplesOrEvidence": ["本課以變更／不變欄、正式詢問與回應測試重新設計。"], "misconceptions": ["忽略格式語氣或把原訊息目的改成自己的話題。"], "assessmentEmphasis": ["評量文本目的、細節、語氣與功能性回應。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持便條、卡片、書信、email 與公告理解。", "可靠書面溝通需整合收件人、目的、時間、地點、行動與語氣。", "可用五欄卡、改變／不變對照與讀者回應測試完成遷移。"], "versionDifferences": ["南一較突顯生活訊息與主要內容；康軒較突顯圖文、任務、關係與禮貌；翰林較突顯功能文本、收件人、格式與回應界線。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Sender、Recipient、Purpose、Key details、Next response 五欄讀寫短文本。", "用遺留物品、感謝卡、生日、火車、博物館、缺課、圖書館、明信片與社團原創訊息練習。", "以改變／不變對照和不同正式程度回覆檢查溝通完整。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織卡片、訊息、書信與電郵的收件人、目的、細節、格式、語氣與回應。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-4-iv-7-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先辨認收件人與書面目的，再定位日期、時間、地點、行動和限制，最後用合適語氣回應。"; q["solutionSteps"] = ["先讀稱呼、寄件／收件線索或主旨，判斷誰寫給誰。", "判斷目的為提醒、感謝、通知、請求、分享、詢問或回覆。", "將日期、時間、地點、物品、改變與下一步分欄定位。", "檢查稱呼、語氣、結尾與資訊是否符合讀者關係，排除錯套格式。", "用收件人視角重讀，確認能依訊息直接採取正確行動。" ]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的卡片、訊息、書信、電郵與公告模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 4-iv-7")


if __name__ == "__main__":
    main()
