import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/english/lesson-english-performance-1-iv-4.json"
REPORT=ROOT/"implementation/reports/english-performance-1-iv-4-first-pass-review.json"

def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher":name,"edition":f"{name} 公立校方英語課程計畫章節級證據","sourceType":"public-web","sourceLocator":locator,"reviewedAt":"2026-09-21","findings":{"concepts":concepts,"representations":forms,"examplesOrEvidence":["本課以原創校園與家庭日常對話、關鍵細節卡與主旨／推論任務，承接公開課程的對話理解、生活溝通與聽讀策略方向。"],"misconceptions":[misconception],"assessmentEmphasis":[assessment]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}

def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-english-performance-1-iv-4"
    data["title"]="1-Ⅳ-4：從日常對話抓住主要內容、細節與下一步"
    data["content"]={"summary":"理解日常對話不能只抓最後一句或聽見的單字，而要辨認誰在談什麼、發生了什麼變化、哪些細節支持主旨，以及對方接下來要做什麼。本課以放學安排、尋物、飲料選擇、圖書館期限、簡報準備、活動評價、照顧寵物、天氣改期與共享資料夾等原創對話練習，使用人物、時間、地點、原因、轉折與決定卡重建對話內容，再用英文短句說出主旨與可支持的推論。", "sections":[{"heading":"先定位人物、目的與情境","body":"聽或讀對話第一遍時，先記錄人物關係、地點、時間和正在處理的任務；第二遍再找問題、改變與決定。*Are you free after school?* 的重點不只是 free，而是兩人能否在時間限制下安排活動；情境能幫助你判斷哪些單字是主線、哪些只是背景。"},{"heading":"用細節拼出主要內容","body":"主要內容要涵蓋對話的任務和結果，不能只摘一個物件或人物的感受。抓出誰提出什麼、誰補充什麼條件、最後採取哪個行動，再用一句簡單英文或中文摘要重述；若摘要漏掉 but, until, after, because 等關係詞，可能已經改變重點。"},{"heading":"區分明說與可合理推論","body":"對話直接說出的是明示資訊，例如 library closes at six；由兩句合起來才能推得的是合理推論，例如要先還書或改變計畫。推論必須有對話線索，不能把自己的生活經驗補成答案；遇到兩個可能性時，選證據較完整者並標記不確定。"},{"heading":"理解要連到下一步","body":"日常對話通常為了完成行動：列印簡報、尋找檔案、帶鑰匙、改期或準備手套。最後問『誰要做什麼、何時、在哪裡、為什麼』，再檢查是否和前面的限制一致。能說出下一步，表示不只是認出單字，而是掌握對話主要內容。"}]}
    data["studyHighlights"]=["先定位人物、地點、時間與對話任務。","用問題、條件、轉折與結果整理主要內容。","區分明示細節和有證據的合理推論。","以誰、何時、在哪裡、為什麼和下一步驗證理解。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"最後一句就是對話重點嗎？","body":"提供一段自編對話：簡報十分鐘後開始，學生需要列印資料，夥伴指出印表機在圖書館旁。請學習者先只看最後一句猜重點，再回到整段畫出時間、任務、問題和決定，比較單句猜測與完整情境理解的差異。"},{"id":"explain","phase":"explain","heading":"日常對話五格理解卡","body":"依序填人物與關係、地點與時間、主要任務、關鍵條件／轉折、最後決定與下一步。每個答案都要貼回對話中的詞句；*but*, *until*, *then*, *so* 等連接線索要特別標記，因為它們常常改變人物的選擇和結果。"},{"id":"worked-example","phase":"worked-example","heading":"從天氣消息推到改期決定","body":"以自編對話中 heavy rain tonight 和 move the picnic indoors 為例，先說明明示的天氣資訊，再指出因此產生的計畫改變。不能推成活動取消或所有人都不開心，除非對話提供證據；示範如何把主旨、細節與推論分開。"},{"id":"guided-practice","phase":"guided-practice","heading":"用人物卡重建尋物對話","body":"給出自編尋傘對話和人物、地點、時間卡，學生先按出現順序排列，再用一句英文摘要說明傘在哪裡、何時看見、接下來要去哪裡找。夥伴只能依摘要移動到地圖位置；若走錯，回查漏掉的介系詞、時間或轉折。"},{"id":"transfer","phase":"transfer","heading":"把主旨策略帶到不同日常場景","body":"輪換放學安排、寵物照顧、圖書館期限、志工清理與共享檔案等對話，固定五格理解卡但改變任務和資訊密度。學生需說出一個主旨、一個明示細節和一個有證據推論，再指出角色下一步，避免只靠熟悉單字作答。"},{"id":"reflect","phase":"reflect","heading":"檢查我是否把自己的經驗加進對話","body":"回看答案，將每句判斷標成直接聽見、由兩句推得或自己猜想。刪掉沒有對話線索的推論，補上支持主旨的時間、地點、條件或結果；若仍不確定，用 *The conversation suggests...* 的方式降低肯定程度。"}],"summary":["先定位人物、時間、地點和對話任務。","以條件、轉折和結果重建主要內容。","分開明示細節、證據推論與個人猜想。","用主旨、細節和下一步完成不同日常對話的理解。"],"exitCheck":[{"prompt":"日常對話的主要內容和單一細節有何不同？","expectedEvidence":"能說明主旨要涵蓋任務與結果，細節只支持其中一部分，並用整段對話重述。"},{"prompt":"何時可以做合理推論？","expectedEvidence":"能指出推論必須由兩個以上對話線索支持，不能只靠生活經驗或單一單字。"},{"prompt":"為什麼說出下一步能檢查理解？","expectedEvidence":"能把人物、時間、地點、原因與決定連起來，說出對話後可執行的行動。"}]}
    data["interactive"]={"type":"guided-choice","goal":"從日常對話辨認主旨、關鍵細節、合理推論與人物下一步。","scenario":"學生在校園地圖和時間表上重建不同對話，依序標記人物、任務、條件、結果，再用英文摘要讓同伴完成行動。","variables":[{"symbol":"p","meaning":"人物、地點與時間"},{"symbol":"m","meaning":"主旨、細節與轉折"},{"symbol":"n","meaning":"推論與下一步"}],"steps":[{"id":"step-1","prompt":"A: Are you free after school? B: I have basketball practice until five. What is the main point?","options":["B is available all afternoon.","B cannot meet before five because of practice.","B does not like basketball."],"answer":"B","feedback":"B combines the question and the time limit; the conversation is about when B can meet."},{"id":"step-2","prompt":"The library closes at six, so what should the students most likely do?","options":["Return the books before the library closes.","Leave the books at home for a month.","Start a basketball practice in the library."],"answer":"A","feedback":"A is a reasonable next step supported by the closing time and the topic of library books."},{"id":"step-3","prompt":"A: I cannot find the homework file. B: Check the shared class folder. What is B doing?","options":["Giving a possible place to look for the file.","Inviting A to a school play.","Saying the homework is finished."],"answer":"A","feedback":"A identifies the purpose of the reply and the action it asks the listener to take."}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語日常對話、聽讀理解與生活溝通定位；核讀 2026-09-21。",["由校園與生活情境理解對話主要內容，掌握人物正在處理的任務與結果。","以人物、時間、地點與任務線索掌握訊息。"],["校園對話、問答、安排、尋物、請求與回應。"],"只抓最後一句或熟悉單字，忽略整段任務和結果。","重視對話主旨、關鍵細節與能否完成生活溝通理解。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語對話、句段理解與課堂活動定位；核讀 2026-09-21。",["透過聽讀、圖片與角色活動理解日常對話。","依時間、條件、轉折與回應重建主要內容。"],["放學安排、尋物、購物、圖書館、天氣與共享資料。"],"把單一細節或個人經驗擴大成對話主旨。","要求理解對話功能、結果與下一步。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語日常對話、聽說互動與評量定位；核讀 2026-09-21。",["從聽說讀寫活動掌握對話的主要內容。","以明示資訊、合理推論與溝通目的支持理解。"],["短對話、主旨、細節、推論、角色意圖與生活任務。"],"把推測當成明示資訊，或只依熟悉字詞選答案。","評量主旨、細節、推論與情境回應。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持日常對話、聽讀理解、生活情境與溝通任務。","人物、時間、地點、條件、轉折與結果共同形成主要內容。","理解需區分明示細節、合理推論與個人猜想。"],"versionDifferences":["南一較突顯生活情境與對話訊息；康軒較突顯聽讀、圖片、角色活動與條件結果；翰林較突顯主旨、細節、推論與溝通目的。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以五格理解卡整理人物、任務、條件、結果與下一步。","用天氣改期和尋傘地圖區分明示資訊與推論。","以英文摘要讓同伴依對話理解完成校園行動。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織日常對話主旨、細節、轉折、推論、角色意圖與下一步。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 每項判斷旁都要貼回原對話中的英文詞句，並將 but、until、then、so 等關係線索圈起來；若摘要漏掉一個限制，就重新檢查主旨是否被放大或改變。"
    data["teaching"]["body"][4]["body"] += " 換場景時固定五格理解卡，再改變人物關係、時間壓力和任務結果，讓學生依對話證據調整摘要，而不是把熟悉句型套成同一答案。"
    data["teaching"]["body"][5]["body"] += " 將每個推論標成直接資訊、兩句合推或個人猜想，並把沒有線索的答案改成較保守的英文表達，維持理解的證據邊界。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"1-Ⅳ-4：從日常對話抓住主要內容、細節與下一步","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored english performance 1-iv-4")

if __name__=="__main__": main()
