"""INg-Ⅳ-6：新興科技對自然環境的影響第一輪原創題庫。"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-content-ing-iv-6.json"; REPORT=ROOT/"implementation/reports/science-content-ing-iv-6-first-pass-review.json"; QDIR=ROOT/"questions/science"; TODAY="2026-09-23"
SOURCES=[
 {"url":"https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%87%AA%E7%84%B6.pdf","title":"高雄市立鹽埕國民中學 114 學年度第 2 學期第 1 次段考自然科公開試題","year":"114","locator":"科技應用、能源、環境影響與資料判讀","pattern":"取由科技系統的輸入輸出、生命週期與環境資料評估新興技術的能力方向。"},
 {"url":"https://www.grow22.com/download/114/114_cp/05_114P_Nature.pdf","title":"114 年國中教育會考自然科公開試題","year":"114","locator":"生活科技、環境、能源與證據限制","pattern":"取從圖表、實驗與生活情境判斷科技效益、風險與替代解釋的能力方向。"},
 {"url":"https://www.hkjh.hc.edu.tw/uploads/1661481260739sfuB4gG2.pdf","title":"新竹市立新科國中公開康軒版自然課程計畫","year":"公開課程計畫","locator":"新興科技、環境承載、資源循環與公共決策","pattern":"取比較科技便利性、資源使用、污染轉移、回收與長期環境影響的教學與評量方向。"},
]
REFS=[{**s,"subject":"science","observedPattern":s["pattern"],"reuseDecision":"pattern-only","status":"recorded","locatorLevel":"paper"} for s in SOURCES]
def q(n,prompt,opts,ans,exp,strat,steps,d="medium"):
 return {"id":f"question-science-content-ing-iv-6-{n}","subject":"science","type":"single-choice","prompt":prompt,"options":[{"id":k,"text":v} for k,v in zip("ABCD",opts)],"knowledgeIds":["kg-science-content-ing-iv-6"],"difficulty":d,"answer":{"value":ans,"explanation":exp},"provenance":{"origin":"original","license":"All rights reserved","sourceUrl":SOURCES[0]["url"],"sourceLocator":"三筆公立學校／公開自然科試題與課程資料的新興科技、環境效益、生命週期、資源循環及資料判讀能力方向；本題只作 pattern-only 改寫來源。","authoringNote":"依公開資料能力方向獨立改寫；題幹、選項、答案、解析與五步解法均依 INg-Ⅳ-6 單元重新撰寫，未複製原題、圖表或答案；待第二輪 AI／Terra 內容複核。"},"reviewStatus":"draft","updatedAt":TODAY,"lessonId":"lesson-science-content-ing-iv-6","examPatternRefs":REFS,"solutionStrategy":strat,"solutionSteps":steps}
Q=[
q(1,"評估校園安裝太陽能板的環境影響時，哪項資料範圍最完整？",["製造、運輸、安裝、使用發電、維修與報廢回收的生命週期資料","只記錄安裝後第一天的發電量","只比較面板表面顏色","只引用廠商宣稱的零污染"],"A","太陽能板使用時可能沒有燃燒排放，但製造、運輸、維修與報廢仍有資源和環境影響，必須看完整生命週期。","先界定系統邊界，再比較科技的效益和代價。",["列出面板從原料到報廢的階段。","記錄各階段的能源、材料與排放。","將使用期發電效益與全生命週期代價比較。","B、C、D 只提供片段或宣傳資訊。","所以 A 最完整。"],"hard"),
q(2,"比較電動公車與柴油公車的環境影響，哪項最不應忽略？",["電力來源、電池製造與回收、行駛里程及柴油燃燒排放","只比較車身顏色","只看站牌數量","因電動車沒有尾氣就宣稱全程零排放"],"A","電動公車的使用端排放、電力來源、電池生命週期和柴油車燃燒都會影響完整比較。","把使用端與上游供能、製造、回收放在相同功能單位。",["設定相同載客里程作為比較基準。","記錄兩種車的能源來源和使用效率。","加入電池、燃料製造與回收排放。","B、C、D 忽略生命週期或過度絕對化。","答案為 A。"],"hard"),
q(3,"智慧灌溉系統顯示節水 30%，要判斷是否由系統造成，哪項設計較可靠？",["在相近地塊設有、無系統對照，跨相同季節記錄雨量、作物量與用水","只比較安裝後一週且不記錄降雨","看到感測器就認定一定節水","只詢問使用者喜不喜歡介面"],"A","對照地塊與跨季節資料可排除降雨、作物生長與地塊差異，較能判斷系統效果。","建立基線與對照，避免把季節差異當科技效果。",["選擇條件相近的有、無系統地塊。","記錄雨量、作物量與灌溉用水。","比較同季節的單位產量用水量。","B、C、D 缺乏對照或只依主觀感受。","所以 A 較可靠。"],"medium"),
q(4,"無人機巡查可減少人員車輛行駛，但需要充電與維修；哪項比較最公平？",["以相同巡查面積為基準，計入飛行、充電、製造、維修與替代交通的能源排放","只比較無人機飛行時的耗電","只看巡查速度","因設備很小就忽略製造和回收"],"A","科技環境效益應以相同服務量比較，並計入整個設備與替代方案的能源和排放。","用功能單位與生命週期避免只看使用階段。",["設定相同巡查面積和頻率。","記錄無人機、車輛和人力方案的能源使用。","加上製造、充電、維修與報廢資料。","B、C、D 都縮小比較範圍。","答案為 A。"],"hard"),
q(5,"校園雨水回收系統宣稱可減少自來水使用，哪項問題最能檢驗其環境效益？",["在相同降雨條件下，比較導入前後的自來水量、儲水量、溢流與維護耗材","系統水桶是否是藍色","只看下雨當天水箱有沒有水","只問學生覺得設備新不新奇"],"A","雨量、儲水、使用量、溢流與維護能反映系統是否實際替代自來水及新增耗材。","把節水效益和設備維護、降雨變動一起量測。",["記錄導入前基線與導入後相同季節資料。","同步記錄降雨、儲水、用水和溢流。","扣除維護與清潔的新增資源使用。","B、C、D 不能支持環境效益判斷。","所以 A 最適合。"],"medium"),
q(6,"某電子設備使用時耗電很低，但所需稀有金屬開採造成水污染；最合適的評估方式是？",["把原料開採、製造、運輸、使用、回收與污染地點全部納入生命週期","只以使用期耗電判定環保","因科技方便就忽略採礦地居民","看到回收標誌就假定回收率百分之百"],"A","低使用能耗不代表整體環境影響低，必須把污染可能轉移到供應鏈與報廢階段的現象納入。","追蹤污染在空間與生命週期的轉移。",["畫出設備的物料與能量流程。","標記各階段的污染、用水與資源使用地點。","比較完整生命週期而非單一使用階段。","B、C、D 都忽略或假設未驗證的影響。","答案為 A。"],"hard"),
q(7,"空氣清淨設備導入後教室缺課率下降，哪項證據最能避免誤判因果？",["設置未使用設備的相近教室作對照，並記錄季節、通風、病原與學生出席的長期資料","只比較導入前後兩天","看到缺課下降就直接歸功設備","只詢問設備廠商的成功案例"],"A","長期對照資料可檢查季節、通風與疾病流行等替代因素，降低把相關誤認為因果的風險。","用對照、基線和多變量資料檢查科技成效。",["選擇條件相近且未使用設備的教室。","同步記錄缺課、通風、季節與疾病資料。","比較導入前後及有無設備的差異。","B、C、D 缺乏對照或直接跳到因果。","所以 A 最有力。"],"hard"),
q(8,"選擇新型 LED 照明時，哪項表達最完整？",["比較相同照度下的耗電、壽命、材料、製造、回收、光害與使用需求","只看每盞燈購買價格","只看燈泡最亮就判定最好","因 LED 節能就不需處理廢棄物"],"A","照明的環境評估要在相同服務量下比較能源、壽命、材料、回收與光害，不能只看價格或亮度。","用相同照明服務量建立多指標生命週期比較。",["設定相同照度與使用時數。","記錄耗電、壽命、製造與材料。","納入回收、光害和實際需求。","B、C、D 只看單一特性或忽略廢棄物。","答案為 A。"],"medium"),
q(9,"某新科技的短期實驗顯示能源消耗下降，但長期生態影響尚未知；最謹慎的結論是？",["短期結果顯示可能有節能效益，但不能直接宣稱長期環境影響一定較小","已證明對所有環境都安全","因未知所以一定有害","只要短期數據漂亮就不需後續監測"],"A","短期結果只能支持特定條件下的節能觀察，長期生態、材料與使用規模仍需追蹤，不應超出證據範圍。","區分已觀測效益、尚未測試的風險與外推限制。",["界定實驗的時間、地點與樣本。","列出長期使用會新增的環境變因。","把結論限定在已測試條件並規劃後續監測。","B、C、D 都過度推論或放棄證據。","所以 A 最謹慎。"],"medium"),
q(10,"某新材料降低使用期碳排，但需要稀有金屬且回收率低；最合適的結論是？",["它在使用期有優點，但整體環境效益要等生命週期與回收資料比較後才能判定","只要使用期排放下降就一定永續","回收率低代表材料完全沒有用途","只比較材料重量即可"],"A","使用期碳排下降是局部效益，稀有金屬與低回收率可能增加上游和報廢代價，需完整生命週期判斷。","把局部優勢與系統總體環境結果分開。",["標記使用期碳排下降的證據。","加入採礦、製造、運輸與回收資料。","比較同功能產品的完整生命週期。","B、C、D 都忽略或錯誤解讀部分證據。","答案為 A。"],"hard"),
]
def main():
 lesson=json.loads(LESSON.read_text(encoding="utf-8")); lesson["updatedAt"]=TODAY; lesson["reviewStatus"]="draft"
 lesson["fusionRecord"]={"commonCore":["三版本公開線索共同支持以生命週期、功能單位、系統邊界與環境承載評估新興科技的效益與代價。","科技效益不能只看使用期或單一成功指標，需檢查資源開採、製造、使用、回收、污染轉移、替代方案與不確定性。"],"versionDifferences":["公立段考與會考公開題型提供科技應用、能源、環境與證據限制方向；康軒公開課程線索偏向便利性、資源循環、污染轉移、回收與公共決策。公開資料不足以宣稱取得完整教材內容。"],"originalAdditions":["以太陽能板、電動公車、智慧灌溉、無人機、雨水回收、電子設備、空氣清淨、LED、新材料建立科技環境影響的生命週期證據鏈。","把『使用端低碳就代表全生命週期環保』、『科技設備越新越永續』與『短期成效可直接外推長期生態』列為迷思診斷。"],"llmSynthesisNote":"依官方課綱、本單元 KG、南一／康軒／翰林公開版本線索與三筆公立學校／公開自然科試題及課程資料的能力方向，重新撰寫新興科技、生命週期、功能單位、污染轉移、對照設計與環境不確定性。原有 10 題為泛用研究句型套題，已逐題改寫為科技環境影響專屬題，均具唯一答案、解析與五步解法，未複製教材或試題文字、圖表與答案；Terra 第二輪與正式發布審查尚未完成，維持 draft。"}
 for e in lesson.get("versionResearch",[])+lesson.get("publisherResearch",[]): e["reviewedAt"]=TODAY
 for x in Q: (QDIR/f"question-science-content-ing-iv-6-{x['id'].rsplit('-',1)[-1]}.json").write_text(json.dumps(x,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"INg-Ⅳ-6：新興科技對自然環境的影響","lessonId":lesson["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checkedQuestions":10,"checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"threePublicSchoolExamPatternSources":True,"answersAndDetailedSteps":True,"interactivePredictionManipulationExplanation":True,"terraSecondPass":"pending"},"reviewedAt":TODAY,"note":"原有 10 題為泛用研究句型套題，已逐題改寫為新興科技環境影響專屬問題；每題有唯一答案、解析與五步解法，三筆公開試題／課程資料僅作 pattern-only 來源，正式發布前仍須第二輪 AI／Terra 內容複核。"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 LESSON.write_text(json.dumps(lesson,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); print("authored science content ing iv 6")
if __name__=="__main__": main()
