import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-13.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-13-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "short play plot, dialogue, stage direction, conflict, and ending"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "script action, character goal, clue, change, and inference"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "dialogue purpose, stage direction, problem, solution, and theme"),
    ]
    return [{"url": u, "title": f"{t}；僅取簡易短劇、對話與舞台指示的理解能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以短劇角色、對話目的、舞台指示、衝突、線索、結局與人物改變測量戲劇文本理解；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-3-iv-13"
    data["title"] = "3-Ⅳ-13：從角色、舞台指示與衝突理解簡易短劇"
    data["content"] = {"summary": "短劇的意義同時存在於台詞、舞台指示、道具、燈光、走位與結局；不能只讀角色說出的句子。本課以遺失錢包、主持報告、黑窗、末班車、班級禮物、跳電、犯錯後發言、紅圍巾、傾聽與失蹤布條等原創劇本，練習角色目標、舞台動作、衝突、線索、解決方案、象徵、人物改變與結局主旨。", "sections": [{"heading": "先分辨台詞和舞台指示", "body": "台詞讓觀眾聽見角色的想法或行動，方括號中的 points、steps back、lights go out 則告訴演員如何呈現場面。兩者合在一起才構成可演出的資訊，舞台指示不能當成角色直接說出的內容。"}, {"heading": "角色目標推動衝突", "body": "想搭末班車、想把錢用作禮物、想保存作為旅行基金，都是不同目標；當資源或時間不能同時滿足目標，就形成衝突。先寫每個角色要什麼，再看對話如何協商或改變。"}, {"heading": "道具和動作可以成為線索", "body": "手機燈、保險絲開關、紅圍巾與遺失布條不只是背景物件，它們可能揭示問題、串聯角色或象徵互助。但解讀道具功能必須回到它出現、被使用與結局的前後關係。"}, {"heading": "結局要回應前面的問題", "body": "短劇結尾若說 We solved it because we listened，便把解決方案和傾聽連起來；若角色從小聲道歉到主動解釋，代表可由前後行動支持的改變。不能只把最後一句當成獨立格言。"}]}
    data["studyHighlights"] = ["分開台詞、舞台指示、道具與燈光，再整合成可演出的情節。", "用角色目標和資源／時間限制辨識衝突與協商。", "追蹤道具、動作和線索在問題、轉折與結局中的功能。", "以結尾回應開頭問題，並用前後台詞或動作證明人物改變與主旨。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "方括號裡的動作也在說話嗎？", "body": "給學生一段原創劇本：Mia points to the dark window and steps back。學生先只讀台詞猜場面，再加入舞台指示比較觀眾知道的危險、距離與情緒，理解非口語線索的戲劇功能。"}, {"id": "explain", "phase": "explain", "heading": "短劇六格排演卡", "body": "建立 Role、Goal、Stage clue、Conflict、Choice、Outcome 六格。先標角色想做什麼，再把舞台動作、對話與道具放入事件鏈，最後檢查結局是否回應衝突。"}, {"id": "worked-example", "phase": "worked-example", "heading": "由燈光和道具找到解決方案", "body": "以停電場景示範：lights go out 是問題，phone light 讓角色能看見，fuse switch 提供解決線索；不能把使用手機燈誤說成已修好電力。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "台詞、動作與結局輪換", "body": "用錢包、報告、末班車、班級禮物、紅圍巾與布條六組原創短劇，學生輪流回答角色目標、舞台指示、衝突、道具功能與結局主旨，並在劇本上圈出證據。"}, {"id": "transfer", "phase": "transfer", "heading": "把閱讀答案變成排演提示", "body": "學生將一場短劇改寫成三張演員提示卡：誰要什麼、哪個動作改變局面、結尾如何收束。交換後請同伴只依提示卡重述情節，檢查是否漏掉關鍵舞台線索。"}, {"id": "reflect", "phase": "reflect", "heading": "我忽略了哪一種舞台資訊？", "body": "回看答案，標記把舞台指示當台詞、把道具當裝飾、把衝突當角色性格、把方案當結局或把最後一句脫離情節的錯誤。修訂時補回動作、目的與結果的連結。"}], "summary": ["分辨 Role、Goal、Stage clue、Conflict、Choice、Outcome 六種短劇資訊。", "從台詞與舞台指示共同建立角色目標、問題與行動。", "以道具、燈光和走位追蹤線索與解決方案。", "用前後排演證據理解人物改變、結局與主旨。"], "exitCheck": [{"prompt": "舞台指示和台詞如何共同傳達場景？", "expectedEvidence": "能指出方括號動作或燈光提供的非口語資訊，並說明它如何補充角色台詞。"}, {"prompt": "如何判斷短劇中的主要衝突？", "expectedEvidence": "能分別說出角色目標與阻礙，並指出哪段對話或動作顯示兩者碰撞。"}, {"prompt": "結局主旨為什麼要回看前面的排演線索？", "expectedEvidence": "能用問題、選擇、道具或人物前後行動解釋結尾，而非只摘錄最後一句。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "整合短劇台詞、舞台指示、角色目標、道具與結局，理解衝突、解決方案與人物改變。", "scenario": "學生擔任小劇場導讀員，要為演員標出角色目標、舞台線索與能解決問題的關鍵行動。", "variables": [{"symbol": "r", "meaning": "角色、目標與對話"}, {"symbol": "s", "meaning": "舞台指示、道具、燈光與線索"}, {"symbol": "o", "meaning": "衝突、選擇、結果與結局主旨"}], "steps": [{"id": "step-1", "prompt": "Two students find a lost wallet, ask the office for help, and reunite it with its owner. What is the main action?", "options": ["They seek help to return the wallet.", "They keep the wallet for themselves.", "They leave the school without telling anyone."], "answer": "A", "feedback": "A 整合發現、求助與歸還三個劇情行動。"}, {"id": "step-2", "prompt": "[Mia points to the dark window and steps back.] What does this stage direction show?", "options": ["She notices something alarming and reacts cautiously.", "She is giving a speech about lunch.", "She has already left the stage."], "answer": "A", "feedback": "指向黑窗與後退共同呈現注意到危險及謹慎反應。"}, {"id": "step-3", "prompt": "A red scarf is passed whenever someone agrees to help. What can it represent?", "options": ["A connection of shared help among the characters.", "A rule that no one may cooperate.", "Only the weather outside."], "answer": "A", "feedback": "反覆傳遞與同意幫助的情節共同支持互助連結的象徵解讀。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；短劇對話、角色與主要情節定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由簡易短劇理解角色、對話與主要內容。", "以順序、行動與結果整理表演情節。"], "representations": ["錢包、報告、班級活動與校園短劇。"], "examplesOrEvidence": ["本課以遺失物、主持報告與失蹤布條原創劇本承接公開結構。"], "misconceptions": ["只讀台詞，不看動作與場景提示。"], "assessmentEmphasis": ["重視短劇主要內容、角色與行動。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖像、表演任務與角色衝突定位；核讀 2026-09-21。", "findings": {"concepts": ["透過對話、動作與任務辨識角色目標和問題。", "依選擇、道具與結果理解短劇。"], "representations": ["舞台指示、道具、燈光、協商與排演。"], "examplesOrEvidence": ["本課以六格排演卡重新設計戲劇理解。"], "misconceptions": ["把舞台指示當成角色台詞，或把道具當成無功能裝飾。"], "assessmentEmphasis": ["評量角色、衝突、方案與結局。"], "misconceptions": ["把舞台指示當成角色台詞，或把道具當成無功能裝飾。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；劇本觀點、舞台指示、象徵與結局定位；核讀 2026-09-21。", "findings": {"concepts": ["從台詞、舞台動作與觀眾資訊形成短劇理解。", "以道具、衝突、改變與結局表達戲劇意義。"], "representations": ["role、stage direction、conflict、clue、symbol、outcome。"], "examplesOrEvidence": ["本課以黑窗、手機燈、紅圍巾與傾聽結局重新設計推論。"], "misconceptions": ["脫離前後劇情解讀最後一句或物件象徵。"], "assessmentEmphasis": ["評量舞台資訊、解決方案、人物與主旨。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持簡易短劇、角色、對話與主要情節理解。", "可靠戲劇理解需整合台詞、舞台指示、目標、衝突、道具與結局。", "可用排演卡、道具功能、事件鏈與前後角色比較完成遷移。"], "versionDifferences": ["南一較突顯對話、角色與主要內容；康軒較突顯圖像、表演任務、道具與衝突；翰林較突顯舞台指示、象徵、改變與結局主旨。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Role、Goal、Stage clue、Conflict、Choice、Outcome 六格排演短劇。", "用錢包、報告、黑窗、末班車、停電、紅圍巾與布條原創劇本練習。", "以排演提示卡和道具前後功能檢查人物、衝突與結局。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織短劇台詞、舞台指示、角色目標、衝突、道具、象徵、解決方案與結局。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-3-iv-13-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先分辨台詞與舞台指示，再追蹤角色目標、衝突、道具線索、選擇與結局。"; q["solutionSteps"] = ["先讀完整場景，標出角色、目標與問題。", "分開台詞、方括號動作、燈光與道具等證據類型。", "依題目要求定位主要行動、舞台意義、衝突、象徵、改變或結局。", "用前後兩個以上的劇本線索核對答案，排除脫離情節的解讀。", "把答案改述成包含角色與戲劇功能的完整句，確認沒有新增劇本未提供的結果。" ]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的簡易短劇、舞台指示、角色、衝突與結局模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-13")


if __name__ == "__main__":
    main()
