import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/chinese/lesson-chinese-performance-6-iv-5.json"
REPORT=ROOT/"implementation/reports/chinese-performance-6-iv-5-first-pass-review.json"

def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher":name,"edition":f"{name} 公立校方國文課程計畫章節級證據","sourceType":"public-web","sourceLocator":locator,"reviewedAt":"2026-09-21","findings":{"concepts":concepts,"representations":forms,"examplesOrEvidence":["本課以原創閱讀題、資料判讀、研究發布與同儕試答卡，承接公開課程的自主創作、表述見解與溝通發布方向。"],"misconceptions":[misconception],"assessmentEmphasis":[assessment]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}

def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-chinese-performance-6-iv-5"
    data["title"]="6-Ⅳ-5：從自主創作到可驗證、可修訂的題目與發布"
    data["content"]={"summary":"主動創作不只是產出一個新題目，而是從學習目標、讀者需要和資料證據出發，設計別人能理解、作答與回饋的作品。本課以自訂閱讀題、選項與解析、研究見解及不同發布管道為材料，練習把目標轉成題幹、建立唯一最佳答案、標示公開資料來源與改寫界線，再用同儕試答找出歧義，依群組、校刊或口頭分享的讀者調整內容。發布前要誠實區分觀察、推論、限制與個人立場。", "sections":[{"heading":"先把學習目標變成作答任務","body":"設計題目前先寫學習者要辨認、比較、解釋、計算或評估什麼，再決定材料和題型。『校園午餐』太寬，若目標是判讀調查圖表，題幹就要提供對象、時間、單位與問題；題目不應靠猜作者想考什麼才能作答。"},{"heading":"好題目要讓答案可判定","body":"單選題的題幹要交代任務，選項要同層次、互斥且只有一個最符合證據的答案；誘答可以反映常見迷思，但不能因語氣、長短或超出材料而被猜中。資料題解析要指出讀哪個數值、如何推論及其他選項在哪一步不成立。"},{"heading":"原創資料和公開來源要分清楚","body":"可以用公開統計或試題呈現的能力型態作為改寫靈感，但題幹、選項、圖表、答案和解析要重新設計。若引用公開資料，記錄機構、日期、定位和授權／使用界線；若是自編資料，標明它是教學模擬，不能把模擬結果冒充真實調查。"},{"heading":"發布是溝通與責任的最後一輪","body":"先讓同學試答，記錄錯誤集中在哪個詞、條件或選項，再修題幹和解析而不是責怪作答者。班級群組需要短而清楚的任務與連結，校刊需要背景、方法、限制與來源；發布前確認答案、版權、個資、讀者年齡與版本都可追溯。"}]}
    data["studyHighlights"]=["由學習目標反推材料、題型、題幹與作答任務。","建立唯一最佳答案、互斥選項與可回溯解析。","區分自編資料、公開來源與能力型態改寫界線。","用試答回饋修訂題目，依發布管道調整證據與責任。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"題目新就是好題目嗎？","body":"展示一題完全自編的校園午餐題目：主題新鮮，卻沒有說明調查時間，兩個選項都能成立。請學習者先試答，再把問題分成目標不清、資料不足、選項重疊或解析缺口，體會創作品質來自可理解、可作答與可修訂，而不是只來自新奇。"},{"id":"explain","phase":"explain","heading":"原創題目五格設計卡","body":"第一格寫學習目標；第二格選材料與資料定位；第三格寫清楚題幹與限制；第四格設計互斥選項、唯一答案與逐步解析；第五格請讀者試答並記錄誤解。每格都要能回到上一格核對，若答案依賴題外常識或語氣猜測，就必須重寫。"},{"id":"worked-example","phase":"worked-example","heading":"讓資料判讀題的解析真的能教人","body":"示範一題自編剩食圖表題：解析先指出比較的欄位與單位，再寫差值或趨勢，最後說明正解如何由資料支持、其他選項在哪個條件錯誤。解析不是公布答案的同義句，而是讓作答者學會下一題可重做的方法。"},{"id":"guided-practice","phase":"guided-practice","heading":"用同儕試答抓出兩個正解","body":"每組交換自訂題目，作答者先獨立選答案，再朗讀自己理解的任務和依據。若兩個選項都能成立，設計者要檢查題幹條件、資料範圍與選項措辭，加入必要限制或改成多選／開放題，不能只把其中一個答案標成『老師認為的正解』。"},{"id":"transfer","phase":"transfer","heading":"把同一研究發布給不同讀者","body":"將一項自編校園研究分別發布在班級群組與校刊：群組版本先給行動重點、短摘要和完整連結，校刊版本補上問題、方法、樣本、結果、限制與來源。兩版都不能把相關說成因果，也不能公開同學姓名或可識別資訊。"},{"id":"reflect","phase":"reflect","heading":"檢查作品是否對讀者負責","body":"回看題目與發布稿，逐項檢查學習目標、材料來源、答案唯一性、解析可教性、版權界線、個資、限制與讀者適切。把同儕誤解當成設計資料，記錄改動前後和仍待查證的問題，讓作品留下可以繼續修訂的版本。"}],"summary":["由學習目標設計材料、題幹與作答任務。","以互斥選項、唯一最佳答案與可重做解析建立題目。","標示自編資料、公開來源、改寫界線與引用責任。","透過試答回饋與不同發布管道修訂作品。"],"exitCheck":[{"prompt":"自訂題目為何要先寫學習目標？","expectedEvidence":"能說明目標會決定材料、題型、題幹動詞、答案證據與解析方式，避免主題大但任務不清。"},{"prompt":"如何處理同儕指出兩個選項都能成立？","expectedEvidence":"能檢查題幹條件、資料範圍與選項互斥性，必要時補限制、重寫或改成適合的題型。"},{"prompt":"研究發布時如何區分觀察、推論與限制？","expectedEvidence":"能分別寫方法與資料看到什麼、可合理推論到哪裡、哪些尚未證明並附來源。"}]}
    data["interactive"]={"type":"guided-choice","goal":"從學習目標設計原創題目與解析，經試答修訂後，以符合讀者與責任的方式發布。","scenario":"學生要為同學設計校園午餐閱讀題並發布一項小研究，依序填目標卡、寫題目、試答、修訂與分眾發布。","variables":[{"symbol":"g","meaning":"學習目標與作答任務"},{"symbol":"q","meaning":"題幹、選項、答案與解析"},{"symbol":"p","meaning":"試答回饋與發布責任"}],"steps":[{"id":"step-1","prompt":"要為同學設計校園午餐閱讀題，哪種做法最能讓題目有明確學習目標？","options":["先指定要判讀圖表的趨勢或比較，再提供對象、時間、單位與可作答資料","只寫『午餐很重要』，讓同學自由猜題目重點","先設計漂亮版面，目標和材料之後再補"],"answer":"A","feedback":"A 把學習目標轉成明確資料任務，作答者知道要找什麼證據。"},{"id":"step-2","prompt":"好的單選題選項應具備哪項特徵？","options":["正解比其他選項長很多，讓人容易猜","選項同層次、互斥，且依題幹資料只有一個最符合的答案","每個選項都加入不同題外知識，考作答者背景"],"answer":"B","feedback":"B 讓答案來自材料與推理，不是從字數、語氣或題外常識猜測。"},{"id":"step-3","prompt":"同儕試答發現多數人誤解題意，下一步最應做什麼？","options":["責怪同學不夠認真，保留原題","檢查題幹動詞、條件、資料範圍與選項措辭，依誤解證據修訂並重新試答","把正解標粗體，其他內容不變"],"answer":"B","feedback":"B 把試答當成設計資料，修正題目本身並驗證是否改善。"}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；國語文自主創作、表述見解與發布定位；核讀 2026-09-21。",["由學習與生活需求主動創作、表達並分享。","以讀者、目的與內容責任完成作品。"],["自訂題目、資料判讀、研究見解、同儕回饋與發布。"],"只把新奇或個人想法當成完整創作，忽略作答者與來源。","重視目標、創作歷程、表述與溝通。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；國語文寫作、閱讀評量與表達實作定位；核讀 2026-09-21。",["透過設計、試作與回饋改善作品。","依讀者、任務、資料與媒介調整發布。"],["選擇題、解析、研究摘要、班級群組、校刊與試答。"],"把答案公布或版面完成誤當成題目已通過測試。","要求作品可理解、可驗證、可修訂。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；國文自主創作、見解表述與評量定位；核讀 2026-09-21。",["從自訂題目與創作主動形成學習作品。","以證據、限制、引用與發布責任支持見解。"],["題幹、選項、答案、解析、研究方法、來源與分眾發布。"],"把公開資料或試題形式直接複製，或把相關說成因果。","評量原創性、答案品質、來源界線、讀者與修訂。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持自主創作、見解表述、讀者溝通、回饋與發布。","作品品質需要由目標、材料、形式、試答與修訂共同驗證。","公開來源、原創界線、答案責任、限制與個資需明確標示。"],"versionDifferences":["南一較突顯主動創作與生活表達；康軒較突顯設計、試作、回饋與媒介調整；翰林較突顯自訂題目、證據、引用、答案與發布責任。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以原創題目五格設計卡連結目標、題幹、選項、解析與試答。","用兩個正解的同儕試答案例示範修訂而非硬指定答案。","以班級群組／校刊雙版本檢查研究發布的讀者與證據責任。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織自主創作、自訂題目、資料來源、答案解析、同儕試答、分眾發布與修訂責任。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 每格完成後都要保存一個可被別人檢查的證據，例如目標動詞、資料定位、選項排除理由或試答紀錄；沒有證據的創意暫列為草稿，不直接發布。"
    data["teaching"]["body"][4]["body"] += " 比較不同發布管道時固定研究結果與限制，再調整摘要長度、背景、方法、連結與隱私；平台不同不代表證據標準可以降低。"
    data["teaching"]["body"][5]["body"] += " 將同儕的錯誤答案視為設計回饋，逐一檢查是否來自題幹、資料、選項或解析，並保留修訂前後版本與仍未解決的問題。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"6-Ⅳ-5：從自主創作到可驗證、可修訂的題目與發布","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored chinese performance 6-iv-5")

if __name__=="__main__": main()
