#!/usr/bin/env python3
"""Independent first-pass authoring for science performance po-IV-2."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-performance-po-iv-2.json"; REPORT=ROOT/"implementation/reports/science-performance-po-iv-2-first-pass-review.json"
URLS={"nani":"https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf","kanghsuan":"https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110","hanlin":"https://drive.google.com/uc?id=1gMUVcDjfXmqIapg-fNnfPuLFaK98dxGX&export=download"}
def rec(p,c,r,m,a): return {"publisher":p,"edition":f"{p} 公立校方自然課程計畫章節級證據","sourceType":"public-web","sourceLocator":f"{URLS[p]}；可探究問題、問題範圍、變因與評量欄位；核讀 2026-09-21。","reviewedAt":"2026-09-21","findings":{"concepts":[c,"公開課程結構支持辨識可由觀察和證據回答的問題，界定範圍、變因、對象與可行方法。"],"representations":[r],"examplesOrEvidence":["本課的校園噪音、植物澆水與月相觀察問題皆為原創情境，只承接公開課程所示的能力方向。"],"misconceptions":[m],"assessmentEmphasis":[a]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。"}
def main():
 d=json.loads(LESSON.read_text(encoding="utf-8")); assert d["id"]=="lesson-science-performance-po-iv-2" and d["reviewStatus"]=="draft"
 d["title"]="po-Ⅳ-2：辨識可科學探究的問題並提出探究問題——把好奇變成可回答"
 d["content"]={"summary":"不是所有好奇都能用同一種科學方法回答。『宇宙為什麼存在』太大，『校園哪個時段噪音分貝較高』有對象、時間、可測量結果和比較範圍；『哪個顏色最美』可能需要價值或文化討論，不宜假裝只有一個實驗答案。本課以校園噪音、植物澆水和月相觀察的原創情境，練習辨識可探究與不可直接探究的問題，縮小範圍、定義變因、檢查安全與資源，提出能被資料回答的問題。","sections":[{"heading":"先分辨問題在問哪一種答案","body":"有些問題問事實和可觀察變化，有些問價值、意義、偏好或倫理。科學探究可以提供資料，但不會單獨決定『應不應該』或『哪個最美』。辨識問題類型能避免選錯方法。"},{"heading":"可探究問題要有邊界","body":"對象、條件、時間、比較和結果越清楚，越能設計觀察或實驗。把『植物怎麼長』縮成『相同光照下，不同澆水量對某植物一週葉片數有何影響』，問題就能被操作。"},{"heading":"不可行不等於沒有價值","body":"太大、太危險、缺少器材或涉及不能操弄的條件，可能暫時無法直接研究。可以縮小尺度、改用觀察資料、模型或公開資料，保留核心好奇並改寫成可行版本。"},{"heading":"好問題會帶出下一步","body":"提出問題後要能說明需要哪些資料、如何測量、哪些條件固定、誰可能受影響和安全界線。若問題仍有兩種解釋，就把它寫成比較，讓下一步能區分它們。"}]}
 d["studyHighlights"]=["分辨事實、價值、偏好、倫理與可由證據回答的問題。","用對象、條件、時間、比較和結果縮小問題範圍。","遇到不可行或有風險的問題，改用觀察、模型或公開資料。","讓問題直接連到資料、變因、方法、影響者與安全界線。"]
 d["teaching"]={"body":[
 {"id":"hook","phase":"hook","heading":"校園哪裡最吵？","body":"有人問『校園噪音是不是很糟』，有人問『午休時操場和圖書館外哪裡分貝較高』。請小組分類兩個問題的差異：第一個含有價值判斷，第二個有地點、時間、數值和比較。再把第一題改寫成既能量測又不抹掉學生感受的兩個問題。"},
 {"id":"explain","phase":"explain","heading":"問題可探究性六項檢查","body":"看問題是否有可觀察對象、可測量結果、明確範圍、可比較條件、可取得資源和安全倫理。通過不代表答案已知，而是表示可以開始規畫資料。未通過時先問能否縮小、改成觀察、使用模型或查公開資料。"},
 {"id":"worked-example","phase":"worked-example","heading":"植物澆水問題的三次縮小","body":"從『水對植物有什麼影響』縮成『同品種植物在相同光照下，不同澆水量一週後葉片數是否不同』，再補上盆土、初始葉片、測量時間和安全方式。這樣自變因、應變因和控制條件都有線索，能形成可檢查的探究。"},
 {"id":"guided-practice","phase":"guided-practice","heading":"月相問題分類卡","body":"判斷三句話：『月亮為什麼存在？』『不同日期同一時間月亮亮面比例如何變化？』『哪個月相最美？』第二題適合觀察和記錄，第一題太大需縮小，第三題涉及偏好。學習者為每題寫一個可行改寫，保留原本的好奇而不混淆問題類型。"},
 {"id":"transfer","phase":"transfer","heading":"設計問題審查會","body":"交換問題後，讀者用六項檢查標註對象、結果、範圍、比較、資源和風險。提問者不能只接受『有趣』評語，要把一個太大或太危險的問題改成下週能安全蒐集資料的版本，並寫出仍未回答的部分。"},
 {"id":"reflect","phase":"reflect","heading":"修正兩個提問迷思","body":"請修正『問題越大越科學』與『不能做實驗就不是科學問題』。大問題可拆成一連串小問題；不能直接操弄的問題仍可用觀察、歷史資料、模型或比較資料回答，重點是方法要和問題類型相配。"}
 ],"summary":["辨識事實、價值、偏好、倫理和可由證據回答的問題。","用對象、結果、範圍、比較和時間把問題縮小。","不可直接操弄時改用觀察、模型或公開資料。","審查問題的資源、安全、倫理與下一步資料。"],"exitCheck":[{"prompt":"為什麼『哪個月相最美』不能只用實驗決定？","expectedEvidence":"它涉及個人偏好與文化價值；可調查觀點，但資料不會單獨決定唯一美感答案。"},{"prompt":"如何把『水對植物有什麼影響』縮小？","expectedEvidence":"指定植物、光照、澆水量、時間、葉片數等結果和控制條件。"},{"prompt":"沒有器材時可如何保留科學問題？","expectedEvidence":"縮小範圍、改用觀察、模型、公開資料或可取得的安全測量，不假裝已能回答。"}]}
 d["interactive"]={"type":"guided-choice","goal":"辨識問題類型與可行性，把好奇改寫成有範圍、可觀察、可安全探究的問題。","scenario":"審查校園噪音、植物澆水與月相問題，逐步選出合適的方法和改寫。","variables":[{"symbol":"q","meaning":"原始問題"},{"symbol":"b","meaning":"問題邊界"},{"symbol":"m","meaning":"可行方法"}],"steps":[{"id":"step-1","prompt":"哪個問題最接近可直接量測比較？","options":["午休時操場和圖書館外的分貝是否不同","校園噪音是不是很糟","哪種聲音最有意義"],"answer":"A","feedback":"它指定時間、地點、數值和比較，能形成觀察計畫。"},{"id":"step-2","prompt":"『月亮為什麼存在』要如何處理？","options":["縮小成特定日期、時間的月相或亮面變化觀察","直接用一次照片回答宇宙起源","因為太大就嘲笑提問"],"answer":"A","feedback":"保留好奇並縮小尺度，才能讓資料和方法接得上。"},{"id":"step-3","prompt":"沒有安全器材時最合理的做法是什麼？","options":["改用觀察、公開資料或模型，並說明仍無法回答的部分","為了完成而冒險操作","捏造一組看似完整的測量"],"answer":"A","feedback":"可行性和安全是問題設計的一部分，不能用虛構資料取代。"}]}
 d["authoringStandard"]="version-fused-v1"
 d["versionResearch"]=[rec("nani","以觀察現象、界定問題和探究方法培養科學提問能力。","問題分類、變因、對象、時間、結果、可行性檢核。","把大問題、價值偏好或原因猜測直接當成可做實驗。","重視問題品質、範圍、方法對齊與安全。"),rec("kanghsuan","透過討論、改寫和探究設計辨識問題可行性與證據需求。","問題卡、同儕審查、觀察、模型、公開資料與修正版。","因沒有器材就捏造資料，或因不能操弄就否定問題價值。","評量提問、縮小範圍、資源、變因與方法選擇。"),rec("hanlin","連結校園、環境、月相與生活議題，區分事實、價值、倫理和科學問題。","噪音、植物、月相、時間、尺度、資源與安全。","把科學資料當成唯一價值答案，或忽略受影響者與倫理。","要求問題適切、範圍清楚、方法可行與負責任。")]
 d["fusionRecord"]={"commonCore":["三版本公開結構共同支持辨識可由觀察和證據回答的問題並提出探究問題。","對象、結果、範圍、比較、資源、方法和安全是共同檢核項目。","太大、不可行或涉及價值的問題可縮小、改用觀察／模型／資料並保留好奇。"],"versionDifferences":["南一證據較突顯現象、問題和基本探究方法；康軒較突顯討論、問題改寫、資源與方法選擇；翰林較突顯校園環境、月相、事實價值倫理與責任。這是公開課程計畫層級差異，不宣稱完整教材差異。"],"originalAdditions":["以校園噪音比較價值判斷和分貝觀察問題。","以植物澆水問題三次縮小示範變因、結果和控制。","以月相分類卡練習太大、可觀察和偏好問題的改寫。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織問題類型、可探究性、範圍、變因、資源、安全、倫理與觀察／模型／公開資料方法。正文、原創問題卡、互動步驟、錯誤回饋與檢核均為本專案重寫，未複製任何教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
 d["updatedAt"]="2026-09-21"; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"po-Ⅳ-2：辨識可科學探究的問題並提出探究問題","lessonId":d["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 print(json.dumps({"lesson":str(LESSON.relative_to(ROOT)),"reviewStatus":d["reviewStatus"]},ensure_ascii=False))
if __name__=="__main__": main()
