import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/chinese/lesson-chinese-performance-6-iv-3.json"
REPORT=ROOT/"implementation/reports/chinese-performance-6-iv-3-first-pass-review.json"

def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher":name,"edition":f"{name} 公立校方國文課程計畫章節級證據","sourceType":"public-web","sourceLocator":locator,"reviewedAt":"2026-09-21","findings":{"concepts":concepts,"representations":forms,"examplesOrEvidence":["本課以原創比喻、語體轉換、視角限制、短句節奏與壓縮改寫卡，承接公開課程的語文表達、仿寫改寫與語意保留方向。"],"misconceptions":[misconception],"assessmentEmphasis":[assessment]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}

def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-chinese-performance-6-iv-3"
    data["title"]="6-Ⅳ-3：在仿寫與改寫中保留核心、轉換形式"
    data["content"]={"summary":"仿寫不是把名詞換掉，改寫也不是把句子縮短；兩者都要求先辨認原句的核心關係、形式限制與溝通目的，再有意識地改變指定部分。比喻仿寫要保留喻體關係，語體改寫要保留原意而調整對象與語氣，視角改寫要守住知道什麼的範圍，縮寫則要留住必要流程。本課用自編句型、敘述、公告、標題與緊張節奏練習，最後用語意回譯檢查作品是否仍然成立。", "sections":[{"heading":"先拆原句的不可失去部分","body":"讀原句時標記主體、動作、因果、時間、語氣、比喻關係與資訊限制，再區分必須保留和可以替換的元素。『雨水沿著屋簷落下，像透明珠簾』的核心不只在雨水，也在沿著屋簷落下的動態和雨簾的視覺相似；換場景仍要保留這個關係。"},{"heading":"仿寫改變材料但不偷換結構","body":"仿寫可以換主詞、場景或感官細節，但句型骨架和修辭關係要可辨認。若原句是『A 的動作，像 B』，新句也要讓 A 與 B 具有可說明的相似處，不能只放兩個漂亮名詞；完成後把新句拆回骨架，檢查是否仍對得上。"},{"heading":"改寫要先指定轉換任務","body":"口語改公告、第一人稱改第三人稱限知、長句改標題或短文改短句，各有不同限制。先寫目標讀者、文體、字數與不得改動的語意，再進行變形；若第三人稱限知角色不知道弟弟的內心，就不能補寫全知心理。"},{"heading":"用回譯和讀者測試守住原意","body":"改寫完成後先把新句回譯成一句原意摘要，再對照原文檢查因果、時間、主客體、肯定程度和語氣是否改變。最後請讀者只看改寫版說出資訊與任務；若形式漂亮卻使讀者誤解，就應優先修正語意而非繼續裝飾。"}]}
    data["studyHighlights"]=["拆出原句核心關係、形式骨架與不可改動資訊。","仿寫換材料但保留句型或修辭關係。","依目標讀者、文體、視角與字數進行改寫。","用回譯、限制檢查與讀者測試確認原意。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"換了名詞就算仿寫嗎？","body":"展示原創句『雨水沿著屋簷落下，像一串透明的珠簾』和三個候選句：一個只換名詞、一個保留動態與比喻、一個句意漂亮但沒有相似關係。請學習者先畫出主體、動作與喻體，再判斷哪句真正保留骨架，建立先拆結構再創作的入口。"},{"id":"explain","phase":"explain","heading":"仿寫與改寫四步檢核","body":"第一步寫原句核心語意；第二步標出固定骨架、限制與可換材料；第三步依任務改變指定形式；第四步回譯新句並請讀者重述。每一步都要記錄哪個元素被保留、哪個被轉換，若語意或語氣偷偷改變，就回到限制重新修訂。"},{"id":"worked-example","phase":"worked-example","heading":"把快速奔跑改成看得見的動作","body":"以自編句『他很快地跑過操場』示範，先保留人物、方向與速度，再加入鞋底敲擊、呼吸、身體前傾等可觀察細節。提醒學習者畫面感不是堆形容詞，而是選擇能讓讀者推得出速度的動作；改寫後仍要能回譯成原本的基本事件。"},{"id":"guided-practice","phase":"guided-practice","heading":"在視角限制內改寫信封情節","body":"原句由『我』看見弟弟藏起信封，練習改成第三人稱限知。學習者先列出敘述者能看到的動作，再刪除只有弟弟才知道的心理和秘密內容；互換稿件後，讀者圈出任何超出視角的資訊，讓限制成為創作提示而非阻礙。"},{"id":"transfer","phase":"transfer","heading":"同一訊息轉成公告與標題","body":"把口語邀請改成校方公告，再將小組研究流程壓縮成標題。先固定活動內容、對象、時間和順序，再調整語氣、格式與字數；公告要能執行，標題要保留流程主幹，若壓縮後讀者不知道下一步，就補回必要詞語。"},{"id":"reflect","phase":"reflect","heading":"檢查我是否把改寫變成另一件事","body":"將改寫版和原句並列，逐項核對主客體、因果、時間、肯定程度、視角與讀者任務。若句子更華麗但原本的限制消失，刪除多餘創意；若縮寫漏掉關鍵步驟，恢復能讓讀者重做任務的最小資訊。"}],"summary":["先拆出原句語意、形式骨架與限制。","仿寫換材料但保留句型或修辭關係。","依文體、視角、讀者與字數進行受約束的改寫。","用回譯與讀者重述檢查原意和任務是否仍清楚。"],"exitCheck":[{"prompt":"仿寫時哪些元素通常不能隨意丟掉？","expectedEvidence":"能指出原句的核心事件或關係、句型／修辭骨架與題目指定限制，並說明可替換材料。"},{"prompt":"第三人稱限知改寫為何不能補寫所有角色的內心？","expectedEvidence":"能說明視角決定敘述者可知道的範圍，只能寫該角色可觀察或已知的資訊。"},{"prompt":"如何確認改寫沒有改變原意？","expectedEvidence":"能用回譯核對主客體、因果、時間、語氣與字數任務，再請讀者重述比較。"}]}
    data["interactive"]={"type":"guided-choice","goal":"在指定形式、語體、視角與字數限制中保留原句核心語意並完成可讀改寫。","scenario":"學生接到一組仿寫與改寫卡，先拆解原句骨架，再依不同任務創作，最後用回譯和讀者重述驗證。","variables":[{"symbol":"s","meaning":"原句骨架與語意"},{"symbol":"t","meaning":"轉換任務與限制"},{"symbol":"v","meaning":"回譯、視角與讀者檢查"}],"steps":[{"id":"step-1","prompt":"要保留比喻結構仿寫校園景象，哪種做法最適切？","options":["換掉所有詞語即可，不必保留相似關係","保留主體動作與『像……』的可說明相似處，再替換校園材料","只使用更多形容詞，句型和關係可以完全不同"],"answer":"B","feedback":"B 同時保留句型骨架、動態與比喻關係，材料才是有控制的替換。"},{"id":"step-2","prompt":"原句由『我』看見弟弟藏起信封，改成第三人稱限知時，哪項符合限制？","options":["直接說出弟弟藏信封是因為害怕被發現","寫第三人稱敘述者看見弟弟把信封塞進抽屜，但不補寫弟弟不知道的內心","補上所有人物的想法，讓讀者知道完整真相"],"answer":"B","feedback":"B 守住限知視角，只使用可觀察或該視角已知的資訊。"},{"id":"step-3","prompt":"題目要求三十字內改寫且不可改變語意，完成後最重要的檢查是什麼？","options":["只數字數，越短越好","回譯核對主客體、因果、時間與肯定程度，再確認讀者仍能完成原任務","加入新觀點讓句子更有創意"],"answer":"B","feedback":"B 同時檢查字數與語意保留，避免形式合格但內容已變質。"}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；國語文仿寫、改寫與表達定位；核讀 2026-09-21。",["以語文形式轉換與仿寫發展表達能力。","在保留內容的條件下調整語句與文體。"],["比喻、描寫、公告、標題、句型與語意保留。"],"只替換名詞或把句子變長就當成改寫。","重視形式辨識、語意保留與表達創意。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；國語文句型、文體與寫作實作定位；核讀 2026-09-21。",["透過仿寫、改寫與比較理解語句效果。","依讀者、文體與限制調整語氣和結構。"],["比喻、短句、視角、口語／公告、流程標題與回譯。"],"忽略視角、字數或讀者任務，只追求句子漂亮。","要求轉換有依據、限制可檢查且原意清楚。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；國文仿寫、改寫技巧與評量定位；核讀 2026-09-21。",["從原句結構、語意與表達目的完成仿寫改寫。","以讀者、視角與任務檢核轉換後的內容。"],["句型仿寫、語體、敘述視角、縮寫、修辭與語意回譯。"],"把創意新增內容當成保留原意，或超出限知視角。","評量結構掌握、語意、形式轉換與修訂反思。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持仿寫、改寫、句型、文體與語意表達。","形式轉換必須同時處理原句核心、讀者任務與指定限制。","創意要建立在可回譯、可檢查的語意保留上。"],"versionDifferences":["南一較突顯仿寫改寫與語文表達；康軒較突顯句型、文體、讀者與實作比較；翰林較突顯原句結構、視角、任務限制與評量檢核。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以仿寫與改寫四步檢核拆開骨架、限制、轉換與回譯。","用視角改寫卡實際標出可知道與不可補寫的資訊。","用公告與標題兩種壓縮任務測試讀者能否完成原目的。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織仿寫、改寫、修辭、文體、視角、字數限制與語意回譯。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 每張檢核卡都要同時保存原句與新句，並在轉換位置旁標記保留或改變的理由；若讀者回譯不回原意，先修正限制而非增加裝飾。"
    data["teaching"]["body"][4]["body"] += " 比較公告與標題時固定核心資訊，再分別處理讀者、語氣、格式與字數；兩者都要讓讀者知道下一步，但不必用同樣的句型。"
    data["teaching"]["body"][5]["body"] += " 把新句中所有新增的心理、因果或評價圈出，確認題目是否允許；若沒有依據，就刪除或改成可觀察、可回譯的說法。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"6-Ⅳ-3：在仿寫與改寫中保留核心、轉換形式","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored chinese performance 6-iv-3")

if __name__=="__main__": main()
