import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-2-iv-12.json"
REPORT = ROOT / "implementation/reports/english-performance-2-iv-12-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創午餐減廢、圖書館噪音、植物、數位檔案、海報與短片討論，承接公開課程的引導式討論、理由證據與合作決策方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-2-iv-12"
    data["title"] = "2-Ⅳ-12：用主持、理由與證據完成引導式討論"
    data["content"] = {"summary": "引導式討論不是每個人輪流發表意見而已；主持人要界定主題、邀請想法、管理輪次與時間，成員要提出主張、理由、證據、疑慮與替代方案，最後把共識轉成分工、表決或可追蹤的下一步。本課以午餐減廢、圖書館噪音、飲水站、校園植物、紙張使用、海報或短片方案等原創討論，練習 because、for example、I agree, but、Could we compare …?、Let's summarize 與 vote 等語句，讓意見不只停在喜好，而能被檢查、回應與執行。", "sections": [{"heading": "主持人先畫出討論範圍", "body": "Our topic is how to make lunch less wasteful. What ideas do we have? 同時完成定題與開放邀請；主持人不應一開始替小組選好答案。先確認主題、時間和決策方式，再讓成員提出一個可理解的想法，討論才不會漂移。"}, {"heading": "主張後面要有理由和證據", "body": "We should add a water station because many students forget to bring bottles. because 後面說明理由，但 many students 是可查證的主張，還需要調查、觀察或紀錄支持。討論時可問 What evidence do we have?，把意見和資料分開。"}, {"heading": "同意可以保留疑慮", "body": "I agree that more plants could help, but who will water them? 先承認提案價值，再提出資源與執行疑問；這不是反對人，而是補足條件。兩人同時發言時，moderator 要分配輪次，讓每個意見都能被聽見而不互相覆蓋。"}, {"heading": "結論要留下可追蹤的工作", "body": "Less paper、share digital files、review next month 若沒有負責人、期限和檢查方法，只是口號。好的摘要列出決定、分工、資料蒐集、呈現方式與回顧時間；遇到海報和短片分歧，可先比較觀眾、時間與成本，或用小規模測試再決定。"}]}
    data["studyHighlights"] = ["用主題、時間與決策方式建立討論邊界。", "以主張、理由、證據與疑慮區分意見和可查資料。", "用主持輪次、I agree, but 與比較問題保持建設性。", "把結論轉成分工、期限、檢查方法與可修訂的下一步。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "討論有很多意見就算成功嗎？", "body": "給出完全自編的午餐減廢討論，第一組只收集 I like it、I do not like it，第二組加上因果、證據問題和下一步。請第三組判斷哪一組能真的做決定，讓學生看見引導式討論的品質在於理由、回應和可執行結果。"}, {"id": "explain", "phase": "explain", "heading": "討論七欄紀錄板", "body": "建立 Topic、Proposal、Reason、Evidence、Concern、Decision、Next action 七欄。主持人先填 Topic，再讓成員把提案和理由分開，追問證據，記錄疑慮，最後才寫決定與負責人、期限、檢查方式。每一欄都要能回指發言或資料。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從同意到可執行的疑問", "body": "以 more plants 提案示範 I agree, but who will water them?，再補 Could we make a weekly schedule?。學生先辨認支持的價值，再把疑慮改成可以解決的問題；比較直接說 No plants 與提出條件，理解建設性異議如何推進方案。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "讓主持人管理同時發言和時間", "body": "給四人小組午餐、噪音、紙張與展示方案卡，安排兩人同時說話、只剩五分鐘或資料不足的突發情境。主持人使用 Could you finish your point?、Let's hear one more idea、Let's vote 等句子，記錄成員觀點和決策依據。"}, {"id": "transfer", "phase": "transfer", "heading": "把分歧轉成比較或小測試", "body": "輪換海報／短片、飲水站／提醒標語、紙本／數位檔案等選擇。學生先列比較標準，再提出證據問題或小規模試行，最後以一句英文摘要說明目前決定、尚未確定的部分與下一次檢查時間，避免把多數票誤當成最佳證據。"}, {"id": "reflect", "phase": "reflect", "heading": "我們的結論能被別人接手嗎？", "body": "回看紀錄板，檢查每個決定是否有提案、理由、證據、疑慮、負責人、期限和成功指標。若只有喜好或投票結果，補一個可驗證資料；若沒有下一步，將結論改寫成可在下次會議回報的 action。"}], "summary": ["以 Topic、Proposal、Reason、Evidence、Concern、Decision、Next action 記錄討論。", "將主張、理由、證據與疑慮分開，避免喜好代替資料。", "用主持輪次、時間管理與 I agree, but 維持公平討論。", "把決定連到分工、期限、指標與下次檢查。"], "exitCheck": [{"prompt": "引導式討論的主持人先要管理什麼？", "expectedEvidence": "能指出主題、時間、發言輪次與決策方式，並讓成員知道討論邊界。"}, {"prompt": "如何判斷一句話需要更多證據？", "expectedEvidence": "能區分主張、理由與可查資料，對 many、everyone 或效果等說法提出資料問題。"}, {"prompt": "如何把不同意轉成建設性討論？", "expectedEvidence": "能先承認提案價值，再提出條件、比較標準、小測試或可驗證的疑慮。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "在引導式討論中提出提案、理由、證據與疑慮，並由主持人整理成可執行的決定。", "scenario": "學生組成校園改善小組，要討論午餐減廢、圖書館噪音與展示方案，最後留下分工、期限與檢查方法。", "variables": [{"symbol": "p", "meaning": "主題、提案、理由與證據"}, {"symbol": "d", "meaning": "疑慮、比較標準、輪次與時間"}, {"symbol": "a", "meaning": "決策、分工、期限與回顧行動"}], "steps": [{"id": "step-1", "prompt": "The chair says, 'Our topic is how to make lunch less wasteful. What ideas do we have?' What is the chair doing?", "options": ["Setting the topic and inviting ideas.", "Announcing that one idea has already won.", "Ending the meeting without hearing anyone."], "answer": "A", "feedback": "A identifies both jobs in the chair's sentence: defining the discussion and opening the floor."}, {"id": "step-2", "prompt": "A student says, 'We should add a water station because many students forget to bring bottles.' What does the second part do?", "options": ["It gives a reason for the proposal.", "It changes the topic to a school play.", "It proves that every student forgot a bottle."], "answer": "A", "feedback": "Because many students forget bottles explains the proposal; it is a reason that may still need evidence, not proof about everyone."}, {"id": "step-3", "prompt": "One member wants posters; another wants a short video. Which proposal handles the disagreement constructively?", "options": ["Let's compare our audience, time, and materials, then choose or test one.", "The louder person should decide immediately.", "Neither idea matters, so we should stop talking."], "answer": "A", "feedback": "A creates shared criteria and a possible small test, turning disagreement into a checkable decision."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語引導討論、合作與生活議題定位；核讀 2026-09-21。", ["以生活議題、合作任務和簡易英語表達想法。", "透過提問、理由與回應參與討論。"], ["主題、提案、原因、同意、異議、時間與決策。"], "把討論當成輪流說喜好，沒有主題、理由或下一步。", "重視合作溝通、生活議題與功能性回應。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語聽說、合作討論與任務活動定位；核讀 2026-09-21。", ["透過角色、問題和小組活動提出並回應意見。", "依輪次、禮貌、證據和分工完成共同任務。"], ["午餐、噪音、植物、紙張、數位檔案、海報與短片。"], "只用 I agree／I disagree，沒有說明理由、聽取他人或整理決定。", "評量主要內容、理由、互動、合作與任務完成。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語討論、證據與合作決策評量定位；核讀 2026-09-21。", ["從討論發言、問題和資料形成有界線的結論。", "以摘要、分工、比較和追蹤行動完成表達。"], ["topic、proposal、reason、evidence、concern、decision、next action。"], "用多數票或個人喜好取代證據，或結論沒有負責人和檢查方法。", "評量觀點、理由、證據、聆聽、摘要與後續行動。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持引導討論、合作溝通、理由表達與生活議題決策。", "討論需整合主題、提案、理由、證據、疑慮、輪次、時間與下一步。", "從意見交換到可追蹤結論可用紀錄板、角色主持、比較標準與小測試驗證。"], "versionDifferences": ["南一較突顯生活議題與合作表達；康軒較突顯角色、禮貌、輪次、活動與分工；翰林較突顯討論證據、摘要、比較、決策與追蹤評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Topic、Proposal、Reason、Evidence、Concern、Decision、Next action 七欄紀錄討論。", "用午餐、噪音、植物、紙張、海報與短片原創議題練習理由和證據。", "以主持輪次、比較標準、小測試和下次回顧檢查決策品質。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織主題、提案、理由、證據、疑慮、主持、輪次、比較、決策、分工與追蹤行動。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 七欄填完後讓另一組只看 Decision 和 Next action 重述會議結果；若無法重述，回到 Evidence 或 Concern 找缺漏，而不是用更抽象的 success 取代具體指標。"
    data["teaching"]["body"][4]["body"] += " 小測試要先說明比較標準、樣本或時間，再決定何時回顧；這讓討論保持開放但不無限延後，也不把投票結果假裝成因果證據。"
    data["teaching"]["body"][5]["body"] += " 若結論不能交給下一位同學接手，補上負責人、期限、資料位置與回報方式；一個可追蹤的未決問題也比沒有證據的確定答案更誠實。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "2-Ⅳ-12：用主持、理由與證據完成引導式討論", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 2-iv-12")


if __name__ == "__main__":
    main()
