import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-15.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-15-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "point of view, attitude, purpose, detail, and evidence"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "narrator limitation, tone, audience, claim, and support"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "newsletter purpose, evaluative language, reflection, and inference"),
    ]
    return [{"url": u, "title": f"{t}；僅取敘事觀點、態度、目的與證據判讀方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以第一人稱、形容詞副詞、寫作目的、讀者行動、觀點限制與主張證據測量文本分析；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-3-iv-15"
    data["title"] = "3-Ⅳ-15：從敘事觀點、語氣與目的辨識作者立場並核對證據"
    data["content"] = {"summary": "分析文本不能只找內容，也要問誰在說、知道什麼、用什麼語氣、為何寫給誰，以及主張是否有足夠證據。本課以校園花園觀察、社區花園、節能倡議、公車報告、有限視角、回收招募、迎接新同學、步行會議、時程評論與海灘清理反思等原創文本，練習敘事觀點、資訊限制、態度語氣、寫作目的、受眾行動、主張支持與反思可信度。", "sections": [{"heading": "先找說話位置與可見範圍", "body": "I checked、I saw、I do not know 等第一人稱線索顯示敘事者的位置與限制；看到 Mei 進房間不代表知道她的計畫。先畫出 narrator knows 和 narrator cannot know 兩欄，避免把全知資訊放進有限觀點。"}, {"heading": "態度藏在選字和語氣", "body": "cheerful、unfortunately、wonderfully 等詞不只是修飾，它們透露正面、遺憾、讚賞或評價方向。要分清可驗證事實與作者態度，不能因一個褒義詞就推成所有讀者都同意。"}, {"heading": "目的要連到讀者下一步", "body": "社團招募信若列加入方式、email 和 deadline，目的偏向提供資訊並促成報名；三個關燈理由後以 Small actions save energy 收束，則可能在說服讀者改變行動。目的由結構與語氣共同支持。"}, {"heading": "主張需要可對照的證據", "body": "walking meetings help teams think 的主張，應由比較會議成果、參與者回饋或具體任務表現支持。第一人稱反思若承認 underestimated the trash，能增加自我修正的可信度，但不自動證明所有海灘清理都會成功。"}]}
    data["studyHighlights"] = ["用 narrator knows／cannot know 分析觀點、資訊範圍與推論限制。", "從形容詞、副詞、轉折和結尾判斷作者態度與語氣。", "把寫作目的連到讀者、文本結構與要求的下一步。", "主張要和直接、相關、足夠的證據配對，反思也要保留範圍。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "第一人稱就知道所有人的想法嗎？", "body": "比較兩段原創文字：I saw Mei enter the room 與 Mei felt nervous about the plan。請學生判斷哪句是敘事者可直接觀察、哪句需要內在證據，建立觀點限制。"}, {"id": "explain", "phase": "explain", "heading": "觀點—語氣—目的三層卡", "body": "建立 Viewpoint、Attitude、Purpose 三欄，再加 Evidence／Limit。先辨識資訊來源與語氣詞，接著問文本要告知、說服、招募、反思或評價什麼，最後標出證據和不能確定的範圍。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從評論詞和事實分開態度", "body": "以 wonderfully flexible plan 為例：schedule 的彈性可能是事實，但 wonderfully 是作者的正面評價。示範改寫成中性句，再比較兩句語氣差異，避免把評價詞當客觀測量。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一主張換證據", "body": "用步行會議、節能、回收、社區花園、巴士舒適度與海灘清理六組原創文本，學生輪流標主張、理由、證據、語氣與受眾，並判斷資料是否足夠支持結論。"}, {"id": "transfer", "phase": "transfer", "heading": "把觀點改寫成不同讀者版本", "body": "把海灘清理反思分別改成給同學的行動邀請、給校方的報告與給自己的學習札記。學生保留事實，調整語氣與目的，說明哪些新增詞是評價而非觀察。"}, {"id": "reflect", "phase": "reflect", "heading": "我把作者的話當成事實了嗎？", "body": "回看答案，標記把第一人稱當全知、把語氣詞當資料、把目的當主旨、把單一例子擴大或忽略反思限制的地方。修訂時用觀點、態度、目的、證據四欄重新核對。"}], "summary": ["用 Viewpoint、Attitude、Purpose、Evidence／Limit 四欄分析文本。", "分辨敘事者知道的事、觀察到的事與不能確定的內在想法。", "從選字、結構、讀者與結尾判斷語氣和寫作目的。", "將主張與相關證據配對，保留單一案例和反思的範圍。"], "exitCheck": [{"prompt": "如何判斷第一人稱敘事者的資訊限制？", "expectedEvidence": "能指出 I saw、I do not know 等語句，說明哪些是直接觀察、哪些不能確定。"}, {"prompt": "褒義或貶義詞對文本分析有什麼作用？", "expectedEvidence": "能把選字連到作者態度與語氣，並與可驗證事實分開。"}, {"prompt": "如何檢查一個主張是否被支持？", "expectedEvidence": "能找出直接、相關、足夠的理由或資料，並指出證據不足時結論應縮小。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "辨識敘事觀點、作者態度與寫作目的，並用範圍適當的證據檢查文本主張。", "scenario": "學生擔任校刊編輯，要分析不同文章的說話位置、語氣、讀者目的與證據強度。", "variables": [{"symbol": "v", "meaning": "敘事者位置、知道與不知道的資訊"}, {"symbol": "t", "meaning": "態度、語氣詞與寫作目的"}, {"symbol": "e", "meaning": "主張、證據、受眾行動與限制"}], "steps": [{"id": "step-1", "prompt": "A narrator says, 'I saw Mei enter the room, but I do not know what she planned.' What is the limitation?", "options": ["The narrator can observe the action but not Mei's private plan.", "The narrator knows every character's thoughts.", "The narrator was not present at all."], "answer": "A", "feedback": "A 同時保留看見的直接證據與不知道內在計畫的限制。"}, {"id": "step-2", "prompt": "A review calls a schedule 'a wonderfully flexible plan.' What does wonderfully mainly show?", "options": ["The writer's positive attitude.", "The exact number of free hours.", "That the schedule is impossible."], "answer": "A", "feedback": "wonderfully 是評價語氣，顯示作者態度，不是精確數據。"}, {"id": "step-3", "prompt": "Which evidence best supports the claim that walking meetings help teams think?", "options": ["A comparison shows teams generated more ideas while walking.", "The writer likes the color of walking shoes.", "One unrelated person owns a bicycle."], "answer": "A", "feedback": "A 直接比較行走會議與想法產出，與主張相關且可檢驗。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；生活文本、觀點與主要訊息定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由生活文本理解說話者、主要訊息與目的。", "以人物、行動、理由與結果整理觀點。"], "representations": ["花園、交通、回收、報告與校刊文本。"], "examplesOrEvidence": ["本課以觀察、招募、節能與海灘原創文本承接公開結構。"], "misconceptions": ["把第一人稱敘事當成全知視角。"], "assessmentEmphasis": ["重視主要內容、觀點與生活溝通目的。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖文、任務與作者目的定位；核讀 2026-09-21。", "findings": {"concepts": ["透過圖文與任務辨識作者態度、讀者與行動。", "依理由、例子與資訊限制完成理解。"], "representations": ["新聞稿、評論、社區倡議、電子報與報告。"], "examplesOrEvidence": ["本課以三層分析卡重新設計觀點與目的活動。"], "misconceptions": ["把評價詞當成客觀資料，或忽略讀者下一步。"], "assessmentEmphasis": ["評量觀點、目的、語氣與證據。"], "misconceptions": ["把評價詞當成客觀資料，或忽略讀者下一步。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；敘事觀點、語氣、主張與證據定位；核讀 2026-09-21。", "findings": {"concepts": ["從敘事者位置、選字與結構形成文本分析。", "以主張、證據、限制與反思檢查可信度。"], "representations": ["viewpoint、attitude、purpose、claim、support、limit。"], "examplesOrEvidence": ["本課以敘事限制、評價詞與主張比較重新設計證據活動。"], "misconceptions": ["以單一例子或作者語氣推成普遍事實。"], "assessmentEmphasis": ["評量觀點、語氣、目的、證據與推論範圍。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持生活文本、說話者、觀點與目的理解。", "可靠分析需整合敘事位置、態度語氣、讀者目的、主張與證據。", "可用觀點—語氣—目的卡、讀者改寫與證據配對完成遷移。"], "versionDifferences": ["南一較突顯生活文本、人物與目的；康軒較突顯圖文、任務、態度與讀者行動；翰林較突顯敘事限制、評價詞、主張、證據與反思。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Viewpoint、Attitude、Purpose、Evidence／Limit 四欄分析文本。", "用社區花園、節能、公車、回收、步行會議、評論與海灘原創文本練習。", "以同一事實的校刊、報告與札記改寫檢查觀點與目的轉換。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織敘事觀點、資訊限制、作者態度、寫作目的、受眾、主張與證據。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-3-iv-15-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先辨識敘事者位置與文本目的，再分析語氣選字，最後把主張和直接相關證據及限制配對。"; q["solutionSteps"] = ["先找 I／we、觀察動詞與評價詞，判斷資訊來源和語氣。", "判斷文本給誰、為何寫，以及題目要求觀點、態度、目的或證據哪一層。", "回到原文找支持答案的句子、資料、結構或受眾行動。", "分開可驗證事實、作者評價與推論，排除把單一例子擴大的選項。", "用完整句說明答案及其限制，確認沒有把敘事者不知道的事補成事實。" ]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的觀點、態度、目的、主張與證據模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-15")


if __name__ == "__main__":
    main()
