#!/usr/bin/env python3
"""Independent first-pass authoring for math a-IV-5."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/'lessons/math/lesson-math-performance-a-iv-5.json'
REPORT=ROOT/'implementation/reports/math-performance-a-iv-5-first-pass-review.json'
URLS={'nani':'https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf','kanghsuan':'https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110','hanlin':'https://www.cp.ptc.edu.tw/storage/134513/134513_112_B-1_9A.pdf'}
def rec(p,c,r,m,a):
 return {'publisher':p,'edition':f'{p} 公立校方數學課程計畫章節級證據','sourceType':'public-web','sourceLocator':f'{URLS[p]}；多項式運算、乘法公式與代數表徵評量欄位；核讀 2026-09-21。','reviewedAt':'2026-09-21','findings':{'concepts':[c,'公開結構支持把多項式視為可分解、可重組的代數物件，運算結果要能回到原式檢查。'],'representations':[r],'examplesOrEvidence':['本課的面積模型、符號式與反向因式分解例子均為原創，只研究公開能力方向。'],'misconceptions':[m],'assessmentEmphasis':[a]},'licenseBoundary':'只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。'}
def main():
 d=json.loads(LESSON.read_text(encoding='utf-8')); assert d['id']=='lesson-math-performance-a-iv-5' and d['reviewStatus']=='draft'
 d['title']='a-Ⅳ-5：多項式運算與乘法公式的來回檢查'
 d['content']={'summary':'多項式的加減乘除不是把符號排隊，而是先辨識同類項、分配律與結構。本課以矩形面積拆分建立 (a+b)² 與 (a+b)(a−b)，再把展開式反向整理成因式，讓學生用圖形、符號與數值代入互相驗算，並診斷漏寫中間項、符號錯誤與把不同類項硬合併的迷思。','sections':[{'heading':'先分清同類項','body':'3x 與 5x 都含相同的 x 次方，可以合成 8x；3x 與 5x² 不是同類項，不能只因都有 x 就相加。整理多項式前先標記每一項的字母部分與次方。'},{'heading':'分配律是乘法的路徑','body':'(x+2)(x+5) 要把第一個括號的每一項都乘到第二個括號，再合併同類項，得到 x²+7x+10。漏乘一項會讓結果看似簡潔卻失去原式。'},{'heading':'公式來自面積與差平方','body':'(a+b)² 可看成邊長 a+b 的正方形拆成 a²、ab、ab、b² 四塊，所以中間有 2ab；(a+b)(a−b) 則可視為差平方 a²−b²。圖形是理解係數來源的證據。'},{'heading':'展開與因式分解互相回查','body':'x²+6x+9 可反向看成 (x+3)²；完成因式分解後再展開一次，若回不到原式，就要檢查符號、常數與中間項。'}]}
 d['studyHighlights']=['先標記每一項的字母與次方，再判斷是否同類項。','乘法使用分配律，逐項相乘並保留正負號。','用面積拆分理解乘法公式，不把 2ab 漏成 ab。','展開與因式分解要互相代回，確認形式改變但值不變。']
 d['teaching']={'body':[{'id':'hook','phase':'hook','heading':'一塊被切開的地毯','body':'把邊長 a+b 的正方形畫成四塊，請學生先預測總面積中為何會出現兩塊 ab。讓圖形中的兩個長方形成為 2ab 的來源，避免公式只停留在口訣。'},{'id':'explain','phase':'explain','heading':'同類項與分配律','body':'以 (x+2)(x+5) 的四格面積表逐格填入 x²、5x、2x、10，再把 5x 與 2x 合成 7x。每一格都標記來自哪兩項，讓漏乘能被定位。'},{'id':'worked-example','phase':'worked-example','heading':'兩個公式的結構差異','body':'先用面積得到 (a+b)²=a²+2ab+b²，再用相同方法比較 (a+b)(a−b)=a²−b²。代入 a=5、b=2 做數值回算，確認左右兩種寫法相等。'},{'id':'guided-practice','phase':'guided-practice','heading':'從展開走回因式','body':'處理 x²−10x+25，學生先找平方項與常數的平方根，再確認中間項是 2×x×(−5)，所以可寫成 (x−5)²。完成後反向展開，不接受只看外觀的答案。'},{'id':'transfer','phase':'transfer','heading':'用差平方估算面積','body':'一個矩形邊長為 (30+1) 與 (30−1)，學生可以直接用差平方算出面積，也可展開後計算；比較兩條路徑在心算與檢查上的優勢，說明公式適用的結構。'},{'id':'reflect','phase':'reflect','heading':'找出錯誤的那一項','body':'出口題提供一個漏掉 2ab 的展開式，學生要用面積圖、代入小數值與反向整理三種證據指出錯誤位置；最後寫出下一次要檢查的順序，而不是只改答案。'}],'summary':['辨認同類項與分配律是整理多項式的起點。','用面積拆分說明公式中的每個項與係數來源。','展開與因式分解是可互相回查的兩個方向。','代入簡單數值與反向運算能抓出符號及漏項錯誤。'],'exitCheck':[{'prompt':'為什麼 3x 與 5x² 不能合併？','expectedEvidence':'字母次方不同，不是同類項。'},{'prompt':'(a+b)² 中的 2ab 從哪裡來？','expectedEvidence':'面積拆分有兩個 ab 長方形，或由分配律得到 ab+ab。'},{'prompt':'因式分解後如何確認正確？','expectedEvidence':'重新展開並與原多項式逐項比較。'}]}
 d['interactive']={'type':'algebra-expression-builder','goal':'以面積格與符號步驟理解多項式展開、公式與因式分解。','scenario':'調整 a、b 的數值，觀察四塊面積、展開式與乘法結果同步變化。','variables':[{'symbol':'a','meaning':'正方形邊長的第一部分'},{'symbol':'b','meaning':'正方形邊長的第二部分'}],'steps':[{'id':'step-1','prompt':'(a+b)² 的面積拆分包含哪些項？','options':['a²、ab、ab、b²','a²、b²','a²、2a、2b、b²'],'answer':'A','feedback':'兩個交叉長方形各是 ab，因此合起來是 2ab。'},{'id':'step-2','prompt':'x²+6x+9 可整理成哪個平方？','options':['(x+3)²','(x+6)²','(x−3)²'],'answer':'A','feedback':'常數 9 的平方根是 3，中間項 2×x×3=6x。'},{'id':'step-3','prompt':'完成因式分解後如何回查？','options':['重新展開並逐項比對','只看括號長相','刪掉中間項'],'answer':'A','feedback':'反向展開能檢查每個係數與正負號。'}]}
 for i, extra in enumerate(['並請學生把兩個 ab 長方形的位置標記出來，說明係數不是背來的。','再把每一格對應到兩個括號中的來源項，讓漏乘可以被定位與修正。','同時計算左右兩邊的數值，檢查公式的每一項都保留了面積。','完成後逐項展開並和原式比較，說明為何外觀相似不足以判定正確。','最後用另一組 a、b 值重算，判斷這個結構是否仍然成立。','並把三種證據的檢查順序寫成自己的核對清單，避免只更正結論。']):
  d['teaching']['body'][i]['body'] += ' ' + extra
 d['authoringStandard']='version-fused-v1'; d['versionResearch']=[rec('nani','以同類項、分配律與乘法公式建立多項式運算順序','符號式、面積拆分與數值代入互證','把所有含相同字母的項都當成同類項','逐項完成運算、辨識公式並回查結果是否與原式一致'),rec('kanghsuan','以操作或圖形表徵說明公式項與係數來源','四格面積、代數式與展開結果同步','漏乘一項或把 2ab 寫成 ab','要求操作證據與符號結果互相對照並說出係數來源'),rec('hanlin','在代數整理與因式分解間往返檢查','結構辨識、反向展開與情境估算的互換','只套公式不看正負號或不做反向驗證','評估結構選擇、錯誤診斷與形式等值的完整性')]
 d['fusionRecord']={'commonCore':['三版本公開結構共同支持同類項、分配律與乘法公式的連貫學習。','公式需能以表徵或運算理由解釋，而非只記結果。','展開與因式分解要以代回或反向運算驗證。'],'versionDifferences':['南一證據較突顯運算順序與公式結構；康軒較突顯圖形或操作表徵；翰林較突顯形式轉換、估算與錯誤分析。這是公開課程計畫層級差異，不宣稱完整教材差異。'],'originalAdditions':['以四格面積呈現 2ab 的來源。','設計漏項與符號錯誤診斷，要求三種證據定位。','用差平方情境比較公式與直接展開的效率。'],'llmSynthesisNote':'本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG 重新設計多項式運算與乘法公式路徑。正文、例題、互動與回饋均為原創，未複製教材；Terra 第二輪與正式發布審查尚未完成，維持 draft。'}
 d['updatedAt']='2026-09-21'; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 REPORT.write_text(json.dumps({'unit':'a-Ⅳ-5：多項式運算與乘法公式的來回檢查','lessonId':d['id'],'status':'first-pass-ai-review-complete','reviewStatus':'draft','checks':{'unitSpecificOriginalContent':True,'threeVersionResearchRecords':True,'fusionRecordPresent':True,'interactivePredictionManipulationExplanation':True,'terraSecondPass':'pending'},'reviewedAt':'2026-09-21'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps({'lesson':str(LESSON.relative_to(ROOT)),'reviewStatus':d['reviewStatus']},ensure_ascii=False))
if __name__=='__main__': main()
