import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-4-iv-4.json"
REPORT = ROOT / "implementation/reports/english-performance-4-iv-4-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "forms, tables, fields, values, and functional information"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "form completion, table detail, date, quantity, and choice"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "schedule, contact, survey, order, and information matching"),
    ]
    return [{"url": u, "title": f"{t}；僅取簡單表格、表單欄位與資料配對能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以報名表、卡片、調查、行程、聯絡、訂單與餐點資料要求學生讀欄名、配對值並完成可執行資訊；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-4-iv-4"
    data["title"] = "4-Ⅳ-4：依欄名、資料型態與條件填寫簡單表格"
    data["content"] = {"summary": "填表不是把看到的字逐格抄入，而是先辨認欄名、資料型態、單位、格式與條件，再把正確資訊放到正確位置。本課以報名表、借書卡、旅行表、調查、聯絡表、工作坊課表、訂單、日程、志工表與餐點表等原創資料，練習姓名、年級、日期、時間、數量、價格、email、偏好與限制的欄位配對，並用回查原始資料和讀者需求避免欄位錯置。", "sections": [{"heading": "欄名先決定答案形狀", "body": "Club 要填活動名稱、Due date 要填日期、Quantity 要填數量、Email 要填電子郵件格式。看到 Lina Wu 不代表每一欄都填姓名，先讀欄名再找同一列或同一標籤的值。"}, {"heading": "表格的單位和格式不能混用", "body": "8:15 a.m. 是時間、May 18 是日期、$40 是單價、3 是數量；填表時不能把價格放進 Quantity 或把 Return time 當 Departure。若欄位要求 total，要看是否已有計算結果或需要依資料計算。"}, {"heading": "填表要保留條件", "body": "vegetarian、Saturday morning、planting 與 does not eat meat 都是條件，不是裝飾文字。當表格要選主餐時，要同時看學生限制和餐點種類，不能只抄 Main dish 的第一個字。"}, {"heading": "完成後逐列核對", "body": "先用欄名定位，再沿列或標籤回查來源，最後從使用者需求測試表格是否可執行。日期、聯絡方式、數量與時間若錯一格，整張表可能導致錯誤行動。"}]}
    data["studyHighlights"] = ["先讀欄名與資料型態，再從同列、同標籤或來源段落找值。", "分辨姓名、日期、時間、數量、價格、聯絡方式與條件的格式。", "填寫時保留飲食、可用時段、任務與其他限制。", "用逐欄、逐列回查和使用者需求測試確認表格可用。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "看到 3 就能放進任何欄嗎？", "body": "展示原創訂單表：Quantity 3、Price each $40、Total $120。學生先把三個值放入空表，再比較把 $40 填進 Quantity 會造成什麼錯誤，建立欄名先於抄數字的習慣。"}, {"id": "explain", "phase": "explain", "heading": "欄名—型態—來源三欄卡", "body": "建立 Field、Data type、Source value 三欄。先寫欄位要求姓名、日期、時間、數量、金額、選項或限制，再沿同列／標籤定位來源，最後按格式填入。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從時間表找單一欄位", "body": "以 9:00 English、10:00 break、10:20 Science 示範：題目問 10:20 時要先鎖定時間欄，再回查同一列的 Science；不能用下一個時段或科目名稱猜。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "十種表格十種欄位線索", "body": "輪換報名、借書、旅行、調查、聯絡、課表、訂單、日程、志工與餐點表。學生先讀欄名，再填值並用螢光筆連來源；同伴故意交換一格，請原作者找出錯誤。"}, {"id": "transfer", "phase": "transfer", "heading": "為不同使用者重組資料", "body": "把志工資料做成老師名冊、學生提醒和活動清單。保留同一事實，調整欄名、順序與顯示單位，檢查使用者是否能找到姓名、時間與任務。"}, {"id": "reflect", "phase": "reflect", "heading": "錯在看錯欄還是漏掉條件？", "body": "回看答案，標記欄名誤讀、列錯、單位錯、格式錯、條件漏失或擅自計算。修訂時寫出來源位置和欄位需求，再重新測試表格能否支持下一步。"}], "summary": ["用 Field、Data type、Source value 三欄理解表格。", "依欄名、同列、標籤與格式配對姓名、日期、時間、數量與金額。", "保留飲食、時段、任務與其他限制，不用第一個看到的值填空。", "以來源連線和使用者行動測試驗證表格。"], "exitCheck": [{"prompt": "填表為什麼要先讀欄名？", "expectedEvidence": "能說明同一個數字或文字在不同欄位有不同功能，並舉出日期、數量或價格例子。"}, {"prompt": "如何避免把時間、日期、數量和價格混在一起？", "expectedEvidence": "能指出格式、單位與欄名的區別，並沿來源列回查。"}, {"prompt": "表格中的條件欄位為什麼不能省略？", "expectedEvidence": "能以飲食、可用時間或任務限制說明條件如何改變可執行答案。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "依欄名、資料型態、來源位置與使用者條件，正確填入簡單表格。", "scenario": "學生擔任校園資料助理，要完成報名、借書、訂單、行程與志工表，讓下一位使用者能直接採取行動。", "variables": [{"symbol": "f", "meaning": "欄名與欄位功能"}, {"symbol": "d", "meaning": "資料型態、格式、單位與來源列"}, {"symbol": "c", "meaning": "使用者條件、任務、時間與需求"}], "steps": [{"id": "step-1", "prompt": "A registration row says Name—Lina Wu; Grade—8; Club—Drama. What belongs in Club?", "options": ["Drama", "Lina Wu", "8"], "answer": "A", "feedback": "先看欄名 Club，再回到同一列取活動名稱 Drama。"}, {"id": "step-2", "prompt": "An order lists Quantity—3, Price each—$40, Total—$120. What belongs in Quantity?", "options": ["3", "$40", "$120"], "answer": "A", "feedback": "Quantity 是數量欄，不能用單價或總價代替。"}, {"id": "step-3", "prompt": "A food table lists Main dish—rice, and a student does not eat meat. Which entry fits the condition?", "options": ["Rice is a suitable main dish.", "The student must choose a meat dish.", "The drink field should contain the main dish."], "answer": "A", "feedback": "A 同時讀取主餐欄與不吃肉的條件，完成可執行配對。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；生活表格、主要訊息與資料定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由生活表格、卡片與表單理解欄位資料。", "以人物、日期、時間、數量與行動完成填寫。"], "representations": ["報名、借書、旅行、聯絡與志工表。"], "examplesOrEvidence": ["本課以活動、圖書館、行程與志工原創表格承接公開結構。"], "misconceptions": ["看到資料就填入第一個空格，不看欄名。"], "assessmentEmphasis": ["重視資訊定位、欄位配對與生活應用。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖文、表格、任務與資料配對定位；核讀 2026-09-21。", "findings": {"concepts": ["透過圖文、欄名與任務完成簡單表格。", "依格式、單位、排序與條件填入資訊。"], "representations": ["調查、課表、訂單、餐點與日程。"], "examplesOrEvidence": ["本課以欄名—型態—來源卡重新設計表格活動。"], "misconceptions": ["把數量、價格、時間或選項格式混用。"], "assessmentEmphasis": ["評量資料配對、格式、條件與可用性。"], "misconceptions": ["把數量、價格、時間或選項格式混用。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；表格、功能文本與欄位理解定位；核讀 2026-09-21。", "findings": {"concepts": ["從欄名、資料型態與使用者需求完成表格。", "以條件、來源回查與可執行性檢查資訊。"], "representations": ["field、data type、source value、condition、validation。"], "examplesOrEvidence": ["本課以來源連線和使用者測試重新設計填表。"], "misconceptions": ["漏掉條件或填完後不回查來源。"], "assessmentEmphasis": ["評量表格資訊、條件、格式與驗證。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持表格、表單、日程與生活資料理解。", "可靠填表需整合欄名、資料型態、來源位置、單位與使用者條件。", "可用欄名—型態—來源卡、故意錯欄與使用者測試完成遷移。"], "versionDifferences": ["南一較突顯生活表格與資料定位；康軒較突顯圖文、任務、格式與條件；翰林較突顯欄位功能、來源回查與可執行驗證。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Field、Data type、Source value 三欄理解表格。", "用報名、借書、旅行、調查、聯絡、課表、訂單、日程、志工與餐點原創表格練習。", "以故意交換一格和不同使用者版本檢查欄位、格式與條件。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織表單欄名、資料型態、單位、來源回查、條件與可執行驗證。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-4-iv-4-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先讀欄名和資料型態，再沿來源列或標籤配對，最後核對條件、格式、單位與使用者需求。"; q["solutionSteps"] = ["先辨認題目要求的欄位與資料型態。", "沿同列、同標籤或來源表找到候選值。", "核對日期、時間、數量、價格、email 或選項格式。", "把飲食、時段、任務與其他條件套回答案，排除只看字面的位置。", "從使用者行動回測表格，確認填值可直接使用且來源可回查。" ]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的表格、表單、欄位與資料配對模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 4-iv-4")


if __name__ == "__main__":
    main()
