import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-performance-ah-iv-1.json"; REPORT=ROOT/"implementation/reports/science-performance-ah-iv-1-first-pass-review.json"
URLS={"nani":"https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf","kanghsuan":"https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110","hanlin":"https://drive.google.com/uc?id=1gMUVcDjfXmqIapg-fNnfPuLFaK98dxGX&export=download"}
def rec(p,c,r,m,a): return {"publisher":p,"edition":f"{p} 公立校方自然課程計畫章節級證據","sourceType":"public-web","sourceLocator":f"{URLS[p]}；科學報導、證據判讀與評量欄位；核讀 2026-09-21。","reviewedAt":"2026-09-21","findings":{"concepts":[c,"公開課程結構支持從來源、方法、資料、利益關係與可檢驗性評估科學主張。"],"representations":[r],"examplesOrEvidence":["本課的保健食品、氣候圖表與網路影片皆為原創情境，只承接公開課程所示的能力方向。"],"misconceptions":[m],"assessmentEmphasis":[a]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。"}
def main():
 d=json.loads(LESSON.read_text(encoding="utf-8")); assert d["id"]=="lesson-science-performance-ah-iv-1" and d["reviewStatus"]=="draft"
 d["title"]="ah-Ⅳ-1：懷疑並評估科學報導或權威解釋的證據——把可信度拆開檢查"
 d["content"]={"summary":"看到『專家證實』、『研究顯示』或一張漂亮圖表時，真正需要問的是：誰提出主張、資料從哪裡來、方法如何做、樣本是否合適、結果能否重複、有哪些利益關係與未說明限制。懷疑不是逢權威必反對，而是把主張拆成可檢查的證據鏈。本課用保健食品廣告、氣候圖表與網路影片三個原創情境，練習辨認相關與因果、來源品質、統計圖表、專家角色和查證步驟。","sections":[{"heading":"先把主張寫清楚","body":"『有效』『安全』『造成』『大幅改善』各自需要不同證據。先圈出對象、比較條件、結果、時間和因果語氣，才能知道報導到底聲稱什麼，而不是被標題的情緒帶走。"},{"heading":"來源可靠不只看頭銜","body":"專業訓練是線索，不是結論保證；還要查原始研究、方法、樣本、日期、同行檢視、資料限制與是否有商業利益。匿名貼文也可能提供線索，但不能只靠轉發數判斷。"},{"heading":"圖表會選擇性說話","body":"注意座標起點、單位、時間窗、樣本數、平均值和變異。兩條線同時上升不等於一方造成另一方；缺少對照、基準或完整分母時，視覺差距可能誤導。"},{"heading":"形成可查證的結論","body":"把報導分成已由資料支持、合理但仍待驗證、沒有足夠證據三類，寫出下一個查證動作。結論要保留範圍，不把一次研究或權威語氣擴大成所有人、所有時間都成立。"}]}
 d["studyHighlights"]=["把標題主張拆成對象、比較、結果、因果與時間。","查來源、原始方法、樣本、日期、利益關係與限制。","閱讀圖表的座標、單位、分母、變異與相關／因果差異。","以證據分級並提出下一個可查證行動。"]
 d["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"專家說有效，就一定有效嗎？","body":"學生看到保健食品廣告寫『醫師推薦、七天有感』，有人立刻購買，有人完全不相信。請先把推薦者身分、產品效果、比較對象、時間和研究方法分欄，再列出哪一項資料仍缺少；懷疑要指向證據缺口，不是只交換立場。"},{"id":"explain","phase":"explain","heading":"科學報導五層查核","body":"依序檢查主張、來源、方法、資料和限制：標題是否誇大？是否連到原始研究？樣本與對照是否合適？圖表是否保留分母和變異？作者或資助者是否有利益關係？每層都要留下可追溯筆記。"},{"id":"worked-example","phase":"worked-example","heading":"氣候圖表的斷軸陷阱","body":"一張圖把兩年溫度差畫得很陡，新聞說『暴增十倍』。學習者先查縱軸是否從 29°C 截到 30°C、單位與樣本，再區分視覺斜率和實際差值；若只有兩個月份，不能推成長期全球趨勢。"},{"id":"guided-practice","phase":"guided-practice","heading":"網路影片的三種證據","body":"影片展示磁鐵讓植物長更快，卻沒有控制組、日期或完整操作。請把『看得到結果』、『能支持因果』和『值得查證的線索』分開，設計同品種、同光照、重複樣本與盲測的下一步。"},{"id":"transfer","phase":"transfer","heading":"寫一張查核卡","body":"每組選一則科學新聞，完成主張、原始來源、方法、樣本、圖表、利益、限制與下一步八欄卡。交換後同學只能用卡上證據提出質疑，並把一句過度確定的結論改成有範圍的說法，再指出哪一個新增資料最可能改變判斷，避免查核停在個人感覺。"},{"id":"reflect","phase":"reflect","heading":"修正兩個權威迷思","body":"請修正『權威說了就不用查』與『只要有一個反例就全部是假』。權威可提供查找方向但仍要看方法；單一反例也要查條件、重複與資料品質，才能判斷是修正、限制還是測量問題。"}],"summary":["拆解標題主張並辨識因果、比較與時間範圍。","查來源、方法、樣本、圖表、利益與限制。","區分相關、因果、視覺差距與實際證據。","將查核結果分級並提出下一個可驗證行動。"],"exitCheck":[{"prompt":"為什麼『醫師推薦』不能單獨證明產品有效？","expectedEvidence":"身分只是來源線索，仍需查研究設計、樣本、對照、結果、限制與利益關係。"},{"prompt":"圖表讀者要先查哪些項目？","expectedEvidence":"查座標起點、單位、時間、分母、樣本數、平均與變異，避免被視覺斜率誤導。"},{"prompt":"看到一個反例時為何不能立刻全盤否定？","expectedEvidence":"要查條件、方法、重複與資料品質，判斷是模型限制、測量問題或真正矛盾。"}]}
 d["interactive"]={"type":"guided-choice","goal":"將科學報導拆成主張、來源、方法、資料、限制與下一步查證。","scenario":"查核保健食品廣告、氣候圖表與網路實驗影片，逐步判斷證據強度。","variables":[{"symbol":"c","meaning":"主張"},{"symbol":"s","meaning":"來源與方法"},{"symbol":"e","meaning":"證據與限制"}],"steps":[{"id":"step-1","prompt":"看到『專家證實七天有效』先做什麼？","options":["找原始研究，查樣本、對照、結果、日期與利益關係","只看專家頭銜","只看廣告轉發數"],"answer":"A","feedback":"A 把權威語氣轉回可查證的方法和資料。"},{"id":"step-2","prompt":"氣候圖表看起來暴增時，先查什麼？","options":["查座標起點、單位、時間窗、分母與樣本數","直接用圖形斜率判斷因果","只讀新聞標題"],"answer":"A","feedback":"A 能排除截斷座標和樣本不足造成的誤導。"},{"id":"step-3","prompt":"影片沒有控制組和完整方法，最恰當的判斷是？","options":["當作值得查證的線索，不能直接宣稱因果已證明","因為看到結果就已證明","因為來源不明就永遠不必查"],"answer":"A","feedback":"A 同時保留線索價值與證據界線。"}]}
 d["authoringStandard"]="version-fused-v1"
 d["versionResearch"]=[rec("nani","以資料、來源與探究方法評估科學報導和權威解釋。","主張、方法、樣本、圖表、查證與限制。","把頭銜、標題或轉發數當成證據。","重視來源追溯、資料判讀和結論界線。"),rec("kanghsuan","透過討論、查找與實作辨認報導中的證據、推論和不足。","原始研究、對照、重複、利益與同儕檢核。","看到結果就當因果，或只選支持自己的來源。","評量質疑、查證步驟與證據分級。"),rec("hanlin","連結健康、環境與媒體情境，理解權威、圖表與社群傳播的限制。","保健、氣候、影片、座標、分母、時間與責任溝通。","把一個反例全盤否定，或用專業身分代替方法。","要求來源透明、資料解讀、風險與負責任判斷。")]
 d["fusionRecord"]={"commonCore":["三版本公開結構共同支持從來源、方法、資料與限制評估科學報導。","主張拆解、圖表判讀、查證、因果界線與責任溝通是共同要求。","懷疑應指向可檢查證據，不是逢權威反對或盲目接受。"],"versionDifferences":["南一證據較突顯資料、來源與基本查證；康軒較突顯討論、原始研究、對照與同儕檢核；翰林較突顯健康環境媒體、圖表、風險與責任溝通。這是公開課程計畫層級差異，不宣稱完整教材差異。"],"originalAdditions":["以保健食品廣告拆解權威語氣與研究證據。","以斷軸氣候圖表區分視覺差距和實際資料。","以網路實驗影片設計控制組、重複樣本與查證步驟。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織主張、來源、方法、樣本、圖表、利益、因果、限制與查證行動。正文、原創情境、互動步驟、錯誤回饋與檢核均為本專案重寫，未複製任何教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
 d["updatedAt"]="2026-09-21"; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"ah-Ⅳ-1：懷疑並評估科學報導或權威解釋的證據","lessonId":d["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 print("ah-iv-1 lesson authored")
if __name__=="__main__": main()
