import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-9.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-9-first-pass-review.json"


def refs():
    items = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "story main idea, sequence, conflict, cause, and character change"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "narrative details, event order, motives, and inference"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "story problem, solution, theme, and evidence"),
    ]
    return [{"url": u, "title": f"{t}；僅取故事閱讀的能力與資料型態方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以故事事件、順序、問題、原因、人物感受、解決方案與主題測量敘事理解；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in items]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-3-iv-9"
    data["title"] = "3-Ⅳ-9：沿著事件、衝突與人物改變理解故事"
    data["content"] = {"summary": "故事理解不是把角色和地點逐一翻譯，而是要追蹤事件如何造成問題、角色如何選擇、結果如何改變局面，最後用多個線索歸納主旨或主題。本課以交通卡、受傷小鳥、迎新演講、校園花園、迷路、停電、上台緊張、拾獲錢包、修理籬笆與失蹤獎盃等原創故事，練習事件順序、衝突、原因、人物感受、解決方案、結局與主題推論。", "sections": [{"heading": "先畫故事的因果鏈", "body": "用 Situation、Goal、Obstacle、Choice、Result、Change 六格整理故事。角色想完成什麼、遇到什麼阻礙、採取什麼行動，以及結果是否改變人物或環境，會比記住零散名詞更接近主要情節。"}, {"heading": "事件順序要看連接詞和動作", "body": "first、next、then、finally、after 與 later 是時間路標；先找到每個動作，再檢查哪一步造成下一步。若把呼叫中心、找到鳥與工作人員接手的順序倒置，就會誤讀解決方案。"}, {"heading": "衝突、原因與主題不是同一題", "body": "衝突是目標和阻礙的碰撞，原因是事件為何發生，主題則要跨越開頭、選擇與結局歸納可遷移的意義。沒有陽光的花園空間是衝突；停電是蠟燭與遊戲的原因；善意行動帶來社區互助才可能是主題。"}, {"heading": "人物改變要有前後證據", "body": "Aya 從 nervous 到 speaks more confidently，必須同時看前後情緒與同學回應。只看微笑不能推成永久性格改變；只看一次成功也不能說她在所有場合都不緊張。"}]}
    data["studyHighlights"] = ["用 Situation、Goal、Obstacle、Choice、Result、Change 六格追蹤情節。", "依順序詞與動作建立事件鏈，分清原因、衝突、方案與結局。", "主題必須由開頭、角色選擇與結果的多個線索共同支持。", "用前後對照證明人物感受或行為改變，不把單一細節擴大。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "故事的最後一句就是主題嗎？", "body": "先讀原創小故事：學生遺失交通卡，設計標籤口袋後不再忘記。學生先選『找到卡片』或『建立方法改變習慣』作主旨，再回看開頭問題、行動與結果，發現主題需要跨段證據。"}, {"id": "explain", "phase": "explain", "heading": "六格情節地圖", "body": "建立 Situation、Goal、Obstacle、Choice、Result、Change 六格。先寫角色目標與障礙，再把動作按時間排序，最後用 because／so／after 把因果鏈說完整。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從衝突找到可行方案", "body": "以花園沒有陽光為例：目標是種植，障礙是空間條件，方案需回應光線限制，而不是只重述想種花。示範如何排除『天氣很好』等沒有處理衝突的答案。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一故事換問題角度", "body": "用受傷小鳥、迷路、停電、演講、籬笆與獎盃六個原創故事，輪流回答 who／what happened first／why／problem／solution／theme。每次都要在情節地圖上圈出至少兩個支持答案的事件。"}, {"id": "transfer", "phase": "transfer", "heading": "把情節變成故事摘要", "body": "學生將一篇故事改寫成三句：目標與障礙、關鍵選擇、結果與改變。交換後刪掉一個細節，請同伴判斷主旨是否仍成立；若不能，補回造成轉折的事件。"}, {"id": "reflect", "phase": "reflect", "heading": "我是從結局猜，還是從情節推？", "body": "回看答案，標記順序顛倒、衝突和原因混淆、把方案當主旨、主題證據不足或人物改變過度。每次修訂都寫出 before／after 證據，讓推論不只依賴印象。"}], "summary": ["以六格情節地圖追蹤目標、障礙、選擇、結果與改變。", "用時間詞與因果詞重建事件順序，分辨衝突、原因、方案與結局。", "主題和人物改變都要由前後多個線索支持。", "把故事濃縮成摘要並檢查刪掉細節後是否仍保留轉折。"], "exitCheck": [{"prompt": "衝突、原因與主題各自回答什麼問題？", "expectedEvidence": "能分別說明目標與阻礙、事件為何發生、故事可遷移的意義，並用本課故事舉例。"}, {"prompt": "如何證明人物真的發生改變？", "expectedEvidence": "能比較開頭與結尾的情緒或行動，指出中間事件如何造成轉變，避免擴大到文本未支持的性格結論。"}, {"prompt": "故事摘要至少要保留哪些情節？", "expectedEvidence": "能保留目標／障礙、關鍵選擇、結果／改變，並刪除不影響因果的裝飾細節。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "沿著故事的目標、障礙、選擇與結果，判斷主要情節、衝突、原因、人物改變與主題。", "scenario": "學生擔任故事編輯，要把校園短篇整理成情節地圖，協助讀者理解角色如何面對問題。", "variables": [{"symbol": "p", "meaning": "角色目標與阻礙"}, {"symbol": "e", "meaning": "事件順序、選擇與結果"}, {"symbol": "m", "meaning": "人物改變、主題與證據範圍"}], "steps": [{"id": "step-1", "prompt": "A student loses a bus card, makes a labeled pocket, and stops losing it. What is the main idea?", "options": ["A practical habit helps solve a repeated problem.", "The student dislikes every bus.", "The card was never missing."], "answer": "A", "feedback": "A 同時涵蓋反覆問題、角色選擇與結果，不只重述找到卡片。"}, {"id": "step-2", "prompt": "A team wants to plant a garden, but the space has no sunlight. What is the conflict?", "options": ["Their planting goal conflicts with the lack of sunlight.", "The team has already grown every plant.", "The garden is inside a library."], "answer": "A", "feedback": "A 說明目標與條件阻礙的碰撞，正是 conflict 的核心。"}, {"id": "step-3", "prompt": "Aya is nervous at first, but after kind classmates listen, she speaks more confidently. What changed?", "options": ["Her confidence in presenting increased during the story.", "She stopped speaking forever.", "The classmates refused to listen."], "answer": "A", "feedback": "A 以開頭 nervous 與後來 more confidently 的對照描述文本支持的改變。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；故事主要內容、事件順序與生活情節定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由短篇故事理解主要內容與事件順序。", "以人物、動作、問題與結果整理情節。"], "representations": ["校園故事、動物、迷路、家庭與活動。"], "examplesOrEvidence": ["本課以交通卡、小鳥、迷路與停電原創故事承接公開結構。"], "misconceptions": ["只記住結局，忽略造成轉折的選擇。"], "assessmentEmphasis": ["重視故事主要內容、細節與順序。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；故事任務、圖像情節與問題解決定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["透過情節、圖像與任務理解角色目標與行動。", "依衝突、選擇與方案整理故事。"], "representations": ["花園、演講、籬笆、獎盃與活動故事。"], "examplesOrEvidence": ["本課以六格情節地圖重新設計敘事任務。"], "misconceptions": ["把任何困難細節都當成主題，或把原因當成解決方案。"], "assessmentEmphasis": ["評量情節、問題、方案與人物行動。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；故事理解、推論與主題定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["從前後情節、人物感受與結果形成故事理解。", "以主旨、衝突、原因、主題與改變表達結論。"], "representations": ["goal、obstacle、choice、result、change、theme。"], "examplesOrEvidence": ["本課以人物前後對照和情節證據重新設計主題推論。"], "misconceptions": ["由單一表情或結局過度推論長期性格。"], "assessmentEmphasis": ["評量故事主旨、推論、人物與主題證據。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持短篇故事、事件順序與主要情節理解。", "可靠敘事理解需整合目標、障礙、選擇、結果與人物改變。", "可用情節地圖、因果鏈、前後對照與摘要刪減完成遷移。"], "versionDifferences": ["南一較突顯故事主要內容與事件順序；康軒較突顯圖像情節、問題與方案；翰林較突顯人物、推論、主題與證據界線。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Situation、Goal、Obstacle、Choice、Result、Change 六格追蹤故事。", "用交通卡、小鳥、花園、迷路、停電、演講、籬笆與獎盃原創情節練習。", "以摘要刪減和 before／after 證據檢查主旨、主題與人物改變。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織故事主要內容、事件順序、衝突、原因、方案、人物改變與主題。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    ex = ["摘要需同時涵蓋遺失問題、標籤口袋的選擇與不再遺失的結果。", "first、next、finally 指出三個事件順序，worker takes the bird 是最後一步。", "practices each evening 與 wants to welcome... 支持為了自信迎新而練習。", "planting goal 與 no sunlight 條件衝突，形成主要問題。", "忽略地圖造成迷路，問路後到達車站構成轉折與解決。", "power outage 是使用蠟燭和玩文字遊戲的直接原因。", "nervous 到 more confidently 的前後對照支持信心提升。", "歸還錢包、找到失主與收到感謝共同支持誠實互助的主題。", "修理籬笆、留字條與鄰居種花共同形成互助回應的主題線索。", "尋找、查訪與揭露失蹤獎盃位置構成謎題的主要情節。"]
    paths = sorted(ROOT.glob("questions/english/question-english-performance-3-iv-9-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for i, p in enumerate(paths):
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["answer"]["explanation"] = ex[i] + f" 正確答案：{q['answer']['value']}"; q["solutionStrategy"] = "先畫出目標、障礙、選擇、結果的情節鏈，再依題目分類定位主旨、順序、原因、衝突或主題。"; q["solutionSteps"] = ["先讀完整故事並標記角色目標與主要障礙。", "依 first／next／after／finally 或動作因果排列事件。", "回到題目要求的主旨、衝突、原因、方案、改變或主題欄位。", "用至少兩個故事事件核對答案，排除只取單一細節或過度推論。", "把答案改述成短摘要，確認沒有漏掉轉折也沒有加入故事外資訊。"]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的故事主旨、順序、衝突、人物與主題模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-9")


if __name__ == "__main__":
    main()
