"""Fb：地球與太空第一輪來源融合與題數補齊。"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-content-fb.json"; REPORT=ROOT/"implementation/reports/science-content-fb-first-pass-review.json"; QDIR=ROOT/"questions/science"; TODAY="2026-09-23"
SOURCES=[
 {"url":"https://www.grow22.com/download/114/114_cp/05_114P_Nature.pdf","title":"114 年國中教育會考自然科公開試題","year":"114","locator":"地球自轉公轉、日月地、月相與天文觀測資料判讀","pattern":"取由週期、位置、光照與觀測資料推論地球與太空現象的能力方向。"},
 {"url":"https://www.hkjh.hc.edu.tw/uploads/1661481260739sfuB4gG2.pdf","title":"新竹市立新科國中公開康軒版自然課程計畫","year":"公開課程計畫","locator":"地球運動、月相、日月食、潮汐與行星","pattern":"取地球自轉／公轉、日月地模型、月相、食現象與觀測紀錄的教學及評量方向。"},
 {"url":"https://lgt.ntpc.edu.tw/TeachPlanFile_Upload/2022/plan/641_plan.pdf","title":"新北市文山區安康高中國中部公開翰林版自然簡案","year":"公開課程計畫","locator":"地球與太空、月球運動與天文資料","pattern":"取季節、月相、潮汐、天體觀測與控制條件的能力方向。"},
]
def refs(): return [{**s,"subject":"science","observedPattern":s["pattern"],"reuseDecision":"pattern-only","status":"recorded","locatorLevel":"paper"} for s in SOURCES]
def main():
 lesson=json.loads(LESSON.read_text(encoding="utf-8")); lesson["updatedAt"]=TODAY; lesson["reviewStatus"]="draft"; lesson["fusionRecord"]={"commonCore":["三版本公開線索共同支持以地球自轉、公轉、月球運動與太陽光照的幾何關係解釋地球與太空現象。","季節、月相、日月食、潮汐、行星觀測與週期資料判讀是共同能力核心。"],"versionDifferences":["南一公開定位偏向地球運動與季節；康軒線索偏向日月地模型、月相、食現象與潮汐；翰林線索偏向觀測紀錄、週期和控制條件。公開資料不足以宣稱取得完整教材內容。"],"originalAdditions":["以觀測者位置、光照方向、週期與影像紀錄工作台串接自轉、公轉、月相、食與潮汐。","把季節由日地距離單獨決定、月球自己發光、每次滿月都月食列為單元迷思診斷。"],"llmSynthesisNote":"依官方課綱、本單元 KG、南一／康軒／翰林公開版本線索與三筆公立學校公開自然科試題／課程資料能力方向，重新組織地球運動、日月地、月相、日月食、潮汐與行星觀測；補足原先缺少的第 10 題，10 題題幹、選項、答案、解析與五步解法均為原創，未複製教材或試題文字、圖表與答案。Terra 第二輪與正式發布審查尚未完成，維持 draft。"}
 for e in lesson.get("versionResearch",[])+lesson.get("publisherResearch",[]): e["reviewedAt"]=TODAY
 for p in sorted(QDIR.glob("question-science-content-fb-[0-9].json")):
  q=json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"]=refs(); q.setdefault("provenance",{})["sourceUrl"]=SOURCES[0]["url"]; q["provenance"]["sourceLocator"]="三筆公立學校公開自然科試題／課程資料的地球運動、日月地、月相、潮汐與觀測能力方向；本題只作 pattern-only 改寫。"; q["provenance"]["authoringNote"]="本題取公開資料能力方向，題幹、選項、答案、解析與五步解法均依 Fb 單元重新核對與撰寫，未複製原題、圖表或答案；待第二輪 AI／Terra 內容複核。"; q["reviewStatus"]="draft"; q["updatedAt"]=TODAY; p.write_text(json.dumps(q,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 q10={"id":"question-science-content-fb-10","subject":"science","type":"single-choice","prompt":"同一地點連續幾天在相同時刻觀察星空，若某行星相對背景星的位置逐日改變，最適合的解釋與紀錄方式是？","options":[{"id":"A","text":"以日期、時間、觀測方向和高度角記錄，再比較天體相對位置"},{"id":"B","text":"只記錄當天亮度即可判定所有運動"},{"id":"C","text":"因為星星都固定不動，所以位置差異一定是照片錯誤"},{"id":"D","text":"只要知道行星名稱，就能直接推出觀測位置"}],"knowledgeIds":["kg-science-content-fb"],"difficulty":"medium","answer":{"value":"A","explanation":"天體觀測需把日期、時間、方向與高度角等條件記錄下來，才能比較相對位置並區分觀測條件與天體運動。正確答案：A。"},"provenance":{"origin":"original","license":"All rights reserved","sourceUrl":SOURCES[0]["url"],"sourceLocator":"三筆公立學校公開自然科試題／課程資料的地球運動、行星觀測與資料判讀能力方向；本題只作 pattern-only 改寫。","authoringNote":"本題取公開資料能力方向，題幹、選項、答案、解析與五步解法均依 Fb 單元重新撰寫，未複製原題、圖表或答案；待第二輪 AI／Terra 內容複核。"},"reviewStatus":"draft","updatedAt":TODAY,"lessonId":"lesson-science-content-fb","examPatternRefs":refs(),"solutionStrategy":"先固定觀測條件，再以時間序列比較行星相對背景星的位置。","solutionSteps":["固定同一地點、相同觀測時刻與記錄格式。","每次記下日期、方向、高度角與可辨識背景星。","比較不同日期的位置差異，而不是只看亮度。","排除視線、天氣與器材造成的觀測誤差。","用資料支持有限範圍的天體運動結論，避免過度延伸。"]}
 (QDIR/"question-science-content-fb-10.json").write_text(json.dumps(q10,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"Fb：地球與太空","lessonId":lesson["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checkedQuestions":10,"checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"threePublicSchoolExamPatternSources":True,"answersAndDetailedSteps":True,"interactivePredictionManipulationExplanation":True,"questionCountRemediated":True,"terraSecondPass":"pending"},"reviewedAt":TODAY,"note":"已補足原先缺少的第 10 題；三筆公開試題／課程資料僅作 pattern-only 來源，版本融合、逐題內容 QA、Terra 第二輪與正式發布尚未完成，維持 draft。"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 LESSON.write_text(json.dumps(lesson,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); print("authored science content fb")
if __name__=="__main__": main()
