#!/usr/bin/env python3
"""Independent first-pass authoring for math f-IV-2."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/'lessons/math/lesson-math-performance-f-iv-2.json'
REPORT=ROOT/'implementation/reports/math-performance-f-iv-2-first-pass-review.json'
URLS={'nani':'https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf','kanghsuan':'https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110','hanlin':'https://www.cp.ptc.edu.tw/storage/134513/134513_112_B-1_9A.pdf'}
def rec(p,c,r,m,a):
 return {'publisher':p,'edition':f'{p} 公立校方數學課程計畫章節級證據','sourceType':'public-web','sourceLocator':f'{URLS[p]}；二次函數圖形與資料表徵評量欄位；核讀 2026-09-21。','reviewedAt':'2026-09-21','findings':{'concepts':[c,'公開結構支持以係數、表格與圖形理解二次函數的變化，而非只代入計算。'],'representations':[r],'examplesOrEvidence':['本課的拋物線、拋擲與面積資料均為原創，只承接公開課程的能力方向。'],'misconceptions':[m],'assessmentEmphasis':[a]},'licenseBoundary':'只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。'}
def main():
 d=json.loads(LESSON.read_text(encoding='utf-8')); assert d['id']=='lesson-math-performance-f-iv-2' and d['reviewStatus']=='draft'
 d['title']='f-Ⅳ-2：從係數讀二次函數圖形'
 d['content']={'summary':'二次函數的圖形是一條有方向的拋物線；係數改變時，開口、寬窄、平移與對稱位置也會改變。本課從拋擲高度與時間的原創資料開始，讓學生在表格、式子與圖形間辨認頂點、對稱軸和開口方向，並用多個點與對稱關係檢查圖形，而不是只看最高點猜答案。','sections':[{'heading':'係數先告訴我們什麼','body':'在 y=ax² 中，a 的正負決定開口向上或向下，絕對值大小影響圖形張開程度。先固定其他條件比較 a，才能看見單一係數的作用。'},{'heading':'對稱軸整理左右資料','body':'拋物線左右對稱，對稱軸上的 x 值是左右對應點的中間位置。表格若出現相同輸出，先檢查輸入是否以某條直線為中心成對出現。'},{'heading':'頂點是位置資訊不是全部答案','body':'頂點同時提供極大或極小的輸出與對稱軸位置，但不一定是 x 軸交點。讀題時先分辨要找最高點、零點、y 截距還是某個輸入的輸出。'},{'heading':'圖形判讀要看尺度','body':'座標軸刻度、視窗範圍與單位會影響視覺判斷；一條看似較陡的曲線不一定代表係數較大。用式子或數值點回查圖形的判讀。'}]}
 d['studyHighlights']=['先固定其他條件，比較係數正負與絕對值對圖形的影響。','用對稱軸配對資料，辨認頂點與左右對應點。','分清頂點、零點、截距與一般函數值的任務。','讀圖時檢查刻度、單位與視窗，再用數值回查。']
 d['teaching']={'body':[{'id':'hook','phase':'hook','heading':'球飛過的最高點','body':'給出一組原創的時間與高度資料，請學生先找出高度最大的一筆，再猜測最高點是否正好落在表格中的時間。用對稱的前後資料讓學生預測拋物線，而不是先公布頂點公式。'},{'id':'explain','phase':'explain','heading':'a 的正負與圖形方向','body':'比較 y=x²、y=−x² 與 y=2x² 的少量計算值，將開口方向與寬窄標在同一張坐標圖。學生需說出哪個係數改變、哪些條件保持不變，避免把所有圖形差異歸因於一個詞。'},{'id':'worked-example','phase':'worked-example','heading':'用對稱找到頂點','body':'對 y=(x−2)²+3，指出對稱軸 x=2、頂點 (2,3) 且開口向上；再代入 x=1 與 x=3 得相同輸出 4，驗證左右對稱。最後說明頂點不是 x 軸截距。'},{'id':'guided-practice','phase':'guided-practice','heading':'辨認題目真正要找的量','body':'給三個問題：最高高度、何時碰到地面、初始高度。學生分別選頂點、x 軸交點或 y 軸截距作為目標，再用式子與圖形各做一次確認。'},{'id':'transfer','phase':'transfer','heading':'改變視窗仍要保留證據','body':'調整坐標圖的比例與顯示範圍，請學生判斷視覺上是否仍能可靠讀出頂點；若不能，改用完成平方式與代入點補足證據。這把讀圖策略轉移到不同工具視窗。'},{'id':'reflect','phase':'reflect','heading':'圖形判讀的三重檢查','body':'出口題要求學生寫出開口、對稱軸與目標量，再列一個左右對稱的點或代入值。最後指出若坐標軸刻度不等距，哪一種視覺結論需要重新計算。'}],'summary':['先辨認係數改變與圖形要觀察的特徵。','用對稱軸和成對資料找頂點與核對形狀。','分清頂點、零點、截距與一般函數值。','圖形判讀要配合刻度、式子與代入證據。'],'exitCheck':[{'prompt':'a<0 時拋物線開口方向如何？','expectedEvidence':'開口向下，並能用一個數值例子支持。'},{'prompt':'y=(x−2)²+3 的對稱軸與頂點是什麼？','expectedEvidence':'對稱軸 x=2，頂點 (2,3)。'},{'prompt':'為什麼頂點不一定是 x 軸交點？','expectedEvidence':'頂點的 y 值可能不為 0，是否交 x 軸要另看零點。'}]}
 d['interactive']={'type':'guided-choice','goal':'以係數、對稱軸與數值點讀取二次函數圖形。','scenario':'調整二次式係數與平移量，觀察開口、頂點、對稱點同步更新。','variables':[{'symbol':'a','meaning':'二次項係數'},{'symbol':'h','meaning':'對稱軸的水平位置'}],'steps':[{'id':'step-1','prompt':'a<0 對圖形有何影響？','options':['開口向下','一定平移到右邊','一定沒有頂點'],'answer':'A','feedback':'二次項係數的正負決定開口方向。'},{'id':'step-2','prompt':'y=(x−2)²+3 的對稱軸在哪裡？','options':['x=2','x=−2','y=3'],'answer':'A','feedback':'括號中的平移量決定水平對稱軸位置。'},{'id':'step-3','prompt':'如何檢查左右對稱？','options':['代入對稱軸兩側等距的兩個 x 比較輸出','只看最高點','只看 y 軸截距'],'answer':'A','feedback':'成對輸入得到相同輸出是可定位的對稱證據。'}]}
 for i, extra in enumerate(['並請學生將係數、表格差異與圖形特徵寫在同一張對照表，避免只用外觀猜測。','再標記每一對對稱點的水平距離與共同輸出，讓對稱軸有可核對證據。','並把最高點、交軸點與截距分成三欄，說明每一欄回答的問題不同。','最後用式子與代入值回查，不把視覺上像交點的位置直接當成精確答案。','再比較同一條曲線在不同視窗的讀值，指出哪些結論需要重新計算。','並寫出至少一個數值證據，說明視覺結論與代數結果如何互相支持。']):
  d['teaching']['body'][i]['body'] += ' ' + extra
 d['authoringStandard']='version-fused-v1'; d['versionResearch']=[rec('nani','以二次式係數與圖形特徵建立函數理解','係數、表格、坐標與拋物線的互相轉換','只看一個點便判斷開口或寬窄，忽略其他證據','完整核對係數、頂點、對稱軸與數值回查結果'),rec('kanghsuan','以操作和圖形表徵比較平移、對稱與變化','成對點、滑動圖形與坐標刻度的同步呈現','把頂點當成所有問題的答案或忽略圖形刻度','操作後完整解釋圖形特徵與式子如何互相對應'),rec('hanlin','在情境資料中判斷頂點、零點與截距的用途','拋擲、時間、高度與視窗限制的情境表徵','把最高點誤當 x 軸交點或外推不合理範圍','評估目標辨識、方法選擇與證據界線是否完整')]
 d['fusionRecord']={'commonCore':['三版本公開結構共同支持由式子、表格與圖形理解二次函數。','係數、對稱軸、頂點與交點是可互相檢查的圖形資訊。','情境與坐標尺度會限制圖形解讀的範圍。'],'versionDifferences':['南一證據較突顯係數與代數基礎；康軒較突顯操作、平移與圖形表徵；翰林較突顯情境中的目標辨識與視窗限制。這是公開課程計畫層級差異，不宣稱完整教材差異。'],'originalAdditions':['以原創拋擲資料引出頂點、對稱與高度解讀。','用三種不同任務診斷頂點、零點與截距的混淆。','加入圖形視窗與刻度改變時的證據補強活動。'],'llmSynthesisNote':'本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG 重新設計二次函數圖形、對稱與目標辨識。正文、例題、互動與回饋均為原創，未複製教材；Terra 第二輪與正式發布審查尚未完成，維持 draft。'}
 d['updatedAt']='2026-09-21'; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 REPORT.write_text(json.dumps({'unit':'f-Ⅳ-2：從係數讀二次函數圖形','lessonId':d['id'],'status':'first-pass-ai-review-complete','reviewStatus':'draft','checks':{'unitSpecificOriginalContent':True,'threeVersionResearchRecords':True,'fusionRecordPresent':True,'interactivePredictionManipulationExplanation':True,'terraSecondPass':'pending'},'reviewedAt':'2026-09-21'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps({'lesson':str(LESSON.relative_to(ROOT)),'reviewStatus':d['reviewStatus']},ensure_ascii=False))
if __name__=='__main__': main()
