import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-11.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-11-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "title, picture, heading, prediction, and main idea"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "visual text, topic, detail, and evidence-based prediction"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "heading, cover, caption, topic, and reading purpose"),
    ]
    return [{"url": u, "title": f"{t}；僅取標題、圖片、標示與閱讀預測能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以標題、書名、圖片、海報、圖示與小標題建立主題預測，並要求回到可見線索確認範圍；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-3-iv-11"
    data["title"] = "3-Ⅳ-11：從標題、圖片與圖說建立有證據的閱讀預測"
    data["content"] = {"summary": "標題、書名、圖片、海報與圖說能幫助讀者進入文本，但它們只提供預測線索，不等於全文答案。本課以種子、博物館、機器人、節水、車站謎團、沙拉、健行、城市鳥、雨天與新鄰居等原創視覺文字，練習從可見資訊提出主題、讀者、可能內容與閱讀目的，再用後續文字修正預測，區分直接觀察、合理推測與尚不能確定的內容。", "sections": [{"heading": "先拆開可見線索", "body": "讀一個封面時分開 Title、Image、Caption、Labels、Audience 五欄。The Last Seed 的書名和乾燥土壤中的小植物共同提示資源與照顧，但不能只憑一株植物預言完整結局。"}, {"heading": "預測要具體又保留範圍", "body": "好預測會說可能討論節水、健行安全或新鄰居互動，並指出標題或圖像證據；過度預測則捏造角色姓名、事件結果或作者立場。用 may、could、probably 與 cannot tell 調整確定程度。"}, {"heading": "標題組合可以縮小主題", "body": "City Birds 與 Deep-Sea Travelers 都指向動物及其生活環境，但不代表兩篇文章一定比較同一種遷徙。先找共同主題，再保留各自尺度與差異，避免把相似名詞當成相同內容。"}, {"heading": "新證據要能修正舊預測", "body": "標題與圖片只是入口；讀到圖說、段落或資料後，若新證據不支持原猜測，就刪除或改寫預測。閱讀策略不是猜中，而是能說明預測如何被證據支持、限制或修正。"}]}
    data["studyHighlights"] = ["用 Title、Image、Caption、Labels、Audience 五欄整理視覺文字。", "提出主題或閱讀目的時，附上可見線索並調整確定程度。", "比較多個標題時先找共同主題，再保留各文本的差異。", "把新段落當作修正預測的證據，不把封面猜測當成全文事實。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "封面能告訴我們多少？", "body": "展示原創封面 A Rainy Saturday：孩子看窗外、雨滴與一本書。學生先寫一個可能主題，再標記哪些是看見的、哪些是推測的，最後討論『室內閱讀』可能但『一定很孤單』沒有足夠證據。"}, {"id": "explain", "phase": "explain", "heading": "五欄預測卡", "body": "建立 Title、Image、Caption、Labels、Audience 五欄；每個預測後面加 Evidence 與 Confidence。要求使用 may／could／probably 或 cannot tell，讓語句呈現證據強弱，而不是只有對錯。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從海報轉成閱讀目的", "body": "以 Before You Hike 的水瓶、地圖與多雲山徑示範：先觀察物件，再推測文本可能提醒裝備、路線與天候安全；不能只因看見雲就宣稱一定會下雨。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "標題、圖像、圖說互相校正", "body": "輪換種子、博物館、機器人、節水、車站、沙拉、城市鳥與新鄰居八組原創視覺資料。學生先預測，再閱讀一行新增圖說，刪除不再被支持的部分並保留仍有證據的部分。"}, {"id": "transfer", "phase": "transfer", "heading": "替不同讀者選閱讀入口", "body": "把同一張海報分別給健行初學者、家長與研究者，寫出不同的閱讀目的和第一個要查的細節。學生交換後指出哪些預測由 Audience 改變，哪些觀察仍固定。"}, {"id": "reflect", "phase": "reflect", "heading": "我把猜測寫成事實了嗎？", "body": "回看答案，標記把圖像當結局、把標題當完整摘要、忽略圖說、混淆共同主題或過度確定的地方。修訂時補證據、降確定度或寫 cannot tell，讓預測可被後文檢驗。"}], "summary": ["用五欄卡拆開標題、圖像、圖說、標示與讀者。", "提出有證據且保留程度的主題、內容或閱讀目的預測。", "比較標題時保留共同主題與文本差異，不擅自補全文。", "讀到新證據後修正預測，區分觀察、推論與不能確定。"], "exitCheck": [{"prompt": "標題或圖片為什麼不能直接當成全文答案？", "expectedEvidence": "能說明它們只提供入口線索，並指出仍需後文、圖說或資料確認的內容。"}, {"prompt": "如何讓預測顯示證據強弱？", "expectedEvidence": "能附上可見線索並使用 may、could、probably 或 cannot tell 調整確定程度。"}, {"prompt": "新段落與原預測不一致時，要怎麼做？", "expectedEvidence": "能指出新證據、刪除不再支持的部分，並保留或改寫仍有證據的主題。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "從標題、圖片與圖說提出有證據、有限度且可被後文修正的閱讀預測。", "scenario": "學生擔任閱讀導覽員，要為書封、海報、網頁標題與圖示選出合適的閱讀入口。", "variables": [{"symbol": "v", "meaning": "標題、圖片、圖說與標示"}, {"symbol": "a", "meaning": "讀者、主題與閱讀目的"}, {"symbol": "c", "meaning": "證據強度、預測範圍與修正"}], "steps": [{"id": "step-1", "prompt": "A poster titled 'Three Ways to Save Water' shows a short shower and a closed tap. What is the likely topic?", "options": ["Practical ways to reduce water use.", "A history of mountain climbing.", "A story about a lost train."], "answer": "A", "feedback": "標題與圖示共同支持節水方法的主題，但不必先猜完整內容。"}, {"id": "step-2", "prompt": "A sign titled 'Before You Hike' shows a water bottle, a map, and a cloudy trail. What is a careful prediction?", "options": ["It may give preparation or safety advice for a hike.", "It definitely says a storm will destroy the trail.", "It is certainly about cooking dinner."], "answer": "A", "feedback": "A 以 may 保留證據範圍；圖像支持準備與安全，但沒有證明災害結果。"}, {"id": "step-3", "prompt": "Two titles are 'City Birds' and 'Deep-Sea Travelers.' What common topic do they suggest?", "options": ["Animals and the environments they live in.", "The exact same bird species in one city.", "Recipes for seafood and bread."], "answer": "A", "feedback": "兩個標題共同支持動物與生活環境，但不應把差異抹成同一物種。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；標題、圖片、生活文本與主要訊息定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由標題、圖片與簡短文字預測主要訊息。", "以物件、人物、地點與活動建立閱讀入口。"], "representations": ["書封、海報、網頁標題、圖示與圖說。"], "examplesOrEvidence": ["本課以種子、節水、健行與新鄰居原創視覺資料承接公開結構。"], "misconceptions": ["把看見的圖像直接當成完整故事結局。"], "assessmentEmphasis": ["重視標題、圖片與主要內容連結。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖片、任務與文字訊息整合定位；核讀 2026-09-21。", "findings": {"concepts": ["透過圖像、標示與任務建立主題預測。", "依讀者、目的與可見細節完成閱讀。"], "representations": ["博物館、機器人、票券、活動海報與網頁。"], "examplesOrEvidence": ["本課以五欄預測卡和證據強度重新設計活動。"], "misconceptions": ["只抓標題單字，不看圖說、受眾或限制。"], "assessmentEmphasis": ["評量視覺文字理解、主題與功能。"], "misconceptions": ["只抓標題單字，不看圖說、受眾或限制。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；圖文整合、推論與閱讀策略定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["從標題、圖像、圖說與後文形成可修正預測。", "以證據強度、共同主題與差異控制推論。"], "representations": ["title、image、caption、audience、prediction、confidence。"], "examplesOrEvidence": ["本課以視覺線索、讀者差異與新證據修正重新設計推論。"], "misconceptions": ["以單一圖像或標題捏造角色、結局或作者立場。"], "assessmentEmphasis": ["評量圖文整合、預測、修正與推論界線。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持標題、圖片、圖說與生活文本理解。", "可靠預測需整合可見線索、讀者、目的、證據強度與後文修正。", "可用五欄預測卡、共同主題比較與 evidence／confidence 檢查完成遷移。"], "versionDifferences": ["南一較突顯標題、圖片與主要訊息；康軒較突顯圖像、標示、任務與讀者；翰林較突顯圖文整合、預測修正與推論界線。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Title、Image、Caption、Labels、Audience 五欄整理視覺文字。", "用種子、博物館、機器人、節水、健行、城市鳥與新鄰居原創資料練習。", "以 Confidence、may／could／cannot tell 與新增圖說修正預測。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織標題、圖片、圖說、讀者、主題預測、證據強度與修正界線。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-3-iv-11-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先拆解標題、圖片、圖說與讀者，再提出有證據且有限度的預測，最後用新增資訊修正。"; q["solutionSteps"] = ["先讀完整標題與可見圖像，列出直接觀察。", "判斷讀者與閱讀目的，縮小可能主題或行動。", "提出與線索相符的預測，並用 may、could、probably 或 cannot tell 表示確定程度。", "回查選項是否捏造圖像沒有提供的角色、結果或立場。", "把預測改寫成可被後文確認或修正的句子，保留證據範圍。"]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的標題、圖片、圖說與閱讀預測模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-11")


if __name__ == "__main__":
    main()
