import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-performance-tr-iv-1.json"; REPORT=ROOT/"implementation/reports/science-performance-tr-iv-1-first-pass-review.json"
URLS={"nani":"https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf","kanghsuan":"https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110","hanlin":"https://drive.google.com/uc?id=1gMUVcDjfXmqIapg-fNnfPuLFaK98dxGX&export=download"}
def rec(p,c,r,m,a): return {"publisher":p,"edition":f"{p} 公立校方自然課程計畫章節級證據","sourceType":"public-web","sourceLocator":f"{URLS[p]}；知識連結、現象、數據推論與評量欄位；核讀 2026-09-21。","reviewedAt":"2026-09-21","findings":{"concepts":[c,"公開課程結構支持把既有概念、自然現象與實驗數據連結，提出有條件、可檢查的推論。"],"representations":[r],"examplesOrEvidence":["本課的摩擦、植物蒸散與聲音振動皆為原創推論情境，只承接公開課程所示的能力方向。"],"misconceptions":[m],"assessmentEmphasis":[a]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。"}
def main():
 d=json.loads(LESSON.read_text(encoding="utf-8")); assert d["id"]=="lesson-science-performance-tr-iv-1" and d["reviewStatus"]=="draft"
 d["title"]="tr-Ⅳ-1：連結知識、自然現象與實驗數據進行推論——讓資料回答為什麼"
 d["content"]={"summary":"推論不是把課本名詞貼到數據旁邊，而是說明既有知識如何預測現象、數據支持哪個部分、還有哪些替代解釋。摩擦力、植物蒸散或聲音振動的資料，都需要先區分直接觀察和推論，再檢查變因、機制、尺度與證據範圍。本課以三個原創情境練習從資料出發連結概念，提出條件式解釋並找出能進一步區分的測試。","sections":[{"heading":"先說資料看見什麼","body":"表格或圖形直接顯示數值、差異和變化，不會自己說出原因。先描述資料，再引用相關知識提出機制，避免把『一起增加』直接寫成因果。"},{"heading":"知識要能預測","body":"若摩擦概念能解釋鞋底材質差異，就應預測在相同重量和表面下，粗糙程度改變會如何影響所需拉力。好的連結能提出可被資料支持或削弱的結果。"},{"heading":"推論有尺度和條件","body":"同一概念在不同材料、溫度、時間或測量尺度可能表現不同。推論要寫固定條件、樣本與資料範圍，也要說明未測量因素，不能把局部結果擴大。"},{"heading":"多個解釋要靠新資料分辨","body":"若植物失水增加，可能是葉面積、風速、溫度或根部狀態造成。列出解釋後，設計一次只改變關鍵條件的比較，讓推論逐步變強，而不是只選最熟悉的概念。"}]}
 d["studyHighlights"]=["區分數據直接顯示、概念解釋與推論。","用既有知識提出可檢查的機制和預測。","標示條件、尺度、樣本與未測因素的限制。","用新資料比較替代解釋並修正推論。"]
 d["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"拉力變大就是摩擦力變大嗎？","body":"兩種鞋底在同一斜面上需要不同拉力，學生直接說『粗糙所以摩擦大』。先把量到的拉力、表面、重量和角度列出，再用摩擦概念預測；如果重量和角度沒有固定，推論就不能只歸因於鞋底。"},{"id":"explain","phase":"explain","heading":"推論三段鏈","body":"先寫資料顯示什麼，再寫相關概念如何提供機制，最後寫在什麼條件下能推出哪個結論。每一段都標示證據與未知，避免讓名詞看似解釋卻沒有預測。"},{"id":"worked-example","phase":"worked-example","heading":"植物失水的多重解釋","body":"葉片質量下降可能來自蒸散、溫度、風速或根部供水。先固定盆土、光照和時間，分別記錄葉面積、空氣流動和質量變化，再用控制條件比較；數據若只測質量，不能直接判定單一機制。"},{"id":"guided-practice","phase":"guided-practice","heading":"聲音振動的資料連結","body":"兩條弦長度不同，測得基頻不同。學習者先描述頻率差，再連結振動與弦長概念，預測縮短弦長的方向，並列出張力、材料和測量工具要固定的條件。"},{"id":"transfer","phase":"transfer","heading":"推論審查桌","body":"小組交換一段『因為 X 所以 Y』的結論，審查者圈出直接資料、引用知識、缺少條件和替代解釋。作者補上一個能區分原因的測試，並把過度肯定的句子改成可檢查的條件式推論。"},{"id":"reflect","phase":"reflect","heading":"修正兩個推論迷思","body":"請修正『有相關就知道原因』與『只要背過概念就能解釋所有數據』。推論需要機制、控制條件和可檢查預測；概念的適用範圍有限，資料不符合時要回頭檢查。"}],"summary":["先描述數據，再用概念提出機制與預測。","讓推論標示條件、尺度、樣本與未知。","區分相關、因果、觀察與解釋。","用控制條件和新資料比較替代解釋。"],"exitCheck":[{"prompt":"為什麼拉力不同不能直接歸因鞋底材質？","expectedEvidence":"還要固定重量、角度、表面與拉法，否則其他變因也可能造成差異。"},{"prompt":"植物失水資料為何需要多個條件？","expectedEvidence":"質量下降可能由蒸散、溫度、風速、葉面積或供水造成，需要控制與比較。"},{"prompt":"完整推論包含哪些部分？","expectedEvidence":"資料描述、相關概念與機制、條件式結論、證據限制和可區分替代解釋的下一步。"}]}
 d["interactive"]={"type":"guided-choice","goal":"把既有知識、自然現象與數據連成有條件、可檢查的推論。","scenario":"分析摩擦、植物失水與弦振動資料，逐步區分觀察、機制和替代解釋。","variables":[{"symbol":"d","meaning":"資料觀察"},{"symbol":"k","meaning":"知識與機制"},{"symbol":"i","meaning":"推論與檢查"}],"steps":[{"id":"step-1","prompt":"鞋底拉力資料首先要配合什麼？","options":["先描述拉力差，再檢查重量、角度、表面與摩擦概念","直接說粗糙一定造成差異","只看鞋底外觀"],"answer":"A","feedback":"A 把數據、控制條件和概念連起來。"},{"id":"step-2","prompt":"植物質量下降時如何避免單一原因？","options":["列出蒸散、溫度、風速與供水等解釋，設計控制比較","只背蒸散定義","選最熟悉的原因不測量"],"answer":"A","feedback":"A 讓替代解釋接受資料比較。"},{"id":"step-3","prompt":"聲音弦長改變要如何提出推論？","options":["連結弦長與振動頻率，預測方向並固定張力、材料和測量方法","只描述聲音變大","把任何變化都叫共振"],"answer":"A","feedback":"A 有概念機制、預測和控制條件。"}]}
 d["teaching"]["body"][1]["body"]="先寫資料顯示什麼，再寫相關概念如何提供機制，最後寫在什麼條件下能推出哪個結論。每一段都標示證據與未知，避免讓名詞看似解釋卻沒有預測，還要指出什麼新資料會削弱這個推論。"
 d["teaching"]["body"][3]["body"]="兩條弦長度不同，測得基頻不同。學習者先描述頻率差，再連結振動與弦長概念，預測縮短弦長的方向，並列出張力、材料和測量工具要固定的條件，最後用第二組長度檢查預測是否一致。"
 d["teaching"]["body"][5]["body"]="請修正『有相關就知道原因』與『只要背過概念就能解釋所有數據』，並各舉一個資料例子。推論需要機制、控制條件和可檢查預測；概念的適用範圍有限，資料不符合時要回頭檢查。"
 d["teaching"]["summary"][2]="區分相關、因果、觀察與解釋，並用控制條件與資料檢查推論。"
 d["versionResearch"][1]["findings"]["assessmentEmphasis"][0]="評量推理、預測、控制與修正，要求學生說明資料如何支持或削弱解釋。"
 d["authoringStandard"]="version-fused-v1"
 d["versionResearch"]=[rec("nani","以自然現象、實驗數據和既有知識形成有條件推論。","資料描述、概念、機制、預測、控制與限制。","把相關當因果或把名詞當成完整解釋。","重視證據連結、條件與推論界線。"),rec("kanghsuan","透過探究、討論與資料比較連結概念和現象。","摩擦、變因、替代解釋、重測與同儕檢核。","只選熟悉概念，忽略測量和其他可能原因。","評量推理、預測、控制與修正。"),rec("hanlin","連結生活物理、生物與聲音情境，依尺度和資料建立解釋。","鞋底、植物、弦振動、機制、樣本與方法。","把一次差異擴大成普遍規律，忽略條件和替代解釋。","要求知識應用、資料透明、因果界線與責任推論。")]
 d["versionResearch"][1]["findings"]["assessmentEmphasis"][0]="評量推理、預測、控制與修正，要求學生說明資料如何支持或削弱解釋。"
 d["fusionRecord"]={"commonCore":["三版本公開結構共同支持連結知識、自然現象與實驗數據進行推論。","資料描述、概念機制、預測、控制、替代解釋與限制是共同要求。","推論要能被資料支持或削弱，不能只靠名詞、相關或直覺。"],"versionDifferences":["南一證據較突顯現象、數據與基本概念連結；康軒較突顯探究、變因、替代解釋與同儕檢核；翰林較突顯生活物理、生物、聲音、尺度與責任推論。這是公開課程計畫層級差異，不宣稱完整教材差異。"],"originalAdditions":["以鞋底拉力連結摩擦概念並檢查重量與角度。","以植物失水多重解釋設計控制條件與測量。","以弦振動資料預測頻率方向並固定張力與材料。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織資料描述、知識機制、預測、條件、尺度、替代解釋與推論檢核。正文、原創情境、互動步驟、錯誤回饋與檢核均為本專案重寫，未複製任何教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
 d["updatedAt"]="2026-09-21"; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"tr-Ⅳ-1：連結知識、自然現象與實驗數據進行推論","lessonId":d["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 print("tr-iv-1 lesson authored")
if __name__=="__main__": main()
