#!/usr/bin/env python3
"""Independent first-pass authoring for math f-IV-1."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/'lessons/math/lesson-math-performance-f-iv-1.json'
REPORT=ROOT/'implementation/reports/math-performance-f-iv-1-first-pass-review.json'
URLS={'nani':'https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf','kanghsuan':'https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110','hanlin':'https://www.cp.ptc.edu.tw/storage/134513/134513_112_B-1_9A.pdf'}
def rec(p,c,r,m,a):
 return {'publisher':p,'edition':f'{p} 公立校方數學課程計畫章節級證據','sourceType':'public-web','sourceLocator':f'{URLS[p]}；常數、一次函數與資料表徵評量欄位；核讀 2026-09-21。','reviewedAt':'2026-09-21','findings':{'concepts':[c,'公開結構支持以輸入、輸出與變化關係理解函數，而非只記一條公式。'],'representations':[r],'examplesOrEvidence':['本課的租借費、表格、座標與斜率資料均為原創，只承接公開課程的能力方向。'],'misconceptions':[m],'assessmentEmphasis':[a]},'licenseBoundary':'只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。'}
def main():
 d=json.loads(LESSON.read_text(encoding='utf-8')); assert d['id']=='lesson-math-performance-f-iv-1' and d['reviewStatus']=='draft'
 d['title']='f-Ⅳ-1：一次函數把變化說成規則'
 d['content']={'summary':'一次函數不是看到 y=ax+b 就結束，而是描述輸入改變時輸出如何跟著改變。本課以共享單車的固定費與每分鐘費用建立 y=2x+30，讓學生在情境、表格、座標圖與式子間來回轉換，辨認斜率代表每單位變化、截距代表起始量，並檢查定義域與單位。','sections':[{'heading':'輸入與輸出要先命名','body':'租借分鐘數是輸入 x，總費用是輸出 y；固定費 30 元在尚未騎乘時就存在，每分鐘 2 元則描述增加一分鐘會多出的費用。變量角色不同，不能任意互換。'},{'heading':'表格顯示固定變化','body':'當 x 每增加 1，y 都增加 2，這個固定差是一次函數的斜率線索。表格不只是代數式的附屬品，可以用來檢查輸出是否符合規則。'},{'heading':'圖形的斜率與截距','body':'座標圖上的直線斜率是輸出差除以輸入差，y 軸截距是 x=0 時的輸出。讀圖時要先看軸標籤與刻度，否則同一條線可能被誤讀成不同速率。'},{'heading':'函數有合理的定義域','body':'數學上可代入任意 x 不代表情境允許任意值；租借時間不能是負數，營業時段也可能設定上限。寫答案時要同時呈現規則與可使用的輸入範圍。'}]}
 d['studyHighlights']=['先辨認輸入、輸出、單位與起始量。','用表格的固定差找斜率，再用 x=0 找截距。','在式子、表格與座標圖間互相核對，不只背公式。','最後檢查定義域，分清數學規則與情境可行範圍。']
 d['teaching']={'body':[{'id':'hook','phase':'hook','heading':'固定費和每分鐘費','body':'呈現共享單車的原創收費卡：開鎖 30 元、每分鐘 2 元。學生先預測騎 0、1、5 分鐘的費用，並說明哪部分固定、哪部分會隨時間改變，建立輸入輸出的語意。'},{'id':'explain','phase':'explain','heading':'從故事到一次函數','body':'令分鐘數為 x、費用為 y，寫成 y=2x+30；把 2 標成每分鐘增加量，把 30 標成起始費。接著生成表格與座標點，讓同一規則在三種表徵中保持一致。'},{'id':'worked-example','phase':'worked-example','heading':'用兩點讀出斜率','body':'選取 (5,40) 與 (15,60)，計算 (60−40)/(15−5)=2，說明每分鐘費用為 2；再用 y−2x 得到截距 30。代回另一個表格點，檢查不是只靠一對點猜測。'},{'id':'guided-practice','phase':'guided-practice','heading':'找出錯誤的截距','body':'給出同一條費用線的三個候選式，學生先代入 x=0 判斷哪個保留固定費，再用另一個點檢查斜率。若只檢查一點，回饋會要求找第二個輸入值。'},{'id':'transfer','phase':'transfer','heading':'把費用換成水箱水量','body':'水箱每分鐘進水 4 公升，起始已有 10 公升；學生建立水量函數並限制時間直到容量上限。接著說明斜率、截距與定義域各自代表什麼，不能只換符號。'},{'id':'reflect','phase':'reflect','heading':'規則的適用範圍','body':'出口題請學生用一句話解釋斜率與截距，再指出若把 x 設成總費用而非分鐘數，哪個表徵需要改寫。最後標示負時間是否可接受，以及為何。'}],'summary':['先命名輸入輸出與單位，再建立規則。','表格固定差、圖形斜率與式子係數是同一變化關係。','用 x=0 看截距、用兩點差商檢查斜率。','把數學規則和情境定義域分開說明。'],'exitCheck':[{'prompt':'y=2x+30 中的 2 與 30 各代表什麼？','expectedEvidence':'2 是每分鐘增加費用，30 是輸入為零時的固定費。'},{'prompt':'為什麼要用兩個點檢查斜率？','expectedEvidence':'一點只能檢查輸出值，兩點的差商才能確認固定變化率。'},{'prompt':'租借時間為負數時如何處理？','expectedEvidence':'數學式可能可代入，但情境定義域不允許，需標示限制。'}]}
 d['interactive']={'type':'guided-choice','goal':'在情境、表格、座標與一次函數式之間同步轉換。','scenario':'調整租借分鐘數，觀察費用、斜率與固定費的文字狀態同步更新。','variables':[{'symbol':'x','meaning':'租借分鐘數'},{'symbol':'y','meaning':'總費用（元）'}],'steps':[{'id':'step-1','prompt':'開鎖 30 元、每分鐘 2 元如何表示？','options':['y=2x+30','y=30x+2','y=2x−30'],'answer':'A','feedback':'每分鐘費用乘輸入，再加上起始固定費。'},{'id':'step-2','prompt':'式子中的 2 如何從表格確認？','options':['x 每增加 1，y 固定增加 2','看 x=0 的 y','只看最大費用'],'answer':'A','feedback':'固定差是一次函數的斜率線索。'},{'id':'step-3','prompt':'如何檢查規則適用範圍？','options':['確認時間非負且不超過營業上限','允許所有負時間','只看直線是否漂亮'],'answer':'A','feedback':'定義域來自情境限制，不由圖形外觀決定。'}]}
 for i, extra in enumerate(['再請學生圈出固定費和每分鐘費，並把分鐘與元的單位分別寫在卡片上。','同時對照表格、點列與式子的同一筆資料，指出哪一個數字是輸出而不是輸入。','並把三個候選式各代入第二個輸入值，避免只用截距做片面判斷。','再設定一個容量上限，讓學生說明定義域如何由情境而非直線外觀決定。','最後比較兩種變量設定，寫出單位改變時式子與圖軸如何重新標記。','並用「數學上可代入」和「情境上可接受」兩句話分開表達。']):
  d['teaching']['body'][i]['body'] += ' ' + extra
 d['authoringStandard']='version-fused-v1'; d['versionResearch']=[rec('nani','以變量關係、表格與一次式描述固定變化','情境、表格、座標與函數式的互相轉換','把截距誤當斜率或混淆輸入輸出的角色','完整檢查固定差、截距、單位與定義域是否一致'),rec('kanghsuan','以操作和圖形表徵理解直線變化率','點列、直線、差商與文字敘述的同步呈現','只看一個點判斷整條規則或忽略圖形刻度','操作後完整解釋斜率和圖形變化如何互相支持'),rec('hanlin','在生活資料中判斷函數規則與適用範圍','費用、時間、起始量與限制條件的情境表徵','忽略負輸入或把公式外推到不合理範圍','評估模型選擇、單位與定義域說明是否完整')]
 d['fusionRecord']={'commonCore':['三版本公開結構共同支持以輸入輸出與固定變化理解一次函數。','表格、圖形與式子應互相轉換並保持單位意義。','斜率、截距與定義域都需要回到情境解釋。'],'versionDifferences':['南一證據較突顯代數與表格基礎；康軒較突顯圖形、操作與差商；翰林較突顯生活模型、單位與適用範圍。這是公開課程計畫層級差異，不宣稱完整教材差異。'],'originalAdditions':['以共享單車的固定費與每分鐘費用建立函數。','加入一點不足以驗證規則的錯誤診斷。','以水箱容量限制轉移到定義域判斷。'],'llmSynthesisNote':'本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG 重新設計一次函數的變化、表徵與限制。正文、例題、互動與回饋均為原創，未複製教材；Terra 第二輪與正式發布審查尚未完成，維持 draft。'}
 d['updatedAt']='2026-09-21'; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 REPORT.write_text(json.dumps({'unit':'f-Ⅳ-1：一次函數把變化說成規則','lessonId':d['id'],'status':'first-pass-ai-review-complete','reviewStatus':'draft','checks':{'unitSpecificOriginalContent':True,'threeVersionResearchRecords':True,'fusionRecordPresent':True,'interactivePredictionManipulationExplanation':True,'terraSecondPass':'pending'},'reviewedAt':'2026-09-21'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps({'lesson':str(LESSON.relative_to(ROOT)),'reviewStatus':d['reviewStatus']},ensure_ascii=False))
if __name__=='__main__': main()
