import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-1-iv-7.json"
REPORT = ROOT / "implementation/reports/english-performance-1-iv-7-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創校園通知、生活說明與短敘述，承接公開課程的情境理解、主旨判讀與簡易表達方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8"))
    assert data["id"] == "lesson-english-performance-1-iv-7"
    data["title"] = "1-Ⅳ-7：用線索說明短文與生活情境的主旨"
    data["content"] = {"summary": "短文的主旨不是把每個細節重新念一遍，而是說清楚文本談什麼、發生了什麼關鍵行動，以及作者要讀者理解的結果或用途。本課把校園公告、操作說明與生活敘述放在同一張線索圖中：先圈出主題，再找反覆出現的行動、時間順序、原因與結果，最後刪去只支持單一細節的選項。學習者會從雨水花園、節約能源、清洗水壺、貓頭鷹作息、植樹降溫、整理盒子、博物館入場、回收社團、保護濕畫與圖書館安靜時段等原創材料，練習用簡短英文說明主旨與用途。", "sections": [{"heading": "主旨要抓住整段共同談的事", "body": "讀完一段文字先問 What is this mostly about? 再問 What does it say about it? 前一問找主題，後一問找重要行動、結果或用途。雨水花園段落若同時提到收集雨水、澆灌植物與減少浪費，主旨應涵蓋整個做法與目的，不能只回答有一個花園。"}, {"heading": "細節要回到主旨的位置", "body": "日期、地點、顏色和單一人物可能是細節，不一定能代表全文。把每個選項放回文章，標記它支持一個句子、兩個句子，還是貫穿全文；只在一處出現的資訊若沒有連結其他句子，通常不足以當作 main idea。"}, {"heading": "說明文靠順序與因果完成意思", "body": "First、next、finally 幫助讀者照步驟行動，because、so、to help 則揭示原因與目的。清洗可重複水壺的文字裡，先沖洗、再刷洗、最後晾乾是操作順序；『避免異味』是目的。漏掉順序會讓答案看似相關卻不能完成任務。"}, {"heading": "敘述情境要看變化而非只看主角", "body": "短敘述常用時間、地點和前後變化傳達重點。城鎮植樹後道路變涼，重點不只是誰種樹，而是行動帶來的環境結果；貓頭鷹在夜間活動，重點是作息與安靜棲息地的關係。用一句話連接行動和結果，才能避免只摘抄名詞。"}]}
    data["studyHighlights"] = ["用主題加重要行動或結果概括整段共同內容。", "分辨貫穿全文的主旨與只出現一次的細節。", "用順序、原因、目的與結果線索理解說明情境。", "以簡短英文句子表達生活文本的用途或主要訊息。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "哪一個答案能讓整段文字都站得住？", "body": "展示一張雨水花園示意圖與三句原創英文短文，先請學生各自圈出重複出現的動作，再把三個候選主旨貼到句子旁。若選項只說花園有花，便用其餘句子反證；若選項同時包含收水、澆灌與減少浪費，才有機會涵蓋全文。"}, {"id": "explain", "phase": "explain", "heading": "主旨線索三欄卡", "body": "把閱讀內容拆成 Topic、Important action/result、Purpose 三欄。Topic 回答談的是誰或什麼，action/result 回答做了什麼或造成什麼變化，purpose 回答為何要做。三欄合起來才是完整主旨；若某選項只能填滿第一欄，先標記為主題而不是答案。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從節能通知刪掉過窄選項", "body": "以自編通知『Turn off unused lights and close doors to save energy.』示範：lights 和 doors 是兩個例子，save energy 才連起共同目的。比較『關門』、『教室有燈』與『用日常行動節省能源』，讓學生看到最後一項能解釋兩個細節，且沒有加入文本未說的結果。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "依順序完成生活說明", "body": "給出清洗可重複水壺的四格圖卡與 First、Next、Finally 句條，學生先排動作，再回答下一步和最終用途。若把目的句當成動作，請回查文字中的動詞；若順序顛倒，讓同伴實際模擬一次並指出哪一步無法完成。"}, {"id": "transfer", "phase": "transfer", "heading": "換場景仍要保留主旨證據", "body": "輪換貓頭鷹作息、植樹降溫、博物館入場、回收社團、濕畫保護與圖書館安靜時段等原創卡組。每組用一句英文完成『This text is mainly about … because …』，並在句下標兩個跨句證據；若句子只重述一個日期或地點，就必須重寫。"}, {"id": "reflect", "phase": "reflect", "heading": "我的答案是否只抓到一個亮點？", "body": "回看錯題，將選項分類為主題、單一細節、全文主旨或無證據推論。再用刪除法移除文章沒有支持的誇張結果，最後檢查答案是否同時保留文本的行動、目的或前後變化，並能用簡短英文說明理由。"}], "summary": ["以 Topic、action/result、purpose 三欄建立主旨。", "用跨句重複與因果順序排除單一細節。", "從生活說明的動詞、順序與目的判斷用途。", "以兩項文本證據支持一句簡短英文摘要。"], "exitCheck": [{"prompt": "怎樣判斷選項是全文主旨而非單一細節？", "expectedEvidence": "能說明主旨要涵蓋多個句子的共同內容，並指出行動、結果或目的。"}, {"prompt": "First、next、finally 和 because、so 各自提供什麼線索？", "expectedEvidence": "能分辨操作順序與原因、目的或結果，並用段落中的動詞說明。"}, {"prompt": "如何檢查英文主旨句沒有過度推論？", "expectedEvidence": "能指出至少兩項文本證據，刪除文本未說的誇張結果，保留主題與重要訊息。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "從短文的主題、行動、順序、原因與結果，選出能涵蓋全文的主旨並用英文說明。", "scenario": "學生擔任校園英文公告小編，要替雨水花園、節能通知和操作說明各寫一行摘要；每次選擇都必須回到多個句子找證據。", "variables": [{"symbol": "t", "meaning": "主題與文本範圍"}, {"symbol": "a", "meaning": "重要行動、順序與結果"}, {"symbol": "p", "meaning": "目的、用途與主旨句"}], "steps": [{"id": "step-1", "prompt": "A school garden collects rainwater to water plants and reduce waste. What is the main idea?", "options": ["The garden uses collected rainwater to help plants and save water.", "The garden has one small flower near a wall.", "Students visit the garden only on Friday."], "answer": "A", "feedback": "A connects the garden, the repeated action, and its purpose; B and C are narrow details not supported as the whole message."}, {"id": "step-2", "prompt": "First rinse the reusable bottle. Next brush the inside. Finally let it dry. What should happen after rinsing?", "options": ["Brush the inside of the bottle.", "Put the bottle in a museum.", "Close the library for the day."], "answer": "A", "feedback": "The sequence word Next gives the required action; the other choices do not belong to this instruction."}, {"id": "step-3", "prompt": "Turn off unused lights and close doors to save energy. Which sentence best summarizes the notice?", "options": ["Small daily actions can save energy at school.", "The school has exactly two doors.", "The notice is about a Tuesday library hour."], "answer": "A", "feedback": "A covers both actions and the shared purpose without inventing a number, date, or unrelated topic."}]}
    data["authoringStandard"] = "version-fused-v1"
    data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [rec("nani", "https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語短文、生活情境與主旨理解定位；核讀 2026-09-21。", ["由生活情境與短文理解主要內容及簡易訊息。", "以脈絡、圖片、順序和情境支持英語理解。"], ["公告、操作說明、敘述短文、主旨、細節與用途。"], "把一個醒目的名詞或日期直接當成全文主旨。", "重視主要內容、生活情境理解與簡易英文表達。"), rec("kanghsuan", "https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語閱讀、聽讀活動與情境表達定位；核讀 2026-09-21。", ["透過圖片、聽讀與生活任務掌握短文訊息。", "依序列、原因、行動與結果重建內容。"], ["雨水花園、節能、清洗水壺、植樹與校園公告。"], "只找第一句或最後一句，沒有核對整段的共同訊息。", "評量主要內容、順序、用途與生活英語表達。"), rec("hanlin", "https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語閱讀理解、短文主旨與情境評量定位；核讀 2026-09-21。", ["從短文脈絡、關鍵字與事件結果形成整體理解。", "以簡短句型說明主旨、目的與文本證據。"], ["主旨、細節、因果、目的、時間地點與結果。"], "把單一細節擴大，或加入文章沒有的誇張結果。", "評量主要訊息、推論、因果關係與簡易摘要。")]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持生活情境、短文理解、主要內容與簡易表達。", "主旨需由主題、重要行動、順序、原因、目的或結果共同支持。", "從細節辨識到摘要表達可透過圖片、任務、排序與證據核對完成。"], "versionDifferences": ["南一較突顯生活情境與脈絡支持；康軒較突顯聽讀、圖片、順序與任務；翰林較突顯短文主旨、因果、推論與摘要評量。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以雨水花園、節能通知與可重複水壺建立主旨三欄卡。", "用跨句證據和刪除法區分主旨與單一細節。", "以英文摘要句檢查生活情境的行動、目的與結果。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織短文主題、重要行動、順序、原因、目的、結果與主旨表達。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 每個選項都要回填三欄卡；若只能填入 Topic，便先當作不完整主旨，回到段落找 action、result 或 purpose。"
    data["teaching"]["body"][4]["body"] += " 換成新場景時不沿用答案位置，要求學生圈出兩個跨句證據，再用因果或目的連接詞把證據合成一句話。"
    data["teaching"]["body"][5]["body"] += " 同伴只看摘要猜原文主題，若猜到的是單一日期或地點，作者須補回全文共同的行動與結果，並刪掉沒有證據的推論。"
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": "1-Ⅳ-7：用線索說明短文與生活情境的主旨", "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 1-iv-7")


if __name__ == "__main__":
    main()
