import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/english/lesson-english-performance-1-iv-3.json"
REPORT=ROOT/"implementation/reports/english-performance-1-iv-3-first-pass-review.json"

def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher":name,"edition":f"{name} 公立校方英語課程計畫章節級證據","sourceType":"public-web","sourceLocator":locator,"reviewedAt":"2026-09-21","findings":{"concepts":concepts,"representations":forms,"examplesOrEvidence":["本課以原創校園時間線、教室地圖與合作任務，承接公開課程的基本句型、時態、問句與生活溝通方向。"],"misconceptions":[misconception],"assessmentEmphasis":[assessment]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}

def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-english-performance-1-iv-3"
    data["title"]="1-Ⅳ-3：用基本英語句型描述校園事件與計畫"
    data["content"]={"summary":"基本句型是把英文資訊組織成可理解訊息的工具，不是只背動詞變化表。本課以校園空間、日常習慣、正在進行的活動、過去行程、能力與規則、位置問句、比較、原因和未來計畫為主軸，讓學生先從時間、主詞、數量和語意線索判斷句型，再在地圖、時間線和合作任務中產出短句。每次修正都要說明是主詞、be 動詞、動詞形式、介系詞、比較級或連接詞哪一層需要調整。", "sections":[{"heading":"先看時間和句子任務","body":"*The science room is quiet before the experiment* 描述狀態，*Nina reviews her notebook every morning* 描述習慣，*The students are building a bridge now* 描述正在發生。先圈時間詞、主詞和句子要回答的問題，再選句型；不要看到動詞就直接套自己最熟的形式。"},{"heading":"句型的骨架要和主詞一致","body":"be 動詞、一般動詞、there is／are、情態動詞與疑問詞各自有骨架。*There are two chairs* 需要複數，*A careful student can use...* 的 can 後用原形，*Where did you put...?* 的 did 後也回到原形。把句子拆成主詞、動詞、受詞或位置，能看見錯誤真正發生在哪裡。"},{"heading":"時間線和關係詞改變意思","body":"過去事件用 yesterday 等線索和過去式連結，現在進行式配合 now 或 Look!，比較級要有兩個比較對象，because 連接原因與結果。句型選對不等於資訊完整；還要檢查地點、時間、數量和因果是否與情境相符。"},{"heading":"從選答案走到自己說清楚","body":"完成選擇題後，把答案換成自己的校園句子，再讓同伴依句子畫出位置、排出時間或做出動作。若對方無法理解，先檢查句型骨架與關係詞，再調整字詞；文法的目標是讓訊息穩定可理解，而不是只在考卷上選對。"}]}
    data["studyHighlights"]=["用時間、主詞、數量和任務線索選擇句型。","拆解主詞、動詞、受詞、位置與關係詞檢查骨架。","以時間線、比較對象與因果關係確認語意。","把選擇題答案改成自己的校園句並讓同伴驗證。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"看到 yesterday 就一定只改一個字嗎？","body":"提供三張自編校園照片和時間卡：昨天參觀博物館、現在正在做模型、下週將展示海報。請學習者先把事件排進時間線，再選句型說明；比較只換動詞和真正依時間、主詞與計畫改寫的版本，建立句型服務訊息的入口。"},{"id":"explain","phase":"explain","heading":"基本句型六格檢查","body":"依序檢查時間／語意、主詞與數量、be 或助動詞、主要動詞形式、受詞／位置、連接與比較關係。將 *There are two chairs*、*She can use the computer*、*Where did you put it?* 拆成色塊，讓學生看見複數、原形和疑問倒裝是不同層次的線索。"},{"id":"worked-example","phase":"worked-example","heading":"從時間線選出正確動詞骨架","body":"以 *Look! The students ___ a model bridge.* 示範：Look! 指向現在正在發生，主詞 students 是複數，故需要 are building。再把時間換成 yesterday 或 every morning，讓學生觀察句型和動詞如何一起變動，而不是背一個固定答案。"},{"id":"guided-practice","phase":"guided-practice","heading":"用教室地圖完成 there is、there are 和 where","body":"給一張自編教室地圖，學生輪流放置椅子、書包和海報，再說 *There is...*, *There are...* 或回答 *Where did you put...?*。同伴只依英文句子移動物件；若位置或數量錯誤，回到主詞、介系詞與地圖證據修正。"},{"id":"transfer","phase":"transfer","heading":"把句型串成校園計畫","body":"小組設計一個科學展示日，必須寫現在的準備、昨天完成的工作、可以遵守的規則、兩個方案比較、取消原因和下週計畫。抽換時間、主詞和條件卡，觀察學生能否維持句型骨架並改變動詞與連接詞。"},{"id":"reflect","phase":"reflect","heading":"找出我的句型錯誤層次","body":"回看句子，將問題分類為時間、主詞數量、助動詞後原形、疑問順序、位置、比較或因果。每類重寫一個不同情境的句子，請同伴畫圖或排時間線驗證；如果只有中文解釋沒有英文產出，補上可理解的短句。"}],"summary":["先用時間、主詞、數量與任務判斷句型。","以句子色塊檢查 be、助動詞、動詞形式與位置。","用時間線、地圖、比較與因果確認語意。","在校園計畫中串連句型並依錯誤層次修正。"],"exitCheck":[{"prompt":"Look! 和 yesterday 對句型選擇有何影響？","expectedEvidence":"能分別連到現在進行式與過去式，並指出主詞和動詞形式也要配合。"},{"prompt":"There are two chairs 和 can use 為何要注意不同規則？","expectedEvidence":"能說明 there are 配合複數，而 can 後接原形動詞，並各造句。"},{"prompt":"如何證明句型不是只在考卷上選對？","expectedEvidence":"能把句子放進校園地圖、時間線或合作任務，讓同伴依英文訊息完成動作或理解關係。"}]}
    data["interactive"]={"type":"guided-choice","goal":"依時間、主詞、數量、位置與語意關係選擇並產出基本英語句型。","scenario":"學生要用英文完成科學展示日計畫，先從時間線和教室地圖取證，再寫句子並讓同伴依句子行動。","variables":[{"symbol":"t","meaning":"時間與事件狀態"},{"symbol":"g","meaning":"句型骨架與主詞"},{"symbol":"m","meaning":"地圖、比較與因果訊息"}],"steps":[{"id":"step-1","prompt":"Look! The students ___ a model bridge now. Which form is correct?","options":["build","are building","built"],"answer":"B","feedback":"B matches Look! and now: the plural subject is doing the action at this moment."},{"id":"step-2","prompt":"___ two extra chairs beside the window for visitors.","options":["There is","There are","It are"],"answer":"B","feedback":"B agrees with the plural noun two chairs and introduces their location."},{"id":"step-3","prompt":"A careful student ___ use the lab computer without permission.","options":["can","can to","cans to"],"answer":"A","feedback":"A uses the modal can followed by the base verb use, matching the rule in the situation."}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；英語基本句型、課堂溝通與生活表達定位；核讀 2026-09-21。",["由校園與生活情境理解並使用基本句型，讓句子能完成具體溝通任務。","以時間、人物與任務線索表達意思。"],["be、一般動詞、疑問、位置、比較、原因與計畫。"],"只背規則名稱，忽略主詞、時間與句意。","重視句型理解、情境選用、語意正確與實際溝通完成。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；英語句型、句段理解與課堂活動定位；核讀 2026-09-21。",["透過圖片、對話與活動掌握基本句型。","依主詞、時態、數量與語意調整句子。"],["時間線、教室地圖、there is／are、助動詞與比較。"],"只改動詞，沒有檢查助動詞、數量或位置。","要求句型正確且能完成情境任務。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；英語句型、時態與評量定位；核讀 2026-09-21。",["從聽說讀寫活動理解基本重要句型。","以句型替換、情境產出與回饋修正表達。"],["現在、過去、進行式、情態、問句、比較、because與未來計畫。"],"把句型選對等同於訊息完整或能在新情境使用。","評量句型辨識、語意、形式與產出。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持基本句型、時態、問句、位置與生活情境溝通。","句型需連同時間、主詞、數量、受詞、位置和因果理解。","從辨識到產出需要圖片、時間線、替換與同伴回饋。"],"versionDifferences":["南一較突顯情境與生活表達；康軒較突顯圖片、活動、主詞時態與句型調整；翰林較突顯聽說讀寫、句型替換與新情境產出。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以三張時間卡建立現在、過去與未來句型對比。","用教室地圖實作 there is／are、where 與位置介系詞。","以科學展示日串連時態、助動詞、比較與因果。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織基本句型、主詞、時態、助動詞、問句、位置、比較與因果。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 每個句型判斷旁都要保留一個時間、數量或位置證據，並將助動詞與主要動詞分色；若句子只因語感猜中，要求用規則和情境重新說明。"
    data["teaching"]["body"][4]["body"] += " 抽換時間、主詞、數量和條件卡時固定事件核心，再觀察句型骨架哪些不變、哪些形式必須改變，讓學生看見規則能遷移。"
    data["teaching"]["body"][5]["body"] += " 讓同伴只看英文句子畫出位置、排出時間或判斷原因；若對方無法完成，就依錯誤層次修正，而不是只抄老師的正句。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"1-Ⅳ-3：用基本英語句型描述校園事件與計畫","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored english performance 1-iv-3")

if __name__=="__main__": main()
