import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; LESSON=ROOT/"lessons/science/lesson-science-performance-pc-iv-1.json"; REPORT=ROOT/"implementation/reports/science-performance-pc-iv-1-first-pass-review.json"
URLS={"nani":"https://www.yfms.tyc.edu.tw/uploads/1661134274196HXsSSWEB.pdf","kanghsuan":"https://www.dfsh.ntpc.edu.tw/app/index.php?Action=downloadfile&file=WVhSMFlXTm9MemMwTDNCMFlWOHlNak00WHpZNE56STJOMTg0TkRNNU9TNXdaR1k9&fname=WSGGIGB0MK10OOMP50POSWHGFC30WTIG14JCB114A1A1GCFCYSA4FCB4FGOOJG50VWPOXT154404MOWS1430ICNPOP34GCGCIHXTXW40YSUSB450PKSSXXFCNO10XX21JCLKSWIGQOB4SWHCUS30A110","hanlin":"https://drive.google.com/uc?id=1gMUVcDjfXmqIapg-fNnfPuLFaK98dxGX&export=download"}
def rec(p,c,r,m,a): return {"publisher":p,"edition":f"{p} 公立校方自然課程計畫章節級證據","sourceType":"public-web","sourceLocator":f"{URLS[p]}；探究檢核、證據、結果與改善欄位；核讀 2026-09-21。","reviewedAt":"2026-09-21","findings":{"concepts":[c,"公開課程結構支持回看問題、方法、資料、結論與限制，依證據提出具體改善。"],"representations":[r],"examplesOrEvidence":["本課的隔熱杯、植物生長與噪音測量皆為原創情境，只承接公開課程所示的能力方向。"],"misconceptions":[m],"assessmentEmphasis":[a]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、例題、圖表、題目、答案、影音或版面。"}
def main():
 d=json.loads(LESSON.read_text(encoding="utf-8")); assert d["id"]=="lesson-science-performance-pc-iv-1" and d["reviewStatus"]=="draft"
 d["title"]="pc-Ⅳ-1：檢核探究過程、證據與結果並提出改善——讓下一次更能回答問題"
 d["content"]={"summary":"探究完成不等於只看最後答案。要回頭檢查問題是否清楚、變因是否真的被控制、資料是否完整、測量是否可信、結論是否超出證據，才能提出下一次有意義的改善。本課用隔熱杯、植物生長與校園噪音三個原創情境，練習把『結果不理想』拆成可定位的流程問題，依證據排序改善，而不是只把數字改得更漂亮。","sections":[{"heading":"先回到原問題","body":"如果問題問的是澆水量對葉片數，卻記錄了高度和印象，就算表格整齊也沒有回答原問題。檢核先對齊問題、變因、指標和方法，找出研究真正測到什麼。"},{"heading":"資料品質要能追溯","body":"檢查原始紀錄、單位、重複次數、異常、器材與時間條件。少量資料不必然錯，但要說明不確定；缺資料時不能用平均或漂亮圖表掩蓋。"},{"heading":"結論要停在證據邊界","body":"把結論和資料範圍並排，問是否把相關說成因果、把一次觀察推成所有情況，或忽略相反資料。好的改善建議要針對造成判斷不穩的環節。"},{"heading":"改善要能驗證","body":"改善不是列出更多器材，而是提出改變一項程序後會如何檢查：增加重複、校正工具、固定時間、改良取樣或重新定義指標，並說明何種結果表示改善有效。"}]}
 d["studyHighlights"]=["對齊問題、變因、指標與實際測量內容。","檢查原始資料、單位、重複、異常、器材與時間。","限制結論範圍，區分相關、因果與未測量機制。","提出可驗證、能定位問題來源的具體改善。"]
 d["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"隔熱杯為什麼每組都說成功？","body":"三組隔熱杯都宣稱保溫效果最好，但一組量溫度、一組問手感、一組只記最後一次。先把原問題、測量指標、時間點和原始紀錄並排，找出『成功』其實代表不同事情，再決定要改善哪個環節。"},{"id":"explain","phase":"explain","heading":"探究回看四層","body":"依序回看問題與設計、資料與測量、分析與結論、改善與再測。每層都寫支持證據、缺口和可能影響；先定位最大的不確定來源，再提出最小但可驗證的改動。"},{"id":"worked-example","phase":"worked-example","heading":"植物生長結果互相矛盾","body":"兩組研究不同澆水量，一組葉片數增加，另一組高度沒有差異。先比較植物品種、初始狀態、光照、澆水定義、測量時間和重複，再判斷是否真的矛盾；改善可固定品種、增加樣本並同時記錄兩項指標。"},{"id":"guided-practice","phase":"guided-practice","heading":"噪音結論超出哪裡？","body":"學生在兩個地點各測一次，便寫『圖書館永遠比操場安靜』。學習者圈出樣本、時段和推廣範圍，改寫成條件式結論，再設計不同日子重複測量、記錄活動與校正工具的方案。"},{"id":"transfer","phase":"transfer","heading":"主持一次證據審查會","body":"小組交換完整探究紀錄，審查者只能指出資料支持的部分、不能支持的部分、最大缺口與一項可驗證改善。作者依建議修正方法卡，預測改善後哪個指標應出現什麼變化。"},{"id":"reflect","phase":"reflect","heading":"修正兩個改善迷思","body":"請修正『結果不好就把數字重算到合理』與『改善就是買更貴器材』。改善要保留原始資料並找出流程原因；工具只有在能降低特定誤差且可驗證時才值得更換，不能用成本取代方法。"}],"summary":["把問題、變因、指標和實際測量重新對齊。","從原始紀錄、程序與條件找出最大資料缺口。","讓結論停在樣本、時間與方法能支持的範圍。","提出改變程序後可再測、可比較的改善方案。"],"exitCheck":[{"prompt":"為什麼隔熱杯三組都說成功仍需要檢核？","expectedEvidence":"各組的成功定義、指標、時間和紀錄不同，未必回答同一問題，需重新對齊。"},{"prompt":"植物結果不同時先比較什麼？","expectedEvidence":"比較品種、初始狀態、光照、水量定義、時間、測量和重複，再判斷是否真矛盾。"},{"prompt":"什麼才是可驗證的改善？","expectedEvidence":"指出要改變的程序、預期改善指標與再測方式，而不是只重算數字或增加昂貴器材。"}]}
 d["interactive"]={"type":"guided-choice","goal":"回看探究流程、證據與結論，定位缺口並提出可驗證改善。","scenario":"審查隔熱杯、植物生長與噪音探究紀錄，逐步對齊問題、資料、結論和再測方法。","variables":[{"symbol":"q","meaning":"問題與設計"},{"symbol":"d","meaning":"資料與證據"},{"symbol":"i","meaning":"改善與再測"}],"steps":[{"id":"step-1","prompt":"隔熱杯各組使用不同成功指標時，先檢查什麼？","options":["對齊原問題、指標、時間點與測量方法","只比較最後最高溫度","把手感改寫成數字"],"answer":"A","feedback":"A 先確認各組是否真的測同一件事。"},{"id":"step-2","prompt":"兩組植物結果不同時，如何判斷是否矛盾？","options":["比較品種、條件、定義、時間、樣本與測量，再查原始資料","直接選符合預期的一組","把不同結果平均掉"],"answer":"A","feedback":"A 先排除方法和背景差異，不用平均掩蓋問題。"},{"id":"step-3","prompt":"哪項是可驗證的改善？","options":["固定測量時間並增加重複，預先寫出預期的資料品質變化","把結論改得更肯定","只購買昂貴器材"],"answer":"A","feedback":"A 有明確程序改動、預期效果和再測方式。"}]}
 d["teaching"]["body"][1]["body"]="依序回看問題與設計、資料與測量、分析與結論、改善與再測。每層都寫支持證據、缺口和可能影響；先定位最大的不確定來源，再提出最小但可驗證的改動，並預先說明改動後應觀察到的資料品質變化。"
 d["teaching"]["body"][3]["body"]="學生在兩個地點各測一次，便寫『圖書館永遠比操場安靜』。學習者圈出樣本、時段和推廣範圍，改寫成條件式結論，再設計不同日子重複測量、記錄活動與校正工具的方案，最後說明哪些新資料可能推翻原先比較。"
 d["teaching"]["body"][4]["body"]="小組交換完整探究紀錄，審查者只能指出資料支持的部分、不能支持的部分、最大缺口與一項可驗證改善。作者依建議修正方法卡，預測改善後哪個指標應出現什麼變化，並說明如何判定改善真的降低了不確定性。"
 d["authoringStandard"]="version-fused-v1"
 d["versionResearch"]=[rec("nani","以探究回顧、資料檢核與方法改善提升證據品質。","問題、變因、指標、原始資料、結論與再測。","把結果重算或漂亮化當成改善，因而掩蓋真正的流程缺口。","重視流程對齊、資料追溯與結論界線。"),rec("kanghsuan","透過實作、討論與反思檢查探究限制並提出改進。","同儕審查、異常、重複、校正、取樣與修正版。","只增加器材或只看最後答案，忽略方法來源。","評量證據批判、改善理由與再測設計。"),rec("hanlin","連結生活實驗、環境觀察與科學溝通，從結果提出負責任改善。","隔熱、植物、噪音、條件、誤差、結論與回饋。","把一次結果過度推廣，或把不同資料直接平均。","要求限制透明、證據對齊、安全與可驗證改善。")]
 d["fusionRecord"]={"commonCore":["三版本公開結構共同支持檢核探究過程、證據、結果並提出改善。","問題、方法、資料、結論、限制、重複與再測是共同要求。","改善須對準可定位的缺口並能以新資料驗證，不是美化結果。"],"versionDifferences":["南一證據較突顯探究回顧、資料與基本改善；康軒較突顯實作、同儕審查、異常與修正版；翰林較突顯生活實驗、環境觀察、限制與溝通。這是公開課程計畫層級差異，不宣稱完整教材差異。"],"originalAdditions":["以隔熱杯不同成功指標檢查問題與測量對齊。","以植物生長矛盾示範條件比較、原始資料與改善。","以噪音一次測量的過度結論設計重複、校正與再測。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織問題、方法、資料、結論、限制、異常、重複、改善與再測。正文、原創情境、互動步驟、錯誤回饋與檢核均為本專案重寫，未複製任何教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
 d["updatedAt"]="2026-09-21"; LESSON.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 REPORT.write_text(json.dumps({"unit":"pc-Ⅳ-1：檢核探究過程、證據與結果並提出改善","lessonId":d["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 print("pc-iv-1 lesson authored")
if __name__=="__main__": main()
