import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-4-iv-6.json"
REPORT = ROOT / "implementation/reports/english-performance-4-iv-6-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "translation, sentence frame, tense, modal, comparison, and connector"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "Chinese-English sentence meaning, subject, time, place, and function"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "translation, because, if, there is/are, questions, and comparison"),
    ]
    return [{"url": u, "title": f"{t}；僅取簡單中翻英的句意轉換、句型與語意完整能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以中文情境、時間、主詞、功能與句型要求學生產出英文句子；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-4-iv-6"
    data["title"] = "4-Ⅳ-6：從中文句意轉換時間、語序與功能完整的英文句子"
    data["content"] = {"summary": "簡單中翻英不是逐字替換，而是先拆解中文的主詞、動作、時間、地點、數量、語氣與邏輯關係，再選擇英文句型和詞序。本課以日常作息、現在進行、過去否定、借傘、原因、存在句、過去問句、比較、禮貌請求與未來條件等原創句子，練習保留原意而不添加或漏掉資訊，並用回譯檢查時態、助動詞、冠詞、介系詞與連接詞。", "sections": [{"heading": "先拆中文句子的資訊角色", "body": "我每天在七點吃早餐含主詞、頻率、時間與動作；她正在圖書館讀一本書含正在進行、地點與受詞。先畫角色欄，再組英文骨架，不能從第一個中文字逐字搬移。"}, {"heading": "時間和語氣決定句型", "body": "每天用現在簡單式，正在用現在進行式，上週／昨晚用過去式；可以用 can，請求用祈使或 please，嗎要組助動詞問句。中文沒有明顯字尾，英文仍要把時間和功能寫出來。"}, {"heading": "數量、比較與存在句不能漏", "body": "桌上有三本英文書要有 There are、three、books、on the desk；妹妹比我高要保留比較級 taller than me。冠詞、複數、介系詞和比較對象都是原意的一部分。"}, {"heading": "因果與條件保留邏輯", "body": "because 下雨所以留家是原因句，if 明天下雨則取消比賽是條件句。先判斷兩個子句的關係，再選 because／if 和適當時態，不能把可能條件寫成已發生事實。"}]}
    data["studyHighlights"] = ["先拆主詞、動作、時間、地點、數量、語氣與邏輯關係。", "依每天、正在、過去、可以、請求、比較、because 或 if 選句型。", "核對主詞動詞、助動詞、冠詞、複數、介系詞與比較對象。", "用中文回譯檢查英文是否保留原意且沒有添加或漏掉資訊。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "中文順序能直接搬到英文嗎？", "body": "比較『我每天在七點吃早餐』的中文順序與英文 I eat breakfast at seven every day。學生先圈主詞、動作、時間與頻率，再討論英文為何要調整位置與動詞形式。"}, {"id": "explain", "phase": "explain", "heading": "句意四層拆解卡", "body": "建立 Who、Action／state、Time／place、Relation／tone 四欄。翻譯前先填欄位，再選陳述、問句、否定、比較、請求、because 或 if 的英文骨架。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從條件句保留未來關係", "body": "以『如果明天下雨，我們將取消比賽』示範：if 子句用現在式 rains，主要句用 will cancel；說明英文條件句不把 if 子句直接寫成 will rain。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一句意換時間和功能", "body": "輪換作息、圖書館、過去行程、借傘、原因、存在、問句、比較、請求與條件十組原創中文句。學生先標功能，再翻譯，互伴依四層卡找漏失。"}, {"id": "transfer", "phase": "transfer", "heading": "從生活筆記寫雙語訊息", "body": "學生將日程、天氣與借物需求寫成中文原句和英文訊息，交換後只看英文回譯中文，檢查時間、語氣、數量和邏輯是否一致。"}, {"id": "reflect", "phase": "reflect", "heading": "我翻的是字，還是意思？", "body": "回看答案，標記時態、語序、助動詞、冠詞、複數、介系詞、比較或連接詞錯誤。修訂時先回到中文四層卡，不只逐字替換一個字。"}], "summary": ["用 Who、Action／state、Time／place、Relation／tone 四欄拆解中文句意。", "依時間、語氣、比較、原因與條件選英文句型。", "核對時態、助動詞、冠詞、複數、介系詞、比較與子句關係。", "以回譯和雙語訊息檢查原意是否完整保留。"], "exitCheck": [{"prompt": "中翻英為什麼不能逐字替換？", "expectedEvidence": "能說明中文資訊角色與英文語序、動詞形式不同，並以一句話拆解示範。"}, {"prompt": "如何讓英文保留中文的時間與語氣？", "expectedEvidence": "能依每天、正在、過去、可以、請求或條件選用正確句型。"}, {"prompt": "如何確認翻譯沒有漏掉數量或邏輯？", "expectedEvidence": "能用四層卡和中文回譯核對複數、介系詞、比較對象、because 或 if 關係。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "拆解中文句意並轉換成保留時間、語氣、數量與邏輯關係的英文句子。", "scenario": "學生擔任雙語訊息編輯，要把日常、行程、天氣與借物句子翻成讀者能直接使用的英文。", "variables": [{"symbol": "w", "meaning": "Who、Action／state、Time／place"}, {"symbol": "f", "meaning": "陳述、否定、問句、比較、請求與情態"}, {"symbol": "r", "meaning": "數量、because／if、條件、順序與回譯"}], "steps": [{"id": "step-1", "prompt": "「我每天在七點吃早餐。」Which translation is correct?", "options": ["I eat breakfast at seven every day.", "I eating breakfast seven yesterday.", "Every I breakfast eat at seven."], "answer": "A", "feedback": "A 保留主詞、現在習慣、時間與頻率，英文語序完整。"}, {"id": "step-2", "prompt": "「桌上有三本英文書。」Which translation is correct?", "options": ["There are three English books on the desk.", "There is three English book at desk.", "Three are desk English on books."], "answer": "A", "feedback": "A 正確使用複數 there are、three books、English 與 on the desk。"}, {"id": "step-3", "prompt": "「如果明天下雨，我們將取消比賽。」Which translation is correct?", "options": ["If it rains tomorrow, we will cancel the game.", "If it will rain tomorrow, we cancel yesterday.", "Tomorrow if rain, game cancelling we."], "answer": "A", "feedback": "A 保留 if 條件和主要句未來結果，if 子句使用現在式 rains。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；生活句型、句意與書寫定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由中文情境與生活句子轉換基本英文。", "以人物、時間、地點與行動表達原意。"], "representations": ["作息、圖書館、家庭、天氣與課堂句。"], "examplesOrEvidence": ["本課以早餐、借傘、雨天、存在句與比較原創句子承接公開結構。"], "misconceptions": ["逐字翻譯，不先拆主詞、時間和功能。"], "assessmentEmphasis": ["重視句意、句型與生活英文書寫。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖文、任務與翻譯句型定位；核讀 2026-09-21。", "findings": {"concepts": ["透過情境、提示與任務轉寫英文句子。", "依時間、主詞、疑問、比較與連接詞調整。"], "representations": ["雙語訊息、行程、借物、條件、原因與比較。"], "examplesOrEvidence": ["本課以句意四層拆解卡重新設計翻譯活動。"], "misconceptions": ["中文順序直搬，漏掉助動詞、冠詞或子句。"], "assessmentEmphasis": ["評量句意、語序、時態與功能。"], "misconceptions": ["中文順序直搬，漏掉助動詞、冠詞或子句。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；基本句型、翻譯、連接與書寫定位；核讀 2026-09-21。", "findings": {"concepts": ["從中文句意、句型功能與英文語序形成轉換。", "以時態、助動詞、比較、because、if 與 there is/are 保留關係。"], "representations": ["who、action、time、relation、tone、back-translation。"], "examplesOrEvidence": ["本課以雙語訊息、回譯與條件句重新設計翻譯校對。"], "misconceptions": ["英文句子看似通順卻漏掉中文的時間、數量或邏輯。"], "assessmentEmphasis": ["評量句意保留、格式、句型與自我修訂。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持生活情境、句型與中英句意轉換。", "可靠翻譯需整合主詞、動作、時間、地點、功能、數量與邏輯。", "可用四層卡、雙語訊息、回譯與條件句校對完成遷移。"], "versionDifferences": ["南一較突顯生活句子與主要訊息；康軒較突顯圖文、任務、語序與功能；翰林較突顯句型關係、時態、連接與回譯修訂。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Who、Action／state、Time／place、Relation／tone 四欄拆解中文句意。", "用早餐、圖書館、雨天、借傘、存在、比較與條件原創句子練習。", "以雙語訊息、中文回譯與錯誤位置記錄檢查原意是否完整。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織簡單中翻英的句意拆解、語序、時態、助動詞、比較、存在、because 與 if 關係。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-4-iv-6-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先拆中文主詞、動作、時間、地點、數量、語氣與邏輯，再組英文句型並以回譯校對。"; q["solutionSteps"] = ["先圈中文句的主詞、主要動作或狀態及時間線。", "判斷陳述、否定、問句、請求、比較、存在、原因或條件功能。", "依英文語序組主詞、動詞、受詞、助動詞、介系詞與連接詞。", "核對時態、主詞動詞、冠詞、複數、比較對象和子句關係。", "回譯成中文並朗讀，確認原意、數量、語氣與邏輯沒有漏失。" ]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的簡單中翻英、句型、時態、比較、存在與連接詞模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 4-iv-6")


if __name__ == "__main__":
    main()
