import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/chinese/lesson-chinese-performance-5-iv-2.json"
REPORT = ROOT / "implementation/reports/chinese-performance-5-iv-2-first-pass-review.json"


def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher": name, "edition": f"{name} 公立校方國文課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": locator, "reviewedAt": "2026-09-21", "findings": {"concepts": concepts, "representations": forms, "examplesOrEvidence": ["本課以原創校園觀察、訪談摘要與短文比較卡，承接公開課程的句段理解、閱讀策略與表達方向。"], "misconceptions": [misconception], "assessmentEmphasis": [assessment]}, "licenseBoundary": "只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}


def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-chinese-performance-5-iv-2"
    data["title"]="5-Ⅳ-2：從句段證據辨認主要概念、寫作目的與觀點"
    data["content"]={"summary":"理解一段文字，不是把每個句子重新抄一次，而是辨認作者把哪些資訊放在核心位置、希望讀者完成什麼，以及作者如何看待議題。本課以自編校園觀察、訪談摘要、勸說段落與資料限制為材料，練習用重複概念、因果鏈、轉折、例證與語氣找出主要概念，再區分寫作目的和可由文字支持的觀點，避免把例子、背景或個別受訪者的話誤當全文結論。", "sections":[{"heading":"先找句段在回答什麼問題","body":"讀完句段先不要急著下標題，試著問它在回答『發生什麼』『為什麼』『怎麼做』還是『作者如何評價』。把每句標成現象、原因、例證、轉折或結論，觀察哪些資訊被重複、承接或放在段尾，主要概念才不會被最鮮明的一個例子帶走。"},{"heading":"主要概念要能統攝而不過度放大","body":"好的主要概念比單一句子抽象一層，能涵蓋段落多數重要資訊，又不加入原文沒有的價值判斷。若段落寫觀察溪流、訪問居民與整理污染來源，概念應保留調查的對象、方法與目的；只寫『溪流很髒』便漏掉作者如何形成結論。"},{"heading":"寫作目的與觀點是兩個問題","body":"目的問作者寫這段要讓讀者知道、理解、比較、反思還是採取行動；觀點問作者對議題的立場或判斷。說明失敗實驗的目的可能是分享經驗，並不代表作者主張所有實驗都會失敗；必須分別找提示語、論據、語氣與限制。"},{"heading":"結論的大小不能超過證據","body":"文章只報告三位受訪者的喜好，最多支持這三人的看法，不能直接推成全校或所有人都如此。遇到『然而』『不只』『仍需考慮』等轉折，要把保留條件放進理解；最後用一句話寫出主概念、目的、觀點與證據邊界。"}]}
    data["studyHighlights"]=["用句段問題、資訊角色與重複概念定位核心。","讓主要概念統攝多數內容但不加入原文沒有的結論。","分開寫作目的、作者觀點、例證與背景。","依樣本、限定語與轉折控制結論範圍。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"最醒目的句子就是主旨嗎？","body":"提供一段自編校園老樹短文：開頭有鮮明故事，中段寫不同年級交換經驗，結尾補上遮蔭與公共空間功能。請學習者先圈出最想引用的句子，再用一句話說明它是否能涵蓋整段；若不能，回到資訊之間的共同問題，建立『統攝』而非摘句的概念。"},{"id":"explain","phase":"explain","heading":"主要概念、目的、觀點三欄卡","body":"先在第一欄將句子標成現象、原因、例證、轉折或結論；第二欄回答作者希望讀者知道或做什麼；第三欄只寫能由語句、論據和語氣支持的立場。最後把三欄互相核對：若目的或觀點無法指出文字證據，就降低肯定程度或列為待查。"},{"id":"worked-example","phase":"worked-example","heading":"從失敗實驗記錄判斷作者在做什麼","body":"以自編段落示範：作者留下失敗步驟，下一組因此避開彎路。主要概念是經驗記錄能支持後續學習，寫作目的偏向分享方法與提醒，不能擴大成所有失敗都必然有價值。示範如何用因果鏈和限定詞排除過大的選項。"},{"id":"guided-practice","phase":"guided-practice","heading":"用轉折句修正過度結論","body":"每組閱讀含『然而，這項方案仍需考慮無法上網的家庭』的自編勸說段落，先寫原先可能的主張，再把轉折後的限制補回去。互相交換後，檢查對方是否把方案支持者的觀點誤讀成作者無條件支持，並要求指出至少兩個文字線索。"},{"id":"transfer","phase":"transfer","heading":"換成訪談與資料摘要仍要守住範圍","body":"比較三位受訪者的訪談摘要、班級調查和一段評論文字，使用同一張三欄卡，但在答案旁註明樣本大小、資料來源與未涵蓋對象。若要提出更大的結論，先寫需要增加哪些資料，讓閱讀理解連接到資料素養，而不是憑直覺補全。"},{"id":"reflect","phase":"reflect","heading":"檢查我是否把自己的想法放進作者口中","body":"回看答案，把句子分成原文直接說出、由多句推論、自己額外補充三類。刪除沒有證據的價值判斷，將『作者認為所有人都應該』改成文字真正支持的範圍，並補寫哪個轉折、例證或限定語讓你做出修正。"}],"summary":["先用問題與資訊角色找到句段的共同核心。","區分主要概念、寫作目的與作者觀點，逐欄提出證據。","以轉折、例證、因果和語氣修正過度概括。","標示樣本與資料限制，讓結論不超出文字支持範圍。"],"exitCheck":[{"prompt":"主要概念和摘錄最醒目的句子有何不同？","expectedEvidence":"能說明主要概念需統攝多數重要資訊，並以段落中的共同關係或因果鏈支持，而非只摘一句。"},{"prompt":"如何分辨寫作目的和作者觀點？","expectedEvidence":"能分別回答作者希望讀者知道／做什麼，以及作者對議題的判斷，並各指出文字線索。"},{"prompt":"為什麼三位受訪者的看法不能直接代表所有人？","expectedEvidence":"能指出樣本範圍與未涵蓋對象，並說明需要更多資料才能擴大結論。"}]}
    data["interactive"]={"type":"guided-choice","goal":"用句段證據分辨主要概念、寫作目的與觀點，並控制結論範圍。","scenario":"學生收到一篇校園提案摘要，依序標記資訊角色、建立三欄判讀卡、處理轉折限制，再寫出不超出證據的結論。","variables":[{"symbol":"c","meaning":"主要概念"},{"symbol":"p","meaning":"寫作目的"},{"symbol":"v","meaning":"觀點與證據範圍"}],"steps":[{"id":"step-1","prompt":"判斷一段文章的主要概念時，第一步最適切的是什麼？","options":["把每句標成現象、原因、例證、轉折或結論，再找能統攝多數資訊的共同問題","直接選最長或最有情緒的一句當主旨","先看標題並把自己的生活經驗補進段落"],"answer":"A","feedback":"A 先整理資訊角色與共同關係，避免被單一鮮明句子或外部經驗帶走。"},{"id":"step-2","prompt":"作者寫下失敗實驗供下一組參考，最合理的目的與觀點判讀為何？","options":["目的可能是分享經驗、支持後續學習；不能因此推成作者認為所有失敗都必然有價值","目的必然是批評實驗，觀點是所有研究都不可靠","目的只是記錄日期，觀點與段落無關"],"answer":"A","feedback":"A 把目的與觀點分開，並用段落真正提供的因果範圍限制結論。"},{"id":"step-3","prompt":"段落只呈現三位受訪者都喜歡夜市，哪個結論最負責任？","options":["可說這三位受訪者有共同看法；不能直接說所有居民或所有學生都喜歡","直接宣布全市民意一致，因為三個例子已足夠","否定受訪者資料，因為訪談永遠不能支持任何理解"],"answer":"A","feedback":"A 保留樣本範圍，既使用資料也不把小樣本擴大成普遍結論。"}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；國語文句段理解、閱讀策略與表達定位；核讀 2026-09-21。",["由句段關係與關鍵概念理解文章內容。","以目的、觀點與證據支援閱讀表達。"],["主旨、因果、轉折、例證、作者目的與摘要。"],"把最醒目的例子或自己的想法當成全文主旨。","重視概念統攝、文本證據與摘要範圍。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；國語文閱讀流暢、句段概念與文本形式定位；核讀 2026-09-21。",["透過閱讀、討論與比較理解句段主要概念。","依文本語氣、結構與資料限制修正解釋。"],["校園觀察、訪談摘要、勸說段落、轉折與三欄判讀卡。"],"把作者目的、觀點、例證和背景混成同一項。","要求判讀有理由、能回到文字並標示限制。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；國文句段理解、文本形式與評量定位；核讀 2026-09-21。",["從句段概念、寫作目的與觀點理解文本。","以文本中的證據、限定語與樣本範圍控制結論大小，避免把局部資料擴大。"],["主要概念、作者立場、因果、轉折、樣本與摘要。"],"將小樣本或單一語句擴大成全文或普遍結論。","評量概念統整、觀點辨識、目的判讀與證據界線。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持句段理解、主要概念、寫作目的、觀點與閱讀表達。","閱讀判斷需要由句間關係、語氣、例證與轉折逐步形成。","摘要與結論必須服從文本證據和資料範圍。"],"versionDifferences":["南一較突顯句段關係與閱讀表達；康軒較突顯閱讀、比較、討論與文本形式；翰林較突顯概念、目的、觀點及證據限制。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以主要概念、目的、觀點三欄卡拆開閱讀任務。","用轉折與樣本限制修正過度結論。","以校園觀察、訪談與資料摘要進行跨情境遷移。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織主要概念、寫作目的、觀點、句段證據與結論界線。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 把每一項推論旁邊寫上支持它的詞句或句間關係，若同一證據可以支持兩種解釋，就保留差異並說明需要補查的資訊。"
    data["teaching"]["body"][4]["body"] += " 比較不同資料時先固定問題和判讀欄位，再處理樣本、來源與語氣差異，避免因資料形式不同就偷偷改變結論標準。"
    data["teaching"]["body"][5]["body"] += " 將答案中最肯定的詞逐一圈出，檢查是否有原文的限定語支持；沒有就改成範圍較小、可以回讀驗證的說法。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"5-Ⅳ-2：從句段證據辨認主要概念、寫作目的與觀點","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored chinese performance 5-iv-2")


if __name__ == "__main__": main()
