import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/chinese/lesson-chinese-performance-6-iv-6.json"
REPORT=ROOT/"implementation/reports/chinese-performance-6-iv-6-first-pass-review.json"

def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher":name,"edition":f"{name} 公立校方國文課程計畫章節級證據","sourceType":"public-web","sourceLocator":locator,"reviewedAt":"2026-09-21","findings":{"concepts":concepts,"representations":forms,"examplesOrEvidence":["本課以原創線上文章、簡報、短影音、資料視覺化與共同編輯版本卡，承接公開課程的科技編輯、媒體表達與分享見解方向。"],"misconceptions":[misconception],"assessmentEmphasis":[assessment]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}

def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-chinese-performance-6-iv-6"
    data["title"]="6-Ⅳ-6：以科技編輯、改編與發布負責任地分享見解"
    data["content"]={"summary":"科技編輯不是把文章貼到另一個平台，而是依媒介、讀者與任務重新安排資訊，同時守住原始意義、證據、授權、個資與版本責任。本課從校園樹木調查出發，練習將訪談、照片、圖表與文字編成線上文章、簡報或短影音腳本，調整標題、摘要、視覺層級、字幕與替代文字；發布後再讀取回饋修訂，讓作品既容易理解，也不把編輯造成的省略或效果誤當成原始資料。", "sections":[{"heading":"先決定媒介要幫讀者完成什麼","body":"同一份樹木調查給同學閱讀，可以用短摘要加圖表快速看趨勢；給研究社團，則要保留樣本、方法、單位與限制。媒介選擇不是追求最炫，而是先問讀者要理解、比較、行動還是討論，再安排文字、照片、圖表、音訊與連結。"},{"heading":"改編要保留證據與脈絡","body":"將訪談逐字稿編成短文，可以刪除重複口語、重排段落，但不能把不同人的話拼成一個人說，也不能刪掉改變意思的限定語。長報導改成短影音時要保留核心主張、來源、時間與不確定性，字幕和畫面都不能暗示資料沒有支持的結論。"},{"heading":"視覺與無障礙也是內容編輯","body":"標題、摘要、圖表標籤、色彩對比、照片說明、字幕、替代文字與版面留白會改變讀者理解路徑。圖表要有單位、基準與圖例；照片要說明時間、地點和必要脈絡；若只靠顏色或聲音傳遞關鍵訊息，部分讀者就會被排除。"},{"heading":"發布後仍要追蹤版本和回饋","body":"多人共同編輯時要有檔名、版本、責任欄、變更紀錄、發布前檢查和可回復副本。上線後若讀者看不懂圖表，先辨認是標籤、尺度、文字或媒介問題，再用小範圍改版測試；不要悄悄覆蓋原始資料或刪除批評意見。"}]}
    data["studyHighlights"]=["依讀者、任務與媒介功能安排資訊。","改編時保留主張、來源、脈絡、限定語與人物界線。","用視覺層級、字幕、替代文字與圖表標示支援理解。","以版本紀錄、發布檢查與回饋測試維持作品責任。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"同一資料做成簡報就一定更容易懂嗎？","body":"提供一份自編校園樹木調查與兩個成品：一個有炫目的動畫但沒有單位和圖例，一個畫面簡單卻清楚標出樣本、趨勢與限制。請學習者先以讀者任務測試能否回答問題，再指出媒介選擇、視覺層級和證據是否互相支持，建立科技編輯服務理解的入口。"},{"id":"explain","phase":"explain","heading":"科技編輯六格檢查卡","body":"依序填讀者與任務、核心主張、資料與來源、媒介轉換、可近性與發布版本。每次改編都要標出刪除、重排或新增的部分及理由，檢查是否改變原意；完成後用替代文字、字幕、單位、圖例和引用資訊測試不同讀者能否使用。"},{"id":"worked-example","phase":"worked-example","heading":"把訪談變成短文但不製造新聲音","body":"示範將自編訪談整理成短文：先把每位受訪者分開標記，再刪除口頭贅詞與重複，保留語意限定和不同觀點，引用時標示說話者與情境。若需要合併主題，使用編者敘述，不把拼接句放進引號冒充原話。"},{"id":"guided-practice","phase":"guided-practice","heading":"把氣候資料做成兩種讀者版本","body":"小組將同一張自編氣候圖表改成國小生版與研究社團版：前者用簡短句、圖例和一個重點問題，後者補上單位、樣本、基準與限制。交換後請兩組讀者回答同一問題，若簡化造成錯誤或專業版找不到重點，就調整視覺和文字層級。"},{"id":"transfer","phase":"transfer","heading":"長報導到短影音的責任轉換","body":"先做長報導的主張—來源—限制表，再寫短影音的畫面、旁白、字幕與來源提示。每個剪接都問是否改變時間順序、因果或人物位置；對無法放入的背景提供連結或簡短說明，避免用快速剪輯製造過度確定的效果。"},{"id":"reflect","phase":"reflect","heading":"檢查發布作品留下了誰","body":"回看作品，圈出只靠顏色、聲音或動態才能理解的訊息，補上文字、圖例、字幕或替代文字；再查圖片、統計、訪談與位置資料的授權和個資。最後比較發布前後版本，確認讀者回饋帶來的是可追溯修訂，而不是無紀錄的任意覆蓋。"}],"summary":["先以讀者任務選擇媒介與資訊層級。","改編保留主張、來源、限定語、人物和時間脈絡。","用圖例、單位、字幕、替代文字與對比支援多元讀者。","以共同編輯版本、發布檢查和回饋修訂維持責任。"],"exitCheck":[{"prompt":"長文改成短影音時哪些資訊不能任意刪除？","expectedEvidence":"能指出核心主張、來源、時間、限制、人物界線與必要脈絡，並提出用字幕或連結補足的方法。"},{"prompt":"為什麼圖表和替代文字也屬於內容編輯？","expectedEvidence":"能說明標籤、單位、圖例、色彩、字幕與替代文字會影響讀者取得證據與理解結論。"},{"prompt":"多人共同編輯如何避免發布錯誤版本？","expectedEvidence":"能提出版本命名、變更紀錄、責任欄、發布前檢查、備份與可回復流程。"}]}
    data["interactive"]={"type":"guided-choice","goal":"依媒介和讀者改編作品，同時保留證據、脈絡、可近性、來源與版本責任。","scenario":"學生要把校園樹木調查做成線上文章、簡報與短影音，依序選媒介、改編資料、補無障礙資訊、標示來源並用讀者回饋修訂。","variables":[{"symbol":"m","meaning":"媒介與讀者任務"},{"symbol":"e","meaning":"證據、脈絡與可近性"},{"symbol":"v","meaning":"版本、發布與回饋"}],"steps":[{"id":"step-1","prompt":"要介紹校園樹木調查給同學，哪種媒介安排最能兼顧資料與理解？","options":["只放一張漂亮照片，不必寫調查方法","用清楚標題與摘要搭配有單位、圖例和來源的圖表，必要處補文字說明","把完整原始資料全部貼上，不做任何組織"],"answer":"B","feedback":"B 讓媒介協助讀者抓重點，也保留可核對的資料條件。"},{"id":"step-2","prompt":"把長篇報導改成短影音腳本時，哪項做法最負責任？","options":["只保留最戲劇化的片段，來源和限制可省略","先整理主張、來源、時間與限制，再安排畫面、旁白、字幕和延伸連結，避免剪輯改變因果","加快畫面和音樂，讓觀眾沒有時間質疑"],"answer":"B","feedback":"B 把媒介轉換建立在來源和脈絡上，避免效果取代證據。"},{"id":"step-3","prompt":"作品上線後讀者反映圖表看不懂，最好的編輯回應是什麼？","options":["責怪讀者不熟悉資料，維持原版","記錄讀者卡住的位置，檢查標題、單位、尺度、圖例與文字說明，做可回溯的小範圍修訂再測試","刪掉整張圖表，只留下自己想表達的結論"],"answer":"B","feedback":"B 把回饋轉成具體編輯假設，修訂後重新驗證而不是取消證據。"}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；國語文科技編輯、媒介表達與發布定位；核讀 2026-09-21。",["運用科技媒介編輯作品並分享見解。","依讀者、目的與媒介調整表達，使資訊層級和呈現方式服務理解與溝通。"],["線上文章、簡報、照片、圖表、影片與字幕。"],"把上傳或加動畫等同於完成科技編輯。","重視內容組織、媒介適切與分享責任。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；國語文寫作、資訊表達與實作評量定位；核讀 2026-09-21。",["透過改編、比較與回饋改善科技作品。","依不同讀者與平台調整層級、格式與互動。"],["訪談編輯、資料視覺化、短影音、簡報與共同編輯。"],"只追求視覺效果，忽略原意、來源與可近性。","要求媒介轉換有依據、發布可追溯且能修訂。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；國文科技編輯、作品分享與評量定位；核讀 2026-09-21。",["從科技編輯、改編與發布形成個人見解。","以來源、授權、個資、無障礙與版本責任支持分享。"],["線上文章、圖表、字幕、替代文字、引用、版本與回饋。"],"把原始資料拼貼或把媒介效果當成證據。","評量編輯判斷、媒介適切、證據責任與發布反思。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持科技編輯、媒介轉換、作品分享與讀者表達。","改編需兼顧內容核心、讀者任務、媒介功能與可近性。","發布要保留來源、授權、個資、版本和回饋責任。"],"versionDifferences":["南一較突顯科技媒介與分享表達；康軒較突顯改編、比較、實作與回饋；翰林較突顯引用、無障礙、個資、版本與發布責任。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以科技編輯六格檢查卡統整讀者、主張、來源、媒介、可近性與版本。","用訪談逐字稿改編示範人物聲音與編者敘述界線。","以圖表回饋和小範圍版本測試驗證發布後修訂。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織科技編輯、媒介改編、資料視覺化、無障礙、來源授權、個資與版本回饋。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 每次刪除、重排或新增都要在版本卡寫明理由與可能影響，並用原始資料回查；若動態、照片或剪輯改變了讀者對時間和因果的理解，就必須重做媒介安排。"
    data["teaching"]["body"][4]["body"] += " 比較不同平台時固定核心主張和限制，再調整摘要、畫面、字幕、連結與互動；平台的速度不能成為省略來源或脈絡的理由。"
    data["teaching"]["body"][5]["body"] += " 把讀者回饋、授權查核、個資處理和無障礙修訂放進同一份發布紀錄，讓作品即使下線或改版也能回溯誰改了什麼、為什麼改。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"6-Ⅳ-6：以科技編輯、改編與發布負責任地分享見解","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored chinese performance 6-iv-6")

if __name__=="__main__": main()
