import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSON = ROOT / "lessons/english/lesson-english-performance-3-iv-14.json"
REPORT = ROOT / "implementation/reports/english-performance-3-iv-14-first-pass-review.json"


def refs():
    rows = [
        ("https://www.yacjh.kh.edu.tw/upload/221/101_30637/114%E4%B8%8B%E5%AD%B8%E6%9C%9F%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%AE%B5%E8%80%83%E4%B8%89%E5%B9%B4%E7%B4%9A%E8%8B%B1%E6%96%87.pdf", "高雄市立鹽埕國民中學公開英文段考", "rapid reading, topic, repeated detail, summary, and structure"),
        ("https://www.bhjh.ntpc.edu.tw/p/406-1000-10627%2Cr111.php?Lang=zh-tw", "新北市立北投國民中學公開定期評量試題頁", "skimming, scanning, heading, key information, and purpose"),
        ("https://www.hcjh.ntpc.gov.tw/p/406-1000-7527%2Cr146.php", "新北市立新埔國民中學公開段考試題頁", "main idea, detail priority, text structure, and confirmation"),
    ]
    return [{"url": u, "title": f"{t}；僅取快速閱讀、重點擷取與文本結構能力方向，未複製原題、選項、圖片或答案。", "year": "113-114", "subject": "english", "locator": loc, "observedPattern": "公開英文評量以標題、標題層級、重複細節、主旨、摘要、尋讀與回讀確認測量快速理解；本題為獨立改寫。", "reuseDecision": "pattern-only", "status": "recorded", "locatorLevel": "paper"} for u, t, loc in rows]


def main():
    data = json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"] == "lesson-english-performance-3-iv-14"
    data["title"] = "3-Ⅳ-14：用略讀、尋讀與結構線索快速抓住重點"
    data["content"] = {"summary": "快速閱讀不是把每句都讀快一點，而是先決定任務，再用標題、標題層級、首尾句、重複詞與格式線索建立全貌，之後尋找日期、地點、費用或期限等特定資訊，最後回讀關鍵段落確認。本文以城市樹木、可重複杯、食物浪費、活動網頁、校園交通、問題—想法—下一步結構與火車資訊等原創文本，練習在時間限制下取捨資訊、寫出不失真的摘要。", "sections": [{"heading": "先看結構，不急著翻每句", "body": "標題、段落標題、首句和末句能先告訴讀者文章方向。若要知道城市樹木文章在談什麼，先找 Why、Problem 或 Next Steps 等結構，再決定哪一段值得細讀。"}, {"heading": "重複與格式是優先線索", "body": "通知反覆出現 bring a reusable cup，代表這是行動要求，不必先翻完歷史背景。日期、時間、費用、email、地址等格式明顯的細節可用 scanning 快速定位。"}, {"heading": "主旨摘要要保留關係", "body": "學生步行、搭公車、共乘不是三個互不相關的動作，而是為了減少校門口交通。摘要要留下行動與目的，不能只列其中一種交通方式。"}, {"heading": "快速讀完仍要回讀驗證", "body": "先略讀再尋讀，最後重讀一段確認，是取捨而不是猜測。若新句子推翻初步摘要，就修正理解；若需要註冊，還要確認地點、活動、費用與聯絡方式是否足夠。"}]}
    data["studyHighlights"] = ["先由標題、標題層級、首尾句與格式建立文章全貌。", "用重複詞和日期、地點、費用等格式線索決定資訊優先順序。", "摘要保留行動與目的的關係，不只是列出細節。", "略讀、尋讀後回讀關鍵段落，修正不被證據支持的初步理解。"]
    data["teaching"] = {"body": [{"id": "hook", "phase": "hook", "heading": "三十秒內要讀完整篇嗎？", "body": "給學生一張原創活動頁，分別提出『主題是什麼』與『報名截止日』兩個任務。學生先比較應看標題／標題層級還是日期格式，理解快速閱讀的核心是取捨。"}, {"id": "explain", "phase": "explain", "heading": "快速閱讀四站卡", "body": "建立 Preview、Prioritize、Scan、Confirm 四站：先看標題與結構，依任務排優先，尋讀關鍵格式，最後回讀句子驗證。每站寫下看到的證據，避免只憑速度。"}, {"id": "worked-example", "phase": "worked-example", "heading": "從重複要求找最重要行動", "body": "以 bring a reusable cup 重複三次的海報示範：重複詞是優先細節，先寫行動，再回看位置與活動時間；不能因背景歷史文字較長就把它當主旨。"}, {"id": "guided-practice", "phase": "guided-practice", "heading": "同一文章換讀法", "body": "用城市樹木、食物浪費、交通、活動頁、問題—想法—下一步與火車公告六組原創文本，學生輪流完成主旨、截止日、地點、費用與摘要任務，說明自己如何取捨。"}, {"id": "transfer", "phase": "transfer", "heading": "為不同時間限制設計路線", "body": "同一篇校園說明給 20 秒、2 分鐘與 5 分鐘限制；學生分別選 Preview、Scan 或 Confirm 的深度，最後比較哪些內容始終保留、哪些只在需要時細讀。"}, {"id": "reflect", "phase": "reflect", "heading": "快讀是否犧牲了準確？", "body": "回看答案，標記只看標題、把細節當主旨、漏掉目的、尋讀錯格式或未回讀確認。修訂時在摘要旁補一個支持句，在特定資訊旁標記原文位置。"}], "summary": ["以 Preview、Prioritize、Scan、Confirm 四站調整快速閱讀。", "根據閱讀任務選擇標題、重複詞、格式或段落線索。", "摘要保留事件與目的，特定資訊則精準定位。", "最後回讀關鍵句確認，不把快速猜測當作理解結果。"], "exitCheck": [{"prompt": "快速閱讀為什麼需要先決定任務？", "expectedEvidence": "能說明主旨、特定細節與證據判斷需要不同取捨，並各舉適合的線索。"}, {"prompt": "重複詞、標題層級和日期格式各提供什麼優先線索？", "expectedEvidence": "能分別說明行動重要性、文本結構與特定資訊定位。"}, {"prompt": "快速讀完後如何避免摘要失真？", "expectedEvidence": "能回讀關鍵段落，檢查行動—目的關係與摘要是否被原文支持。"}]}
    data["interactive"] = {"type": "guided-choice", "goal": "在時間限制下依閱讀目的取捨資訊，利用結構、重複與格式線索建立並確認摘要或細節答案。", "scenario": "學生擔任校園資訊快讀員，要在不同時間限制中替同伴找出主題、截止日、地點與可執行行動。", "variables": [{"symbol": "p", "meaning": "Preview：標題、標題層級與首尾句"}, {"symbol": "r", "meaning": "Prioritize／Scan：重複詞、格式與任務要求"}, {"symbol": "c", "meaning": "Confirm：回讀關鍵句與行動—目的關係"}], "steps": [{"id": "step-1", "prompt": "You have 30 seconds to understand 'Why Cities Need Trees.' What should you inspect first?", "options": ["The title, headings, and opening sentences.", "Every word in the longest paragraph.", "Only the last number on the page."], "answer": "A", "feedback": "快速掌握主題先用標題、結構與開頭線索，而不是逐字精讀。"}, {"id": "step-2", "prompt": "A notice repeats 'bring a reusable cup' three times. What should you treat as important?", "options": ["Bringing a reusable cup is a key action.", "The notice has no required action.", "The repeated phrase is only decoration."], "answer": "A", "feedback": "重複要求提高優先度，直接指出讀者要採取的行動。"}, {"id": "step-3", "prompt": "You need a train departure time quickly. What is the most efficient process?", "options": ["Scan for the time, then reread the line to confirm it.", "Translate every sentence before looking for a time.", "Guess the time from the station name."], "answer": "A", "feedback": "先尋讀特定格式，再回讀句子確認，兼顧速度與準確。"}]}
    data["authoringStandard"] = "version-fused-v1"; data["updatedAt"] = "2026-09-21"
    data["versionResearch"] = [{"publisher": "nani", "edition": "nani 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course113/sub1/15636172843290327.pdf；生活文本、主要訊息與快速理解定位；核讀 2026-09-21。", "reviewedAt": "2026-09-21", "findings": {"concepts": ["由標題、段落與生活資料快速掌握主要訊息。", "依目的定位時間、地點與行動。"], "representations": ["公告、活動頁、環境、交通與校園文本。"], "examplesOrEvidence": ["本課以樹木、節水、食物、交通與活動原創文本承接公開結構。"], "misconceptions": ["為求快速只讀第一句，沒有回讀確認。"], "assessmentEmphasis": ["重視主要內容、細節與生活閱讀。"]}, "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "kanghsuan", "edition": "kanghsuan 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course112/sub1/15342166894673419.pdf；圖文、任務與資訊定位；核讀 2026-09-21。", "findings": {"concepts": ["透過標題、圖文與任務選擇閱讀深度。", "依關鍵字、格式與結構完成快讀。"], "representations": ["海報、活動頁、問題—想法—下一步、時間與費用。"], "examplesOrEvidence": ["本課以四站卡重新設計不同時間限制的閱讀任務。"], "misconceptions": ["看到長段落就逐字翻譯，忽略題目需要的資訊。"], "assessmentEmphasis": ["評量資訊取捨、摘要與細節定位。"], "misconceptions": ["看到長段落就逐字翻譯，忽略題目需要的資訊。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}, {"publisher": "hanlin", "edition": "hanlin 公立校方英語課程計畫章節級證據", "sourceType": "public-web", "sourceLocator": "https://course.cyc.edu.tw/upfile/course114/sub1/15939623345151225.pdf；閱讀策略、結構與確認定位；核讀 2026-09-21。", "findings": {"concepts": ["從閱讀目的選擇略讀、尋讀與回讀確認。", "以標題層級、重複詞、格式與行動—目的關係檢查理解。"], "representations": ["preview、prioritize、scan、confirm、summary、detail。"], "examplesOrEvidence": ["本課以時間限制、重複要求與結構標題重新設計快速閱讀。"], "misconceptions": ["把快讀猜測或單一細節直接當成摘要。"], "assessmentEmphasis": ["評量快速理解、重點排序、摘要與證據。"]}, "reviewedAt": "2026-09-21", "licenseBoundary": "只記錄公開章節定位與評量方向，不複製教材正文、題目或答案。"}]
    data["fusionRecord"] = {"commonCore": ["三版本公開結構共同支持標題、段落、生活文本與主要訊息理解。", "可靠快讀需依任務取捨，再用結構、重複、格式與回讀驗證。", "可用四站卡、不同時間限制與摘要—證據檢查完成遷移。"], "versionDifferences": ["南一較突顯生活文本與主要訊息；康軒較突顯圖文、任務、關鍵字與資訊定位；翰林較突顯閱讀目的、文本結構、摘要與回讀確認。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"], "originalAdditions": ["以 Preview、Prioritize、Scan、Confirm 四站調整快速閱讀。", "用城市樹木、可重複杯、食物浪費、交通、活動頁與火車公告原創文本練習。", "以不同時間限制比較取捨，並用行動—目的關係驗證摘要。"], "llmSynthesisNote": "本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織快速閱讀、文本結構、重點排序、尋讀、摘要與回讀確認。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    paths = sorted(ROOT.glob("questions/english/question-english-performance-3-iv-14-*.json"), key=lambda p: int(p.stem.rsplit('-', 1)[1]))
    for p in paths:
        q = json.loads(p.read_text(encoding="utf-8")); q["examPatternRefs"] = refs(); q["reviewStatus"] = "draft"; q["updatedAt"] = "2026-09-21"; q["solutionStrategy"] = "先判斷閱讀任務，再用標題與結構預覽、重複與格式尋讀，最後回讀關鍵句確認。"; q["solutionSteps"] = ["先讀題目，判斷要掌握主旨、找特定細節或驗證摘要。", "選擇與任務相配的快速閱讀工具並說明優先線索。", "回到標題、標題層級、重複詞、格式或段落找證據。", "把細節放回行動—目的或結構關係，排除只看一個詞的選項。", "回讀關鍵句確認答案，若初步摘要不被支持就修正。"]; q["provenance"]["sourceUrl"] = refs()[0]["url"]; q["provenance"]["sourceLocator"] = "公立學校公開英文評量的快速閱讀、主旨、重點排序、結構與回讀模式；本題只改寫能力、資料型態與推理層次。"; p.write_text(json.dumps(q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    LESSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    REPORT.write_text(json.dumps({"unit": data["title"], "lessonId": data["id"], "status": "first-pass-ai-review-complete", "reviewStatus": "draft", "checks": {"unitSpecificOriginalContent": True, "threeVersionResearchRecords": True, "publicExamPatternRewrite": True, "fusionRecordPresent": True, "interactivePredictionManipulationExplanation": True, "answersAndDetailedSteps": True, "terraSecondPass": "pending"}, "reviewedAt": "2026-09-21"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("authored english performance 3-iv-14")


if __name__ == "__main__":
    main()
