import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LESSON=ROOT/"lessons/chinese/lesson-chinese-performance-5-iv-6.json"
REPORT=ROOT/"implementation/reports/chinese-performance-5-iv-6-first-pass-review.json"

def rec(name, locator, concepts, forms, misconception, assessment):
    return {"publisher":name,"edition":f"{name} 公立校方國文課程計畫章節級證據","sourceType":"public-web","sourceLocator":locator,"reviewedAt":"2026-09-21","findings":{"concepts":concepts,"representations":forms,"examplesOrEvidence":["本課以原創圖書館檢索、網路查核、專題筆記與資料組織卡，承接公開課程的資訊素養、閱讀策略與研究表達方向。"],"misconceptions":[misconception],"assessmentEmphasis":[assessment]},"licenseBoundary":"只記錄公開課程計畫的概念與評量方向；不複製出版社或學校教材正文、篇章、題目、答案、影音或版面。"}

def main():
    data=json.loads(LESSON.read_text(encoding="utf-8")); assert data["id"]=="lesson-chinese-performance-5-iv-6"
    data["title"]="5-Ⅳ-6：用圖書館與科技工具蒐集、組織並驗證資訊"
    data["content"]={"summary":"有效的資訊研究不是把搜尋結果堆成一長串連結，而是從問題定義、關鍵詞設計、圖書館目錄與資料庫檢索開始，逐筆記錄來源、版本、日期、方法與可用主張，再依研究問題組織成可回溯的筆記。科技工具可以加快全文搜尋、標籤、引用管理與比較，但不能代替來源查核、不同觀點補充或個人資料保護。本課以屋頂綠化、海洋塑膠、移民經驗與統計版本差異等自編任務，完成一條可重做的研究流程。", "sections":[{"heading":"把大題目改成可搜尋的問題","body":"『環境很好不好』太寬，『校園屋頂綠化對夏季教室夜間溫度有何影響』才包含對象、措施、結果與時間。從問題拆出核心詞、同義詞、地點、年份與資料類型，再用 AND、引號或排除詞逐輪縮小；每輪保留搜尋式和結果，才能知道如何改善。"},{"heading":"圖書館工具和網路搜尋各有任務","body":"目錄適合找書名、主題與館藏位置，資料庫能依作者、摘要、年份與學科篩選，全文檢索可定位詞句但不等於理解上下文，普通網頁則需要額外檢查機構、作者、日期與原始資料。先選工具再定關鍵詞，並記錄取得版本，避免把搜尋排名誤當可信度。"},{"heading":"筆記要保留主張與來源的接點","body":"每則筆記寫下原文主張的自己的摘要、直接引用的必要範圍、頁碼或段落、作者與日期、網址或識別碼，以及它支持哪個研究問題。把事實、推論、疑問和自己的想法分欄，日後才能回到原文核對，不會把他人的說法寫成自己的發現。"},{"heading":"拓展視野也要管理差異與風險","body":"若資料都來自同一機關，應補找學術研究、地方組織、當事人敘述或不同地區資料，並說明它們的立場與方法差異。遇到網頁與 PDF 數字不同，先查版本日期、修訂說明和統計定義；使用公共電腦或雲端工具時，也要登出、清除下載和保護個人資料。"}]}
    data["studyHighlights"]=["把研究問題拆成對象、措施、結果、時間與資料類型。","依任務選圖書館目錄、資料庫、全文檢索或網路來源。","每則筆記保留主張、定位、版本、來源與研究問題接點。","補充不同立場並處理版本差異、著作權與個資風險。"]
    data["teaching"]={"body":[{"id":"hook","phase":"hook","heading":"搜尋結果多就代表研究完整嗎？","body":"給出一個自編大題目『校園屋頂綠化好不好』和三頁混雜搜尋結果，請學習者先指出哪些結果只是宣傳、哪些有方法與日期，再把大題目改寫成含對象、措施、結果與時間的可搜尋問題。比較改寫前後的結果差異，讓工具服從問題而非反過來。"},{"id":"explain","phase":"explain","heading":"研究流程六格卡","body":"依序完成問題界定、關鍵詞與搜尋式、工具選擇、來源篩選、證據筆記、觀點與版本比較。每格要留下可重做的紀錄：搜尋式、篩選條件、取得日期、頁碼、識別碼和下一個查證問題，不能只保存最後找到的連結。"},{"id":"worked-example","phase":"worked-example","heading":"從『海洋塑膠』到可組織的專題資料夾","body":"示範把寬題拆成來源、進入途徑、影響、政策與案例五個資料夾，並在每筆檔名或標籤加入年份與來源類型。挑一則資料寫成主張—證據—限制三欄，說明資料夾不是分類遊戲，而是幫助寫作時快速找到可引用且能核對的證據。"},{"id":"guided-practice","phase":"guided-practice","heading":"同一數字不同版本怎麼辦？","body":"給出網頁與下載 PDF 的同一統計數字，請學習者比較發布日期、修訂註記、指標定義與表格頁碼。暫不選擇自己喜歡的版本，而是把差異記入版本表，必要時回到原始機構詢問或引用較新版本並說明變更。"},{"id":"transfer","phase":"transfer","heading":"為單一經驗補上多元視角","body":"以移民經驗研究為任務，先整理政策機關資料，再設計搜尋式找到學術研究、地方組織與當事人敘述。比較各來源的問題、方法與位置，不把任何一種聲音自動當成全貌，最後寫出研究還缺少哪類資料及為何需要它。"},{"id":"reflect","phase":"reflect","heading":"檢查工具是否讓我失去研究責任","body":"回看筆記，圈出沒有頁碼、日期、作者、版本或研究問題連結的項目；再檢查是否混入未標示的直接引語、下載在公共電腦留下的個資或只來自同一立場的來源。補齊一項紀錄並刪除不必要的個資，讓便利與責任同時存在。"}],"summary":["把大題目拆成可搜尋且可驗證的研究問題。","依任務選擇目錄、資料庫、全文搜尋與網路來源。","以主張、定位、版本、來源與限制建立可回溯筆記。","補充視角、處理版本差異並保護著作權與個人資料。"],"exitCheck":[{"prompt":"如何把寬泛題目改成可搜尋的問題？","expectedEvidence":"能加入研究對象、措施、結果、時間與資料類型，並提出可逐輪修正的關鍵詞。"},{"prompt":"專題筆記為何必須記錄頁碼、日期與版本？","expectedEvidence":"能說明這些資訊讓主張可回到原文核對，也能處理更新、不同版本與引用責任。"},{"prompt":"如何拓展視野而不把所有來源混成同一種證據？","expectedEvidence":"能補找不同位置的來源，並比較作者、方法、立場與限制。"}]}
    data["interactive"]={"type":"guided-choice","goal":"以圖書館與科技工具建立可重做、可查核、保護資料的研究流程。","scenario":"學生要研究校園屋頂綠化，從問題拆解與關鍵詞開始，使用目錄、資料庫和網路來源，整理筆記並處理版本差異與不同觀點。","variables":[{"symbol":"q","meaning":"研究問題與搜尋式"},{"symbol":"e","meaning":"來源、版本與證據筆記"},{"symbol":"r","meaning":"多元觀點與研究風險"}],"steps":[{"id":"step-1","prompt":"要查找校園屋頂綠化對降溫的影響，哪組關鍵詞最有助於縮小範圍？","options":["校園 屋頂綠化 降溫 夏季 溫度測量","綠色 很好","所有環境資料"],"answer":"A","feedback":"A 同時指定對象、措施、結果與時間，能讓搜尋結果更接近研究問題。"},{"id":"step-2","prompt":"做專題筆記時，哪項紀錄最能避免日後找不到證據？","options":["只記自己覺得重要的一句話","記錄主張摘要、作者、日期、頁碼或段落、網址／識別碼與它支持的研究問題","只截圖搜尋結果，不記來源"],"answer":"B","feedback":"B 保留主張與原文定位的接點，日後能核對、引用和修正。"},{"id":"step-3","prompt":"網頁與下載 PDF 的統計數字不同，最適當的處理是什麼？","options":["選數字較符合自己結論的版本","比較日期、修訂說明與指標定義，記錄版本差異，必要時回查原始機構","把兩個數字平均後當成新資料"],"answer":"B","feedback":"B 把版本差異當成研究資料處理，不用任意平均或挑選。"}]}
    data["authoringStandard"]="version-fused-v1"; data["updatedAt"]="2026-09-21"
    data["versionResearch"]=[rec("nani","https://course.cyc.edu.tw/upfile/course114/sub1/15950803923674214.pdf；國語文圖書館、資訊蒐集與研究表達定位；核讀 2026-09-21。",["運用圖書館與科技工具拓展閱讀與資訊蒐集。","以閱讀問題、整理與表達形成研究成果。"],["目錄、資料庫、搜尋式、專題筆記與引用。"],"把搜尋結果數量或排名當成可靠度。","重視問題界定、來源記錄與研究表達。"),rec("kanghsuan","https://course.cyc.edu.tw/upfile/course114/sub1/15939547496629384.pdf；國語文閱讀策略、資訊判讀與文本形式定位；核讀 2026-09-21。",["透過閱讀、比較與科技工具整理資訊。","依來源、版本與研究目的修正搜尋和解釋。"],["關鍵詞、全文搜尋、資料夾、版本表與多元視角。"],"只保存連結，不保存頁碼、日期與主張接點。","要求資料可追溯、可比較且能支援後續寫作。"),rec("hanlin","https://www.msjh.ntpc.edu.tw/uploads/1691978949408RP7cOuyZ.pdf；國文圖書館利用、科技蒐集與評量定位；核讀 2026-09-21。",["從資料庫、圖書館與網路來源形成研究。","區分事實、引用、推論、版本與個資責任。"],["研究問題、來源查核、統計版本、引用管理與資訊安全。"],"把科技工具當成查核與判斷的替代品。","評量資訊組織、來源責任、多元閱讀與安全使用。")]
    data["fusionRecord"]={"commonCore":["三版本公開結構共同支持圖書館利用、科技蒐集、資訊組織與研究表達。","研究需從問題、工具、來源、筆記與比較逐步建立。","科技便利不能取代來源查核、觀點拓展、引用與個資責任。"],"versionDifferences":["南一較突顯圖書館利用與研究表達；康軒較突顯搜尋、比較、整理與策略調整；翰林較突顯資料庫、來源責任、版本與安全使用。這是公立校方課程計畫層級差異，不宣稱完整出版社教材差異。"],"originalAdditions":["以研究流程六格卡讓搜尋步驟可重做。","用同一統計的網頁／PDF 差異建立版本表。","以移民經驗研究補足政策機關以外的多元位置並納入個資風險。"],"llmSynthesisNote":"本課依官方課綱、三筆公立校方章節級公開證據與本單元 KG，重新組織研究問題、檢索工具、來源查核、筆記組織、多元視角、版本差異與資訊安全。正文、原創情境、互動步驟、回饋與檢核均為本專案重寫，未複製教材題目或答案；Terra 第二輪與正式發布審查尚未完成，因此維持 draft。"}
    data["teaching"]["body"][1]["body"] += " 每輪搜尋結束都要保存搜尋式與篩選條件，並挑一筆結果回到原始頁面驗證；若只剩排名或摘要，將它標成線索而不是證據。"
    data["teaching"]["body"][4]["body"] += " 比較不同位置的來源時，先固定同一研究問題，再記錄誰被看見、誰被省略、資料如何取得，避免以『多找幾個連結』假裝視角已經多元。"
    data["teaching"]["body"][5]["body"] += " 將每筆筆記的可追溯性、引用風險與個資風險分開打勾，讓最後刪除或補查的決定有理由，而不是只留下看起來方便的資料。"
    LESSON.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps({"unit":"5-Ⅳ-6：用圖書館與科技工具蒐集、組織並驗證資訊","lessonId":data["id"],"status":"first-pass-ai-review-complete","reviewStatus":"draft","checks":{"unitSpecificOriginalContent":True,"threeVersionResearchRecords":True,"fusionRecordPresent":True,"interactivePredictionManipulationExplanation":True,"answersAndDetailedSteps":True,"terraSecondPass":"pending"},"reviewedAt":"2026-09-21"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print("authored chinese performance 5-iv-6")

if __name__=="__main__": main()
