import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { JSDOM } from "jsdom";

const lesson = JSON.parse(readFileSync(new URL("../../lessons/english/lesson-english-performance-3-iv-4.json", import.meta.url), "utf8"));
const source = readFileSync(new URL("../../site/data-explorer-lab.js", import.meta.url), "utf8");
const app = readFileSync(new URL("../../site/app.js", import.meta.url), "utf8");
const html = readFileSync(new URL("../../site/index.html", import.meta.url), "utf8");
const css = readFileSync(new URL("../../site/data-explorer-lab.css", import.meta.url), "utf8");
assert.equal(lesson.interactive.type, "data-explorer-lab");

const dom = new JSDOM("<main id=mount></main>", { url: "https://courseware.test/", runScripts: "outside-only" });
dom.window.eval(source);
const mount = dom.window.document.querySelector("#mount");
const instance = "qa-data-explorer";
mount.innerHTML = dom.window.DataExplorerLab.render(lesson, instance);
const root = () => mount.querySelector("[data-data-explorer-lab]");
const field = name => root().querySelector(`[data-del-field="${name}"]`);
const enter = (name, value) => { field(name).value = value; field(name).dispatchEvent(new dom.window.Event("input", { bubbles: true })); };
const click = action => root().querySelector(`[data-del-action="${action}"]`).click();
assert.equal(root().querySelectorAll("[data-del-scale]").length, 0, "scale manipulation is locked before a correct prediction");
enter("prediction", "4"); click("predict");
assert.match(root().querySelector(".del-status").textContent, /格子/);
assert.equal(root().querySelectorAll("[data-del-scale]").length, 0);
enter("prediction", "20"); click("predict");
assert.match(root().querySelector("[data-del-readout]").textContent, /4 格 × 每格 5 本 = 20 本/);
const scale = root().querySelector("[data-del-scale]");
scale.value = "10"; scale.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
assert.match(root().querySelector("[data-del-readout]").textContent, /4 格 × 每格 10 本 = 40 本/);
assert.equal(root().querySelectorAll("[data-del-cell]").length, 4, "the visual height stays four intervals");
enter("explanation", "格數相同，但每格單位和刻度改了。"); click("explain");
assert.equal(root().querySelectorAll("[data-del-choice]").length, 3);
enter("transferExplanation", "Tuesday has 18 visitors.");
root().querySelector('[data-del-choice][value="A"]').click();
click("transfer");
assert.match(root().querySelector(".del-status").textContent, /逐一比較/);
root().querySelector('[data-del-choice][value="B"]').click();
click("transfer");
assert.match(root().textContent, /完成：你依刻度讀出數量/);
mount.innerHTML = dom.window.DataExplorerLab.render(lesson, instance);
assert.match(root().textContent, /完成：你依刻度讀出數量/, "completion restores from lesson-instance storage");
click("reset");
assert.ok(field("prediction"), "reset returns to the prediction stage");
assert.match(app, /DataExplorerLab\.render/);
assert.match(html, /data-explorer-lab\.js/);
assert.match(html, /data-explorer-lab\.css/);
assert.match(css, /prefers-reduced-motion/);
console.log("3-IV-4 scale prediction, unit manipulation, evidence explanation, chart transfer, persistence and reset: ok");
