import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { JSDOM } from "jsdom";

const lesson = JSON.parse(readFileSync(new URL("../../lessons/english/lesson-english-performance-3-iv-7.json", import.meta.url), "utf8"));
const source = readFileSync(new URL("../../site/dialogue-comprehension-lab.js", import.meta.url), "utf8");
const app = readFileSync(new URL("../../site/app.js", import.meta.url), "utf8");
const html = readFileSync(new URL("../../site/index.html", import.meta.url), "utf8");
const css = readFileSync(new URL("../../site/styles.css", import.meta.url), "utf8");
const registry = JSON.parse(readFileSync(new URL("../component-registry.json", import.meta.url), "utf8"));
const lab = lesson.interactive.dialogueLab;
assert.ok(lab.evidenceLineIds.every(id => lab.conversation.some(line => line.id === id)));
assert.ok(lab.mainQuestion.options.some(option => option.id === lab.mainQuestion.answer));
assert.ok(lab.transfer.evidenceLineIds.every(id => lab.transfer.conversation.some(line => line.id === id)));
assert.ok(lab.transfer.options.some(option => option.id === lab.transfer.answer));
const dom = new JSDOM("<main id=mount></main>", { url: "https://courseware.test/", runScripts: "outside-only" });
dom.window.eval(source);
const mount = dom.window.document.querySelector("#mount");
mount.innerHTML = dom.window.DialogueComprehensionLab.render(lesson, "qa-main");
const root = () => mount.querySelector("[data-dialogue-lab]");
const click = selector => root().querySelector(selector).click();
const selectEvidence = (kind, id) => root().querySelector(`[data-dialogue-select="${kind}"][data-line="${id}"]`).click();

assert.match(root().textContent, /先預測整段對話的重點/);
assert.doesNotMatch(root().textContent, /答案：B/);
assert.equal(root().querySelectorAll(".dialogue-line").length, 4);
assert.equal(root().querySelector('[data-dialogue-action="check-evidence"]'), null);
assert.equal(root().querySelector('[data-dialogue-select="main"]').disabled, true);
const prediction = root().querySelector('[data-dialogue-text="prediction"]');
click('[data-dialogue-action="predict"]');
assert.equal(root().querySelector('[data-dialogue-action="check-evidence"]'), null, "blank prediction must not unlock evidence work");
prediction.value = "他錯過公車，後來安排了接送。";
prediction.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
click('[data-dialogue-action="predict"]');
assert.match(root().textContent, /預測已保存/);
assert.equal(dom.window.document.activeElement.matches('[data-dialogue-select="main"]'), true);

selectEvidence("main", "message");
selectEvidence("main", "reaction");
click('[data-dialogue-action="check-evidence"]');
assert.match(root().textContent, /尚未同時涵蓋問題與解決安排/);
assert.equal(root().querySelector('[data-dialogue-action="check-evidence"]').disabled, false);
selectEvidence("main", "reaction");
selectEvidence("main", "missed");
selectEvidence("main", "pickup");
click('[data-dialogue-action="check-evidence"]');
assert.match(root().textContent, /證據已同時涵蓋事件問題與後續安排/);

const wrongMain = root().querySelector('input[name="main-qa-main"][value="A"]');
wrongMain.checked = true;
wrongMain.dispatchEvent(new dom.window.Event("change", { bubbles: true }));
click('[data-dialogue-action="check-answer"]');
assert.doesNotMatch(root().textContent, /主旨同時涵蓋/);
assert.match(root().textContent, /排除只提到單一地點或人物/);
const rightMain = root().querySelector('input[name="main-qa-main"][value="B"]');
rightMain.checked = true;
rightMain.dispatchEvent(new dom.window.Event("change", { bubbles: true }));
click('[data-dialogue-action="check-answer"]');
assert.match(root().textContent, /主旨同時涵蓋錯過公車的問題/);
assert.match(root().textContent, /遷移：另一段對話/);
selectEvidence("main", "pickup");
assert.equal(root().querySelector('[data-dialogue-action="check-evidence"]').disabled, false, "changing evidence must invalidate downstream answers");
selectEvidence("main", "pickup");
click('[data-dialogue-action="check-evidence"]');
const reselectMain = root().querySelector('input[name="main-qa-main"][value="B"]');
reselectMain.checked = true;
reselectMain.dispatchEvent(new dom.window.Event("change", { bubbles: true }));
click('[data-dialogue-action="check-answer"]');
assert.match(root().textContent, /遷移：另一段對話/);

selectEvidence("transfer", "broken");
const transferAnswer = root().querySelector('input[name="transfer-qa-main"][value="C"]');
transferAnswer.checked = true;
transferAnswer.dispatchEvent(new dom.window.Event("change", { bubbles: true }));
const explanation = root().querySelector('[data-dialogue-text="explanation"]');
explanation.value = "他們改到Room 8使用筆電和螢幕，B會帶簡報，A通知同學。";
explanation.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
click('[data-dialogue-action="check-transfer"]');
assert.match(root().textContent, /答案與所選證據尚未相互支持/);
selectEvidence("transfer", "broken");
selectEvidence("transfer", "suggestion");
selectEvidence("transfer", "roles");
click('[data-dialogue-action="check-transfer"]');
assert.match(root().textContent, /互動完成：已保存預測、證據與遷移解釋/);
const restored = dom.window.document.createElement("main");
restored.innerHTML = dom.window.DialogueComprehensionLab.render(lesson, "qa-main");
assert.match(restored.textContent, /互動完成/);
assert.match(restored.querySelector('[data-dialogue-text="prediction"]').value, /錯過公車/);
assert.equal(restored.querySelector('[data-dialogue-select="main"][data-line="pickup"]').getAttribute("aria-pressed"), "true");
assert.equal(restored.querySelector('[data-dialogue-action="check-transfer"]').disabled, true);

assert.match(app, /DialogueComprehensionLab\.render/);
assert.match(html, /dialogue-comprehension-lab\.js/);
assert.match(css, /@media\(max-width:560px\)\{\.dialogue-lab/);
assert.match(css, /prefers-reduced-motion:reduce/);
assert.ok(registry.components.DialogueComprehensionLab?.stateSerialization);
console.log("dialogue prediction, evidence correction, hints, transfer, persistence, keyboard controls, and responsive hooks: ok");
