import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { JSDOM } from "jsdom";

const lesson = JSON.parse(readFileSync(new URL("../../lessons/english/lesson-english-performance-3-iv-16.json", import.meta.url), "utf8"));
const source = readFileSync(new URL("../../site/genre-reading-lab.js", import.meta.url), "utf8");
const app = readFileSync(new URL("../../site/app.js", import.meta.url), "utf8");
const html = readFileSync(new URL("../../site/index.html", import.meta.url), "utf8");
const css = readFileSync(new URL("../../site/genre-reading-lab.css", import.meta.url), "utf8");
assert.equal(lesson.interactive.type, "genre-reading-lab");
assert.equal(lesson.interactive.genreReadingLab.sources.length, 3);

const dom = new JSDOM("<main id=mount></main>", { url: "https://courseware.test/", runScripts: "outside-only" });
dom.window.eval(source);
const mount = dom.window.document.querySelector("#mount");
const instance = "qa-genre-reading";
mount.innerHTML = dom.window.GenreReadingLab.render(lesson, instance);
const root = () => mount.querySelector("[data-genre-reading-lab]");
const field = name => root().querySelector(`[data-grl-field="${name}"]`);
const enter = (name, value) => { field(name).value = value; field(name).dispatchEvent(new dom.window.Event("input", { bubbles: true })); };
const click = action => root().querySelector(`[data-grl-action="${action}"]`).click();
assert.equal(root().querySelectorAll("[data-grl-source]").length, 0, "source blocks stay hidden until a valid prediction");
enter("prediction", "通知"); click("predict");
assert.match(root().querySelector(".grl-status").textContent, /when/);
assert.equal(root().querySelectorAll("[data-grl-source]").length, 0, "wrong prediction must not reveal source blocks");
enter("prediction", "日期表"); click("predict");
assert.equal(root().querySelectorAll("[data-grl-source]").length, 3);
root().querySelector('[data-grl-source="notice"]').click();
assert.match(root().querySelector(".grl-hint").textContent, /when/);
assert.match(root().querySelector(".grl-excerpt").textContent, /sealed container/);
root().querySelector('[data-grl-source="calendar"]').click();
assert.match(root().querySelector(".grl-excerpt").textContent, /first and third Wednesday/);
enter("explanation", "我選日期表"); click("explain");
assert.match(root().querySelector(".grl-status").textContent, /至少寫/);
enter("explanation", "日期表列出 first and third Wednesday，時段是 3:30–5:00 p.m."); click("explain");
assert.match(root().querySelector(".grl-success").textContent, /Wednesday/);
enter("transferAnswer", "日期表"); click("transfer");
assert.match(root().querySelector(".grl-status").textContent, /why/);
enter("transferAnswer", "說明段落"); click("transfer");
assert.match(root().textContent, /完成：你依問題切換了區塊/);
mount.innerHTML = dom.window.GenreReadingLab.render(lesson, instance);
assert.match(root().textContent, /完成：你依問題切換了區塊/, "completion restores from lesson-instance storage");
click("reset");
assert.ok(field("prediction"), "reset returns to the prediction stage");
assert.match(app, /GenreReadingLab\.render/);
assert.match(html, /genre-reading-lab\.js/);
assert.match(html, /genre-reading-lab\.css/);
assert.match(css, /prefers-reduced-motion/);
console.log("3-IV-16 genre prediction, source switching, evidence rationale, transfer, persistence and reset: ok");
