import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { JSDOM } from "jsdom";

const lesson = JSON.parse(readFileSync(new URL("../../lessons/english/lesson-english-performance-3-iv-12.json", import.meta.url), "utf8"));
const rapidReadingLesson = JSON.parse(readFileSync(new URL("../../lessons/english/lesson-english-performance-3-iv-14.json", import.meta.url), "utf8"));
const viewpointLesson = JSON.parse(readFileSync(new URL("../../lessons/english/lesson-english-performance-3-iv-15.json", import.meta.url), "utf8"));
const backgroundKnowledgeLesson = JSON.parse(readFileSync(new URL("../../lessons/english/lesson-english-performance-7-iv-2.json", import.meta.url), "utf8"));
const studyPlanLesson = JSON.parse(readFileSync(new URL("../../lessons/english/lesson-english-performance-7-iv-5.json", import.meta.url), "utf8"));
const source = readFileSync(new URL("../../site/reading-strategy-lab.js", import.meta.url), "utf8");
const app = readFileSync(new URL("../../site/app.js", import.meta.url), "utf8");
const html = readFileSync(new URL("../../site/index.html", import.meta.url), "utf8");
const css = readFileSync(new URL("../../site/reading-strategy-lab.css", import.meta.url), "utf8");
assert.equal(lesson.interactive.type, "reading-strategy-lab");
assert.equal(lesson.interactive.steps.length, 6);
assert.ok(lesson.interactive.steps.every(step => step.retryHint?.length >= 12));

const dom = new JSDOM("<main id=mount></main>", { url: "https://courseware.test/", runScripts: "outside-only" });
dom.window.eval(source);
dom.window.__courseItems = [lesson];
const mount = dom.window.document.querySelector("#mount");
const instance = "qa-main";
mount.innerHTML = dom.window.ReadingStrategyLab.render(lesson, instance);
const root = () => mount.querySelector("[data-reading-strategy-lab]");
const pick = value => {
  const input = root().querySelector(`[data-rsl-answer][value="${value}"]`);
  input.checked = true;
};
const check = () => root().querySelector('[data-rsl-action="check"]').click();
assert.equal(root().querySelector(".rsl-progress").textContent, "任務 1／6");
pick("B");
check();
assert.equal(root().querySelector(".rsl-progress").textContent, "任務 1／6", "wrong answers must not unlock later tasks");
assert.match(root().querySelector('[role="status"]').textContent, /略讀/);
assert.equal(root().querySelector('[data-rsl-answer][value="B"]').checked, true, "retry selection should remain visible");
pick(lesson.interactive.steps[0].answer);
check();
assert.equal(root().querySelector(".rsl-progress").textContent, "任務 2／6");
assert.match(root().querySelector('[role="status"]').textContent, /主旨任務/);

for (let index = 1; index < lesson.interactive.steps.length; index += 1) {
  pick(lesson.interactive.steps[index].answer);
  check();
}
assert.match(root().textContent, /6 項閱讀任務完成/);
mount.innerHTML = dom.window.ReadingStrategyLab.render(lesson, instance);
assert.match(root().textContent, /6 項閱讀任務完成/, "completed state should restore from localStorage");
root().querySelector('[data-rsl-action="reset"]').click();
assert.equal(root().querySelector(".rsl-progress").textContent, "任務 1／6");
assert.match(app, /ReadingStrategyLab\.render/);
assert.match(html, /reading-strategy-lab\.js/);
assert.match(html, /reading-strategy-lab\.css/);
assert.match(css, /\.reading-strategy-lab/);
const rapidMount = dom.window.document.createElement("div");
dom.window.document.body.append(rapidMount);
const rapidInstance = "qa-rapid-reading";
rapidMount.innerHTML = dom.window.ReadingStrategyLab.render(rapidReadingLesson, rapidInstance);
const rapidRoot = () => rapidMount.querySelector("[data-reading-strategy-lab]");
const rapidPick = value => { rapidRoot().querySelector(`[data-rsl-answer][value="${value}"]`).checked = true; };
const rapidCheck = () => rapidRoot().querySelector('[data-rsl-action="check"]').click();
assert.equal(rapidReadingLesson.interactive.type, "reading-strategy-lab");
assert.equal(rapidReadingLesson.interactive.steps.length, 6);
assert.ok(rapidReadingLesson.interactive.steps.every(step => step.text?.length > 20 && step.retryHint?.length >= 12));
assert.match(rapidRoot().querySelector(".rsl-excerpt").textContent, /WHY CITIES NEED TREES/);
rapidPick("B"); rapidCheck();
assert.match(rapidRoot().querySelector('[role="status"]').textContent, /標題/);
assert.equal(rapidRoot().querySelector('[data-rsl-answer][value="B"]').checked, true);
for (const step of rapidReadingLesson.interactive.steps) { rapidPick(step.answer); rapidCheck(); }
assert.match(rapidRoot().textContent, /六項任務完成/);
assert.equal(rapidRoot().querySelectorAll(".rsl-excerpt").length, 0, "completion should replace the current excerpt");
const viewpointMount = dom.window.document.createElement("div");
dom.window.document.body.append(viewpointMount);
const viewpointInstance = "qa-viewpoint-purpose";
viewpointMount.innerHTML = dom.window.ReadingStrategyLab.render(viewpointLesson, viewpointInstance);
const viewpointRoot = () => viewpointMount.querySelector("[data-reading-strategy-lab]");
const viewpointPick = value => { viewpointRoot().querySelector(`[data-rsl-answer][value="${value}"]`).checked = true; };
const viewpointCheck = () => viewpointRoot().querySelector('[data-rsl-action="check"]').click();
assert.equal(viewpointLesson.interactive.steps.length, 6);
assert.ok(viewpointLesson.interactive.steps.every(step => step.text?.length > 25 && step.retryHint?.length >= 12));
assert.match(viewpointRoot().querySelector(".rsl-excerpt").textContent, /I saw Mei/);
viewpointPick("B"); viewpointCheck();
assert.match(viewpointRoot().querySelector('[role="status"]').textContent, /I saw/);
assert.equal(viewpointRoot().querySelector('[data-rsl-answer][value="B"]').checked, true);
for (const step of viewpointLesson.interactive.steps) { viewpointPick(step.answer); viewpointCheck(); }
assert.match(viewpointRoot().textContent, /六項編輯判讀完成/);
const backgroundMount = dom.window.document.createElement("div");
dom.window.document.body.append(backgroundMount);
const backgroundInstance = "qa-background-knowledge";
backgroundMount.innerHTML = dom.window.ReadingStrategyLab.render(backgroundKnowledgeLesson, backgroundInstance);
const backgroundRoot = () => backgroundMount.querySelector("[data-reading-strategy-lab]");
const backgroundPick = value => { backgroundRoot().querySelector(`[data-rsl-answer][value="${value}"]`).checked = true; };
const backgroundCheck = () => backgroundRoot().querySelector('[data-rsl-action="check"]').click();
assert.equal(backgroundKnowledgeLesson.interactive.type, "reading-strategy-lab");
assert.equal(backgroundKnowledgeLesson.interactive.steps.length, 5);
assert.ok(backgroundKnowledgeLesson.interactive.steps.every(step => step.text?.length > 35 && step.retryHint?.length >= 12));
assert.match(backgroundRoot().querySelector(".rsl-excerpt").textContent, /expected to trade/);
backgroundPick("B"); backgroundCheck();
assert.match(backgroundRoot().querySelector('[role="status"]').textContent, /expected to/);
assert.equal(backgroundRoot().querySelector('[data-rsl-answer][value="B"]').checked, true);
for (const step of backgroundKnowledgeLesson.interactive.steps) { backgroundPick(step.answer); backgroundCheck(); }
assert.match(backgroundRoot().textContent, /完成了預測、相關性篩選、矛盾修正與未知資訊界定/);
backgroundMount.innerHTML = dom.window.ReadingStrategyLab.render(backgroundKnowledgeLesson, backgroundInstance);
assert.match(backgroundRoot().textContent, /完成了預測/);
backgroundRoot().querySelector('[data-rsl-action="reset"]').click();
assert.equal(backgroundRoot().querySelector(".rsl-progress").textContent, "任務 1／5");
const studyPlanMount = dom.window.document.createElement("div");
dom.window.document.body.append(studyPlanMount);
const studyPlanInstance = "qa-study-plan-monitoring";
studyPlanMount.innerHTML = dom.window.ReadingStrategyLab.render(studyPlanLesson, studyPlanInstance);
const studyPlanRoot = () => studyPlanMount.querySelector("[data-reading-strategy-lab]");
const studyPlanPick = value => { studyPlanRoot().querySelector(`[data-rsl-answer][value="${value}"]`).checked = true; };
const studyPlanCheck = () => studyPlanRoot().querySelector('[data-rsl-action="check"]').click();
assert.equal(studyPlanLesson.interactive.type, "reading-strategy-lab");
assert.equal(studyPlanLesson.interactive.steps.length, 6);
assert.ok(studyPlanLesson.interactive.steps.every(step => step.text?.length > 30 && step.retryHint?.length >= 12));
assert.match(studyPlanRoot().querySelector(".rsl-excerpt").textContent, /時間題/);
studyPlanPick("A"); studyPlanCheck();
assert.equal(studyPlanRoot().querySelector(".rsl-progress").textContent, "任務 1／6", "wrong study-plan answer must not unlock later tasks");
assert.match(studyPlanRoot().querySelector('[role="status"]').textContent, /比較兩類題目/);
assert.equal(studyPlanRoot().querySelector('[data-rsl-answer][value="A"]').checked, true, "wrong study-plan choice should remain visible");
for (const step of studyPlanLesson.interactive.steps) { studyPlanPick(step.answer); studyPlanCheck(); }
assert.match(studyPlanRoot().textContent, /六階任務完成/);
studyPlanMount.innerHTML = dom.window.ReadingStrategyLab.render(studyPlanLesson, studyPlanInstance);
assert.match(studyPlanRoot().textContent, /六階任務完成/, "study-plan completion should restore from localStorage");
studyPlanRoot().querySelector('[data-rsl-action="reset"]').click();
assert.equal(studyPlanRoot().querySelector(".rsl-progress").textContent, "任務 1／6");
console.log("3-IV-12/14/15/7-IV-2/7-IV-5 reading labs, retry hints, persistence and reset: ok");
