import assert from 'node:assert/strict';
import fs from 'node:fs';

const lesson = JSON.parse(fs.readFileSync('lessons/science/lesson-science-content-fa-iv-4.json', 'utf8'));
const spec = fs.readFileSync('implementation/unit-specs/science/cur-science-content-fa-iv-4.yaml', 'utf8');
const runtime = fs.readFileSync('site/simulations.js', 'utf8');
assert.equal(lesson.reviewStatus, 'draft');
assert.equal(lesson.teaching.body.length, 6);
assert.deepEqual(lesson.content.sections.map(({ heading }) => heading), lesson.teaching.body.map(({ heading }) => heading));
assert.ok(lesson.teaching.body.every(({ body }) => body.length > 300));
assert.equal(lesson.interactive.steps.length, 4);
assert.ok(lesson.interactive.steps.every(step => step.options.length === 3 && step.answer && step.feedback.length > 20));
assert.equal(lesson.simulation.model, 'fa-iv-4-atmospheric-temperature-profile');
assert.equal(lesson.simulation.learningDesign.steps.length, 4);
assert.match(runtime, /lesson\.simulation\.model !== "fa-iv-4-atmospheric-temperature-profile"/);
assert.match(runtime, /return `\$\{designed\}\$\{atmosphereProfile\(/);
assert.match(runtime, /data-atmo-scenario/);
assert.match(runtime, /marker id="atmo-arrow"/);
assert.match(runtime, /active\?\.matches\("\[data-atmo-scenario\]"\)/);
assert.match(spec, /lessonId: cur-science-content-fa-iv-4/);
assert.match(spec, /component: GuidedChoiceBlock/);
assert.match(spec, /nani: \{status: pending, required: true\}/);
assert.match(spec, /kanghsuan: \{status: pending, required: true\}/);
assert.match(spec, /hanlin: \{status: pending, required: true\}/);
assert.match(spec, /https:\/\/fliphtml5\.com\/zyids\/giyz/);
assert.match(spec, /焦點仍留/);
assert.match(spec, /localStorage/);
assert.match(spec, /沒有第二個同步表徵/);
assert.ok(!spec.includes('EvidenceLabBlock'));
console.log('Fa-IV-4 authored manuscript visibility contract, lesson-specific interaction, truthful spec, and draft/source gates passed.');
